<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="">
<meta name="dcterms.date" content="2026-01-01">

<title>Logistic Regression in Healthcare Management – Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-3bbbbd466991e281563892c5dce73c3d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026)</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mba642-spring-26/mba642-spring-26.github.io/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-to-logistic-regression" id="toc-introduction-to-logistic-regression" class="nav-link active" data-scroll-target="#introduction-to-logistic-regression"><span class="header-section-number">1</span> Introduction to Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#why-logistic-regression-matters-in-healthcare" id="toc-why-logistic-regression-matters-in-healthcare" class="nav-link" data-scroll-target="#why-logistic-regression-matters-in-healthcare"><span class="header-section-number">1.1</span> Why Logistic Regression Matters in Healthcare</a></li>
  <li><a href="#the-problem-with-linear-regression-for-binary-outcomes" id="toc-the-problem-with-linear-regression-for-binary-outcomes" class="nav-link" data-scroll-target="#the-problem-with-linear-regression-for-binary-outcomes"><span class="header-section-number">1.2</span> The Problem with Linear Regression for Binary Outcomes</a></li>
  <li><a href="#the-logistic-solution-an-s-shaped-curve" id="toc-the-logistic-solution-an-s-shaped-curve" class="nav-link" data-scroll-target="#the-logistic-solution-an-s-shaped-curve"><span class="header-section-number">1.3</span> The Logistic Solution: An S-Shaped Curve</a></li>
  </ul></li>
  <li><a href="#understanding-the-core-concepts" id="toc-understanding-the-core-concepts" class="nav-link" data-scroll-target="#understanding-the-core-concepts"><span class="header-section-number">2</span> Understanding the Core Concepts</a>
  <ul class="collapse">
  <li><a href="#from-probability-to-odds" id="toc-from-probability-to-odds" class="nav-link" data-scroll-target="#from-probability-to-odds"><span class="header-section-number">2.1</span> From Probability to Odds</a>
  <ul class="collapse">
  <li><a href="#understanding-odds-values" id="toc-understanding-odds-values" class="nav-link" data-scroll-target="#understanding-odds-values"><span class="header-section-number">2.1.1</span> Understanding Odds Values</a></li>
  </ul></li>
  <li><a href="#from-odds-to-log-odds-logit" id="toc-from-odds-to-log-odds-logit" class="nav-link" data-scroll-target="#from-odds-to-log-odds-logit"><span class="header-section-number">2.2</span> From Odds to Log Odds (Logit)</a>
  <ul class="collapse">
  <li><a href="#visualizing-the-relationship" id="toc-visualizing-the-relationship" class="nav-link" data-scroll-target="#visualizing-the-relationship"><span class="header-section-number">2.2.1</span> Visualizing the Relationship</a></li>
  </ul></li>
  <li><a href="#the-logistic-regression-equation" id="toc-the-logistic-regression-equation" class="nav-link" data-scroll-target="#the-logistic-regression-equation"><span class="header-section-number">2.3</span> The Logistic Regression Equation</a>
  <ul class="collapse">
  <li><a href="#converting-back-to-probability" id="toc-converting-back-to-probability" class="nav-link" data-scroll-target="#converting-back-to-probability"><span class="header-section-number">2.3.1</span> Converting Back to Probability</a></li>
  </ul></li>
  <li><a href="#estimation-method-maximum-likelihood-estimation" id="toc-estimation-method-maximum-likelihood-estimation" class="nav-link" data-scroll-target="#estimation-method-maximum-likelihood-estimation"><span class="header-section-number">2.4</span> Estimation Method: Maximum Likelihood Estimation</a></li>
  </ul></li>
  <li><a href="#simple-logistic-regression" id="toc-simple-logistic-regression" class="nav-link" data-scroll-target="#simple-logistic-regression"><span class="header-section-number">3</span> Simple Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#simple-logistic-regression-example-predicting-hospital-readmission" id="toc-simple-logistic-regression-example-predicting-hospital-readmission" class="nav-link" data-scroll-target="#simple-logistic-regression-example-predicting-hospital-readmission"><span class="header-section-number">3.1</span> Simple Logistic Regression Example: Predicting Hospital Readmission</a></li>
  <li><a href="#creating-and-exploring-the-data" id="toc-creating-and-exploring-the-data" class="nav-link" data-scroll-target="#creating-and-exploring-the-data"><span class="header-section-number">3.2</span> Creating and Exploring the Data</a></li>
  <li><a href="#running-the-logistic-regression" id="toc-running-the-logistic-regression" class="nav-link" data-scroll-target="#running-the-logistic-regression"><span class="header-section-number">3.3</span> Running the Logistic Regression</a></li>
  <li><a href="#interpreting-the-results-step-by-step" id="toc-interpreting-the-results-step-by-step" class="nav-link" data-scroll-target="#interpreting-the-results-step-by-step"><span class="header-section-number">3.4</span> Interpreting the Results Step by Step</a>
  <ul class="collapse">
  <li><a href="#step-1-understanding-the-coefficients-table" id="toc-step-1-understanding-the-coefficients-table" class="nav-link" data-scroll-target="#step-1-understanding-the-coefficients-table"><span class="header-section-number">3.4.1</span> Step 1: Understanding the Coefficients Table</a></li>
  <li><a href="#step-2-writing-the-model-equation" id="toc-step-2-writing-the-model-equation" class="nav-link" data-scroll-target="#step-2-writing-the-model-equation"><span class="header-section-number">3.4.2</span> Step 2: Writing the Model Equation</a></li>
  <li><a href="#step-3-interpreting-the-log-odds-ratio" id="toc-step-3-interpreting-the-log-odds-ratio" class="nav-link" data-scroll-target="#step-3-interpreting-the-log-odds-ratio"><span class="header-section-number">3.4.3</span> Step 3: Interpreting the Log Odds Ratio</a></li>
  <li><a href="#step-4-converting-to-odds-ratio" id="toc-step-4-converting-to-odds-ratio" class="nav-link" data-scroll-target="#step-4-converting-to-odds-ratio"><span class="header-section-number">3.4.4</span> Step 4: Converting to Odds Ratio</a></li>
  </ul></li>
  <li><a href="#predicting-probabilities" id="toc-predicting-probabilities" class="nav-link" data-scroll-target="#predicting-probabilities"><span class="header-section-number">3.5</span> Predicting Probabilities</a>
  <ul class="collapse">
  <li><a href="#manual-calculation" id="toc-manual-calculation" class="nav-link" data-scroll-target="#manual-calculation"><span class="header-section-number">3.5.1</span> Manual Calculation</a></li>
  <li><a href="#using-rs-predict-function" id="toc-using-rs-predict-function" class="nav-link" data-scroll-target="#using-rs-predict-function"><span class="header-section-number">3.5.2</span> Using R’s predict() Function</a></li>
  <li><a href="#visualizing-the-predicted-probabilities" id="toc-visualizing-the-predicted-probabilities" class="nav-link" data-scroll-target="#visualizing-the-predicted-probabilities"><span class="header-section-number">3.5.3</span> Visualizing the Predicted Probabilities</a></li>
  </ul></li>
  <li><a href="#evaluating-model-performance" id="toc-evaluating-model-performance" class="nav-link" data-scroll-target="#evaluating-model-performance"><span class="header-section-number">3.6</span> Evaluating Model Performance</a>
  <ul class="collapse">
  <li><a href="#creating-a-classification-table" id="toc-creating-a-classification-table" class="nav-link" data-scroll-target="#creating-a-classification-table"><span class="header-section-number">3.6.1</span> Creating a Classification Table</a></li>
  <li><a href="#interpreting-the-classification-table" id="toc-interpreting-the-classification-table" class="nav-link" data-scroll-target="#interpreting-the-classification-table"><span class="header-section-number">3.6.2</span> Interpreting the Classification Table</a></li>
  <li><a href="#calculating-model-accuracy" id="toc-calculating-model-accuracy" class="nav-link" data-scroll-target="#calculating-model-accuracy"><span class="header-section-number">3.6.3</span> Calculating Model Accuracy</a></li>
  </ul></li>
  <li><a href="#practice-activities-for-simple-logistic-regression" id="toc-practice-activities-for-simple-logistic-regression" class="nav-link" data-scroll-target="#practice-activities-for-simple-logistic-regression"><span class="header-section-number">3.7</span> Practice Activities for Simple Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#practice-activity-1-medication-adherence" id="toc-practice-activity-1-medication-adherence" class="nav-link" data-scroll-target="#practice-activity-1-medication-adherence"><span class="header-section-number">3.7.1</span> Practice Activity 1: Medication Adherence</a></li>
  <li><a href="#practice-activity-2-emergency-department-return-visits" id="toc-practice-activity-2-emergency-department-return-visits" class="nav-link" data-scroll-target="#practice-activity-2-emergency-department-return-visits"><span class="header-section-number">3.7.2</span> Practice Activity 2: Emergency Department Return Visits</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#multiple-logistic-regression" id="toc-multiple-logistic-regression" class="nav-link" data-scroll-target="#multiple-logistic-regression"><span class="header-section-number">4</span> Multiple Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#multiple-logistic-regression-example-comprehensive-readmission-risk-model" id="toc-multiple-logistic-regression-example-comprehensive-readmission-risk-model" class="nav-link" data-scroll-target="#multiple-logistic-regression-example-comprehensive-readmission-risk-model"><span class="header-section-number">4.1</span> Multiple Logistic Regression Example: Comprehensive Readmission Risk Model</a></li>
  <li><a href="#revisiting-our-readmission-dataset" id="toc-revisiting-our-readmission-dataset" class="nav-link" data-scroll-target="#revisiting-our-readmission-dataset"><span class="header-section-number">4.2</span> Revisiting Our Readmission Dataset</a></li>
  <li><a href="#running-multiple-logistic-regression" id="toc-running-multiple-logistic-regression" class="nav-link" data-scroll-target="#running-multiple-logistic-regression"><span class="header-section-number">4.3</span> Running Multiple Logistic Regression</a></li>
  <li><a href="#interpreting-multiple-predictors" id="toc-interpreting-multiple-predictors" class="nav-link" data-scroll-target="#interpreting-multiple-predictors"><span class="header-section-number">4.4</span> Interpreting Multiple Predictors</a>
  <ul class="collapse">
  <li><a href="#interpreting-coefficients" id="toc-interpreting-coefficients" class="nav-link" data-scroll-target="#interpreting-coefficients"><span class="header-section-number">4.4.1</span> Interpreting Coefficients</a></li>
  </ul></li>
  <li><a href="#comparing-simple-vs.-multiple-regression-why-controlling-for-confounders-matters" id="toc-comparing-simple-vs.-multiple-regression-why-controlling-for-confounders-matters" class="nav-link" data-scroll-target="#comparing-simple-vs.-multiple-regression-why-controlling-for-confounders-matters"><span class="header-section-number">4.5</span> Comparing Simple vs.&nbsp;Multiple Regression: Why Controlling for Confounders Matters</a>
  <ul class="collapse">
  <li><a href="#the-satisfaction-coefficient-simple-vs.-multiple-regression" id="toc-the-satisfaction-coefficient-simple-vs.-multiple-regression" class="nav-link" data-scroll-target="#the-satisfaction-coefficient-simple-vs.-multiple-regression"><span class="header-section-number">4.5.1</span> The Satisfaction Coefficient: Simple vs.&nbsp;Multiple Regression</a></li>
  <li><a href="#why-did-the-coefficient-change" id="toc-why-did-the-coefficient-change" class="nav-link" data-scroll-target="#why-did-the-coefficient-change"><span class="header-section-number">4.5.2</span> Why Did the Coefficient Change?</a></li>
  </ul></li>
  <li><a href="#making-predictions-with-multiple-predictors" id="toc-making-predictions-with-multiple-predictors" class="nav-link" data-scroll-target="#making-predictions-with-multiple-predictors"><span class="header-section-number">4.6</span> Making Predictions with Multiple Predictors</a>
  <ul class="collapse">
  <li><a href="#manual-calculation-for-multiple-predictors" id="toc-manual-calculation-for-multiple-predictors" class="nav-link" data-scroll-target="#manual-calculation-for-multiple-predictors"><span class="header-section-number">4.6.1</span> Manual Calculation for Multiple Predictors</a></li>
  <li><a href="#predictions-for-multiple-patient-profiles" id="toc-predictions-for-multiple-patient-profiles" class="nav-link" data-scroll-target="#predictions-for-multiple-patient-profiles"><span class="header-section-number">4.6.2</span> Predictions for Multiple Patient Profiles</a></li>
  </ul></li>
  <li><a href="#evaluating-the-multiple-regression-model" id="toc-evaluating-the-multiple-regression-model" class="nav-link" data-scroll-target="#evaluating-the-multiple-regression-model"><span class="header-section-number">4.7</span> Evaluating the Multiple Regression Model</a></li>
  </ul></li>
  <li><a href="#choosing-the-classification-threshold" id="toc-choosing-the-classification-threshold" class="nav-link" data-scroll-target="#choosing-the-classification-threshold"><span class="header-section-number">5</span> Choosing the Classification Threshold</a>
  <ul class="collapse">
  <li><a href="#the-0.5-default-is-not-always-optimal" id="toc-the-0.5-default-is-not-always-optimal" class="nav-link" data-scroll-target="#the-0.5-default-is-not-always-optimal"><span class="header-section-number">5.1</span> The 0.5 Default Is Not Always Optimal</a></li>
  <li><a href="#understanding-the-trade-off" id="toc-understanding-the-trade-off" class="nav-link" data-scroll-target="#understanding-the-trade-off"><span class="header-section-number">5.2</span> Understanding the Trade-Off</a></li>
  <li><a href="#sensitivity-and-specificity" id="toc-sensitivity-and-specificity" class="nav-link" data-scroll-target="#sensitivity-and-specificity"><span class="header-section-number">5.3</span> Sensitivity and Specificity</a>
  <ul class="collapse">
  <li><a href="#defining-sensitivity-and-specificity" id="toc-defining-sensitivity-and-specificity" class="nav-link" data-scroll-target="#defining-sensitivity-and-specificity"><span class="header-section-number">5.3.1</span> Defining Sensitivity and Specificity</a></li>
  <li><a href="#the-inverse-relationship-between-sensitivity-and-specificity" id="toc-the-inverse-relationship-between-sensitivity-and-specificity" class="nav-link" data-scroll-target="#the-inverse-relationship-between-sensitivity-and-specificity"><span class="header-section-number">5.3.2</span> The Inverse Relationship Between Sensitivity and Specificity</a></li>
  <li><a href="#calculating-sensitivity-and-specificity-for-our-model" id="toc-calculating-sensitivity-and-specificity-for-our-model" class="nav-link" data-scroll-target="#calculating-sensitivity-and-specificity-for-our-model"><span class="header-section-number">5.3.3</span> Calculating Sensitivity and Specificity for Our Model</a></li>
  </ul></li>
  <li><a href="#choosing-the-right-threshold" id="toc-choosing-the-right-threshold" class="nav-link" data-scroll-target="#choosing-the-right-threshold"><span class="header-section-number">5.4</span> Choosing the Right Threshold</a></li>
  <li><a href="#practice-activities-for-multiple-logistic-regression" id="toc-practice-activities-for-multiple-logistic-regression" class="nav-link" data-scroll-target="#practice-activities-for-multiple-logistic-regression"><span class="header-section-number">5.5</span> Practice Activities for Multiple Logistic Regression</a>
  <ul class="collapse">
  <li><a href="#practice-activity-3-surgical-complication-risk" id="toc-practice-activity-3-surgical-complication-risk" class="nav-link" data-scroll-target="#practice-activity-3-surgical-complication-risk"><span class="header-section-number">5.5.1</span> Practice Activity 3: Surgical Complication Risk</a></li>
  <li><a href="#practice-activity-4-diabetes-management-success" id="toc-practice-activity-4-diabetes-management-success" class="nav-link" data-scroll-target="#practice-activity-4-diabetes-management-success"><span class="header-section-number">5.5.2</span> Practice Activity 4: Diabetes Management Success</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#summary-and-key-takeaways" id="toc-summary-and-key-takeaways" class="nav-link" data-scroll-target="#summary-and-key-takeaways"><span class="header-section-number">6</span> Summary and Key Takeaways</a>
  <ul class="collapse">
  <li><a href="#when-to-use-logistic-regression" id="toc-when-to-use-logistic-regression" class="nav-link" data-scroll-target="#when-to-use-logistic-regression"><span class="header-section-number">6.1</span> When to Use Logistic Regression</a></li>
  <li><a href="#interpreting-results" id="toc-interpreting-results" class="nav-link" data-scroll-target="#interpreting-results"><span class="header-section-number">6.2</span> Interpreting Results</a>
  <ul class="collapse">
  <li><a href="#log-odds-ratios-coefficients" id="toc-log-odds-ratios-coefficients" class="nav-link" data-scroll-target="#log-odds-ratios-coefficients"><span class="header-section-number">6.2.1</span> Log Odds Ratios (Coefficients)</a></li>
  <li><a href="#odds-ratios-exponentiated-coefficients" id="toc-odds-ratios-exponentiated-coefficients" class="nav-link" data-scroll-target="#odds-ratios-exponentiated-coefficients"><span class="header-section-number">6.2.2</span> Odds Ratios (Exponentiated Coefficients)</a></li>
  <li><a href="#converting-between-measures" id="toc-converting-between-measures" class="nav-link" data-scroll-target="#converting-between-measures"><span class="header-section-number">6.2.3</span> Converting Between Measures</a></li>
  </ul></li>
  <li><a href="#simple-vs.-multiple-logistic-regression" id="toc-simple-vs.-multiple-logistic-regression" class="nav-link" data-scroll-target="#simple-vs.-multiple-logistic-regression"><span class="header-section-number">6.3</span> Simple vs.&nbsp;Multiple Logistic Regression</a></li>
  <li><a href="#practical-applications-in-healthcare" id="toc-practical-applications-in-healthcare" class="nav-link" data-scroll-target="#practical-applications-in-healthcare"><span class="header-section-number">6.4</span> Practical Applications in Healthcare</a></li>
  </ul></li>
  <li><a href="#references-and-further-reading" id="toc-references-and-further-reading" class="nav-link" data-scroll-target="#references-and-further-reading"><span class="header-section-number">7</span> References and Further Reading</a>
  <ul class="collapse">
  <li><a href="#statistical-methods" id="toc-statistical-methods" class="nav-link" data-scroll-target="#statistical-methods"><span class="header-section-number">7.1</span> Statistical Methods</a></li>
  <li><a href="#healthcare-applications" id="toc-healthcare-applications" class="nav-link" data-scroll-target="#healthcare-applications"><span class="header-section-number">7.2</span> Healthcare Applications</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Logistic Regression in Healthcare Management</h1>
<p class="subtitle lead">MBA642: Business Analytics in Healthcare Management</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction-to-logistic-regression" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction to Logistic Regression</h1>
<section id="why-logistic-regression-matters-in-healthcare" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="why-logistic-regression-matters-in-healthcare"><span class="header-section-number">1.1</span> Why Logistic Regression Matters in Healthcare</h2>
<p>In healthcare management, many of the most critical decisions involve predicting binary outcomes. For example,</p>
<ul>
<li>Events that either happen vs.&nbsp;don’t happen?</li>
<li>Will a patient be readmitted within 30 days or not?</li>
<li>Will a patient adhere to their medication regimen or not?</li>
<li>Will a treatment be successful or not?</li>
</ul>
<p>These yes/no questions are fundamentally different from predicting continuous outcomes like blood pressure or length of stay.</p>
<p>Let’s think about the following scenario:</p>
<p>A hospital administrator wants to identify patients at high risk of readmission (returning to the hospital after being released) so that care coordinators can provide additional support before discharge. The outcome variable, <em>readmission</em>, can only take two values: YES (the patient was readmitted) or NO (the patient was not readmitted). We cannot use regular linear regression for this problem because linear regression is designed to predict continuous outcomes that can take any value.</p>
<p><strong>Logistic regression</strong> is an appropriate statistical technique when your outcome variable is binary. It allows us to:</p>
<ul>
<li>Predict the <strong>probability</strong> that an event will occur</li>
<li>Identify which factors <strong>increase or decrease</strong> the likelihood of the outcome</li>
<li><strong>Quantify the strength</strong> of each predictor’s effect using odds ratios</li>
<li>Make <strong>data-driven decisions</strong> about resource allocation and interventions</li>
</ul>
</section>
<section id="the-problem-with-linear-regression-for-binary-outcomes" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="the-problem-with-linear-regression-for-binary-outcomes"><span class="header-section-number">1.2</span> The Problem with Linear Regression for Binary Outcomes</h2>
<p>You might wonder why we cannot just use linear regression to predict a binary outcome coded as 0 and 1. Let’s understand why this approach fails.</p>
<p>Imagine we want to predict whether a patient will be readmitted (coded as 1) or not (coded as 0) based on their satisfaction score. If we use linear regression, we might get an equation like:</p>
<p><span class="math display">\[P(\text{Readmission}) = 0.8 - 0.1 \times \text{Satisfaction}\]</span></p>
<p>This seems reasonable at first, but there’s a fundamental problem. What if a patient has a very high satisfaction score of 10?</p>
<p><span class="math display">\[P(\text{Readmission}) = 0.8 - 0.1 \times 10 = -0.2\]</span></p>
<p>We get a negative probability! But probabilities must be between 0 and 1. Similarly, for patients with very low satisfaction, we could get probabilities greater than 1. This is nonsensical. You cannot have a -20% chance or a 140% chance of being readmitted.</p>
<p>Linear regression assumes a straight-line relationship that extends infinitely in both directions. But probabilities are bounded between 0 and 1. We need a different approach that respects these boundaries.</p>
</section>
<section id="the-logistic-solution-an-s-shaped-curve" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="the-logistic-solution-an-s-shaped-curve"><span class="header-section-number">1.3</span> The Logistic Solution: An S-Shaped Curve</h2>
<p>Logistic regression solves this problem by using a special S-shaped curve (called the <strong>logistic</strong> function) that naturally stays between 0 and 1. Instead of predicting the probability directly with a straight line, logistic regression:</p>
<ol type="1">
<li>Transforms the probability into something called <strong>log odds</strong></li>
<li>Models the log odds as a linear function of the predictors</li>
<li>Transforms the result back to a probability</li>
</ol>
<p>This transformation ensures that no matter what values your predictors take, the predicted probability will always be between 0 and 1. The relationship “flattens out” at the extremes, creating the characteristic S-shape.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture13_files/figure-html/sigmoid-curve-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>As you can see in the graph above, the linear regression line (red) extends beyond the valid probability range, while the logistic regression curve (gray) smoothly transitions between 0 and 1, approaching but never crossing these boundaries.</p>
<hr>
<p>Now that we understand <strong>why</strong> we need logistic regression and <strong>how</strong> it solves the boundary problem, let’s explore the mathematical foundations that make it work.</p>
</section>
</section>
<section id="understanding-the-core-concepts" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Understanding the Core Concepts</h1>
<p>Before we jump into running logistic regression analyses, it’s essential to understand three related concepts: <strong>probability</strong>, <strong>odds</strong>, and <strong>log odds</strong>. These transformations are at the heart of how logistic regression works, and understanding them will help you interpret your results correctly.</p>
<section id="from-probability-to-odds" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="from-probability-to-odds"><span class="header-section-number">2.1</span> From Probability to Odds</h2>
<p>You may be already familiar with <strong>probability</strong>. It’s the chance that something will happen, expressed as a number between 0 and 1 (or as a percentage between 0% and 100%). For example, if 30 out of 100 patients are readmitted, the probability of readmission is 0.30 or 30%.</p>
<p><strong>Odds</strong> express the same information in a different way. Instead of comparing the number of events to the total, odds compare the number of events happening to the number of events not happening:</p>
<p><span class="math display">\[\text{Odds} = \frac{p}{1-p} = \frac{\text{Probability of event happening}}{\text{Probability of event not happening}}\]</span></p>
<p>Using our readmission example:</p>
<ul>
<li>Probability of readmission = 0.30</li>
<li>Probability of NOT being readmitted = 0.70</li>
<li>Odds of readmission = 0.30 / 0.70 = 0.429</li>
</ul>
<p>This means that for every patient who is readmitted, there are about 2.3 patients who are not readmitted (since 1/0.429 ≈ 2.3). Alternatively, we can say the odds are “0.429 to 1” or roughly “3 to 7” in favor of not being readmitted.</p>
<section id="understanding-odds-values" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="understanding-odds-values"><span class="header-section-number">2.1.1</span> Understanding Odds Values</h3>
<p>Here’s a helpful table showing how probability and odds relate to each other:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">Probability (p)</th>
<th style="text-align: center;">1 - p</th>
<th style="text-align: center;">Odds</th>
<th style="text-align: center;">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">Very unlikely</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">0.33</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">0.67</td>
<td style="text-align: center;">0.49</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">Equal chance (50/50)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.67</td>
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">2.03</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">3.00</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">9.00</td>
<td style="text-align: center;">Very likely</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Key insight about odds:</strong></p>
<ul>
<li>When odds = 1, the event is equally likely to happen or not happen (50/50 chance)</li>
<li>When odds &lt; 1, the event is less likely than 50/50</li>
<li>When odds &gt; 1, the event is more likely than 50/50</li>
<li>Odds can only be <strong>positive</strong> values (they range from 0 to infinity)</li>
</ul>
</section>
</section>
<section id="from-odds-to-log-odds-logit" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="from-odds-to-log-odds-logit"><span class="header-section-number">2.2</span> From Odds to Log Odds (Logit)</h2>
<p>While odds are more useful than probabilities for our purposes (they range from 0 to infinity instead of 0 to 1), they still have a limitation: they cannot be negative. This asymmetry makes them difficult to model with linear equations.</p>
<p>The solution is to take the <strong>natural logarithm</strong> of the odds, which gives us the <strong>log odds</strong> (also called the <strong>logit</strong>):</p>
<p><span class="math display">\[\text{Log Odds} = \ln(\text{Odds}) = \ln\left(\frac{p}{1-p}\right)\]</span></p>
<p>This transformation has a beautiful property: log odds can range from negative infinity to positive infinity, making them perfect for linear modeling.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">Probability (p)</th>
<th style="text-align: center;">1 - p</th>
<th style="text-align: center;">Odds</th>
<th style="text-align: center;">Log Odds (Logit)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">-2.207</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">-1.109</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">0.67</td>
<td style="text-align: center;">0.49</td>
<td style="text-align: center;">-0.713</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.67</td>
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">2.03</td>
<td style="text-align: center;">0.708</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">3.00</td>
<td style="text-align: center;">1.099</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">9.00</td>
<td style="text-align: center;">2.197</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="visualizing-the-relationship" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="visualizing-the-relationship"><span class="header-section-number">2.2.1</span> Visualizing the Relationship</h3>
<p>Let’s visualize how these three measures relate to each other:</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Lecture13_files/figure-html/prob-odds-logodds-viz-1.png" class="img-fluid figure-img" width="960"></p>
<figcaption>Relationship between Probability, Odds, and Log Odds</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>What does this visualization show?</strong>:</p>
<ul>
<li><strong>Left panel (Probability)</strong>: Linear (identity function), bounded <strong>between 0 and 1</strong></li>
<li><strong>Middle panel (Odds)</strong>: Exponential curve, ranges <strong>from 0 to infinity</strong>, odds = 1 indicates a 50/50 chance</li>
<li><strong>Right panel (Log Odds)</strong>: S-shaped curve (logit function), ranges <strong>from negative infinity to positive infinity</strong>, log odds = 0 indicates a 50/50 chance</li>
</ul>
<p>The <strong>log odds transformation</strong> is what makes logistic regression work. It converts the bounded probability (0 to 1) into an unbounded scale that can be modeled with a linear equation.</p>
<p><strong>Key insight about log odds:</strong></p>
<ul>
<li>When log odds = 0, the event has a 50/50 chance (probability = 0.5)</li>
<li>When log odds &lt; 0, the event is less likely than 50/50</li>
<li>When log odds &gt; 0, the event is more likely than 50/50</li>
<li>Log odds can be any real number (positive or negative)</li>
</ul>
</section>
</section>
<section id="the-logistic-regression-equation" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="the-logistic-regression-equation"><span class="header-section-number">2.3</span> The Logistic Regression Equation</h2>
<p>Now we can write the logistic regression equation. Instead of predicting probability directly (which would cause the boundary problems we discussed), we predict the log odds:</p>
<p><span class="math display">\[\ln\left(\frac{p}{1-p}\right) = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_k X_k\]</span></p>
<p>where <strong>p</strong> is the probability of the outcome (e.g., probability of readmission).</p>
<p>This equation indicates that “the log odds of the outcome is a linear combination of the predictors.”</p>
<p>The coefficients (<span class="math inline">\(\beta\)</span> values) in this equation are <strong>log odds ratios</strong>, which tell us how much the log odds change when the predictor increases by one unit.</p>
<p>By using this equation, we can get <strong>predicted log odds</strong>.</p>
<section id="converting-back-to-probability" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="converting-back-to-probability"><span class="header-section-number">2.3.1</span> Converting Back to Probability</h3>
<p>Once we have predicted log odds, we can convert back to probability using these relationships:</p>
<ol type="1">
<li><strong>From log odds to odds:</strong> <span class="math inline">\(\text{Odds} = e^{\text{log odds}}\)</span> (exponentiated log odds)</li>
<li><strong>From odds to probability:</strong> <span class="math inline">\(p = \frac{\text{Odds}}{1 + \text{Odds}}\)</span></li>
</ol>
<p>Or in one step:</p>
<p><span class="math display">\[p = \frac{e^{\beta_0 + \beta_1 X_1 + \cdots}}{1 + e^{\beta_0 + \beta_1 X_1 + \cdots}}\]</span></p>
<p>Don’t worry if these formulas seem complex. R will do all these calculations for us (that’s why we use a statistical software!). The important thing is to understand the conceptual flow: (1) we model log odds linearly, then (2) transform the results back to probabilities.</p>
</section>
</section>
<section id="estimation-method-maximum-likelihood-estimation" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="estimation-method-maximum-likelihood-estimation"><span class="header-section-number">2.4</span> Estimation Method: Maximum Likelihood Estimation</h2>
<p>Unlike linear regression, we cannot use the OLS method, because:</p>
<ol type="1">
<li><strong>Probability must stay between 0 and 1</strong>: OLS could predict probabilities outside this range (e.g., -0.3 or 1.4), which doesn’t make sense.</li>
<li><strong>Binary outcomes violate OLS assumptions</strong>: The residuals in binary outcomes can’t be normally distributed (as they can only take on two values).</li>
<li><strong>Non-constant variance</strong>: When outcomes are binary, the variance changes systematically with the predicted probability, violating the OLS assumption of constant variance (homoscedasticity).</li>
</ol>
<p>Logistic regression uses <strong>Maximum Likelihood Estimation (MLE)</strong>, a different approach that:</p>
<ul>
<li>Finds the coefficient values (parameters) that make the observed data <strong>most likely</strong> to have occurred</li>
<li>Naturally respects the probability boundaries (predictions always stay between 0 and 1)</li>
<li>Works well with the binomial distribution of binary outcomes</li>
</ul>
<p>You don’t need to understand the mathematics of MLE for this course. The key point is that <strong>the estimation method is different from linear regression</strong>, but R handles all the computation automatically. When you use the <code>glm()</code> function with <code>family = binomial</code>, R is using MLE behind the scenes.</p>
<hr>
</section>
</section>
<section id="simple-logistic-regression" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Simple Logistic Regression</h1>
<p>Simple logistic regression involves predicting a binary outcome using a single predictor variable. This is the foundation for understanding more complex models, so we’ll work through this carefully with a detailed healthcare example.</p>
<section id="simple-logistic-regression-example-predicting-hospital-readmission" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="simple-logistic-regression-example-predicting-hospital-readmission"><span class="header-section-number">3.1</span> Simple Logistic Regression Example: Predicting Hospital Readmission</h2>
<p>You are a quality improvement analyst at a regional hospital. Hospital readmissions within 30 days are a major concern because they indicate potential gaps in care quality and result in financial penalties under Medicare’s Hospital Readmissions Reduction Program.</p>
<p>Your hospital has been tracking patient satisfaction scores (measured on a 1-10 scale at discharge) and wants to understand: <strong>Does patient satisfaction predict the likelihood of 30-day readmission?</strong></p>
<p>The hypothesis is that patients who are more satisfied with their care may be better prepared for discharge, have better understanding of their follow-up instructions, and therefore be less likely to be readmitted.</p>
<p>The Hospital Readmissions Reduction Program (HRRP), established by the Affordable Care Act in 2012, penalizes hospitals with excess readmissions for specific conditions. Research has shown that patient experience metrics, including satisfaction scores, are associated with readmission rates, though the relationship is complex and influenced by multiple factors including patient demographics, clinical complexity, and post-discharge support systems.</p>
</section>
<section id="creating-and-exploring-the-data" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="creating-and-exploring-the-data"><span class="header-section-number">3.2</span> Creating and Exploring the Data</h2>
<p>Let’s first create our dataset and explore it to understand what we’re working with. Our dataset includes not only patient satisfaction but also other important factors like age, comorbidities, and insurance type. For this simple regression example, we’ll focus only on satisfaction, but having all these variables in the dataset will allow us to compare simple vs.&nbsp;multiple regression later.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create comprehensive readmission dataset</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate predictor variables</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>satisfaction <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">3</span>, <span class="at">max =</span> <span class="dv">10</span>), <span class="dv">1</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">65</span>, <span class="at">sd =</span> <span class="dv">12</span>))</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>age <span class="ot">&lt;-</span> <span class="fu">pmax</span>(<span class="fu">pmin</span>(age, <span class="dv">95</span>), <span class="dv">30</span>)  <span class="co"># Keep age between 30 and 95</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>comorbidities <span class="ot">&lt;-</span> <span class="fu">rpois</span>(n, <span class="at">lambda =</span> <span class="dv">2</span>)  <span class="co"># Number of chronic conditions</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>insurance <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Private"</span>, <span class="st">"Medicare"</span>, <span class="st">"Medicaid"</span>), n,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>                    <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.4</span>, <span class="fl">0.4</span>, <span class="fl">0.2</span>))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate readmission outcomes based on all predictors</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Higher satisfaction = lower risk</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Higher age = higher risk</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># More comorbidities = higher risk</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Insurance type affects risk</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>insurance_effect <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(insurance <span class="sc">==</span> <span class="st">"Private"</span>, <span class="sc">-</span><span class="fl">0.5</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">ifelse</span>(insurance <span class="sc">==</span> <span class="st">"Medicare"</span>, <span class="dv">0</span>, <span class="fl">0.4</span>))</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>log_odds <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">2</span> <span class="sc">-</span> <span class="fl">0.325</span> <span class="sc">*</span> satisfaction <span class="sc">+</span> <span class="fl">0.02</span> <span class="sc">*</span> age <span class="sc">+</span> <span class="fl">0.6</span> <span class="sc">*</span> comorbidities <span class="sc">+</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>            insurance_effect <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="fl">0.5</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>prob_readmit <span class="ot">&lt;-</span> <span class="fu">exp</span>(log_odds) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(log_odds))</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>readmitted <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, prob_readmit)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Create data frame</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>readmit_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  <span class="at">patient_id =</span> <span class="dv">1</span><span class="sc">:</span>n,</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">satisfaction =</span> satisfaction,</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> age,</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">comorbidities =</span> comorbidities,</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">insurance =</span> <span class="fu">factor</span>(insurance),</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">readmitted =</span> readmitted</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="co"># View first few rows</span></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(readmit_data, <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   patient_id satisfaction age comorbidities insurance readmitted
1           1          7.9  80             2  Medicaid          1
2           2          6.9  59             2  Medicare          1
3           3          4.0  62             2   Private          0
4           4          5.0  52             3   Private          0
5           5          6.9  77             1  Medicare          0
6           6          3.2  72             1  Medicaid          0
7           7          6.3  46             3   Private          0
8           8          9.0  83             2  Medicaid          0
9           9          4.8  51             1  Medicare          0
10         10          7.1  52             4  Medicaid          0</code></pre>
</div>
</div>
<p><strong>Variables in the dataset</strong>:</p>
<ul>
<li><code>patient_id</code>: Unique identifier for each patient (1 to 200)</li>
<li><code>satisfaction</code>: Patient satisfaction score at discharge (1-10 scale, where higher scores indicate greater satisfaction)</li>
<li><code>age</code>: Patient age in years</li>
<li><code>comorbidities</code>: Number of chronic health conditions (e.g., diabetes, hypertension, heart disease)</li>
<li><code>insurance</code>: Insurance type (Private, Medicare, or Medicaid)</li>
<li><code>readmitted</code>: Whether the patient was readmitted within 30 days (1 = yes, 0 = no)</li>
</ul>
<p>Let’s examine our data more closely to understand the descriptive statistics of our variables:</p>
<p><strong>Patient Satisfaction Scores</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Metric</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean</td>
<td style="text-align: center;">6.18</td>
</tr>
<tr class="even">
<td style="text-align: left;">SD</td>
<td style="text-align: center;">2.04</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Minimum</td>
<td style="text-align: center;">3.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maximum</td>
<td style="text-align: center;">9.90</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Readmission Outcomes</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Outcome</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Not Readmitted</td>
<td style="text-align: center;">156</td>
<td style="text-align: center;">78</td>
</tr>
<tr class="even">
<td style="text-align: left;">Readmitted</td>
<td style="text-align: center;">44</td>
<td style="text-align: center;">22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;">200</td>
<td style="text-align: center;">100</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now let’s visualize the relationship between satisfaction and readmission:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create visualization</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(readmit_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(readmitted), <span class="at">y =</span> satisfaction,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">fill =</span> <span class="fu">factor</span>(readmitted))) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"0"</span> <span class="ot">=</span> <span class="st">"#2A9D8F"</span>, <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"#E63946"</span>),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Not Readmitted"</span>, <span class="st">"Readmitted"</span>)) <span class="sc">+</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Not Readmitted"</span>, <span class="st">"Readmitted"</span>)) <span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Satisfaction Scores by Readmission Status"</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Readmission Status"</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Satisfaction Score (1-10)"</span>) <span class="sc">+</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>p1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture13_files/figure-html/simple-viz-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Looking at this boxplot, we can see that patients who were readmitted tend to have lower satisfaction scores than those who were not readmitted. This suggests there may be a relationship worth investigating with logistic regression.</p>
</section>
<section id="running-the-logistic-regression" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="running-the-logistic-regression"><span class="header-section-number">3.3</span> Running the Logistic Regression</h2>
<p>In R, we use the <code>glm()</code> function (Generalized Linear Model) to run logistic regression. The key arguments are:</p>
<ul>
<li><code>formula</code>: Specifies the outcome and predictors (e.g., <code>readmitted ~ satisfaction</code>)</li>
<li><code>data</code>: The dataset to use</li>
<li><code>family = binomial</code>: Tells R to use logistic regression for binary outcomes</li>
</ul>
<p>The syntax is similar to linear regression with <code>lm()</code>, but we add <code>family = binomial(link = "logit")</code> or just <code>family = binomial</code> (the default link function for binomial is logit):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit logistic regression model</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>model_simple <span class="ot">&lt;-</span> <span class="fu">glm</span>(readmitted <span class="sc">~</span> satisfaction,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> readmit_data,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># View the results</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_simple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = readmitted ~ satisfaction, family = binomial(link = "logit"), 
    data = readmit_data)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)  -0.18297    0.53772  -0.340   0.7336  
satisfaction -0.18136    0.08834  -2.053   0.0401 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 210.76  on 199  degrees of freedom
Residual deviance: 206.35  on 198  degrees of freedom
AIC: 210.35

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
</section>
<section id="interpreting-the-results-step-by-step" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="interpreting-the-results-step-by-step"><span class="header-section-number">3.4</span> Interpreting the Results Step by Step</h2>
<p>The output contains a lot of information. Let’s work through it piece by piece to understand what it all means.</p>
<section id="step-1-understanding-the-coefficients-table" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="step-1-understanding-the-coefficients-table"><span class="header-section-number">3.4.1</span> Step 1: Understanding the Coefficients Table</h3>
<p>The most important part of the output is the “Coefficients” table. Let’s take a look it:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">z value</th>
<th style="text-align: right;">Pr(&gt;|z|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-0.1830</td>
<td style="text-align: right;">0.5377</td>
<td style="text-align: right;">-0.3403</td>
<td style="text-align: right;">0.7336</td>
</tr>
<tr class="even">
<td style="text-align: left;">satisfaction</td>
<td style="text-align: right;">-0.1814</td>
<td style="text-align: right;">0.0883</td>
<td style="text-align: right;">-2.0531</td>
<td style="text-align: right;">0.0401</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Each row in this table represents one term in our model:</p>
<ul>
<li><strong><code>(Intercept)</code></strong>: This is <span class="math inline">\(\beta_0\)</span>, the predicted log odds when satisfaction = 0</li>
<li><strong><code>satisfaction</code></strong>: This is <span class="math inline">\(\beta_1\)</span>, the change in log odds for each one-unit increase in satisfaction</li>
</ul>
<p>The columns tell us:</p>
<ul>
<li><strong>Estimate</strong>: The coefficient value (log odds ratio)</li>
<li><strong>Std. Error</strong>: The uncertainty in our estimate</li>
<li><strong>z value</strong>: The test statistic (Estimate / Std. Error)</li>
<li><strong>Pr(&gt;|z|)</strong>: The p-value for testing whether the coefficient significantly differs from zero</li>
</ul>
</section>
<section id="step-2-writing-the-model-equation" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="step-2-writing-the-model-equation"><span class="header-section-number">3.4.2</span> Step 2: Writing the Model Equation</h3>
<p>From our output, we can write the logistic regression equation:</p>
<p><strong>Log Odds of Readmission = -0.183 + (-0.1814) × Satisfaction</strong></p>
<p>This equation tells us that, for each one-unit increase in satisfaction score, the log odds of readmission changes by the coefficient value.</p>
</section>
<section id="step-3-interpreting-the-log-odds-ratio" class="level3" data-number="3.4.3">
<h3 data-number="3.4.3" class="anchored" data-anchor-id="step-3-interpreting-the-log-odds-ratio"><span class="header-section-number">3.4.3</span> Step 3: Interpreting the Log Odds Ratio</h3>
<p>The coefficient for satisfaction is our <strong>log odds ratio</strong>. Let’s interpret it:</p>
<p><strong>Log Odds Ratio for Satisfaction:</strong> -0.1814</p>
<p><strong>Interpretation:</strong></p>
<ol type="1">
<li><p><strong>DIRECTION</strong>: The coefficient is NEGATIVE, which means higher satisfaction is associated with LOWER log odds of readmission.</p></li>
<li><p><strong>STATISTICAL SIGNIFICANCE</strong>: The p-value is 0.0401. Since p &lt; 0.05, this relationship is statistically significant.</p></li>
<li><p><strong>MAGNITUDE</strong>: For each one-unit increase in satisfaction score, the log odds of readmission change by -0.1814.</p></li>
</ol>
</section>
<section id="step-4-converting-to-odds-ratio" class="level3" data-number="3.4.4">
<h3 data-number="3.4.4" class="anchored" data-anchor-id="step-4-converting-to-odds-ratio"><span class="header-section-number">3.4.4</span> Step 4: Converting to Odds Ratio</h3>
<p>While log odds ratios are mathematically convenient, <strong>odds ratios</strong> are much easier to interpret. We convert by exponentiating:</p>
<p><span class="math display">\[\text{Odds Ratio} = e^{\text{Log Odds Ratio}}\]</span></p>
<p>We can get Odds Ratio by using the following <strong>R functions</strong>:</p>
<ul>
<li><code>coef()</code>: Extracts coefficients from the model</li>
<li><code>exp()</code>: Exponentiates values (raises e to the power of the value) to convert log odds ratios to odds ratios</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate odds ratios</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>odds_ratios <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(model_simple))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Then, we get <strong>Odds Ratios:</strong></p>
<ul>
<li>Intercept: 0.8328</li>
<li>Satisfaction: 0.8341</li>
</ul>
<p>Let’s interpret the odds ratio for satisfaction:</p>
<p><strong>Interpretation:</strong></p>
<ul>
<li><p>Since the odds ratio is LESS than 1, higher satisfaction is associated with LOWER odds of readmission.</p></li>
<li><p>For each one-unit increase in satisfaction score, the odds of readmission DECREASE by 16.6%. (or alternatively, the odds of readmission are multiplied by 0.834 for each one-unit increase in satisfaction).</p></li>
</ul>
</section>
</section>
<section id="predicting-probabilities" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="predicting-probabilities"><span class="header-section-number">3.5</span> Predicting Probabilities</h2>
<p>One of the most useful applications of logistic regression is predicting the probability of the outcome for specific values of the predictor. Let’s calculate predicted probabilities step by step.</p>
<section id="manual-calculation" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="manual-calculation"><span class="header-section-number">3.5.1</span> Manual Calculation</h3>
<p>Let’s predict the probability of readmission for <em>a new patient with a satisfaction score of 5</em>:</p>
<p><strong>Step 1: Calculate Predicted Log Odds</strong></p>
<p>First, we use the logistic regression equation to calculate the log odds. We plug the satisfaction score into our model equation with the estimated coefficients:</p>
<p>Log odds = -0.183 + (-0.181) × 5 = -1.0898</p>
<p>This log odds value represents the predicted log odds of readmission on the logit scale. To interpret this meaningfully, we need to convert it to odds and then to probability.</p>
<p><strong>Step 2: Convert Log Odds to Odds</strong></p>
<p>Next, we convert the log odds to odds by exponentiating (taking e to the power of the log odds):</p>
<p><span class="math display">\[\text{Odds} = e^{-1.0898} = 0.3363\]</span></p>
<p>This odds value tells us the ratio of the probability of readmission to the probability of not being readmitted. An odds value of 0.3363 means that readmission is less likely than not being readmitted.</p>
<p><strong>Step 3: Convert Odds to Probability</strong></p>
<p>Finally, we convert odds to probability using the formula: Probability = Odds / (1 + Odds)</p>
<p><span class="math display">\[\text{Probability} = \frac{0.3363}{1 + 0.3363} = 0.2517\]</span></p>
<p>A patient with a satisfaction score of 5 has a 25.2% predicted probability of being readmitted within 30 days. This means that if we had 100 patients with this satisfaction level, we would expect approximately 25.2 of them to be readmitted.</p>
</section>
<section id="using-rs-predict-function" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="using-rs-predict-function"><span class="header-section-number">3.5.2</span> Using R’s predict() Function</h3>
<p>While the manual calculation helps us understand the underlying process, in practice we use R’s <code>predict()</code> function to efficiently calculate predicted probabilities for many observations at once. This function automatically performs all three steps (log odds → odds → probability) for us.</p>
<p>The <code>predict()</code> function in R generates predictions from a fitted model. Key arguments are:</p>
<ul>
<li>First argument: The fitted model object</li>
<li><code>newdata</code>: A data frame containing the predictor values for which you want predictions</li>
<li><code>type = "response"</code>: Returns predicted probabilities (for logistic regression). Without this, it returns log odds.</li>
</ul>
<p>Let’s predict readmission probabilities for patients with different satisfaction levels:</p>
<p><strong>Predicted Probabilities of Readmission:</strong></p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create data frame with values to predict</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>new_patients <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">satisfaction =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>new_patients<span class="sc">$</span>predicted_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_simple,</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">newdata =</span> new_patients,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>                                        <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">round</span>(new_patients, <span class="dv">3</span>),</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Satisfaction Score"</span>, <span class="st">"Predicted Probability"</span>),</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">align =</span> <span class="fu">c</span>(<span class="st">"c"</span>, <span class="st">"c"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>), <span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Satisfaction Score</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Predicted Probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.287</td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;">0.252</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6</td>
<td style="text-align: center;">0.219</td>
</tr>
<tr class="even">
<td style="text-align: center;">7</td>
<td style="text-align: center;">0.190</td>
</tr>
<tr class="odd">
<td style="text-align: center;">8</td>
<td style="text-align: center;">0.163</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As satisfaction scores increase from 4 to 8, the predicted probability of readmission systematically decreases. This quantifies the relationship we observed in our earlier boxplot, which was higher satisfaction is associated with lower readmission risk. We can use these probabilities to identify which patients may need additional discharge support.</p>
</section>
<section id="visualizing-the-predicted-probabilities" class="level3" data-number="3.5.3">
<h3 data-number="3.5.3" class="anchored" data-anchor-id="visualizing-the-predicted-probabilities"><span class="header-section-number">3.5.3</span> Visualizing the Predicted Probabilities</h3>
<p>Visualizing the relationship between our predictor and the predicted probability helps us understand the model and communicate findings to stakeholders. Let’s create a graph showing how the predicted probability of readmission changes across the full range of satisfaction scores:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create prediction data across range of satisfaction</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>pred_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">satisfaction =</span> <span class="fu">seq</span>(<span class="dv">3</span>, <span class="dv">10</span>, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>pred_data<span class="sc">$</span>probability <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_simple, <span class="at">newdata =</span> pred_data, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add prediction curve</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> pred_data, <span class="fu">aes</span>(<span class="at">x =</span> satisfaction, <span class="at">y =</span> probability),</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"#2A9D8F"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add actual data points</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> readmit_data, <span class="fu">aes</span>(<span class="at">x =</span> satisfaction, <span class="at">y =</span> readmitted),</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">height =</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Add reference line at 0.5</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.5</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray50"</span>) <span class="sc">+</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Predicted Probability of Readmission by Satisfaction Score"</span>,</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Points show actual patient outcomes (0 = not readmitted, 1 = readmitted)"</span>,</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Patient Satisfaction Score"</span>,</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Predicted Probability of Readmission"</span>) <span class="sc">+</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture13_files/figure-html/simple-predict-viz-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p><strong>Understanding this visualization:</strong></p>
<p>The <strong>gray curve</strong> represents our model’s predicted probabilities across all satisfaction levels. The <strong>black points</strong> show the actual patient outcomes in our dataset.</p>
<p>Key features of the logistic curve:</p>
<ul>
<li><strong>At low satisfaction scores</strong> (left side): The probability of readmission is (relatively high.</li>
<li><strong>At high satisfaction scores</strong> (right side): The probability of readmission is (relatively) low.</li>
</ul>
<p>The <strong>dashed line at 0.5</strong> (50%) represents the traditional classification threshold used in many statistical applications. However, <strong>in practice, we would likely use a much lower threshold for readmission prediction</strong> (e.g., 10-20%). Why? Because:</p>
<ul>
<li>Actual readmission rates are typically around 15%, not 50%</li>
<li>The cost of missing a high-risk patient (false negative) is high</li>
<li>The cost of providing extra discharge support to a lower-risk patient (false positive) is relatively low</li>
</ul>
<p>For example, if we used a 20% threshold, any patient with predicted probability ≥ 20% would receive enhanced discharge planning. This more conservative approach helps ensure we don’t miss high-risk patients who could benefit from intervention. We’ll explore how to choose the optimal threshold later in this module.</p>
</section>
</section>
<section id="evaluating-model-performance" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="evaluating-model-performance"><span class="header-section-number">3.6</span> Evaluating Model Performance</h2>
<p>After fitting a logistic regression model, we want to assess its practical usefulness. In other words: <strong>How well does this model actually predict outcomes?</strong> While our model provides probabilities, in many healthcare applications we need to make binary decisions (e.g., “provide extra discharge support” vs.&nbsp;“standard discharge”). This requires evaluating how accurately our model classifies patients.</p>
<section id="creating-a-classification-table" class="level3" data-number="3.6.1">
<h3 data-number="3.6.1" class="anchored" data-anchor-id="creating-a-classification-table"><span class="header-section-number">3.6.1</span> Creating a Classification Table</h3>
<p>To evaluate classification performance, we first convert predicted probabilities into predicted classes using a <strong>decision threshold</strong>.</p>
<p><strong>For this example, we’ll use the traditional 0.5 threshold</strong> to demonstrate how classification tables work:</p>
<ul>
<li>If predicted probability ≥ 0.5 → predict “readmitted” (class = 1)</li>
<li>If predicted probability &lt; 0.5 → predict “not readmitted” (class = 0)</li>
</ul>
<p>As discussed earlier, in a real readmission prediction application, we would likely use a lower threshold (e.g., 0.10-0.20) to be more conservative. However, 0.5 is useful for learning how to interpret classification tables.</p>
<p>We then create a <strong>classification table</strong> (also called a <strong>confusion matrix</strong>) that compares our predictions to actual outcomes:</p>
<p><strong>Classification Table (Confusion Matrix):</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Actual Outcome
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">0</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: center;">156</td>
<td style="text-align: center;">44</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="interpreting-the-classification-table" class="level3" data-number="3.6.2">
<h3 data-number="3.6.2" class="anchored" data-anchor-id="interpreting-the-classification-table"><span class="header-section-number">3.6.2</span> Interpreting the Classification Table</h3>
<p>This 2×2 table shows four possible outcomes:</p>
<ul>
<li><strong>True Negatives (TN, top-left)</strong>: Patients we correctly predicted would NOT be readmitted</li>
<li><strong>False Positives (FP, top-right)</strong>: Patients we incorrectly predicted would be readmitted (false alarm)</li>
<li><strong>False Negatives (FN, bottom-left)</strong>: Patients we incorrectly predicted would NOT be readmitted (missed case)</li>
<li><strong>True Positives (TP, bottom-right)</strong>: Patients we correctly predicted would be readmitted</li>
</ul>
</section>
<section id="calculating-model-accuracy" class="level3" data-number="3.6.3">
<h3 data-number="3.6.3" class="anchored" data-anchor-id="calculating-model-accuracy"><span class="header-section-number">3.6.3</span> Calculating Model Accuracy</h3>
<p><strong>Accuracy</strong> measures the overall proportion of correct predictions (both true positives and true negatives) out of all predictions:</p>
<p><span class="math display">\[\text{Accuracy} = \frac{\text{True Positives} + \text{True Negatives}}{\text{Total Number of Observations}} = \frac{TP + TN}{TP + TN + FP + FN}\]</span></p>
<p>Let’s calculate our model’s accuracy:</p>
<p><strong>Model Performance:</strong></p>
<ul>
<li>Correctly classified: 156 out of 200 patients</li>
<li>Overall accuracy: 78%</li>
</ul>
<p><strong>Breakdown:</strong></p>
<ul>
<li>Correctly predicted NOT readmitted (True Negatives): 156</li>
<li>Correctly predicted readmitted (True Positives): 0</li>
<li>Incorrectly predicted readmitted (False Positives - false alarm): 0</li>
<li>Incorrectly predicted NOT readmitted (False Negatives - missed): 44</li>
</ul>
<p><strong>What does this mean?</strong></p>
<p>Our model correctly classified 78% of patients. While accuracy is a useful starting point, in healthcare applications we often care more about specific types of errors. For example:</p>
<ul>
<li><strong>False negatives</strong> (missed readmissions) mean high-risk patients don’t receive intervention</li>
<li><strong>False positives</strong> (false alarms) mean resources are spent on patients who don’t need extra support</li>
</ul>
<p>The relative importance of these errors depends on the costs and benefits of intervention, which we’ll explore further in the section on classification thresholds.</p>
</section>
</section>
<section id="practice-activities-for-simple-logistic-regression" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="practice-activities-for-simple-logistic-regression"><span class="header-section-number">3.7</span> Practice Activities for Simple Logistic Regression</h2>
<section id="practice-activity-1-medication-adherence" class="level3" data-number="3.7.1">
<h3 data-number="3.7.1" class="anchored" data-anchor-id="practice-activity-1-medication-adherence"><span class="header-section-number">3.7.1</span> Practice Activity 1: Medication Adherence</h3>
<p>A pharmacy wants to understand whether the number of medications a patient takes predicts their adherence (whether they take medications as prescribed) to their medication regimen. Adherence is measured as a binary variable: 1 = adherent (taking medications correctly), 0 = non-adherent (not taking medications as prescribed).</p>
<p>Medication non-adherence is a major challenge in managing chronic diseases (long-term health conditions). Studies have shown that patients taking multiple medications often have lower adherence rates due to increased complexity, higher costs, greater risk of side effects, and difficulties managing multiple medication schedules.</p>
<p><strong>Your Tasks</strong></p>
<ol type="1">
<li><p>Run a logistic regression predicting <code>adherent</code> from <code>num_medications</code></p></li>
<li><p>Interpret the log odds ratio and odds ratio for <code>num_medications</code></p></li>
<li><p>Calculate the predicted probability of adherence for a new patient taking 6 medications</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Medication adherence data</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>n_patients <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>num_medications <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">runif</span>(n_patients, <span class="dv">1</span>, <span class="dv">12</span>))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>log_odds_adhere <span class="ot">&lt;-</span> <span class="fl">1.5</span> <span class="sc">-</span> <span class="fl">0.2</span> <span class="sc">*</span> num_medications <span class="sc">+</span> <span class="fu">rnorm</span>(n_patients, <span class="dv">0</span>, <span class="fl">0.5</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>prob_adhere <span class="ot">&lt;-</span> <span class="fu">exp</span>(log_odds_adhere) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(log_odds_adhere))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>adherent <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n_patients, <span class="dv">1</span>, prob_adhere)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>adherence_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">patient_id =</span> <span class="dv">1</span><span class="sc">:</span>n_patients,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">num_medications =</span> num_medications,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">adherent =</span> adherent</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="co"># View the data</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(adherence_data, <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   patient_id num_medications adherent
1           1               2        1
2           2               9        0
3           3               3        0
4           4               4        0
5           5               9        0
6           6               3        0
7           7               5        1
8           8               6        0
9           9              10        0
10         10              11        0</code></pre>
</div>
</div>
</section>
<section id="practice-activity-2-emergency-department-return-visits" class="level3" data-number="3.7.2">
<h3 data-number="3.7.2" class="anchored" data-anchor-id="practice-activity-2-emergency-department-return-visits"><span class="header-section-number">3.7.2</span> Practice Activity 2: Emergency Department Return Visits</h3>
<p>An emergency department wants to predict whether patients will return within 72 hours based on their initial pain score (0-10 scale).</p>
<p>Early return visits to the emergency department (within 72 hours) are often considered an indicator of incomplete treatment or inadequate discharge planning (preparing patients for safe transition home). Pain management is a critical component of emergency department care, and uncontrolled pain is a common reason for return visits.</p>
<p><strong>Your Tasks</strong></p>
<ol type="1">
<li><p>Run a logistic regression predicting <code>returned_72hr</code> from <code>pain_score</code></p></li>
<li><p>Interpret the log odds ratio and odds ratio for <code>pain_score</code></p></li>
<li><p>Evaluate the model’s classification accuracy. In classification, use threshold of 0.5 (i.e., predicted return_72h ≥ 0.5: 1 vs.&nbsp;predicted return_72h &lt; 0.5: 0).</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ED return visit data</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>n_ed <span class="ot">&lt;-</span> <span class="dv">120</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>pain_score <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">runif</span>(n_ed, <span class="dv">1</span>, <span class="dv">10</span>))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>log_odds_return <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">2.5</span> <span class="sc">+</span> <span class="fl">0.35</span> <span class="sc">*</span> pain_score <span class="sc">+</span> <span class="fu">rnorm</span>(n_ed, <span class="dv">0</span>, <span class="fl">0.6</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>prob_return <span class="ot">&lt;-</span> <span class="fu">exp</span>(log_odds_return) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(log_odds_return))</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>returned <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n_ed, <span class="dv">1</span>, prob_return)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>ed_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">visit_id =</span> <span class="dv">1</span><span class="sc">:</span>n_ed,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">pain_score =</span> pain_score,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">returned_72hr =</span> returned</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co"># View the data</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ed_data, <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   visit_id pain_score returned_72hr
1         1          9             0
2         2          1             1
3         3          4             0
4         4          4             0
5         5          9             0
6         6          7             0
7         7          3             0
8         8          9             0
9         9          8             0
10       10          4             0</code></pre>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="multiple-logistic-regression" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Multiple Logistic Regression</h1>
<p>In practice, outcomes like hospital readmission are influenced by multiple factors simultaneously. <strong>Multiple logistic regression</strong> allows us to include several predictors in a single model, which enables us to:</p>
<ol type="1">
<li><strong>Control for confounding variables</strong> (factors that might distort the relationship we’re studying)</li>
<li><strong>Compare the relative importance</strong> of different predictors</li>
<li><strong>Make more accurate predictions</strong> by incorporating more information</li>
</ol>
<section id="multiple-logistic-regression-example-comprehensive-readmission-risk-model" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="multiple-logistic-regression-example-comprehensive-readmission-risk-model"><span class="header-section-number">4.1</span> Multiple Logistic Regression Example: Comprehensive Readmission Risk Model</h2>
<p>Continuing with our hospital readmission example, the quality improvement team wants to build a more comprehensive model. They believe that readmission risk depends not only on patient satisfaction (<code>satisfaction</code>) but also on:</p>
<ul>
<li><strong>Patient age</strong> (<code>age</code>): older patients may have more complex health needs</li>
<li><strong>Number of comorbidities</strong> (<code>comorbidities</code>): patients with multiple chronic conditions may be at higher risk</li>
<li><strong>Insurance type</strong> (<code>insurance</code>): which may reflect access to post-discharge care</li>
</ul>
<p>Our goal is to understand how each of these factors contributes to readmission risk while accounting for the others.</p>
</section>
<section id="revisiting-our-readmission-dataset" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="revisiting-our-readmission-dataset"><span class="header-section-number">4.2</span> Revisiting Our Readmission Dataset</h2>
<p>Let’s return to the <code>readmit_data</code> dataset we created at the beginning. In the simple regression section, we focused only on the relationship between <strong>satisfaction</strong> and readmission. However, our dataset actually includes several other important variables that we haven’t used yet:</p>
<ul>
<li><strong>Age</strong>: Patient age in years</li>
<li><strong>Comorbidities</strong>: Number of chronic health conditions</li>
<li><strong>Insurance type</strong>: Private, Medicare, or Medicaid</li>
</ul>
<p>This is the beauty of planning ahead in data analysis! By including these variables from the start, we can now build a more comprehensive model to answer a critical question:</p>
<p><strong>Does patient satisfaction still predict readmission when we account for age, health complexity, and insurance type?</strong></p>
<p>This question gets at the heart of why we need multiple regression. What if the satisfaction effect we found in simple regression was partly due to <strong>confounding</strong>? For example, perhaps younger, healthier patients tend to have higher satisfaction scores AND are naturally less likely to be readmitted. Without controlling for age and comorbidities, we might be overstating the true effect of satisfaction.</p>
<p>Our dataset (<code>readmit_data</code>) contains 200 patients with the following variables:</p>
<ul>
<li><code>patient_id</code>: Unique identifier for each patient</li>
<li><code>satisfaction</code>: Patient satisfaction score at discharge (1-10 scale)</li>
<li><code>age</code>: Patient age in years</li>
<li><code>comorbidities</code>: Number of chronic health conditions (e.g., diabetes, hypertension, heart disease)</li>
<li><code>insurance</code>: Insurance type (Private, Medicare, or Medicaid)</li>
<li><code>readmitted</code>: Whether the patient was readmitted within 30 days (1 = yes, 0 = no)</li>
</ul>
<p>Notice that we have both <strong>continuous predictors</strong> (satisfaction, age, comorbidities) and a <strong>categorical predictor</strong> (insurance type). Multiple logistic regression can handle both types of predictors simultaneously.</p>
<p>Let’s explore this richer dataset to understand the characteristics of our patient population:</p>
<p><strong>Dataset Overview:</strong></p>
<ul>
<li>Total patients: 200</li>
<li>Readmission rate: 22%</li>
</ul>
<p><strong>Continuous Variables:</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">MIN</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">MAX</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Satisfaction</td>
<td style="text-align: center;">6.18</td>
<td style="text-align: center;">2.04</td>
<td style="text-align: left;">3</td>
<td style="text-align: center;">9.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Age</td>
<td style="text-align: center;">66.30</td>
<td style="text-align: center;">11.00</td>
<td style="text-align: left;">35</td>
<td style="text-align: center;">95.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Comorbidities</td>
<td style="text-align: center;">2.00</td>
<td style="text-align: center;">1.38</td>
<td style="text-align: left;">0</td>
<td style="text-align: center;">6.0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Insurance Type Distribution:</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Insurance Type</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Medicaid</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">26.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Medicare</td>
<td style="text-align: center;">79</td>
<td style="text-align: center;">39.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Private</td>
<td style="text-align: center;">68</td>
<td style="text-align: center;">34.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="running-multiple-logistic-regression" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="running-multiple-logistic-regression"><span class="header-section-number">4.3</span> Running Multiple Logistic Regression</h2>
<p>We understand our data, so we’re ready to fit the multiple logistic regression model. The good news is that the syntax is very similar to simple logistic regression. We just add more predictors to the formula using the <code>+</code> sign.</p>
<p>Remember from simple regression, we had: <code>readmitted ~ satisfaction</code></p>
<p>Now with multiple predictors, we expand this to: <code>readmitted ~ satisfaction + age + comorbidities + insurance</code></p>
<p>Each predictor is added to the right side of the formula, separated by plus signs. Let’s fit the model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit multiple logistic regression model</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>model_multiple <span class="ot">&lt;-</span> <span class="fu">glm</span>(readmitted <span class="sc">~</span> satisfaction <span class="sc">+</span> age <span class="sc">+</span> comorbidities <span class="sc">+</span> insurance,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> readmit_data,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                      <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co"># View the results</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_multiple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = readmitted ~ satisfaction + age + comorbidities + 
    insurance, family = binomial(link = "logit"), data = readmit_data)

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       -2.18252    1.28948  -1.693  0.09054 .  
satisfaction      -0.21828    0.09580  -2.278  0.02270 *  
age                0.03432    0.01666   2.061  0.03933 *  
comorbidities      0.40688    0.13602   2.991  0.00278 ** 
insuranceMedicare -1.18757    0.44030  -2.697  0.00699 ** 
insurancePrivate  -1.71410    0.49612  -3.455  0.00055 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 210.76  on 199  degrees of freedom
Residual deviance: 182.55  on 194  degrees of freedom
AIC: 194.55

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
</section>
<section id="interpreting-multiple-predictors" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="interpreting-multiple-predictors"><span class="header-section-number">4.4</span> Interpreting Multiple Predictors</h2>
<p>The output looks similar to simple logistic regression, but now we have coefficients for each predictor. The key difference in interpretation is that <strong>each coefficient represents the effect of that variable while holding all other variables constant</strong>. This is crucial for proper interpretation.</p>
<p>For example, the coefficient for satisfaction tells us, “How does readmission risk change when satisfaction increases by 1 point, <strong>assuming age, comorbidities, and insurance type stay the same</strong>?” This allows us to isolate the independent effect of each predictor.</p>
<p>Let’s create a summary table to see all coefficients, odds ratios, and p-values together:</p>
<section id="interpreting-coefficients" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="interpreting-coefficients"><span class="header-section-number">4.4.1</span> Interpreting Coefficients</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Log.Odds.Ratio</th>
<th style="text-align: right;">Odds.Ratio</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-2.1825</td>
<td style="text-align: right;">0.1128</td>
<td style="text-align: right;">0.0905</td>
</tr>
<tr class="even">
<td style="text-align: left;">satisfaction</td>
<td style="text-align: right;">-0.2183</td>
<td style="text-align: right;">0.8039</td>
<td style="text-align: right;">0.0227</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0.0343</td>
<td style="text-align: right;">1.0349</td>
<td style="text-align: right;">0.0393</td>
</tr>
<tr class="even">
<td style="text-align: left;">comorbidities</td>
<td style="text-align: right;">0.4069</td>
<td style="text-align: right;">1.5021</td>
<td style="text-align: right;">0.0028</td>
</tr>
<tr class="odd">
<td style="text-align: left;">insuranceMedicare</td>
<td style="text-align: right;">-1.1876</td>
<td style="text-align: right;">0.3050</td>
<td style="text-align: right;">0.0070</td>
</tr>
<tr class="even">
<td style="text-align: left;">insurancePrivate</td>
<td style="text-align: right;">-1.7141</td>
<td style="text-align: right;">0.1801</td>
<td style="text-align: right;">0.0006</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Let’s interpret each predictor:</p>
<p><strong>Interpretation of Each Predictor:</strong></p>
<p><strong>1. Satisfaction</strong></p>
<ul>
<li><strong>Log Odds Ratio:</strong> -0.2183 (p = 0.0227)
<ul>
<li>This means that for each one-unit increase in satisfaction, the log odds of readmission change by -0.2183, holding other variables constant.</li>
</ul></li>
<li><strong>Odds Ratio:</strong> 0.804
<ul>
<li>This means that for each one-unit increase in satisfaction, the odds of readmission are multiplied by 0.804, holding other variables constant. (i.e., the odds DECREASE by 19.6%)</li>
</ul></li>
</ul>
<p><strong>2. Age</strong></p>
<ul>
<li><strong>Log Odds Ratio:</strong> 0.0343 (p = 0.0393)
<ul>
<li>For each one-year increase in age, the log odds of readmission change by 0.0343, holding other variables constant.</li>
</ul></li>
<li><strong>Odds Ratio:</strong> 1.0349
<ul>
<li>For each one-year increase in age, the odds of readmission are multiplied by 1.0349, holding other variables constant. (i.e., the odds increase by 3.5%)</li>
</ul></li>
</ul>
<p><strong>3. Comorbidities</strong></p>
<ul>
<li><strong>Log Odds Ratio:</strong> 0.4069 (p = 0.0028)
<ul>
<li>For each additional comorbidity, the log odds of readmission change by 0.4069, holding other variables constant.</li>
</ul></li>
<li><strong>Odds Ratio:</strong> 1.502
<ul>
<li>For each additional comorbidity, the odds of readmission are multiplied by 1.502, holding other variables constant. (i.e., the odds increase by 50.2%)</li>
</ul></li>
</ul>
<p><strong>4. Insurance Type</strong> (Reference category: Medicaid)</p>
<ul>
<li><strong>Medicaid vs.&nbsp;Medicare:</strong>
<ul>
<li><strong>Log Odds Ratio:</strong> -1.1876 (p = 0.007)</li>
<li><strong>Odds Ratio:</strong> 0.305</li>
<li><strong>Interpretation:</strong> Holding satisfaction, age, and comorbidities constant, patients with Medicare have odds of readmission that are 0.305 times the odds for patients with Medicaid. In other words, Medicare patients have 69.5% lower odds compared to Medicaid patients.</li>
</ul></li>
<li><strong>Medicare vs.&nbsp;Private:</strong>
<ul>
<li><strong>Log Odds Ratio:</strong> -1.7141 (p = 6^{-4})</li>
<li><strong>Odds Ratio:</strong> 0.18</li>
<li><strong>Interpretation:</strong> Holding satisfaction, age, and comorbidities constant, patients with Private insurance have odds of readmission that are 0.18 times the odds for patients with Medicaid. In other words, Private insurance patients have 82% lower odds compared to Medicaid patients.</li>
</ul></li>
</ul>
</section>
</section>
<section id="comparing-simple-vs.-multiple-regression-why-controlling-for-confounders-matters" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="comparing-simple-vs.-multiple-regression-why-controlling-for-confounders-matters"><span class="header-section-number">4.5</span> Comparing Simple vs.&nbsp;Multiple Regression: Why Controlling for Confounders Matters</h2>
<p>As we’ve built both a simple logistic regression (with satisfaction only) and a multiple logistic regression (with satisfaction, age, comorbidities, and insurance), let’s compare them to understand <strong>why multiple regression is necessary</strong>.</p>
<section id="the-satisfaction-coefficient-simple-vs.-multiple-regression" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="the-satisfaction-coefficient-simple-vs.-multiple-regression"><span class="header-section-number">4.5.1</span> The Satisfaction Coefficient: Simple vs.&nbsp;Multiple Regression</h3>
<p><strong>Comparison of Satisfaction Effect:</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Model</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Log Odds Ratio</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Odds Ratio</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">% Change in Odds</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Simple Regression</td>
<td style="text-align: center;">-0.1814</td>
<td style="text-align: center;">0.834</td>
<td style="text-align: center;">-16.6%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Multiple Regression</td>
<td style="text-align: center;">-0.2183</td>
<td style="text-align: center;">0.804</td>
<td style="text-align: center;">-19.6%</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Notice that the absolute satisfaction coefficient is <strong>larger</strong> in the multiple regression compared to the simple regression.</p>
<ul>
<li>In the <strong>simple regression</strong>, we found that each 1-point increase in satisfaction was associated with a 16.6% decrease in the odds of readmission.</li>
<li>In the <strong>multiple regression</strong>, after controlling for age, comorbidities, and insurance type, each 1-point increase in satisfaction is associated with a 19.6% decrease in the odds of readmission.</li>
</ul>
</section>
<section id="why-did-the-coefficient-change" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="why-did-the-coefficient-change"><span class="header-section-number">4.5.2</span> Why Did the Coefficient Change?</h3>
<p>This change reveals the presence of <strong>confounding</strong>. A confounder is a variable that is related to both the predictor we’re interested in (satisfaction) and the outcome (readmission), potentially creating a misleading relationship.</p>
<p>In our case, it’s possible that:</p>
<ul>
<li>Younger, healthier patients (fewer comorbidities) tend to have <strong>higher satisfaction scores</strong></li>
<li>Younger, healthier patients are also <strong>naturally less likely to be readmitted</strong> (regardless of their satisfaction)</li>
</ul>
<p>Without controlling for age and comorbidities, the simple regression may have understated the true effect of satisfaction on readmission. The multiple regression gives us the <strong>“unique” effect</strong> of satisfaction by holding these other factors constant, essentially asking: “For two patients of the same age, with the same number of comorbidities, and the same insurance type, how does a difference in satisfaction affect readmission risk?”</p>
<p>This is why <strong>multiple regression is essential</strong> in healthcare analytics: it helps us isolate the independent effect of each factor and makes our conclusions more informative for decision-making.</p>
</section>
</section>
<section id="making-predictions-with-multiple-predictors" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="making-predictions-with-multiple-predictors"><span class="header-section-number">4.6</span> Making Predictions with Multiple Predictors</h2>
<p>With multiple logistic regression, we can make more nuanced predictions by considering a patient’s complete risk profile, not just one. Instead of just knowing their satisfaction score, we now incorporate their age, health complexity, and insurance status to get a more accurate prediction.</p>
<section id="manual-calculation-for-multiple-predictors" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="manual-calculation-for-multiple-predictors"><span class="header-section-number">4.6.1</span> Manual Calculation for Multiple Predictors</h3>
<p>To understand how multiple predictors combine, let’s walk through a manual calculation for a specific patient. This shows the mathematical process, though in practice R will do this for us automatically.</p>
<p>The multiple logistic regression equation extends the simple version by adding more terms:</p>
<p><span class="math display">\[\text{Log Odds} = \beta_0 + \beta_1 \times \text{Satisfaction} + \beta_2 \times \text{Age} + \beta_3 \times \text{Comorbidities} + \beta_4 \times \text{Medicare} + \beta_5 \times \text{Private}\]</span></p>
<p><strong>Example Patient:</strong></p>
<p>Let’s assume that we have a new patient whose data is as follows, and we would like to predict this patient’s predicted probability of readmission using our multiple logistic regression model.</p>
<ul>
<li>Satisfaction = 6</li>
<li>Age = 70</li>
<li>Comorbidities = 3</li>
<li>Insurance = Medicare</li>
</ul>
<p><strong>Step 1: Calculate Log Odds</strong></p>
<p>Using the multiple logistic regression equation, we plug in all predictor values:</p>
<p>Log odds = -2.183 + (-0.218) × 6 + (0.0343) × 70 + (0.407) × 3 + (-1.188) × 1 + + (-1.714) × 0</p>
<p>Log odds = -1.0564</p>
<p>Note: For Medicare insurance, we use 1 for the Medicare dummy variable and 0 for the Private dummy variable (since the patient doesn’t have private insurance).</p>
<p><strong>Step 2: Convert to Odds</strong></p>
<p>We can get the predicted odds by taking the exponent of the log odds.</p>
<p><span class="math display">\[\text{Odds} = e^{-1.0564} = 0.3477\]</span></p>
<p><strong>Step 3: Convert to Probability</strong></p>
<p>We can get the predicted probability by using the equation we learned above.</p>
<p><span class="math display">\[\text{Probability} = \frac{0.3477}{1 + 0.3477} = 0.258\]</span></p>
<p>This patient has a 25.8% predicted probability of readmission within 30 days.</p>
</section>
<section id="predictions-for-multiple-patient-profiles" class="level3" data-number="4.6.2">
<h3 data-number="4.6.2" class="anchored" data-anchor-id="predictions-for-multiple-patient-profiles"><span class="header-section-number">4.6.2</span> Predictions for Multiple Patient Profiles</h3>
<p>While manual calculations help us understand the mechanics, in practice we use R to generate predictions efficiently. One powerful use of multiple regression is creating <strong>risk profiles</strong>: comparing predicted probabilities for patients with different combinations of risk factors.</p>
<p>For example, we can contrast a “Low Risk” patient (young, few comorbidities, high satisfaction, private insurance) with a “High Risk” patient (older, many comorbidities, low satisfaction, Medicaid). Let’s create three representative profiles and see how their predicted probabilities differ:</p>
<p><strong>Predicted Readmission Probabilities for Different Patient Profiles:</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Profile</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">satisfaction</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">age</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">comorbidities</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">insurance</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Predicted Probability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Low Risk</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">1</td>
<td style="text-align: left;">Private</td>
<td style="text-align: center;">0.029</td>
</tr>
<tr class="even">
<td style="text-align: left;">Medium Risk</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">65</td>
<td style="text-align: center;">2</td>
<td style="text-align: left;">Medicare</td>
<td style="text-align: center;">0.163</td>
</tr>
<tr class="odd">
<td style="text-align: left;">High Risk</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">4</td>
<td style="text-align: left;">Medicaid</td>
<td style="text-align: center;">0.789</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>This shows how combining multiple risk factors leads to dramatically different predicted probabilities. The “High Risk” patient (low satisfaction, advanced age, multiple comorbidities, and Medicaid insurance) has a much higher predicted probability of readmission than the “Low Risk” patient. This demonstrates the power of multiple regression. (It can capture the cumulative effect of multiple risk factors!)</p>
</section>
</section>
<section id="evaluating-the-multiple-regression-model" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="evaluating-the-multiple-regression-model"><span class="header-section-number">4.7</span> Evaluating the Multiple Regression Model</h2>
<p>Finally, let’s assess how well our multiple regression model performs at classifying patients. Just as we did with simple regression, we’ll create a confusion matrix to see how many patients are correctly classified as readmitted or not readmitted.</p>
<p>We’ll use the traditional 0.5 threshold for this demonstration, though as discussed earlier, a lower threshold (e.g., 0.20) would be more appropriate for actual readmission prediction:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add predictions</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>readmit_data<span class="sc">$</span>pred_prob_multiple <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_multiple, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>readmit_data<span class="sc">$</span>pred_class_multiple <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(readmit_data<span class="sc">$</span>pred_prob_multiple <span class="sc">&gt;=</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Classification Table (Confusion Matrix):</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Actual Outcome
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">0</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: center;">153</td>
<td style="text-align: center;">36</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">8</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Model Performance:</strong></p>
<ul>
<li>Correctly classified: 161 out of 200 patients</li>
<li>Overall accuracy: 80.5%</li>
</ul>
<p><strong>Breakdown:</strong></p>
<ul>
<li>Correctly predicted NOT readmitted (True Negatives): 153</li>
<li>Correctly predicted readmitted (True Positives): 8</li>
<li>Incorrectly predicted readmitted (False Positives): 3</li>
<li>Incorrectly predicted NOT readmitted (False Negatives): 36</li>
</ul>
<p>The multiple logistic regression model achieves 80.5% accuracy. This demonstrates the value of incorporating multiple risk factors in predicting readmission.</p>
<p>As we understand both simple and multiple logistic regression, let’s turn to an important practical question: choosing the right classification threshold.</p>
<hr>
</section>
</section>
<section id="choosing-the-classification-threshold" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Choosing the Classification Threshold</h1>
<section id="the-0.5-default-is-not-always-optimal" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="the-0.5-default-is-not-always-optimal"><span class="header-section-number">5.1</span> The 0.5 Default Is Not Always Optimal</h2>
<p>So far, we’ve used <strong>0.5 as the probability cutoff</strong> for classification:</p>
<ul>
<li>If predicted probability ≥ 0.5 → predict “event will occur” (e.g., readmitted)</li>
<li>If predicted probability &lt; 0.5 → predict “event will not occur” (e.g., not readmitted)</li>
</ul>
<p>But <strong>0.5 is arbitrary</strong>. As we noted earlier when discussing readmission prediction, the optimal cutoff depends on your specific application. For hospital readmission, we mentioned that a lower threshold (e.g., 0.10-0.20) might be more appropriate because:</p>
<ul>
<li>Actual readmission rates are typically 10-20%, not 50%</li>
<li>Missing a high-risk patient is costly</li>
<li>Providing extra support to lower-risk patients is relatively inexpensive</li>
</ul>
<p>Let’s explore this more systematically by examining how different thresholds affect our predictions.</p>
</section>
<section id="understanding-the-trade-off" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="understanding-the-trade-off"><span class="header-section-number">5.2</span> Understanding the Trade-Off</h2>
<p>When we change the cutoff threshold, we face a fundamental trade-off:</p>
<p><strong>Lower threshold (e.g., 0.3)</strong>:</p>
<ul>
<li>We predict “event” more often</li>
<li><strong>Catches more true positives</strong> (higher sensitivity)</li>
<li>But also <strong>more false alarms</strong> (lower specificity)</li>
</ul>
<p><strong>Higher threshold (e.g., 0.7)</strong>:</p>
<ul>
<li>We predict “event” less often</li>
<li><strong>Fewer false alarms</strong> (higher specificity)</li>
<li>But <strong>misses more true positives</strong> (lower sensitivity)</li>
</ul>
</section>
<section id="sensitivity-and-specificity" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sensitivity-and-specificity"><span class="header-section-number">5.3</span> Sensitivity and Specificity</h2>
<p>To understand how threshold choice affects our predictions, we need to introduce two critical metrics that measure different aspects of model performance. These metrics help us quantify the trade-offs we make when choosing a threshold.</p>
<section id="defining-sensitivity-and-specificity" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="defining-sensitivity-and-specificity"><span class="header-section-number">5.3.1</span> Defining Sensitivity and Specificity</h3>
<p><strong>SENSITIVITY (True Positive Rate):</strong></p>
<p>Of patients who were <strong>ACTUALLY readmitted</strong>, what percentage did we correctly identify?</p>
<p><span class="math display">\[\text{Sensitivity} = \frac{\text{True Positives}}{\text{True Positives} + \text{False Negatives}}\]</span></p>
<p>In other words, sensitivity measures the model’s ability to <strong>catch positive cases</strong>. (i.e., when a patient is readmitted, how often do we predict that they will be readmitted?) High sensitivity means we’re good at identifying patients who will be readmitted.</p>
<p><strong>SPECIFICITY (True Negative Rate):</strong></p>
<p>Of patients who were <strong>NOT readmitted</strong>, what percentage did we correctly identify?</p>
<p><span class="math display">\[\text{Specificity} = \frac{\text{True Negatives}}{\text{True Negatives} + \text{False Positives}}\]</span></p>
<p>In other words, specificity measures the model’s ability to <strong>correctly identify negative cases</strong>. (i.e., when a patient is not readmitted, how often do we predict that they will not be readmitted?) High specificity means we’re good at identifying patients who will not be readmitted.</p>
</section>
<section id="the-inverse-relationship-between-sensitivity-and-specificity" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="the-inverse-relationship-between-sensitivity-and-specificity"><span class="header-section-number">5.3.2</span> The Inverse Relationship Between Sensitivity and Specificity</h3>
<p>Here’s the crucial insight: <strong>sensitivity and specificity have an inverse relationship</strong>. When we adjust our threshold:</p>
<ul>
<li><strong>Lowering the threshold</strong> → We predict “positive” more often → More true positives captured (↑ sensitivity) BUT also more false positives (↓ specificity)</li>
<li><strong>Raising the threshold</strong> → We predict “positive” less often → Fewer false positives (↑ specificity) BUT we miss more true positives (↓ sensitivity)</li>
</ul>
<p><strong>You cannot maximize both simultaneously.</strong> This creates a fundamental <strong>trade-off</strong> that requires us to think carefully about the costs and benefits of different types of errors in our specific application.</p>
<p>Think of it this way:</p>
<ul>
<li>If you want to catch 100% of readmissions (perfect sensitivity), you’d need to flag almost everyone as high-risk, creating many false alarms (poor specificity).</li>
<li>If you want zero false alarms (perfect specificity), you’d flag almost no one, missing many actual readmissions (poor sensitivity).</li>
</ul>
<p>The optimal threshold depends on which type of error is more costly in your context.</p>
</section>
<section id="calculating-sensitivity-and-specificity-for-our-model" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="calculating-sensitivity-and-specificity-for-our-model"><span class="header-section-number">5.3.3</span> Calculating Sensitivity and Specificity for Our Model</h3>
<p>Let’s calculate these metrics for our multiple regression model with the 0.5 cutoff:</p>
<p><strong>With 0.5 cutoff:</strong></p>
<ul>
<li><strong>Sensitivity:</strong> 18.2%
<ul>
<li>We correctly identified 18.2% of actual readmissions</li>
<li>Calculation: <span class="math inline">\(\frac{8}{8 + 36} = 0.182\)</span></li>
</ul></li>
<li><strong>Specificity:</strong> 98.1%
<ul>
<li>We correctly identified 98.1% of patients who were not readmitted</li>
<li>Calculation: <span class="math inline">\(\frac{153}{153 + 3} = 0.981\)</span></li>
</ul></li>
</ul>
<p>These values serve as our baseline. Now let’s see how they change when we adjust the threshold.</p>
</section>
</section>
<section id="choosing-the-right-threshold" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="choosing-the-right-threshold"><span class="header-section-number">5.4</span> Choosing the Right Threshold</h2>
<p>The 0.5 cutoff is a default, but not necessarily optimal. Different thresholds create different trade-offs between sensitivity and specificity. Let’s compare three different cutoffs using our multiple regression model:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top table-sm small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Cutoff</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Sensitivity (%)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Specificity (%)</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">False Alarms</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Missed Cases</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0.3 (Low)</td>
<td style="text-align: right;">50.0</td>
<td style="text-align: right;">81.4</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.5 (Default)</td>
<td style="text-align: right;">18.2</td>
<td style="text-align: right;">98.1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">36</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0.7 (High)</td>
<td style="text-align: right;">11.4</td>
<td style="text-align: right;">99.4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">39</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>As you can see, as the threshold increases:</p>
<ul>
<li><strong>Sensitivity decreases</strong> (we miss more actual readmissions)</li>
<li><strong>Specificity increases</strong> (we have fewer false alarms)</li>
</ul>
<p><strong>How to choose the optimal threshold?</strong></p>
<p>The optimal threshold depends on your specific context and your interest:</p>
<ul>
<li><strong>Prioritize sensitivity (lower threshold)</strong>: When missing a positive case is very costly (e.g., screening programs, low-cost interventions)</li>
<li><strong>Prioritize specificity (higher threshold)</strong>: When false alarms are costly due to limited resources or expensive interventions</li>
<li><strong>Use default 0.5</strong>: When both types of errors have roughly equal costs</li>
</ul>
<p>In healthcare practice, work with clinical stakeholders to understand the costs of different errors and choose a threshold that aligns with your organizational goals and resource constraints.</p>
<hr>
</section>
<section id="practice-activities-for-multiple-logistic-regression" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="practice-activities-for-multiple-logistic-regression"><span class="header-section-number">5.5</span> Practice Activities for Multiple Logistic Regression</h2>
<section id="practice-activity-3-surgical-complication-risk" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="practice-activity-3-surgical-complication-risk"><span class="header-section-number">5.5.1</span> Practice Activity 3: Surgical Complication Risk</h3>
<p>A surgical department wants to predict the risk of post-operative complications (problems that occur after surgery). They have collected data on patient age (<code>age</code>), BMI (<code>bmi</code> - body mass index, a measure of body weight relative to height), surgery duration in minutes (<code>surgery_duration</code>), and whether the surgery was elective (planned) or emergency (<code>surgery_type</code>).</p>
<p>Post-operative complications represent a significant concern in surgical care, with factors such as patient characteristics, procedure complexity, and surgical urgency all potentially contributing to complication risk. Understanding which factors predict complications can help with risk stratification and targeted prevention strategies.</p>
<p><strong>Your Tasks</strong></p>
<ol type="1">
<li><p>Run a multiple logistic regression predicting <code>complication</code> from all predictors</p></li>
<li><p>Interpret the odds ratios for each predictor</p></li>
<li><p>Identify which factors have statistically significant effects</p></li>
<li><p>Predict the probability of complication for a 68-year-old patient with BMI of 32, undergoing an elective surgery expected to last 150 minutes</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Surgical complication data</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>n_surg <span class="ot">&lt;-</span> <span class="dv">180</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>surgery_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">patient_id =</span> <span class="dv">1</span><span class="sc">:</span>n_surg,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_surg, <span class="dv">60</span>, <span class="dv">15</span>)),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">bmi =</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_surg, <span class="dv">28</span>, <span class="dv">5</span>), <span class="dv">1</span>),</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">surgery_duration =</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_surg, <span class="dv">120</span>, <span class="dv">45</span>)),</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">surgery_type =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Elective"</span>, <span class="st">"Emergency"</span>), n_surg,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>                        <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.7</span>, <span class="fl">0.3</span>))</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate outcomes</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>surgery_data<span class="sc">$</span>age <span class="ot">&lt;-</span> <span class="fu">pmax</span>(<span class="fu">pmin</span>(surgery_data<span class="sc">$</span>age, <span class="dv">90</span>), <span class="dv">25</span>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>surgery_data<span class="sc">$</span>bmi <span class="ot">&lt;-</span> <span class="fu">pmax</span>(<span class="fu">pmin</span>(surgery_data<span class="sc">$</span>bmi, <span class="dv">45</span>), <span class="dv">18</span>)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>surgery_data<span class="sc">$</span>surgery_duration <span class="ot">&lt;-</span> <span class="fu">pmax</span>(surgery_data<span class="sc">$</span>surgery_duration, <span class="dv">30</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>type_effect <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(surgery_data<span class="sc">$</span>surgery_type <span class="sc">==</span> <span class="st">"Emergency"</span>, <span class="fl">0.8</span>, <span class="dv">0</span>)</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>log_odds_comp <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">4</span> <span class="sc">+</span> <span class="fl">0.03</span> <span class="sc">*</span> surgery_data<span class="sc">$</span>age <span class="sc">+</span> <span class="fl">0.05</span> <span class="sc">*</span> surgery_data<span class="sc">$</span>bmi <span class="sc">+</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>                 <span class="fl">0.01</span> <span class="sc">*</span> surgery_data<span class="sc">$</span>surgery_duration <span class="sc">+</span> type_effect <span class="sc">+</span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">rnorm</span>(n_surg, <span class="dv">0</span>, <span class="fl">0.5</span>)</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>prob_comp <span class="ot">&lt;-</span> <span class="fu">exp</span>(log_odds_comp) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(log_odds_comp))</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>surgery_data<span class="sc">$</span>complication <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n_surg, <span class="dv">1</span>, prob_comp)</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a><span class="co"># View the data</span></span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(surgery_data, <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   patient_id age  bmi surgery_duration surgery_type complication
1           1  73 39.9               94    Emergency            1
2           2  48 36.5              172     Elective            1
3           3  44 24.9               90     Elective            0
4           4  80 25.2              175     Elective            1
5           5  75 20.9              103    Emergency            1
6           6  76 22.6              119     Elective            1
7           7  70 18.2              136     Elective            1
8           8  63 31.2               64     Elective            0
9           9  46 23.2              118     Elective            0
10         10  52 27.4              121     Elective            1</code></pre>
</div>
</div>
</section>
<section id="practice-activity-4-diabetes-management-success" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="practice-activity-4-diabetes-management-success"><span class="header-section-number">5.5.2</span> Practice Activity 4: Diabetes Management Success</h3>
<p>A diabetes clinic wants to predict which patients will achieve good blood sugar control. This is measured using HbA1c (a blood test that shows average blood sugar levels over the past 2-3 months). A value below 7% is considered good control.</p>
<p>The clinic has data on patient age (<code>age</code>), years since diagnosis (<code>years_since_dx</code>), number of clinic visits in the past year (<code>clinic_visits</code>), and whether they use insulin injections (<code>uses_insulin</code>).</p>
<p>Diabetes management success depends on multiple factors including patient engagement (reflected in clinic visit frequency), disease duration, treatment complexity, and age-related considerations. Understanding which factors predict successful glycemic control can help clinics target support resources effectively.</p>
<p><strong>Your Tasks</strong></p>
<ol type="1">
<li><p>Run a multiple logistic regression predicting <code>good_control</code> from all predictors</p></li>
<li><p>Compare the effects of different predictors using odds ratios</p></li>
<li><p>Predict the probability of success for a 55-year-old patient diagnosed 8 years ago, with 4 clinic visits, using insulin</p></li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Diabetes management data</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>n_dm <span class="ot">&lt;-</span> <span class="dv">150</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>diabetes_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">patient_id =</span> <span class="dv">1</span><span class="sc">:</span>n_dm,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">round</span>(<span class="fu">rnorm</span>(n_dm, <span class="dv">58</span>, <span class="dv">12</span>)),</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">years_since_dx =</span> <span class="fu">round</span>(<span class="fu">runif</span>(n_dm, <span class="dv">1</span>, <span class="dv">20</span>)),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">clinic_visits =</span> <span class="fu">rpois</span>(n_dm, <span class="at">lambda =</span> <span class="dv">3</span>),</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">uses_insulin =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Yes"</span>, <span class="st">"No"</span>), n_dm, <span class="at">replace =</span> <span class="cn">TRUE</span>, <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.4</span>, <span class="fl">0.6</span>))</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate outcomes</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>diabetes_data<span class="sc">$</span>age <span class="ot">&lt;-</span> <span class="fu">pmax</span>(<span class="fu">pmin</span>(diabetes_data<span class="sc">$</span>age, <span class="dv">85</span>), <span class="dv">30</span>)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>insulin_effect <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(diabetes_data<span class="sc">$</span>uses_insulin <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="sc">-</span><span class="fl">0.5</span>, <span class="dv">0</span>)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>log_odds_control <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">+</span> <span class="fl">0.02</span> <span class="sc">*</span> diabetes_data<span class="sc">$</span>age <span class="sc">-</span> <span class="fl">0.08</span> <span class="sc">*</span> diabetes_data<span class="sc">$</span>years_since_dx <span class="sc">+</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>                    <span class="fl">0.3</span> <span class="sc">*</span> diabetes_data<span class="sc">$</span>clinic_visits <span class="sc">+</span> insulin_effect <span class="sc">+</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">rnorm</span>(n_dm, <span class="dv">0</span>, <span class="fl">0.6</span>)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>prob_control <span class="ot">&lt;-</span> <span class="fu">exp</span>(log_odds_control) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(log_odds_control))</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>diabetes_data<span class="sc">$</span>good_control <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n_dm, <span class="dv">1</span>, prob_control)</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a><span class="co"># View the data</span></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diabetes_data, <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   patient_id age years_since_dx clinic_visits uses_insulin good_control
1           1  61             10             2           No            1
2           2  78              3             4          Yes            1
3           3  61              5             1           No            1
4           4  54              6             4           No            0
5           5  49             16             5           No            0
6           6  75              9             2           No            0
7           7  51              8             1           No            0
8           8  68             10             2           No            1
9           9  43             13             3          Yes            0
10         10  51              2             2          Yes            1</code></pre>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="summary-and-key-takeaways" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Summary and Key Takeaways</h1>
<section id="when-to-use-logistic-regression" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="when-to-use-logistic-regression"><span class="header-section-number">6.1</span> When to Use Logistic Regression</h2>
<p>Use logistic regression when:</p>
<ul>
<li>Your <strong>outcome variable is binary</strong> (two possible values)</li>
<li>You want to predict the <strong>probability</strong> of an event occurring</li>
<li>You want to understand which factors <strong>increase or decrease</strong> the likelihood of the outcome</li>
<li>You need to <strong>quantify effects</strong> using odds ratios</li>
</ul>
</section>
<section id="interpreting-results" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="interpreting-results"><span class="header-section-number">6.2</span> Interpreting Results</h2>
<section id="log-odds-ratios-coefficients" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="log-odds-ratios-coefficients"><span class="header-section-number">6.2.1</span> Log Odds Ratios (Coefficients)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Value</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>= 0</td>
<td>No effect on log odds</td>
</tr>
<tr class="even">
<td>&lt; 0</td>
<td>Negative effect (decreases log odds)</td>
</tr>
<tr class="odd">
<td>&gt; 0</td>
<td>Positive effect (increases log odds)</td>
</tr>
</tbody>
</table>
<p>The further from 0, the stronger the effect.</p>
</section>
<section id="odds-ratios-exponentiated-coefficients" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="odds-ratios-exponentiated-coefficients"><span class="header-section-number">6.2.2</span> Odds Ratios (Exponentiated Coefficients)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Value</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>= 1</td>
<td>No effect on odds</td>
</tr>
<tr class="even">
<td>&lt; 1</td>
<td>Decreases odds (protective factor)</td>
</tr>
<tr class="odd">
<td>&gt; 1</td>
<td>Increases odds (risk factor)</td>
</tr>
</tbody>
</table>
<p>The further from 1, the stronger the effect.</p>
</section>
<section id="converting-between-measures" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="converting-between-measures"><span class="header-section-number">6.2.3</span> Converting Between Measures</h3>
<p><strong>Probability → Odds → Log Odds</strong></p>
<p><span class="math display">\[\text{Odds} = \frac{p}{1-p}\]</span></p>
<p><span class="math display">\[\text{Log Odds} = \ln(\text{Odds})\]</span></p>
<p><strong>Log Odds → Odds → Probability</strong></p>
<p><span class="math display">\[\text{Odds} = e^{\text{Log Odds}}\]</span></p>
<p><span class="math display">\[\text{Probability} = \frac{\text{Odds}}{1 + \text{Odds}}\]</span></p>
</section>
</section>
<section id="simple-vs.-multiple-logistic-regression" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="simple-vs.-multiple-logistic-regression"><span class="header-section-number">6.3</span> Simple vs.&nbsp;Multiple Logistic Regression</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 30%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>Simple</th>
<th>Multiple</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Predictors</td>
<td>One</td>
<td>Two or more</td>
</tr>
<tr class="even">
<td>Interpretation</td>
<td>Direct effect</td>
<td>Effect controlling for other variables</td>
</tr>
<tr class="odd">
<td>Use case</td>
<td>Initial exploration</td>
<td>Comprehensive modeling</td>
</tr>
<tr class="even">
<td>Confounding</td>
<td>Not addressed</td>
<td>Can be controlled</td>
</tr>
</tbody>
</table>
</section>
<section id="practical-applications-in-healthcare" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="practical-applications-in-healthcare"><span class="header-section-number">6.4</span> Practical Applications in Healthcare</h2>
<p>Logistic regression is widely used in healthcare for:</p>
<ul>
<li><strong>Risk prediction models</strong> (readmission, mortality, complications)</li>
<li><strong>Clinical decision support</strong> (identifying high-risk patients)</li>
<li><strong>Quality improvement</strong> (understanding factors affecting outcomes)</li>
<li><strong>Resource allocation</strong> (targeting interventions to those most likely to benefit)</li>
<li><strong>Policy evaluation</strong> (assessing impact of programs on binary outcomes)</li>
</ul>
<hr>
</section>
</section>
<section id="references-and-further-reading" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> References and Further Reading</h1>
<section id="statistical-methods" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="statistical-methods"><span class="header-section-number">7.1</span> Statistical Methods</h2>
<ul>
<li>Hosmer, D. W., Lemeshow, S., &amp; Sturdivant, R. X. (2013). <em>Applied Logistic Regression</em> (3rd ed.). Wiley.</li>
<li>Field, A. (2018). <em>Discovering Statistics Using IBM SPSS Statistics</em> (5th ed.). SAGE Publications.</li>
<li>James, G., Witten, D., Hastie, T., &amp; Tibshirani, R. (2021). <em>An Introduction to Statistical Learning</em> (2nd ed.). Springer.</li>
</ul>
</section>
<section id="healthcare-applications" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="healthcare-applications"><span class="header-section-number">7.2</span> Healthcare Applications</h2>
<p>Examples are motivated by the following:</p>
<ul>
<li><p>Boulding, W., Glickman, S. W., Manary, M. P., Schulman, K. A., &amp; Staelin, R. (2011). Relationship between patient satisfaction with inpatient care and hospital readmission within 30 days. <em>American Journal of Managed Care</em>, 17(1), 41-48. https://www.ajmc.com/view/ajmc_11jan_boulding_41to48</p></li>
<li><p>Wang, W., Gong, Y., Zhang, W., Zhong, Z., Xu, P., Hu, Y., &amp; Chen, H. (2025). Factors influencing medication adherence among Chinese older adults with physical multimorbidity and polypharmacy: A cross‐sectional study. <em>Nursing &amp; Health Sciences</em>. https://doi.org/10.1111/nhs.70192</p></li>
<li><p>Caterino, J. M., Karapanou, O., Pandya, A., Moore, C., Hiestand, B. C., &amp; Perman, S. M. (2020). Predicting pain-related 30-day emergency department return visits in middle-aged and older adults. <em>Pain Medicine</em>, 21(11), 2748-2755. https://pmc.ncbi.nlm.nih.gov/articles/PMC8557807/</p></li>
<li><p>Nigussie, J., Girma, A., Seid, S., &amp; Misganaw Mulat, A. (2022). Incidence and risk factors of postoperative complications in general surgery patients: Prospective cohort study. <em>BMC Surgery</em>, 22(1), 407. https://pmc.ncbi.nlm.nih.gov/articles/PMC9714582/</p></li>
<li><p>Adjei, D. N., Arhin, P. A., Amaglo, J. K., &amp; Osei Bonsu, E. (2025). Poor glycemic control and its predictors among type 2 diabetes patients: Insights from a single‐centre retrospective study in Ghana. <em>Health Science Reports</em>, 8(3), e70558. https://pmc.ncbi.nlm.nih.gov/articles/PMC11896812/</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>