<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="">
  <meta name="dcterms.date" content="2026-04-15">
  <title>Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026) – Logistic Regression</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-9e47a048f9aa32c89095d4c894f35b02.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
  <link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Logistic Regression</h1>
  <p class="subtitle">Week 14</p>

<div class="quarto-title-authors">
</div>

  <p class="date">2026-04-15</p>
</section>
<section id="todays-learning-goals" class="slide level2 scrollable">
<h2>Today’s Learning Goals</h2>
<p>By the end of this lecture, you will be able to:</p>
<ol type="1">
<li class="fragment"><strong>Explain</strong> why logistic regression is necessary for <strong>binary outcomes</strong> and how it differs from linear regression</li>
<li class="fragment"><strong>Interpret</strong> logistic regression coefficients including log odds ratios and odds ratios</li>
<li class="fragment"><strong>Run and interpret</strong> both simple and multiple logistic regression models in R</li>
<li class="fragment"><strong>Evaluate</strong> model performance using classification tables</li>
</ol>
</section>
<section id="why-logistic-regression" class="slide level2">
<h2>Why Logistic Regression?</h2>
<p>In healthcare management, many critical decisions involve <strong>binary</strong> outcomes:</p>
<ul>
<li class="fragment">Will a patient be <strong>readmitted</strong> within 30 days?</li>
<li class="fragment">Will a patient <strong>adhere</strong> to their medication?</li>
<li class="fragment">Will a treatment be <strong>successful</strong> or not?</li>
<li class="fragment">Will a patient develop a <strong>complication</strong> after surgery?</li>
</ul>
<div class="fragment">
<p><br></p>
<p>These yes/no questions are fundamentally different from predicting continuous outcomes (e.g., blood pressure, weight, LOS). We cannot use linear regression because it is designed for continuous outcomes.</p>
</div>
<div class="fragment">
<p>We need a different approach: <strong>logistic regression</strong>.</p>
</div>
</section>
<section id="the-problem-with-linear-regression-for-binary-outcomes" class="slide level2">
<h2>The Problem with Linear Regression for Binary Outcomes</h2>
<p>Imagine predicting readmission (1 = yes, 0 = no) from length of hospital stay (in days):</p>
<p><span class="math display">\[P(\text{Readmission}) = -0.2 + 0.05 \times \text{Length of Stay}\]</span></p>
<div class="fragment">
<p>What if a patient has a very long length of stay of 30 days?</p>
<p><span class="math display">\[P(\text{Readmission}) = -0.2 + 0.05 \times 30 = 1.3\]</span></p>
</div>
<div class="fragment">
<p><br></p>
<p>Probabilities must be between 0 and 1, but the predicted probability of readmission exceeds 1. Linear regression can produce impossible predictions for binary outcomes.</p>
</div>
</section>
<section id="the-logistic-solution-an-s-shaped-curve" class="slide level2">
<h2>The Logistic Solution: An S-Shaped Curve</h2>
<p>Logistic regression uses a special <strong>S-shaped curve</strong> (logistic function) that naturally stays between 0 and 1:</p>

<img data-src="Slide13_files/figure-revealjs/fig-sigmoid-curve-1.png" id="fig-sigmoid-curve" width="864" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;1
</p></section>
<section>
<section id="core-concepts-of-logistic-regression" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>1. Core Concepts of Logistic Regression</h1>

</section>
<section id="from-probability-to-odds" class="slide level2">
<h2>From Probability to Odds</h2>
<p><strong>Probability</strong>: Chance that something happens (0 to 1)</p>
<div class="fragment">
<p><strong>Odds</strong>: Ratio of event happening to event not happening</p>
<p><span class="math display">\[\text{Odds} = \frac{p}{1-p} \qquad \Longleftrightarrow \qquad p = \frac{\text{Odds}}{1 + \text{Odds}}\]</span></p>
</div>
<div class="fragment">
<p><br> <strong>Example</strong> (readmission probability = 0.30):</p>
<ul>
<li>Probability of readmission = 0.30</li>
<li>Probability of NOT readmitted = 0.70</li>
<li>Odds = 0.30 / 0.70 = 0.429</li>
</ul>
</div>
</section>
<section id="understanding-odds-values" class="slide level2">
<h2>Understanding Odds Values</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top" style="font-size: 22px; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Probability (p)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">1 - p</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Odds</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">Very unlikely</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">0.33</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">0.67</td>
<td style="text-align: center;">0.49</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">Equal chance (50/50)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.67</td>
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">2.03</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">3.00</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">9.00</td>
<td style="text-align: center;">Very likely</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="fragment">
<p><strong>Key</strong>:</p>
<ul>
<li>Odds = 1 means 50/50 chance</li>
<li>Odds &lt; 1 = less likely; Odds &gt; 1 = more likely</li>
<li>Odds can be from 0 to positive infinity <br> (unbounded above, but cannot be negative)</li>
</ul>
</div>
</section>
<section id="from-odds-to-log-odds-logit" class="slide level2">
<h2>From Odds to Log Odds (Logit)</h2>
<p>Odds cannot be negative (range: 0 to positive infinity). We need an <strong>unbounded</strong> scale (-∞ to +∞) for linear modeling.</p>
<div class="fragment">
<p><strong>Log Odds</strong> = natural logarithm of odds:</p>
<p><span class="math display">\[\text{Log Odds} = \ln\left(\frac{p}{1-p}\right)\]</span></p>
</div>
<div class="fragment">
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top" style="font-size: 22px; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Probability (p)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">1 - p</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Odds</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Log Odds (Logit)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">-2.207</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">-1.109</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">0.67</td>
<td style="text-align: center;">0.49</td>
<td style="text-align: center;">-0.713</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">1.00</td>
<td style="text-align: center;">0.000</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.67</td>
<td style="text-align: center;">0.33</td>
<td style="text-align: center;">2.03</td>
<td style="text-align: center;">0.708</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">3.00</td>
<td style="text-align: center;">1.099</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">9.00</td>
<td style="text-align: center;">2.197</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:40%;">
<p><strong>Key points</strong></p>
<div style="font-size: 0.8em;">
<ul>
<li>When <strong>p = 0.5</strong>, <strong>log odds = 0</strong></li>
<li>When <strong>p &gt; 0.5</strong>, log odds are <strong>positive</strong></li>
<li>When <strong>p &lt; 0.5</strong>, log odds are <strong>negative</strong></li>
<li>Log odds map probabilities (0, 1) onto the full real line (−∞, +∞)</li>
</ul>
</div>
</div></div>
</div>
</section>
<section id="visualizing-the-three-scales" class="slide level2">
<h2>Visualizing the Three Scales</h2>

<img data-src="Slide13_files/figure-revealjs/fig-three-scales-1.png" id="fig-three-scales" width="864" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;2
</p></section>
<section id="the-logistic-regression-equation" class="slide level2">
<h2>The Logistic Regression Equation</h2>
<p>Instead of predicting probability directly, we predict the <strong>log odds</strong>:</p>
<p><span class="math display">\[\ln\left(\frac{p}{1-p}\right) = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_k X_k\]</span></p>
<div class="fragment">
<p><br> The coefficients (<span class="math inline">\(\beta\)</span> values) represent the <strong>change in log odds</strong> per one-unit increase in the predictor.</p>
</div>
<div class="fragment">
<p><br> <strong>Converting back to probability</strong>:</p>
<p><span class="math display">\[p = \frac{e^{\beta_0 + \beta_1 X_1 + \cdots}}{1 + e^{\beta_0 + \beta_1 X_1 + \cdots}} = \frac{odds}{1 + odds}\]</span></p>
</div>
</section>
<section id="maximum-likelihood-estimation-mle" class="slide level2">
<h2>Maximum Likelihood Estimation (MLE)</h2>
<p>Unlike linear regression (OLS), logistic regression uses <strong>MLE</strong> because:</p>
<ul>
<li class="fragment">OLS could predict probabilities <strong>outside the plausible range (0-1)</strong></li>
<li class="fragment">Binary outcomes <strong>violate OLS assumptions</strong> (non-normal residuals, non-constant variance)</li>
<li class="fragment">MLE finds coefficient values that make the observed data <strong>most likely</strong></li>
</ul>
<div class="fragment">
<p><br></p>
<p>You don’t need to understand the math of MLE as R does it for you (<code>glm()</code> with <code>family = binomial</code>, R uses MLE automatically).</p>
</div>
</section></section>
<section>
<section id="simple-logistic-regression" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>2. Simple Logistic Regression</h1>

</section>
<section id="what-is-it-when-to-use-it" class="slide level2">
<h2>What Is It? / When to Use It</h2>
<p><strong>Simple logistic regression</strong> models the relationship between <strong>one predictor</strong> and a <strong>binary outcome</strong> (0/1).</p>
<div class="fragment">
<p><br> <strong>Use it when:</strong></p>
<ul>
<li class="fragment">Your <strong>outcome variable is binary</strong> (two possible values)</li>
<li class="fragment">You have <strong>one predictor variable</strong> to examine</li>
<li class="fragment">You want to understand <strong>how the predictor affects the probability</strong> of the outcome, quantified through <strong>log odds ratios</strong> and <strong>odds ratios</strong></li>
</ul>
</div>
</section>
<section id="example-case-predicting-hospital-readmission" class="slide level2">
<h2>Example Case: Predicting Hospital Readmission</h2>
<p><strong>Scenario</strong>: A quality improvement analyst wants to understand whether <em>discharge readiness</em> predicts <em>30-day readmission</em>.</p>
<p><br> The dataset contains records for <strong>200 patients</strong> discharged from a single hospital, with each row representing one patient and including their discharge readiness score, demographics, clinical characteristics, and whether they were readmitted within 30 days.</p>
<div class="fragment">
<p><br> <strong>Hypothesis</strong>: Patients who feel more ready for discharge have a better understanding of follow-up care and are less likely to be readmitted.</p>
</div>
<div class="fragment">
<p><br> <strong>Hospital Readmissions Reduction Program (HRRP)</strong>: Hospitals with excess readmissions face financial penalties under Medicare. Understanding predictors of readmission helps target interventions.</p>
</div>
</section>
<section id="loading-and-exploring-the-data" class="slide level2">
<h2>Loading and Exploring the Data</h2>
<p>Let’s load the data and required packages.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># load required packages</span></span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb1-5"><a aria-hidden="true" tabindex="-1"></a>readmit_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week13_readmit_data.csv"</span>)</span>
<span id="cb1-6"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Set the Medicaid as the reference category for insurance</span></span>
<span id="cb1-8"><a aria-hidden="true" tabindex="-1"></a>readmit_data <span class="ot">&lt;-</span> readmit_data <span class="sc">|&gt;</span></span>
<span id="cb1-9"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">insurance =</span> <span class="fu">factor</span>(insurance, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Medicaid"</span>, <span class="st">"Medicare"</span>, <span class="st">"Private"</span>)))</span>
<span id="cb1-10"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(readmit_data, <span class="dv">3</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X patient_id discharge_readiness age comorbidities insurance readmitted
1 1          1                 7.9  80             2  Medicaid          1
2 2          2                 6.9  59             2  Medicare          1
3 3          3                 4.0  62             2   Private          0</code></pre>
</div>
</div>
</section>
<section id="key-variables" class="slide level2">
<h2>Key Variables</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>patient_id</code></td>
<td>Unique identifier for each patient</td>
<td>ID</td>
</tr>
<tr class="even">
<td><code>discharge_readiness</code></td>
<td>Discharge readiness score (1-10, higher = more ready)</td>
<td>Continuous</td>
</tr>
<tr class="odd">
<td><code>age</code></td>
<td>Patient age in years</td>
<td>Continuous</td>
</tr>
<tr class="even">
<td><code>comorbidities</code></td>
<td>Number of chronic conditions (e.g., diabetes, hypertension)</td>
<td>Continuous</td>
</tr>
<tr class="odd">
<td><code>insurance</code></td>
<td>Insurance type (Medicaid, Medicare, or Private)</td>
<td>Categorical</td>
</tr>
<tr class="even">
<td><code>readmitted</code></td>
<td>Whether readmitted within 30 days (1 = yes, 0 = no) — <strong>outcome</strong></td>
<td>Binary</td>
</tr>
</tbody>
</table>
</section>
<section id="exploring-the-data" class="slide level2">
<h2>Exploring the Data</h2>
<p>Let’s start by exploring the distribution of our outcome variable (readmission) and how it relates to our key predictor (discharge readiness).</p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top" style="width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Outcome</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Not Readmitted</td>
<td style="text-align: center;">156</td>
<td style="text-align: center;">78</td>
</tr>
<tr class="even">
<td style="text-align: left;">Readmitted</td>
<td style="text-align: center;">44</td>
<td style="text-align: center;">22</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: center;">200</td>
<td style="text-align: center;">100</td>
</tr>
</tbody>
</table>
</div>
</div>
</div><div class="column" style="width:50%;">
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(readmit_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(readmitted), <span class="at">y =</span> discharge_readiness,</span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a>                          <span class="at">fill =</span> <span class="fu">factor</span>(readmitted))) <span class="sc">+</span></span>
<span id="cb3-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb3-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Discharge Readiness by Readmission Status"</span>,</span>
<span id="cb3-6"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Readmission Status"</span>,</span>
<span id="cb3-7"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Discharge Readiness Score (1-10)"</span>) <span class="sc">+</span></span>
<span id="cb3-8"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">10</span>) <span class="sc">+</span></span>
<span id="cb3-9"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb3-10"><a aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-simple-explore" class="quarto-float quarto-figure quarto-figure-center" width="480">
<figure class="quarto-float quarto-float-fig">
<div aria-describedby="fig-simple-explore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img data-src="Slide13_files/figure-revealjs/fig-simple-explore-1.png" id="fig-simple-explore" width="480">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-simple-explore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3
</figcaption>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="running-simple-logistic-regression" class="slide level2">
<h2>Running Simple Logistic Regression</h2>
<p>Let’s run a simple logistic regression model to see if discharge readiness predicts readmission. We can do this by using <code>glm()</code> with <code>family = binomial</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-hidden="true" tabindex="-1"></a>model_simple <span class="ot">&lt;-</span> <span class="fu">glm</span>(readmitted <span class="sc">~</span> discharge_readiness,</span>
<span id="cb4-2"><a aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> readmit_data,</span>
<span id="cb4-3"><a aria-hidden="true" tabindex="-1"></a>                    <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>)) <span class="co"># link = "logit" is the default, so you can omit this</span></span>
<span id="cb4-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_simple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="running-simple-logistic-regression-output" class="slide level2 output-location-slide"><h2>Running Simple Logistic Regression</h2><div class="cell output-location-slide">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = readmitted ~ discharge_readiness, family = binomial(link = "logit"), 
    data = readmit_data)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)         -0.18297    0.53772  -0.340   0.7336  
discharge_readiness -0.18136    0.08834  -2.053   0.0401 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 210.76  on 199  degrees of freedom
Residual deviance: 206.35  on 198  degrees of freedom
AIC: 210.35

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div></section><section id="step-1-understanding-the-coefficients" class="slide level2 scrollable">
<h2>Step 1: Understanding the Coefficients</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top" style="margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Std. Error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">z value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-0.1830</td>
<td style="text-align: right;">0.5377</td>
<td style="text-align: right;">-0.3403</td>
<td style="text-align: right;">0.7336</td>
</tr>
<tr class="even">
<td style="text-align: left;">discharge_readiness</td>
<td style="text-align: right;">-0.1814</td>
<td style="text-align: right;">0.0883</td>
<td style="text-align: right;">-2.0531</td>
<td style="text-align: right;">0.0401</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="fragment">
<p><br> <strong>Model equation</strong>:</p>
<ul>
<li>Log Odds of Readmission = -0.183 + (-0.1814) x Discharge Readiness</li>
</ul>
</div>
<div class="fragment">
<ol type="1">
<li>For each one-unit increase in discharge readiness (IV), the <strong>log odds</strong> of readmission change by -0.1814.</li>
<li>The p-value for discharge readiness is 0.0401, which indicates the effect of discharge readiness on readmission is statistically significant.</li>
</ol>
</div>
</section>
<section id="step-2-converting-to-odds-ratio" class="slide level2">
<h2>Step 2: Converting to Odds Ratio</h2>
<p>Log odds ratios are hard to interpret. <strong>Exponentiate</strong> to get odds ratios:</p>
<div style="font-size: 0.75em;">
<ul>
<li><code>coef()</code>: to get regression coefficients (log odds ratios)</li>
<li><code>exp()</code>: to exponentiate log odds ratios to get odds ratios</li>
</ul>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a aria-hidden="true" tabindex="-1"></a>odds_ratios <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(model_simple))</span>
<span id="cb6-2"><a aria-hidden="true" tabindex="-1"></a>odds_ratios</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        (Intercept) discharge_readiness 
          0.8327902           0.8341325 </code></pre>
</div>
</div>
<div class="fragment">
<p><strong>Interpretation</strong>:</p>
<div style="font-size: 0.75em;">
<ul>
<li class="fragment"><strong>Direction</strong>: Odds ratio is LESS than 1 -&gt; higher discharge readiness = LOWER odds of readmission</li>
<li class="fragment"><strong>Magnitude</strong>: For each 1-point increase in discharge readiness, odds of readmission DECREASE by 16.6%</li>
</ul>
</div>
</div>
</section>
<section id="step-3-predicting-probabilities" class="slide level2 scrollable">
<h2>Step 3: Predicting Probabilities</h2>
<p>We can use the logistic regression model to get a predicted probability. For a patient with discharge readiness = 5:</p>
<ol type="1">
<li class="fragment"><strong>Log odds</strong> = -0.183 + (-0.181) x 5 = -1.0898</li>
<li class="fragment"><strong>Odds</strong> = <span class="math inline">\(e^{-1.0898}\)</span> = 0.3363</li>
<li class="fragment"><strong>Probability</strong> = 0.3363 / (1 + 0.3363) = 0.2517 (<strong>25.2%</strong>)</li>
</ol>
</section>
<section id="step-4-using-rs-predict-function" class="slide level2">
<h2>Step 4: Using R’s predict() Function</h2>
<p>Let’s get the predicted probabilities of readmission for a range of discharge readiness scores using R’s <code>predict()</code> function with <code>type = "response"</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-hidden="true" tabindex="-1"></a>new_patients <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb8-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">discharge_readiness =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>)</span>
<span id="cb8-3"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a aria-hidden="true" tabindex="-1"></a>new_patients<span class="sc">$</span>predicted_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_simple,</span>
<span id="cb8-6"><a aria-hidden="true" tabindex="-1"></a>                                        <span class="at">newdata =</span> new_patients,</span>
<span id="cb8-7"><a aria-hidden="true" tabindex="-1"></a>                                        <span class="at">type =</span> <span class="st">"response"</span>) <span class="co"># to get predicted probabilities, type = "response" is required. Without it, you would get log odds instead.</span></span>
<span id="cb8-8"><a aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">head</span>(new_patients, <span class="dv">3</span>), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  discharge_readiness predicted_prob
1                   4          0.287
2                   5          0.252
3                   6          0.219</code></pre>
</div>
</div>
</section>
<section id="step-5-visualizing-predicted-probabilities" class="slide level2">
<h2>Step 5: Visualizing Predicted Probabilities</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb10-2"><a aria-hidden="true" tabindex="-1"></a>pred_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">discharge_readiness =</span> <span class="fu">seq</span>(<span class="dv">3</span>, <span class="dv">10</span>, <span class="at">by =</span> <span class="fl">0.1</span>))</span>
<span id="cb10-3"><a aria-hidden="true" tabindex="-1"></a>pred_data<span class="sc">$</span>probability <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_simple, <span class="at">newdata =</span> pred_data, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb10-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb10-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> pred_data, <span class="fu">aes</span>(<span class="at">x =</span> discharge_readiness, <span class="at">y =</span> probability),</span>
<span id="cb10-7"><a aria-hidden="true" tabindex="-1"></a>            <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb10-8"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> readmit_data, <span class="fu">aes</span>(<span class="at">x =</span> discharge_readiness, <span class="at">y =</span> readmitted),</span>
<span id="cb10-9"><a aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">height =</span> <span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb10-10"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fl">0.5</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray50"</span>) <span class="sc">+</span></span>
<span id="cb10-11"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Predicted Probability of Readmission by Discharge Readiness Score"</span>,</span>
<span id="cb10-12"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Points show actual outcomes (0 = not readmitted, 1 = readmitted)"</span>,</span>
<span id="cb10-13"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Discharge Readiness Score"</span>,</span>
<span id="cb10-14"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Predicted Probability of Readmission"</span>) <span class="sc">+</span></span>
<span id="cb10-15"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">labels =</span> scales<span class="sc">::</span>percent) <span class="sc">+</span></span>
<span id="cb10-16"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb10-17"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Slide13_files/figure-revealjs/fig-simple-predict-viz-1.png" id="fig-simple-predict-viz" width="864" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;4
</p></section>
<section id="step-6-from-probabilities-to-decisions" class="slide level2">
<h2>Step 6: From Probabilities to Decisions</h2>
<p>Our model gives us <strong>probabilities</strong>, but in practice we often need to make <strong>binary decisions</strong> (e.g., “provide extra discharge support” vs.&nbsp;“standard discharge”).</p>
<div class="fragment">
<p><br> To classify patients, we use a <strong>decision threshold</strong> (default = 0.5):</p>
<ul>
<li>If predicted probability ≥ 0.5 → predict <strong>readmitted</strong> (1)</li>
<li>If predicted probability &lt; 0.5 → predict <strong>not readmitted</strong> (0)</li>
</ul>
</div>
<div class="fragment">
<p><br> We then compare our predictions to actual outcomes using a <strong>classification table</strong> (also called a <strong>confusion matrix</strong>).</p>
</div>
</section>
<section id="understanding-the-classification-table" class="slide level2">
<h2>Understanding the Classification Table</h2>
<p>The confusion matrix has four possible outcomes:</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;"><strong>Actual: Not Readmitted</strong></th>
<th style="text-align: center;"><strong>Actual: Readmitted</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Predicted: Not Readmitted</strong></td>
<td style="text-align: center;">True Negative (TN)</td>
<td style="text-align: center;">False Negative (FN)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Predicted: Readmitted</strong></td>
<td style="text-align: center;">False Positive (FP)</td>
<td style="text-align: center;">True Positive (TP)</td>
</tr>
</tbody>
</table>
<p><br></p>
<ul>
<li><strong>True Negative (TN)</strong>: Correctly predicted NOT readmitted</li>
<li><strong>True Positive (TP)</strong>: Correctly predicted readmitted</li>
<li><strong>False Positive (FP)</strong>: Predicted readmitted, but was NOT (false alarm)</li>
<li><strong>False Negative (FN)</strong>: Predicted NOT readmitted, but WAS (miss)</li>
</ul>
</section>
<section id="our-models-classification-table" class="slide level2">
<h2>Our Model’s Classification Table</h2>
<p>Let’s make a classification table for our simple logistic regression model using a 0.5 threshold:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-hidden="true" tabindex="-1"></a>readmit_data<span class="sc">$</span>predicted_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_simple, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb11-2"><a aria-hidden="true" tabindex="-1"></a>readmit_data<span class="sc">$</span>predicted_class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(readmit_data<span class="sc">$</span>predicted_prob <span class="sc">&gt;=</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb11-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a aria-hidden="true" tabindex="-1"></a>class_table <span class="ot">&lt;-</span> <span class="fu">table</span>(</span>
<span id="cb11-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">Predicted =</span> <span class="fu">factor</span>(readmit_data<span class="sc">$</span>predicted_class, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)),</span>
<span id="cb11-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">Actual =</span> <span class="fu">factor</span>(readmit_data<span class="sc">$</span>readmitted, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb11-7"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-8"><a aria-hidden="true" tabindex="-1"></a>class_table</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted   0   1
        0 156  44
        1   0   0</code></pre>
</div>
</div>
<div class="fragment">
<p><strong>Accuracy</strong> = (TP + TN) / Total = 156 / 200 = <strong>78%</strong></p>
</div>
</section></section>
<section>
<section id="practice-1-simple-logistic-regression" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>3. Practice 1: Simple Logistic Regression</h1>

</section>
<section id="practice-1-medication-adherence" class="slide level2">
<h2>Practice 1: Medication Adherence</h2>
<p><strong>Scenario</strong>: A pharmacy wants to understand whether the number of medications a patient takes predicts whether they actually take their medications as prescribed.</p>
<div class="fragment">
<p><br> <strong>Sample &amp; data</strong>: The dataset contains records for <strong>100 patients</strong> from a single community pharmacy. For each patient, staff recorded the <strong>number of medications</strong> currently prescribed and whether the patient was classified as <strong>adherent</strong> (1 = took medications as prescribed, 0 = did not) based on refill history and self-report during a follow-up visit.</p>
</div>
<div class="fragment">
<p><br> <strong>Hypothesis</strong>: When patients have more medications to take, it becomes harder to keep track of everything; more pills to remember, different times of day, and more possible side effects. So we expect patients with more medications to be <strong>less likely to take their medications as prescribed</strong>.</p>
</div>
</section>
<section id="practice-1-load-data" class="slide level2">
<h2>Practice 1: Load Data</h2>
<p>Let’s load the data using the code below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Medication adherence data</span></span>
<span id="cb13-2"><a aria-hidden="true" tabindex="-1"></a>adherence_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week13_adherence.data.csv"</span>)</span>
<span id="cb13-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a aria-hidden="true" tabindex="-1"></a><span class="co"># View the data</span></span>
<span id="cb13-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(adherence_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X patient_id num_medications adherent
1 1          1               9        0
2 2          2               7        1
3 3          3               3        0
4 4          4               4        1
5 5          5               7        1</code></pre>
</div>
</div>
</section>
<section id="practice-1-key-variables" class="slide level2">
<h2>Practice 1: Key Variables</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>patient_id</code></td>
<td>Unique identifier for each patient</td>
<td>ID</td>
</tr>
<tr class="even">
<td><code>num_medications</code></td>
<td>Number of medications the patient is taking</td>
<td>Continuous</td>
</tr>
<tr class="odd">
<td><code>adherent</code></td>
<td>Whether the patient is adherent to medication (1 = yes, 0 = no) — <strong>outcome</strong></td>
<td>Binary</td>
</tr>
</tbody>
</table>
</section>
<section id="practice-1-tasks-13" class="slide level2">
<h2>Practice 1: Tasks (1/3)</h2>
<p><strong>Task 1</strong>: Explore the data</p>
<p>Let’s first explore the relationship between the number of medications and adherence rates by creating medication groups.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a aria-hidden="true" tabindex="-1"></a>adherence_summary <span class="ot">&lt;-</span> adherence_data <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">med_group =</span> <span class="fu">cut</span>(num_medications,</span>
<span id="cb15-3"><a aria-hidden="true" tabindex="-1"></a>                         <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">12</span>),</span>
<span id="cb15-4"><a aria-hidden="true" tabindex="-1"></a>                         <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"1-4 meds"</span>, <span class="st">"5-8 meds"</span>, <span class="st">"9-12 meds"</span>))) <span class="sc">%&gt;%</span> <span class="co"># create medication groups</span></span>
<span id="cb15-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(___) <span class="sc">%&gt;%</span></span>
<span id="cb15-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb15-7"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">n_patients =</span> <span class="fu">n</span>(),</span>
<span id="cb15-8"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">adherence_rate =</span> <span class="fu">round</span>(<span class="fu">mean</span>(___) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb15-9"><a aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-10"><a aria-hidden="true" tabindex="-1"></a>adherence_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="practice-1-tasks-23" class="slide level2">
<h2>Practice 1: Tasks (2/3)</h2>
<p><strong>Task 2</strong>: Run simple logistic regression</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-hidden="true" tabindex="-1"></a>model_adhere <span class="ot">&lt;-</span> <span class="fu">glm</span>(___ <span class="sc">~</span> ___,</span>
<span id="cb16-2"><a aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> ___,</span>
<span id="cb16-3"><a aria-hidden="true" tabindex="-1"></a>                    <span class="at">family =</span> ___)</span>
<span id="cb16-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_adhere)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<p><br> <strong>Task 3</strong>: Calculate and interpret odds ratio</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a aria-hidden="true" tabindex="-1"></a>or_medications <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">___</span>(model_adhere)[<span class="st">"num_medications"</span>])</span>
<span id="cb17-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(or_medications, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>
<section id="practice-1-tasks-33" class="slide level2">
<h2>Practice 1: Tasks (3/3)</h2>
<p><strong>Task 4</strong>: Make predictions for three new patients</p>
<p>Use your fitted model to predict the probability of adherence for the following patients:</p>
<ul>
<li><strong>Patient A</strong> — takes <strong>2 medications</strong></li>
<li><strong>Patient B</strong> — takes <strong>6 medications</strong></li>
<li><strong>Patient C</strong> — takes <strong>10 medications</strong></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-hidden="true" tabindex="-1"></a>new_patients <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">num_medications =</span> <span class="fu">c</span>(___, ___, ___))</span>
<span id="cb18-2"><a aria-hidden="true" tabindex="-1"></a>new_patients<span class="sc">$</span>predicted_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(___,</span>
<span id="cb18-3"><a aria-hidden="true" tabindex="-1"></a>                                       <span class="at">newdata =</span> ___,</span>
<span id="cb18-4"><a aria-hidden="true" tabindex="-1"></a>                                       <span class="at">type =</span> ___)</span>
<span id="cb18-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(new_patients, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section></section>
<section>
<section id="multiple-logistic-regression" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>4. Multiple Logistic Regression</h1>

</section>
<section id="what-is-it-when-to-use-it-1" class="slide level2">
<h2>What Is It? / When to Use It</h2>
<p><strong>Multiple logistic regression</strong> includes <strong>two or more predictors</strong> to predict a binary outcome.</p>
<div class="fragment">
<p><br> <strong>Use it when:</strong></p>
<ul>
<li class="fragment">Your <strong>outcome is binary</strong> (0/1)</li>
<li class="fragment">You have <strong>multiple predictor variables</strong> (continuous, categorical, or both)</li>
<li class="fragment">You want the <strong>independent effect</strong> of each predictor while <strong>controlling for</strong> other variables</li>
</ul>
</div>
</section>
<section id="example-case-comprehensive-readmission-model" class="slide level2">
<h2>Example Case: Comprehensive Readmission Model</h2>
<p>Our <code>readmit_data</code> already contains additional predictors:</p>
<ul>
<li class="fragment"><strong>Discharge Readiness</strong>: Discharge readiness score (1-10)</li>
<li class="fragment"><strong>Age</strong>: Patient age in years</li>
<li class="fragment"><strong>Comorbidities</strong>: Number of chronic conditions</li>
<li class="fragment"><strong>Insurance</strong>: Private, Medicare, or Medicaid (reference)</li>
</ul>
<div class="fragment">
<p><br></p>
<p><strong>The questions we have are</strong>:</p>
<ul>
<li>Does discharge readiness still predict readmission when we account for age, health complexity, and insurance type?</li>
<li>And, what are the effects of <strong>age</strong>, <strong>health complexity</strong>, and <strong>insurance type</strong> on the odds of readmission?</li>
</ul>
</div>
</section>
<section id="running-multiple-logistic-regression" class="slide level2">
<h2>Running Multiple Logistic Regression</h2>
<p>We can run a multiple logistic regression model by including all predictors in the formula with the same <code>glm()</code> function and <code>family = binomial</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a aria-hidden="true" tabindex="-1"></a>model_multiple <span class="ot">&lt;-</span> <span class="fu">glm</span>(readmitted <span class="sc">~</span> discharge_readiness <span class="sc">+</span> age <span class="sc">+</span> comorbidities <span class="sc">+</span> insurance,</span>
<span id="cb19-2"><a aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> readmit_data,</span>
<span id="cb19-3"><a aria-hidden="true" tabindex="-1"></a>                      <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb19-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_multiple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="running-multiple-logistic-regression-output" class="slide level2 output-location-slide"><h2>Running Multiple Logistic Regression</h2><div class="cell output-location-slide">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = readmitted ~ discharge_readiness + age + comorbidities + 
    insurance, family = binomial(link = "logit"), data = readmit_data)

Coefficients:
                    Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)         -2.18252    1.28948  -1.693  0.09054 .  
discharge_readiness -0.21828    0.09580  -2.278  0.02270 *  
age                  0.03432    0.01666   2.061  0.03933 *  
comorbidities        0.40688    0.13602   2.991  0.00278 ** 
insuranceMedicare   -1.18757    0.44030  -2.697  0.00699 ** 
insurancePrivate    -1.71410    0.49612  -3.455  0.00055 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 210.76  on 199  degrees of freedom
Residual deviance: 182.55  on 194  degrees of freedom
AIC: 194.55

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div></section><section id="interpreting-multiple-predictors-odds-ratios" class="slide level2">
<h2>Interpreting Multiple Predictors: Odds Ratios</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top" style="margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Log.Odds.Ratio</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Odds.Ratio</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-2.1825</td>
<td style="text-align: right;">0.1128</td>
<td style="text-align: right;">0.0905</td>
</tr>
<tr class="even">
<td style="text-align: left;">discharge_readiness</td>
<td style="text-align: right;">-0.2183</td>
<td style="text-align: right;">0.8039</td>
<td style="text-align: right;">0.0227</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0.0343</td>
<td style="text-align: right;">1.0349</td>
<td style="text-align: right;">0.0393</td>
</tr>
<tr class="even">
<td style="text-align: left;">comorbidities</td>
<td style="text-align: right;">0.4069</td>
<td style="text-align: right;">1.5021</td>
<td style="text-align: right;">0.0028</td>
</tr>
<tr class="odd">
<td style="text-align: left;">insuranceMedicare</td>
<td style="text-align: right;">-1.1876</td>
<td style="text-align: right;">0.3050</td>
<td style="text-align: right;">0.0070</td>
</tr>
<tr class="even">
<td style="text-align: left;">insurancePrivate</td>
<td style="text-align: right;">-1.7141</td>
<td style="text-align: right;">0.1801</td>
<td style="text-align: right;">0.0006</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="fragment">
<p><br> <strong>Each coefficient represents the effect while holding all other variables constant.</strong></p>
</div>
</section>
<section id="interpreting-each-predictor" class="slide level2">
<h2>Interpreting Each Predictor</h2>
<ul>
<li class="fragment"><strong>Discharge Readiness</strong> (OR = 0.804, p = 0.0227): Each 1-point increase -&gt; odds of readmission DECREASE by 19.6%, holding other variables constant</li>
<li class="fragment"><strong>Age</strong> (OR = 1.0349, p = 0.0393): Each additional year -&gt; odds increase by 3.5%</li>
<li class="fragment"><strong>Comorbidities</strong> (OR = 1.502, p = 0.0028): Each additional condition -&gt; odds increase by 50.2%</li>
<li class="fragment"><strong>Insurance (Medicare)</strong> (OR = 0.305, p = 0.007): Compared to Medicaid, Medicare patients have 69.5% lower odds of readmission</li>
<li class="fragment"><strong>Insurance (Private)</strong> (OR = 0.18, p = 0.00055): Compared to Medicaid, Private insurance patients have 82% lower odds of readmission</li>
</ul>
</section>
<section id="making-predictions-manual-calculation" class="slide level2 scrollable">
<h2>Making Predictions: Manual Calculation</h2>
<p>Let’s predict readmission probability for a patient manually:</p>
<ul>
<li>Discharge readiness = 6, Age = 65, Comorbidities = 2, Insurance = Medicare</li>
</ul>
<ol type="1">
<li class="fragment"><strong>Log odds</strong> = -2.183 + (-0.218) x 6 + (0.034) x 65 + (0.407) x 2 + (-1.188) x 1 = -1.6349</li>
<li class="fragment"><strong>Odds</strong> = <span class="math inline">\(e^{-1.6349}\)</span> = 0.195</li>
<li class="fragment"><strong>Probability</strong> = 0.195 / (1 + 0.195) = 0.1632 (<strong>16.3%</strong>)</li>
</ol>
</section>
<section id="making-predictions-using-predict" class="slide level2">
<h2>Making Predictions: Using <code>predict()</code></h2>
<p>We can more easily use <code>predict()</code> with <code>type = "response"</code> to obtain predicted probabilities for multiple patients at once. Consider three hypothetical patients:</p>
<div style="font-size: 0.75em;">
<ul>
<li><strong>Patient A</strong>: discharge readiness = 8, age = 50, 1 comorbidity, Private insurance</li>
<li><strong>Patient B</strong>: discharge readiness = 6, age = 65, 2 comorbidities, Medicare</li>
<li><strong>Patient C</strong>: discharge readiness = 4, age = 80, 4 comorbidities, Medicaid</li>
</ul>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a aria-hidden="true" tabindex="-1"></a>patient_profiles <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb21-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">discharge_readiness =</span> <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">6</span>, <span class="dv">4</span>),</span>
<span id="cb21-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">65</span>, <span class="dv">80</span>),</span>
<span id="cb21-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">comorbidities =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>),</span>
<span id="cb21-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">insurance =</span> <span class="fu">c</span>(<span class="st">"Private"</span>, <span class="st">"Medicare"</span>, <span class="st">"Medicaid"</span>)</span>
<span id="cb21-6"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-7"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a aria-hidden="true" tabindex="-1"></a>patient_profiles<span class="sc">$</span>predicted_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_multiple,</span>
<span id="cb21-9"><a aria-hidden="true" tabindex="-1"></a>                                           <span class="at">newdata =</span> patient_profiles,</span>
<span id="cb21-10"><a aria-hidden="true" tabindex="-1"></a>                                           <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb21-11"><a aria-hidden="true" tabindex="-1"></a>patient_profiles</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  discharge_readiness age comorbidities insurance predicted_prob
1                   8  50             1   Private     0.02875452
2                   6  65             2  Medicare     0.16315549
3                   4  80             4  Medicaid     0.78882182</code></pre>
</div>
</div>
</section>
<section id="evaluating-the-multiple-regression-model" class="slide level2">
<h2>Evaluating the Multiple Regression Model</h2>
<p>Let’s check the accuracy of our multiple logistic regression model by creating a classification table using the same 0.5 threshold:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a aria-hidden="true" tabindex="-1"></a>readmit_data<span class="sc">$</span>pred_prob_multiple <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_multiple, <span class="at">type =</span> <span class="st">"response"</span>) <span class="co"># getting predicted probabilities of the data</span></span>
<span id="cb23-2"><a aria-hidden="true" tabindex="-1"></a>readmit_data<span class="sc">$</span>pred_class_multiple <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(readmit_data<span class="sc">$</span>pred_prob_multiple <span class="sc">&gt;=</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>) <span class="co"># classification</span></span>
<span id="cb23-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a aria-hidden="true" tabindex="-1"></a>class_table_multiple <span class="ot">&lt;-</span> <span class="fu">table</span>(</span>
<span id="cb23-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">Predicted =</span> readmit_data<span class="sc">$</span>pred_class_multiple,</span>
<span id="cb23-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">Actual =</span> readmit_data<span class="sc">$</span>readmitted</span>
<span id="cb23-7"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-8"><a aria-hidden="true" tabindex="-1"></a>class_table_multiple</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Actual
Predicted   0   1
        0 153  36
        1   3   8</code></pre>
</div>
</div>
<div class="fragment">
<p><strong>Multiple regression accuracy</strong>: 80.5% (161 / 200 patients correctly classified)</p>
</div>
</section></section>
<section>
<section id="practice-2-multiple-logistic-regression" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>5. Practice 2: Multiple Logistic Regression</h1>

</section>
<section id="practice-2-surgical-complication-risk" class="slide level2">
<h2>Practice 2: Surgical Complication Risk</h2>
<p><strong>Scenario</strong>: A surgical department wants to predict the risk of post-operative complications from patient age, BMI, surgery duration, and surgery type.</p>
<div class="fragment">
<p><br> <strong>Sample &amp; data</strong>: The dataset contains records for <strong>180 patients</strong> who underwent surgery at a single hospital. For each patient, the team recorded <strong>age</strong>, <strong>BMI</strong>, <strong>surgery duration (minutes)</strong>, whether the surgery was <strong>elective or emergency</strong>, and whether the patient experienced a <strong>post-operative complication</strong> (1 = yes, 0 = no) within 30 days of surgery.</p>
</div>
<div class="fragment">
<p><br> <strong>Hypothesis</strong>: Older patients, patients with higher BMI, longer surgeries, and emergency (vs.&nbsp;elective) procedures are each expected to be associated with <strong>higher odds of complications</strong>.</p>
</div>
</section>
<section id="practice-2-load-data" class="slide level2">
<h2>Practice 2: Load Data</h2>
<p>Let’s start by loading the surgical complications dataset and converting <code>surgery_type</code> into a factor so R treats it as a categorical variable:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Surgical complication data</span></span>
<span id="cb25-2"><a aria-hidden="true" tabindex="-1"></a>surgery_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week13_surgery_data.csv"</span>)</span>
<span id="cb25-3"><a aria-hidden="true" tabindex="-1"></a>surgery_data<span class="sc">$</span>surgery_type <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(surgery_data<span class="sc">$</span>surgery_type)</span>
<span id="cb25-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a aria-hidden="true" tabindex="-1"></a><span class="co"># View the data</span></span>
<span id="cb25-6"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(surgery_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X patient_id age  bmi surgery_duration surgery_type complication
1 1          1  68 24.1              170     Elective            1
2 2          2  44 34.6               30    Emergency            0
3 3          3  62 29.3               30    Emergency            0
4 4          4  59 33.1               62     Elective            1
5 5          5  50 29.1              168    Emergency            0</code></pre>
</div>
</div>
</section>
<section id="practice-2-key-variables" class="slide level2">
<h2>Practice 2: Key Variables</h2>
<p>Before we build the model, let’s review the variables we’ll be working with:</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>patient_id</code></td>
<td>Unique identifier for each patient</td>
<td>ID</td>
</tr>
<tr class="even">
<td><code>age</code></td>
<td>Patient age in years</td>
<td>Continuous</td>
</tr>
<tr class="odd">
<td><code>bmi</code></td>
<td>Body mass index (weight relative to height)</td>
<td>Continuous</td>
</tr>
<tr class="even">
<td><code>surgery_duration</code></td>
<td>Duration of surgery in minutes</td>
<td>Continuous</td>
</tr>
<tr class="odd">
<td><code>surgery_type</code></td>
<td>Type of surgery (Elective or Emergency)</td>
<td>Categorical</td>
</tr>
<tr class="even">
<td><code>complication</code></td>
<td>Whether a post-operative complication occurred (1 = yes, 0 = no) — <strong>outcome</strong></td>
<td>Binary</td>
</tr>
</tbody>
</table>
</section>
<section id="practice-2-tasks-12" class="slide level2">
<h2>Practice 2: Tasks (1/2)</h2>
<p>Now it’s your turn. Fit a multiple logistic regression model using all four predictors, then interpret what each coefficient tells you about complication risk.</p>
<p><strong>Task 1</strong>: Run multiple logistic regression</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a aria-hidden="true" tabindex="-1"></a>model_surg <span class="ot">&lt;-</span> <span class="fu">glm</span>(complication <span class="sc">~</span> ___ <span class="sc">+</span> ___ <span class="sc">+</span> ___ <span class="sc">+</span> ___,</span>
<span id="cb27-2"><a aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> ___,</span>
<span id="cb27-3"><a aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> ___)</span>
<span id="cb27-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(___)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<p><br> <strong>Task 2</strong>: Interpret odds ratios</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">___</span>(<span class="fu">___</span>(model_surg)), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>
<section id="practice-2-tasks-22" class="slide level2">
<h2>Practice 2: Tasks (2/2)</h2>
<p><strong>Task 3</strong>: Predict for three patient profiles</p>
<p>Suppose we have three new patient profiles. Using the multiple logistic regression model you just fitted, predict each patient’s probability of experiencing a post-surgery complication.</p>
<ul>
<li><strong>Patient A</strong> — age 45, BMI 24, 90-min elective surgery</li>
<li><strong>Patient B</strong> — age 65, BMI 30, 150-min elective surgery</li>
<li><strong>Patient C</strong> — age 80, BMI 38, 210-min emergency surgery</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a aria-hidden="true" tabindex="-1"></a>patient_profiles <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb29-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">c</span>(___, ___, ___),</span>
<span id="cb29-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">bmi =</span> <span class="fu">c</span>(___, ___, ___),</span>
<span id="cb29-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">surgery_duration =</span> <span class="fu">c</span>(___, ___, ___),</span>
<span id="cb29-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">surgery_type =</span> <span class="fu">c</span>(___, ___, ___)</span>
<span id="cb29-6"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb29-7"><a aria-hidden="true" tabindex="-1"></a>patient_profiles<span class="sc">$</span>predicted_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(___, <span class="at">newdata =</span> ___, <span class="at">type =</span> ___)</span>
<span id="cb29-8"><a aria-hidden="true" tabindex="-1"></a>patient_profiles</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section></section>
<section>
<section id="summary" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Summary</h1>

</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<ul>
<li class="fragment"><strong>Logistic regression</strong> is for explaining or predicting <strong>binary outcomes</strong>
<ul>
<li class="fragment">Use <code>glm()</code> with <code>family = binomial</code> in R</li>
</ul></li>
<li class="fragment">Coefficients are <strong>log odds ratios</strong>. Exponentiate with <code>exp()</code> to get <strong>odds ratios</strong>
<ul>
<li class="fragment"><strong>Odds ratio &lt; 1</strong> = decreases risk; <strong>OR = 1</strong> = no effect; <strong>OR &gt; 1</strong> = increases risk</li>
</ul></li>
<li class="fragment">In <strong>multiple regression</strong>, each coefficient shows the <strong>individual effect</strong> holding other variables constant</li>
<li class="fragment"><strong>Accuracy</strong> measures the overall percentage of correct predictions
<ul>
<li class="fragment">The <strong>confusion matrix</strong> is helpful to understand where errors occur</li>
<li class="fragment">In healthcare, consider which type of error (false positive vs.&nbsp;false negative) is <strong>more costly</strong> for your specific application</li>
</ul></li>
</ul>
</section>
<section id="assignments" class="slide level2 scrollable">
<h2>Assignments</h2>
<ol type="1">
<li><strong>Week 14 Reflection</strong>: Please share your thoughts on the lecture</li>
</ol>
<ul>
<li>3 interesting things</li>
<li>3 confusing or unclear things</li>
</ul>
<ol start="2" type="1">
<li><strong>Lab Assignment 6</strong>: Logistic Regression</li>
</ol>
<p>Both are due by 11:59 PM on Sunday, April 19.</p>
</section>
<section id="references" class="slide level2">
<h2>References</h2>
<div style="font-size: 0.85em;">
<ul>
<li>Hosmer, D. W., Lemeshow, S., &amp; Sturdivant, R. X. (2013). <em>Applied Logistic Regression</em> (3rd ed.). Wiley.</li>
<li>Weiss, M. E., Piacentine, L. B., Lokken, L., Ancona, J., Archer, J., Ber, S., … &amp; Vega-Stromberg, T. (2007). Perceived readiness for hospital discharge in adult medical-surgical patients. <em>Clinical Nurse Specialist</em>, 21(1), 31-42.</li>
<li>Wang, X., Juntasopeepun, P., Panuthai, S., &amp; Suwankruhasn, N. (2025). Factors influencing medication adherence among Chinese older adults with physical multimorbidity and polypharmacy: A cross-sectional study. <em>Nursing &amp; Health Sciences</em>, 27(3), e70192.</li>
<li>Dharap, S. B., Barbaniya, P., &amp; Navgale, S. (2022). Incidence and risk factors of postoperative complications in general surgery patients. <em>Cureus</em>, 14(11), e30975.</li>
</ul>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Week 14 | Logistic Regression</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>