project:
  type: website
  output-dir: "docs"


website:
  title: "Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      # - href: assignments.qmd
      #   text: Assignments
        
    right:
    - icon: github
      href: https://github.com/mba642-spring-26/mba642-spring-26.github.io/

format:
  html:
    theme: simple
    css: styles.css
    toc: true

editor: visual

