project:
  type: website
  output-dir: "docs"


website:
  title: "business analytics in healthcare management (MBA 642)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - href: assignments.qmd
        text: Assignments
        
    right:
    - icon: github
      href: https://github.com/mba642-spring-26/mba642-spring-26.github.io/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

