---
title: "Course Schedule"
tbl-colwidths: [5,10,40,10,10,15]
format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    code-fold: false
    code-tools: false
---

The schedule can vary depending on the progress of the course or unforeseen circumstances. </br>\
Any changes will be announced in class and posted on the course website and Canvas.\<\br\>

::: column-screen-inset-right
| Week | Date | Topic | Lecture Notes | Practice Files | Assignments |
|:----------:|:----------:|:-----------|:----------:|:-----------:|:-----------:|
| 1 | Jan 14 | Introduction & Course Overview | [{{< fa file-lines >}}](/lectures/Lecture01/Lecture01.qmd){target="_blank"} | \- | \- |
| 2 | Jan 21 | A primer on R, R-Studio, and R-Markdown + Data Wrangling | [{{< fa file-lines >}}](/lectures/Lecture02/Lecture02.qmd){target="_blank"} | [{{< fa file-lines >}}](/lectures/Lecture02/Practice02.qmd){target="_blank"} | \- |
| 3 | Jan 28 | Basic Statistical Concepts | [{{< fa file-lines >}}](/lectures/Lecture03/Lecture03.qmd){target="_blank"} | [{{< fa file-lines >}}](/lectures/Lecture03/Practice03.qmd){target="_blank"} | Assignment 1 |
| 4 | Feb 4 | Data visualization | [{{< fa file-lines >}}](/lectures/Lecture04/Lecture04.qmd){target="_blank"} | [{{< fa file-lines >}}](/lectures/Lecture04/Practice04.qmd){target="_blank"} | Assignment 2 |
| 5 | Feb 11 | Mean difference 1: t-test | [{{< fa file-lines >}}](/lectures/Lecture05/Lecture05.qmd){target="_blank"} | [{{< fa file-lines >}}](/lectures/Lecture05/Practice05.qmd){target="_blank"} | Assignment 3 |
| 6 | Feb 18 | Mean difference 2: ANOVA 1 | [{{< fa file-lines >}}](/lectures/Lecture06/Lecture06.qmd){target="_blank"} | [{{< fa file-lines >}}](/lectures/Lecture06/Practice06.qmd){target="_blank"} | \- |
| 7 | Feb 25 | Mean difference 2: ANOVA 2 | [{{< fa file-lines >}}](/lectures/Lecture07/Lecture07.qmd){target="_blank"} | [{{< fa file-lines >}}](/lectures/Lecture07/Practice07.qmd){target="_blank"} | Assignment 4 |
| 8 | Mar 4 | Crosstab and correlation | [{{< fa file-lines >}}](/lectures/Lecture08/Lecture08.qmd){target="_blank"} | [{{< fa file-lines >}}](/lectures/Lecture08/Practice08.qmd){target="_blank"} | Assignment 5 |
| 9 | Mar 11 | Midterm Exam | \- | \- | \- |
| 10 | Mar 18 | Spring break (no class) | \- | \- | \- |
| 11 | Mar 25 | Linear regression analysis 1 | [{{< fa file-lines >}}](/lectures/Lecture11/Lecture11.qmd){target="_blank"} | [{{< fa file-lines >}}](/lectures/Lecture11/Practice11.qmd){target="_blank"} |  |
| 12 | Apr 1 | Linear regression analysis 2 | [{{< fa file-lines >}}](/lectures/Lecture12/Lecture12.qmd){target="_blank"} | [{{< fa file-lines >}}](/lectures/Lecture12/Practice12.qmd){target="_blank"} | Assignment 6 |
| 13 | Apr 8 | Logistic regression analysis | [{{< fa file-lines >}}](/lectures/Lecture13/Lecture13.qmd){target="_blank"} | [{{< fa file-lines >}}](/lectures/Lecture13/Practice13.qmd){target="_blank"} | Assignment 7 |
| 14 | Apr 15 | Conjoint analysis | [{{< fa file-lines >}}](/lectures/Lecture14/Lecture14.qmd){target="_blank"} | [{{< fa file-lines >}}](/lectures/Lecture14/Practice14.qmd){target="_blank"} | Assignment 8 |
| 15 | Apr 22 | Predictive analytics 1: Penalized Regression | [{{< fa file-lines >}}](/lectures/Lecture15/Lecture15.qmd){target="_blank"} | [{{< fa file-lines >}}](/lectures/Lecture15/Practice15.qmd){target="_blank"} | Assignment 9 |
| 16 | Apr 29 | Predictive analytics 2: Decision Trees | [{{< fa file-lines >}}](/lectures/Lecture16/Lecture16.qmd){target="_blank"} | [{{< fa file-lines >}}](/lectures/Lecture16/Practice16.qmd){target="_blank"} | Assignment 10 |
| 17 | May 6 | Final Exam | \- | \- | \- |
:::

[*b1: Statistics for Health Data Science: An Organic Approach*]{style="font-size: 12px;"}

[*b2: Statistical Analytics for Health Data Science with SAS and R*]{style="font-size: 12px;"}

[*Assignments will be informed during the class*]{style="font-size: 12px;"}