---
title: "Course Schedule"
tbl-colwidths: [10,10,40,20]
format:
  pdf:
    theme: cosmo
    geometry:
      - margin=1in
    fontsize: 10pt
    include-in-header:
      text: |
        \renewcommand{\arraystretch}{1.3}
    include-before-body:
      text: |
        \vspace{-5em}
---

The schedule can vary depending on the progress of the course or unforeseen circumstances.

Any changes will be announced in class and posted on the course website and Canvas.

| Week | Date | Topic | Assignments |
|:---------------:|:---------------:|:--------------------|:---------------:|
| 1 | Jan 14 | Introduction & Course Overview | \- |
| 2 | Jan 21 | R, R-Studio, Quarto, and Data Wrangling | Reflection 1 |
| 3 | Jan 28 | Basic Statistical Concepts | Reflection 2 |
| 4 | Feb 4 | Data visualization | Reflection 3, Assignment 1 |
| 5 | Feb 11 | Mean difference 1: t-test | Reflection 4, Assignment 2 |
| 6 | Feb 18 | Mean difference 2: ANOVA 1 | Reflection 5 |
| 7 | Feb 25 | Mean difference 2: ANOVA 2 | Reflection 6, Assignment 3 |
| 8 | Mar 4 | Crosstab and correlation | Reflection 7, Assignment 4 |
| 9 | Mar 11 | Midterm Exam | \- |
| 10 | Mar 18 | Spring break (no class) | \- |
| 11 | Mar 25 | Linear regression analysis 1 | Reflection 8 |
| 12 | Apr 1 | Linear regression analysis 2 | Reflection 9, Assignment 5 |
| 13 | Apr 8 | Logistic regression analysis | Reflection 10, Assignment 6 |
| 14 | Apr 15 | Conjoint analysis | Reflection 11, Assignment 7 |
| 15 | Apr 22 | Predictive analytics: Penalized Regression | Reflection 12, Assignment 8 |
| 16 | Apr 29 | Predictive analytics: Decision Trees | Reflection 13, Assignment 9 |
| 17 | May 6 | Final Exam | \- |

*Assignments will be informed during the class*