<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="">
  <meta name="dcterms.date" content="2026-04-22">
  <title>Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026) – Conjoint Analysis</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-65c0fb729604bfe8efe950e5016ef687.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
  <link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Conjoint Analysis</h1>
  <p class="subtitle">Week 15</p>

<div class="quarto-title-authors">
</div>

  <p class="date">2026-04-22</p>
</section>
<section id="todays-learning-goals" class="slide level2 scrollable">
<h2>Today’s Learning Goals</h2>
<p>By the end of this lecture, you will be able to:</p>
<ol type="1">
<li class="fragment"><strong>Explain</strong> what conjoint analysis is and why it’s valuable in healthcare management</li>
<li class="fragment"><strong>Estimate</strong> part-worth utilities using both rating-based and choice-based methods</li>
<li class="fragment"><strong>Calculate</strong> attribute importance and willingness-to-pay from conjoint results</li>
<li class="fragment"><strong>Predict</strong> market shares for competing product/service configurations</li>
</ol>
</section>
<section>
<section id="introduction-to-conjoint-analysis" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>1. Introduction to Conjoint Analysis</h1>

</section>
<section id="what-is-conjoint-analysis" class="slide level2">
<h2>What is Conjoint Analysis?</h2>
<p><strong>Conjoint analysis</strong> is a survey-based technique to understand how people make decisions when facing <strong>trade-offs</strong> between multiple attributes.</p>
<div class="fragment">
<p><br></p>
<p>The term “conjoint” comes from <strong>“considered jointly”</strong>; we study how attributes are evaluated together rather than in isolation.</p>
</div>
<div class="fragment">
<p><br></p>
<p>Asking “Do you prefer low cost?” always gets a “yes.” But asking someone to <strong>choose</strong> between a low-cost option with long wait times vs.&nbsp;a high-cost option with short wait times reveals their <strong>true priorities</strong>.</p>
</div>
</section>
<section id="why-conjoint-analysis-in-healthcare" class="slide level2">
<h2>Why Conjoint Analysis in Healthcare?</h2>
<p>Healthcare managers face constant service design decisions:</p>
<ul>
<li class="fragment"><strong>Insurance plan design</strong>: What combination of premium, deductible, and coverage will attract people?</li>
<li class="fragment"><strong>Clinic operations</strong>: Should we prioritize shorter wait times or extended hours?</li>
<li class="fragment"><strong>Telehealth services</strong>: Do patients value video consultations enough to pay more?</li>
</ul>
<div class="fragment">
<p><br></p>
<p>Conjoint analysis <strong>quantifies</strong> these preferences by forcing realistic trade-offs.</p>
</div>
</section>
<section id="key-outputs-from-conjoint-analysis" class="slide level2 scrollable">
<h2>Key Outputs from Conjoint Analysis</h2>
<ol type="1">
<li class="fragment"><strong>Part-Worth Utilities</strong>: Numeric scores for how much value a person derives from each attribute level</li>
<li class="fragment"><strong>Attribute Importance</strong>: Which features have the biggest impact on preferences</li>
<li class="fragment"><strong>Willingness-to-Pay (WTP)</strong>: How much extra someone would pay for an improvement in an attribute</li>
<li class="fragment"><strong>Market Share Prediction</strong>: What percentage of people would choose one option over another</li>
</ol>
</section>
<section id="two-approaches" class="slide level2">
<h2>Two Approaches</h2>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Rating-Based</th>
<th style="text-align: center;">Choice-Based</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Task</strong></td>
<td style="text-align: center;">Rate each profile (1-10)</td>
<td style="text-align: center;">Choose preferred from a set</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Analysis</strong></td>
<td style="text-align: center;">OLS linear regression</td>
<td style="text-align: center;">Multinomial logit</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>Pros</strong></td>
<td style="text-align: center;">Simple, builds on familiar methods</td>
<td style="text-align: center;">Mimics real decisions, forces trade-offs</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Cons</strong></td>
<td style="text-align: center;">May not reveal true trade-offs</td>
<td style="text-align: center;">Requires more data prep</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><br></p>
<p><strong>Choice-based</strong> is generally preferred in practice because it better reflects actual decision-making behavior.</p>
</div>
</section></section>
<section>
<section id="rating-based-conjoint-analysis" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>2. Rating-Based Conjoint Analysis</h1>

</section>
<section id="scenario-health-insurance-plan-selection" class="slide level2">
<h2>Scenario: Health Insurance Plan Selection</h2>
<p>A leading application of conjoint analysis in healthcare is modeling how employees choose health insurance plans during open enrollment.</p>
<div class="fragment">
<p><br> Our example uses three key attributes:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Attribute</th>
<th style="text-align: center;">Level 1</th>
<th style="text-align: center;">Level 2</th>
<th style="text-align: center;">Why It Matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Monthly Premium</td>
<td style="text-align: center;">$200</td>
<td style="text-align: center;">$300</td>
<td style="text-align: center;">Direct, visible cost</td>
</tr>
<tr class="even">
<td style="text-align: center;">Annual Deductible</td>
<td style="text-align: center;">$500</td>
<td style="text-align: center;">$1,500</td>
<td style="text-align: center;">Amount paid before coverage</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Network Size</td>
<td style="text-align: center;">Large</td>
<td style="text-align: center;">Small</td>
<td style="text-align: center;">Access to doctors/hospitals</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p><br> We can construct different insurance plans by combining the attribute levels.</p>
</div>
</section>
<section id="conceptual-overview" class="slide level2">
<h2>Conceptual Overview</h2>
<p>In rating-based conjoint, respondents rate hypothetical profiles one at a time:</p>
<div class="fragment">
<ul>
<li><strong>Profile 1</strong>: Premium $200, Deductible $1,500, Small network (<em>Rate 1-10:</em> <strong>4/10</strong>)</li>
</ul>
</div>
<div class="fragment">
<ul>
<li><strong>Profile 2</strong>: Premium $300, Deductible $500, Large network (<em>Rate 1-10:</em> <strong>7/10</strong>)</li>
</ul>
</div>
<div class="fragment">
<p><br></p>
<p>By collecting ratings for multiple profiles across many respondents, we use <strong>regression</strong> to decompose each rating into the contribution of each attribute.</p>
</div>
</section>
<section id="the-statistical-model" class="slide level2">
<h2>The Statistical Model</h2>
<p>Rating-based conjoint uses <strong>OLS regression</strong>:</p>
<p><span class="math display">\[\text{Rating} = \beta_0 + \beta_1(\text{Premium}) + \beta_2(\text{Deductible}) + \beta_3(\text{Network}) + \varepsilon\]</span></p>
<div class="fragment">
<p><br></p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> = intercept (baseline rating)</li>
<li><span class="math inline">\(\beta_1, \beta_2, \beta_3\)</span> = <strong>part-worth utilities</strong> for each attribute</li>
<li>The coefficients directly tell us how much each attribute contributes to the rating</li>
</ul>
</div>
<div class="fragment">
<p><br></p>
<p><strong>Variable coding</strong>: Premium and Deductible are continuous (dollars); Network is categorical (converted to a factor with Small as reference).</p>
</div>
</section>
<section id="generating-the-experimental-design" class="slide level2">
<h2>Generating the Experimental Design</h2>
<p>With 3 attributes × 2 levels each, we have <span class="math inline">\(2^3 = 8\)</span> possible profiles (<strong>full factorial design</strong>):</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top" style="margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Premium ($)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Deductible ($)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Network</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Profile ID</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">200</td>
<td style="text-align: center;">500</td>
<td style="text-align: center;">Small</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">300</td>
<td style="text-align: center;">500</td>
<td style="text-align: center;">Small</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">200</td>
<td style="text-align: center;">1500</td>
<td style="text-align: center;">Small</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="even">
<td style="text-align: center;">300</td>
<td style="text-align: center;">1500</td>
<td style="text-align: center;">Small</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">200</td>
<td style="text-align: center;">500</td>
<td style="text-align: center;">Large</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: center;">300</td>
<td style="text-align: center;">500</td>
<td style="text-align: center;">Large</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">200</td>
<td style="text-align: center;">1500</td>
<td style="text-align: center;">Large</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td style="text-align: center;">300</td>
<td style="text-align: center;">1500</td>
<td style="text-align: center;">Large</td>
<td style="text-align: center;">8</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="loading-survey-data" class="slide level2">
<h2>Loading Survey Data</h2>
<p>Let’s load the dataset and required packages:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Required packages for rating-based conjoint</span></span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)   </span>
<span id="cb1-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a aria-hidden="true" tabindex="-1"></a>rating_insurance <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week14_rating_insurance_data.csv"</span>)</span>
<span id="cb1-5"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Convert network to a factor (Small = reference level)</span></span>
<span id="cb1-7"><a aria-hidden="true" tabindex="-1"></a>rating_insurance <span class="ot">&lt;-</span> rating_insurance <span class="sc">%&gt;%</span></span>
<span id="cb1-8"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">network =</span> <span class="fu">factor</span>(network, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Small"</span>, <span class="st">"Large"</span>)))</span>
<span id="cb1-9"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rating_insurance, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  respondent_id profile_id premium deductible network rating
1             1          1     200        500   Small    6.0
2             1          2     300        500   Small    4.0
3             1          3     200       1500   Small    5.1
4             1          4     300       1500   Small    3.8
5             1          5     200        500   Large    6.0</code></pre>
</div>
</div>
</section>
<section id="estimating-part-worth-utilities" class="slide level2">
<h2>Estimating Part-Worth Utilities</h2>
<p>Now that the data is prepared, let’s fit an <strong>OLS regression</strong> of <code>rating</code> on the three attributes. The estimated coefficients are exactly the <strong>part-worth utilities</strong> (the “value” each attribute level adds or subtracts).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a>model_rating_ins <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> premium <span class="sc">+</span> deductible <span class="sc">+</span> network,</span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> rating_insurance)</span>
<span id="cb3-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_rating_ins)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="estimating-part-worth-utilities-output" class="slide level2 output-location-slide"><h2>Estimating Part-Worth Utilities</h2><div class="cell output-location-slide">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = rating ~ premium + deductible + network, data = rating_insurance)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.29525 -0.35625  0.00475  0.31625  1.52975 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   8.512e+00  9.679e-02   87.94   &lt;2e-16 ***
premium      -1.161e-02  3.477e-04  -33.39   &lt;2e-16 ***
deductible   -7.725e-04  3.477e-05  -22.22   &lt;2e-16 ***
networkLarge  5.525e-01  3.477e-02   15.89   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4917 on 796 degrees of freedom
Multiple R-squared:  0.7005,    Adjusted R-squared:  0.6993 
F-statistic: 620.5 on 3 and 796 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div></section><section id="interpreting-the-coefficients" class="slide level2">
<h2>Interpreting the Coefficients</h2>
<p>The regression coefficients <strong>are</strong> the part-worth utilities:</p>
<ul>
<li class="fragment"><strong>Premium</strong> (-0.0116): Each $100 increase in premium decreases the rating by 1.16 points</li>
<li class="fragment"><strong>Deductible</strong> (-0.0008): Each $1,000 increase in deductible decreases rating by 0.80 points</li>
<li class="fragment"><strong>networkLarge</strong> (0.55): Having a large network increases rating by 0.55 points</li>
</ul>
</section>
<section id="calculating-attribute-importance" class="slide level2 scrollable">
<h2>Calculating Attribute Importance</h2>
<p>The attribute whose levels produce the largest utility <strong>range</strong> has the most power to influence preferences (i.e., respondents are more sensitive to changes in that attribute).</p>
<div class="fragment">
<p><br></p>
<p><strong>Steps</strong>:</p>
<ol type="1">
<li>Calculate the utility range for each attribute (highest − lowest)</li>
<li>Sum all ranges</li>
<li>Express each as a percentage of the total</li>
</ol>
</div>
<div class="fragment">
<p>Importance scores depend entirely on the levels tested. Testing $200 vs $201 would make premium appear unimportant! Always choose levels that reflect realistic market variation when designing the study.</p>
</div>
</section>
<section id="attribute-importance-calculation" class="slide level2">
<h2>Attribute Importance: Calculation</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the estimated coefficients (part-worth utilities) from the model</span></span>
<span id="cb5-2"><a aria-hidden="true" tabindex="-1"></a>coef_ins <span class="ot">&lt;-</span> <span class="fu">coef</span>(model_rating_ins)</span>
<span id="cb5-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Utility range = |coefficient| * (level span). For continuous attributes,</span></span>
<span id="cb5-5"><a aria-hidden="true" tabindex="-1"></a><span class="co"># multiply by the high-minus-low level to get the full utility swing.</span></span>
<span id="cb5-6"><a aria-hidden="true" tabindex="-1"></a>range_premium    <span class="ot">&lt;-</span> <span class="fu">abs</span>(coef_ins[<span class="st">"premium"</span>]      <span class="sc">*</span> (<span class="dv">300</span> <span class="sc">-</span> <span class="dv">200</span>))    <span class="co"># $200 -&gt; $300</span></span>
<span id="cb5-7"><a aria-hidden="true" tabindex="-1"></a>range_deductible <span class="ot">&lt;-</span> <span class="fu">abs</span>(coef_ins[<span class="st">"deductible"</span>]   <span class="sc">*</span> (<span class="dv">1500</span> <span class="sc">-</span> <span class="dv">500</span>))   <span class="co"># $500 -&gt; $1500</span></span>
<span id="cb5-8"><a aria-hidden="true" tabindex="-1"></a><span class="co"># For the categorical factor, the coefficient itself IS the range (Large vs. Small)</span></span>
<span id="cb5-9"><a aria-hidden="true" tabindex="-1"></a>range_network    <span class="ot">&lt;-</span> <span class="fu">abs</span>(coef_ins[<span class="st">"networkLarge"</span>] <span class="sc">*</span> <span class="dv">1</span>)</span>
<span id="cb5-10"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Sum of ranges = denominator for computing each attribute's importance share</span></span>
<span id="cb5-12"><a aria-hidden="true" tabindex="-1"></a>total_range <span class="ot">&lt;-</span> range_premium <span class="sc">+</span> range_deductible <span class="sc">+</span> range_network</span>
<span id="cb5-13"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a aria-hidden="true" tabindex="-1"></a>importance_rating_ins <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb5-15"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">attribute =</span> <span class="fu">c</span>(<span class="st">"Monthly Premium"</span>, <span class="st">"Annual Deductible"</span>, <span class="st">"Network Size"</span>),</span>
<span id="cb5-16"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">utility_range =</span> <span class="fu">round</span>(<span class="fu">c</span>(range_premium, range_deductible, range_network), <span class="dv">3</span>),</span>
<span id="cb5-17"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">importance_pct =</span> <span class="fu">round</span>(<span class="fu">c</span>(range_premium, range_deductible, range_network) <span class="sc">/</span> total_range <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">3</span>)</span>
<span id="cb5-18"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-19"><a aria-hidden="true" tabindex="-1"></a>importance_rating_ins</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                     attribute utility_range importance_pct
premium        Monthly Premium         1.161         46.702
deductible   Annual Deductible         0.772         31.074
networkLarge      Network Size         0.552         22.224</code></pre>
</div>
</div>
</section>
<section id="attribute-importance-visualization" class="slide level2">
<h2>Attribute Importance: Visualization</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(importance_rating_ins, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(attribute, importance_pct),</span>
<span id="cb7-2"><a aria-hidden="true" tabindex="-1"></a>                                   <span class="at">y =</span> importance_pct)) <span class="sc">+</span></span>
<span id="cb7-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb7-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb7-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(importance_pct, <span class="dv">2</span>), <span class="st">"%"</span>)),</span>
<span id="cb7-6"><a aria-hidden="true" tabindex="-1"></a>            <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.1</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb7-7"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Attribute Importance: Health Insurance Plan Selection"</span>,</span>
<span id="cb7-8"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Rating-Based Conjoint Analysis"</span>,</span>
<span id="cb7-9"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb7-10"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Relative Importance (%)"</span>,</span>
<span id="cb7-11"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Importance = utility range as % of total range"</span>) <span class="sc">+</span></span>
<span id="cb7-12"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb7-13"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)) <span class="sc">+</span></span>
<span id="cb7-14"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="fu">max</span>(importance_rating_ins<span class="sc">$</span>importance_pct) <span class="sc">*</span> <span class="fl">1.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Slide14_files/figure-revealjs/fig-rating-importance-1.png" id="fig-rating-importance" width="864" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;1
</p></section>
<section id="willingness-to-pay-wtp" class="slide level2">
<h2>Willingness-to-Pay (WTP)</h2>
<p>Part-worth utilities are informative, but they live in “utility units” which are hard to interpret or act on. Managers and executives think in <strong>dollars</strong>.</p>
<p>WTP translates the abstract utility gain from an attribute into the concrete price premium customers would accept for it, making the results directly usable for pricing, product design, and ROI decisions.</p>
<div class="fragment">
<p><br></p>
<p>WTP converts utility values into <strong>dollar amounts</strong>:</p>
<p><span class="math display">\[\text{WTP} = -\frac{\beta_{\text{attribute}}}{\beta_{\text{cost}}}\]</span></p>
</div>
<div class="fragment">
<p><br></p>
<p>The basic idea: we divide the utility gain from an attribute by the “utility cost” of $1 of premium. The negative sign flips the premium’s negative coefficient so WTP comes out as a positive dollar value.</p>
</div>
</section>
<section id="computing-wtp" class="slide level2">
<h2>Computing WTP</h2>
<p><strong>A. WTP for a Large network (vs.&nbsp;Small):</strong></p>
<p><span class="math display">\[\text{WTP}_{\text{network}} = -\frac{\beta_{\text{networkLarge}}}{\beta_{\text{premium}}} = -\frac{0.5525}{-0.0116} \approx \$47.63\]</span></p>
<div class="fragment">
<p><br></p>
<p><strong>B. WTP for a $1,000 lower deductible:</strong></p>
<p>A $1,000 <em>reduction</em> in deductible produces a utility gain of <span class="math inline">\(-1000 \times \beta_{\text{deductible}}\)</span>; divide by <span class="math inline">\(-\beta_{\text{premium}}\)</span> to convert to dollars:</p>
<p><span class="math display">\[\text{WTP}_{\text{\$1k deductible}} = \frac{-1000 \times \beta_{\text{deductible}}}{-\beta_{\text{premium}}} = \frac{-1000 \times (-0.0008)}{-(-0.0116)} \approx \$68.97\]</span></p>
<p><br></p>
<p><small><em>Note: coefficients are rounded to 4 decimals here for readability, so the WTP values shown may differ slightly from R’s output, which uses the full-precision coefficients.</em></small></p>
</div>
</section>
<section id="computing-wtp-in-r" class="slide level2">
<h2>Computing WTP: In R</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># A. Large network (vs. Small)</span></span>
<span id="cb8-2"><a aria-hidden="true" tabindex="-1"></a>wtp_network <span class="ot">&lt;-</span> <span class="sc">-</span>coef_ins[<span class="st">"networkLarge"</span>] <span class="sc">/</span> coef_ins[<span class="st">"premium"</span>]</span>
<span id="cb8-3"><a aria-hidden="true" tabindex="-1"></a>wtp_network</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>networkLarge 
    47.58829 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># B. $1,000 lower deductible</span></span>
<span id="cb10-2"><a aria-hidden="true" tabindex="-1"></a>utility_gain_deductible  <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">1000</span> <span class="sc">*</span> coef_ins[<span class="st">"deductible"</span>]</span>
<span id="cb10-3"><a aria-hidden="true" tabindex="-1"></a>wtp_deductible_reduction <span class="ot">&lt;-</span> utility_gain_deductible <span class="sc">/</span> <span class="sc">-</span>coef_ins[<span class="st">"premium"</span>]</span>
<span id="cb10-4"><a aria-hidden="true" tabindex="-1"></a>wtp_deductible_reduction</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>deductible 
  66.53747 </code></pre>
</div>
</div>
</section>
<section id="wtp-results-managerial-insight" class="slide level2">
<h2>WTP Results &amp; Managerial Insight</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Attribute</th>
<th style="text-align: center;">WTP per Month</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Large Network (vs.&nbsp;Small)</td>
<td style="text-align: center;">$47.59</td>
</tr>
<tr class="even">
<td style="text-align: center;">$1,000 Lower Deductible</td>
<td style="text-align: center;">$66.54</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><br></p>
<p>WTP turns customer preferences into a <strong>direct input for profit/cost decisions</strong>.</p>
</div>
<div class="fragment">
<ul>
<li>For example, if:
<ul>
<li>Expanding to <strong>a larger provider network</strong> costs about <strong>$30/member/month</strong>. Each member adds about <strong>$17.59/month</strong> in net contribution.</li>
<li>Absorbing <strong>a $1,000 deductible reduction</strong> costs about <strong>$80/member/month</strong>. Each member produces a net <strong>loss</strong> of about <strong>$13.46/month</strong>.</li>
</ul></li>
</ul>
</div>
</section>
<section id="market-share-simulation-the-two-plans" class="slide level2 scrollable">
<h2>Market Share Simulation: The Two Plans</h2>
<p>If the insurer offered two hypothetical plans side-by-side, what fraction of customers would likely choose each one? Conjoint results let us predict market share <em>before</em> launching the product.</p>
<div class="fragment">
<p><br></p>
<p><strong>How we’ll compute it</strong>:</p>
<ol type="1">
<li>use the fitted regression to predict each plan’s overall rating (i.e., its expected utility), then</li>
<li>divide each plan’s rating by the total of all plan ratings (<strong>proportional allocation</strong>). The plan with the higher rating captures the larger share.</li>
</ol>
<p><span class="math display">\[\text{share}_j = \frac{\text{rating}_j}{\sum_{k=1}^{K} \text{rating}_k}\]</span></p>
</div>
</section>
<section id="market-share-simulation-two-candidate-plans" class="slide level2">
<h2>Market Share Simulation: Two Candidate Plans</h2>
<p>We’ll compare two plans:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Plan</th>
<th style="text-align: center;">Premium</th>
<th style="text-align: center;">Deductible</th>
<th style="text-align: center;">Network</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Premium Plan (A)</strong></td>
<td style="text-align: center;">$250</td>
<td style="text-align: center;">$500</td>
<td style="text-align: center;">Large</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Budget Plan (B)</strong></td>
<td style="text-align: center;">$200</td>
<td style="text-align: center;">$1,500</td>
<td style="text-align: center;">Small</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><br></p>
<p>If both plans were offered side-by-side, what <strong>market share</strong> would each plan capture?</p>
</div>
</section>
<section id="market-share-simulation-compute-ratings" class="slide level2">
<h2>Market Share Simulation: Compute Ratings</h2>
<p><strong>Step 1</strong>: Get the predicted rating (overall utility) of each plan:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a aria-hidden="true" tabindex="-1"></a>plan_A <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">name =</span> <span class="st">"Premium Plan"</span>, <span class="at">premium =</span> <span class="dv">250</span>, <span class="at">deductible =</span> <span class="dv">500</span>, <span class="at">network =</span> <span class="st">"Large"</span>)</span>
<span id="cb12-2"><a aria-hidden="true" tabindex="-1"></a>plan_B <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">name =</span> <span class="st">"Budget Plan"</span>, <span class="at">premium =</span> <span class="dv">200</span>, <span class="at">deductible =</span> <span class="dv">1500</span>, <span class="at">network =</span> <span class="st">"Small"</span>)</span>
<span id="cb12-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Predicted rating = plug each plan's attribute values into the model</span></span>
<span id="cb12-5"><a aria-hidden="true" tabindex="-1"></a>rating_A <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_rating_ins, plan_A)</span>
<span id="cb12-6"><a aria-hidden="true" tabindex="-1"></a>rating_B <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_rating_ins, plan_B)</span>
<span id="cb12-7"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Predicted Rating of Plan A is:"</span>, rating_A, <span class="st">"and predicted rating of Plan B is:"</span>, rating_B, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Predicted Rating of Plan A is: 5.77575 and predicted rating of Plan B is: 5.03125 </code></pre>
</div>
</div>
</section>
<section id="market-share-simulation-compute-shares" class="slide level2">
<h2>Market Share Simulation: Compute Shares</h2>
<p><strong>Step 2</strong>: Convert predicted ratings into market shares via <strong>proportional allocation</strong>: each plan’s share equals its rating divided by the sum of all plan ratings.</p>
<p><span class="math display">\[\text{share}_A = \frac{\text{rating}_A}{\text{rating}_A + \text{rating}_B}\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a aria-hidden="true" tabindex="-1"></a>total_rating <span class="ot">&lt;-</span> rating_A <span class="sc">+</span> rating_B</span>
<span id="cb14-2"><a aria-hidden="true" tabindex="-1"></a>share_A <span class="ot">&lt;-</span> rating_A <span class="sc">/</span> total_rating</span>
<span id="cb14-3"><a aria-hidden="true" tabindex="-1"></a>share_B <span class="ot">&lt;-</span> rating_B <span class="sc">/</span> total_rating</span>
<span id="cb14-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"The market share of Plan A is"</span>, <span class="fu">round</span>(share_A <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb14-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="st">"and the market share of Plan B is"</span>, <span class="fu">round</span>(share_B <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>The market share of Plan A is 53.4 %
 and the market share of Plan B is 46.6 %</code></pre>
</div>
</div>
</section>
<section id="market-share-simulation-results" class="slide level2">
<h2>Market Share Simulation: Results</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top" style="margin-left: auto; margin-right: auto;">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Plan</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Predicted Rating</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Market Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Plan A</td>
<td style="text-align: center;">5.78</td>
<td style="text-align: center;">53.4%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Plan B</td>
<td style="text-align: center;">5.03</td>
<td style="text-align: center;">46.6%</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="fragment">
<p><br></p>
<ul>
<li>The plan with the higher predicted rating captures the larger share. Managers can run this “what-if” for any number of candidate configurations to see which design would win the most customers.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Proportional allocation here is simple but lacks theoretical grounding (e.g., it ignores how people actually <em>choose</em> among options). Choice-based methods (next) are preferred for strategic decisions.</li>
</ul>
</div>
</section></section>
<section>
<section id="practice-1-rating-based-conjoint" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>3. Practice 1: Rating-Based Conjoint</h1>

</section>
<section id="practice-1-telehealth-program-preferences" class="slide level2">
<h2>Practice 1: Telehealth Program Preferences</h2>
<p><strong>Scenario</strong>: Your healthcare organization is designing a telehealth program with three key attributes:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Attribute</th>
<th style="text-align: center;">Level 1</th>
<th style="text-align: center;">Level 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Wait Time</td>
<td style="text-align: center;">Same-day</td>
<td style="text-align: center;">3 days</td>
</tr>
<tr class="even">
<td style="text-align: center;">Mode</td>
<td style="text-align: center;">Video</td>
<td style="text-align: center;">Phone</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Co-pay</td>
<td style="text-align: center;">$20</td>
<td style="text-align: center;">$40</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><br></p>
<p><strong>Questions we will address</strong>:</p>
<div style="font-size: 90%">
<ul>
<li>Which of the three attributes (wait time, mode, co-pay) matters most to patients?</li>
<li>How much extra would patients pay for same-day access and for video mode?</li>
<li>If we launch two programs with different attribute combinations, what share of patients would choose each?</li>
</ul>
</div>
</div>
</section>
<section id="practice-1-load-data" class="slide level2">
<h2>Practice 1: Load Data</h2>
<p>Load the dataset using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-hidden="true" tabindex="-1"></a>rating_telehealth <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week14_practice_data1.csv"</span>)</span>
<span id="cb16-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(rating_telehealth, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  respondent_id profile_id wait_sameday mode_video copay rating
1             1          1            1          1    20    6.2
2             1          2            0          1    20    4.4
3             1          3            1          0    20    5.1
4             1          4            0          0    20    3.9
5             1          5            1          1    40    5.3</code></pre>
</div>
</div>
</section>
<section id="practice-1-variables" class="slide level2">
<h2>Practice 1: Variables</h2>
<p>The dataset contains <strong>one row per rated profile per respondent</strong>, with the following columns:</p>
<div style="font-size: 90%">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: center;">Type</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>respondent_id</code></td>
<td style="text-align: center;">ID</td>
<td style="text-align: left;">Unique identifier for each respondent</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>wait_sameday</code></td>
<td style="text-align: center;">Dummy (0/1)</td>
<td style="text-align: left;"><code>1</code> = same-day appointment, <code>0</code> = 3-day wait</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>mode_video</code></td>
<td style="text-align: center;">Dummy (0/1)</td>
<td style="text-align: left;"><code>1</code> = video consultation, <code>0</code> = phone</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>copay</code></td>
<td style="text-align: center;">Continuous ($)</td>
<td style="text-align: left;">Co-pay amount ($20 or $40)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>rating</code></td>
<td style="text-align: center;">Outcome (1–10)</td>
<td style="text-align: left;">Respondent’s preference rating for the profile</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p><br></p>
<p><strong>Note</strong>: Wait time and mode are coded as dummies because they are categorical (two levels each). Co-pay is continuous so we can compute WTP by dividing other coefficients by <code>copay</code>’s coefficient.</p>
</div>
</section>
<section id="practice-1-tasks-13" class="slide level2">
<h2>Practice 1: Tasks (1/3)</h2>
<p><strong>Task 1</strong>: Estimate part-worth utilities</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-hidden="true" tabindex="-1"></a>model_rating_th <span class="ot">&lt;-</span> <span class="fu">lm</span>(rating <span class="sc">~</span> ___ <span class="sc">+</span> ___ <span class="sc">+</span> ___,</span>
<span id="cb18-2"><a aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> rating_telehealth)</span>
<span id="cb18-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_rating_th)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<p><strong>Task 2</strong>: Calculate attribute importance</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a aria-hidden="true" tabindex="-1"></a>coef_th <span class="ot">&lt;-</span> <span class="fu">coef</span>(model_rating_th)</span>
<span id="cb19-2"><a aria-hidden="true" tabindex="-1"></a>range_wait <span class="ot">&lt;-</span> <span class="fu">abs</span>(coef_th[<span class="st">"___"</span>] <span class="sc">*</span> <span class="dv">1</span>)</span>
<span id="cb19-3"><a aria-hidden="true" tabindex="-1"></a>range_mode <span class="ot">&lt;-</span> <span class="fu">abs</span>(coef_th[<span class="st">"___"</span>] <span class="sc">*</span> <span class="dv">1</span>)</span>
<span id="cb19-4"><a aria-hidden="true" tabindex="-1"></a>range_copay <span class="ot">&lt;-</span> <span class="fu">abs</span>(coef_th[<span class="st">"___"</span>] <span class="sc">*</span> (<span class="dv">40</span> <span class="sc">-</span> <span class="dv">20</span>))</span>
<span id="cb19-5"><a aria-hidden="true" tabindex="-1"></a>total_range_th <span class="ot">&lt;-</span> range_wait <span class="sc">+</span> range_mode <span class="sc">+</span> range_copay</span>
<span id="cb19-6"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a aria-hidden="true" tabindex="-1"></a>importance_rating_th <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb19-8"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">attribute =</span> <span class="fu">c</span>(<span class="st">"Wait Time"</span>, <span class="st">"Consultation Mode"</span>, <span class="st">"Co-pay"</span>),</span>
<span id="cb19-9"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">importance_pct =</span> <span class="fu">c</span>(range_wait, range_mode, range_copay) <span class="sc">/</span> total_range_th <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb19-10"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-11"><a aria-hidden="true" tabindex="-1"></a>importance_rating_th</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>
<section id="practice-1-tasks-23" class="slide level2">
<h2>Practice 1: Tasks (2/3)</h2>
<p><strong>Task 3</strong>: Calculate WTP</p>
<p>We want to know how much patients would pay for each upgrade:</p>
<div style="font-size: 90%;">
<ul>
<li><code>wtp_sameday</code>: how much more would patients pay for <strong>same-day access</strong> (vs.&nbsp;a 3-day wait)?</li>
<li><code>wtp_video</code>: how much more would patients pay for a <strong>video consultation</strong> (vs.&nbsp;phone)?</li>
</ul>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a aria-hidden="true" tabindex="-1"></a>wtp_sameday <span class="ot">&lt;-</span> <span class="sc">-</span>coef_th[<span class="st">"___"</span>] <span class="sc">/</span> coef_th[<span class="st">"___"</span>]</span>
<span id="cb20-2"><a aria-hidden="true" tabindex="-1"></a>wtp_video <span class="ot">&lt;-</span> <span class="sc">-</span>coef_th[<span class="st">"___"</span>] <span class="sc">/</span> coef_th[<span class="st">"___"</span>]</span>
<span id="cb20-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"WTP for Same-day access: $"</span>, <span class="fu">round</span>(wtp_sameday, <span class="dv">2</span>), <span class="st">" per visit</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb20-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"WTP for Video consultation: $"</span>, <span class="fu">round</span>(wtp_video, <span class="dv">2</span>), <span class="st">" per visit</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="practice-1-tasks-33" class="slide level2">
<h2>Practice 1: Tasks (3/3)</h2>
<p><strong>Task 4</strong>: Predict Market Shares</p>
<p>Suppose our organization could offer two telehealth programs side-by-side. What share of patients would choose each?</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Program</th>
<th style="text-align: center;">Wait</th>
<th style="text-align: center;">Mode</th>
<th style="text-align: center;">Co-pay</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><strong>Program A</strong></td>
<td style="text-align: center;">Same-day</td>
<td style="text-align: center;">Video</td>
<td style="text-align: center;">$40</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Program B</strong></td>
<td style="text-align: center;">3-day wait</td>
<td style="text-align: center;">Phone</td>
<td style="text-align: center;">$20</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a aria-hidden="true" tabindex="-1"></a>program_A <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">wait_sameday =</span> <span class="dv">1</span>, <span class="at">mode_video =</span> <span class="dv">1</span>, <span class="at">copay =</span> <span class="dv">40</span>)</span>
<span id="cb21-2"><a aria-hidden="true" tabindex="-1"></a>program_B <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">wait_sameday =</span> <span class="dv">0</span>, <span class="at">mode_video =</span> <span class="dv">0</span>, <span class="at">copay =</span> <span class="dv">20</span>)</span>
<span id="cb21-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Predict ratings, then allocate shares proportionally</span></span>
<span id="cb21-5"><a aria-hidden="true" tabindex="-1"></a>rating_A_th <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_rating_th, ____)</span>
<span id="cb21-6"><a aria-hidden="true" tabindex="-1"></a>rating_B_th <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_rating_th, ____)</span>
<span id="cb21-7"><a aria-hidden="true" tabindex="-1"></a>total_rating_th <span class="ot">&lt;-</span> rating_A_th <span class="sc">+</span> rating_B_th</span>
<span id="cb21-8"><a aria-hidden="true" tabindex="-1"></a>share_A_th <span class="ot">&lt;-</span> rating_A_th <span class="sc">/</span> total_rating_th</span>
<span id="cb21-9"><a aria-hidden="true" tabindex="-1"></a>share_B_th <span class="ot">&lt;-</span> rating_B_th <span class="sc">/</span> total_rating_th</span>
<span id="cb21-10"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Program A: "</span>, <span class="fu">round</span>(share_A_th <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb21-12"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Program B: "</span>, <span class="fu">round</span>(share_B_th <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section></section>
<section>
<section id="choice-based-conjoint-analysis" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>4. Choice-Based Conjoint Analysis</h1>

</section>
<section id="conceptual-overview-1" class="slide level2">
<h2>Conceptual Overview</h2>
<p>Choice-based conjoint (CBC), also called a <strong>Discrete Choice Experiment (DCE)</strong>, presents respondents with sets of competing product profiles and asks them to <strong>choose</strong> the one they most prefer:</p>
<div class="fragment">
<p>For example, <strong>Choice Set 1:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Plan A</th>
<th>Plan B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Premium</td>
<td>$200</td>
<td>$300</td>
</tr>
<tr class="even">
<td>Deductible</td>
<td>$1,500</td>
<td>$500</td>
</tr>
<tr class="odd">
<td>Network</td>
<td>Small</td>
<td>Large</td>
</tr>
</tbody>
</table>
<p><strong>Which plan would you choose?</strong></p>
</div>
<div class="fragment">
<p><br></p>
<p>When <strong>forced to choose</strong>, respondents must make explicit trade-offs (more like real-life decisions), revealing their true priorities.</p>
</div>
</section>
<section id="multinomial-logit-model-step-1-utility-of-each-alternative" class="slide level2">
<h2>Multinomial Logit Model: <br> Step 1: Utility of Each Alternative</h2>
<p>For each alternative <span class="math inline">\(i\)</span>, we define total utility as:</p>
<p><span class="math display">\[U_i = V_i + \varepsilon_i\]</span></p>
<ul>
<li><span class="math inline">\(V_i = \beta_1 X_{i1} + \beta_2 X_{i2} + ... + \beta_k X_{ik}\)</span> (<strong>systematic (observed) part</strong>; utility explained by the attributes we measure)</li>
<li><span class="math inline">\(\varepsilon_i\)</span> (<strong>random (unobserved) part</strong>; everything else that affects perceived utility but isn’t in our data)</li>
</ul>
<ul>
<li class="fragment">The coefficients (<span class="math inline">\(\beta\)</span>) are the <strong>part-worth utilities</strong> (each attribute’s contribution to total utility)</li>
<li class="fragment">We first compute <span class="math inline">\(V_i\)</span> for every alternative in a choice set</li>
</ul>
</section>
<section id="multinomial-logit-model-step-2-from-utility-to-choice-probability" class="slide level2">
<h2>Multinomial Logit Model: <br> Step 2: From Utility to Choice Probability</h2>
<p>People choose the alternative with the <strong>highest total utility</strong>. The <strong>multinomial logit formula</strong> converts systematic utilities into choice probabilities:</p>
<p><span class="math display">\[P(\text{Choose } i) = \frac{e^{V_i}}{\sum_{j=1}^{J} e^{V_j}}\]</span></p>
<ul>
<li class="fragment">Dividing by the sum forces the probabilities to be positive and sum to 1 across the <span class="math inline">\(J\)</span> alternatives</li>
<li class="fragment">Higher utility → <strong>exponentially</strong> higher choice probability (nonlinear)</li>
<li class="fragment">Small differences in <span class="math inline">\(V_i\)</span> can translate into large differences in choice share</li>
</ul>
<div class="fragment">
<p><small><strong>vs.&nbsp;logistic regression</strong>: logistic regression answers <em>“will you choose (yes/no)?”</em>, while multinomial logit answers <em>“which one will you choose?”</em>.</small></p>
</div>
</section>
<section id="recall-health-insurance-plan-selection" class="slide level2">
<h2>Recall: Health Insurance Plan Selection</h2>
<p>Same scenario as before — employees choosing health insurance plans during open enrollment — but now respondents <strong>pick one plan from a choice set</strong> instead of rating each plan individually.</p>
<p><br></p>
<p>Three attributes describe each plan:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Attribute</th>
<th style="text-align: center;">Level 1</th>
<th style="text-align: center;">Level 2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Monthly Premium</td>
<td style="text-align: center;">$200</td>
<td style="text-align: center;">$300</td>
</tr>
<tr class="even">
<td style="text-align: center;">Annual Deductible</td>
<td style="text-align: center;">$500</td>
<td style="text-align: center;">$1,500</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Network Size</td>
<td style="text-align: center;">Large</td>
<td style="text-align: center;">Small</td>
</tr>
</tbody>
</table>
</section>
<section id="example-choice-task" class="slide level2">
<h2>Example Choice Task</h2>
<p>For example: <strong>Which plan would you choose?</strong></p>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Attribute</th>
<th style="text-align: center;"><strong>Plan A</strong></th>
<th style="text-align: center;"><strong>Plan B</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Monthly Premium</td>
<td style="text-align: center;">$200</td>
<td style="text-align: center;">$300</td>
</tr>
<tr class="even">
<td style="text-align: center;">Annual Deductible</td>
<td style="text-align: center;">$1,500</td>
<td style="text-align: center;">$500</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Network Size</td>
<td style="text-align: center;">Small</td>
<td style="text-align: center;">Large</td>
</tr>
</tbody>
</table>
<p><br></p>
<div class="fragment">
<ul>
<li>Each respondent answers several such choice sets with different combinations of attribute levels.</li>
<li>Their pattern of choices reveals how they trade off premium, deductible, and network size.</li>
</ul>
</div>
</section>
<section id="loading-choice-data" class="slide level2">
<h2>Loading Choice Data</h2>
<p>Let’s load the dataset and required packages using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mlogit) <span class="co"># mlogit package for multinomial logit models</span></span>
<span id="cb22-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dfidx) <span class="co"># dfidx package for preparing data for choice models</span></span>
<span id="cb22-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a aria-hidden="true" tabindex="-1"></a>choice_long <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week14_choice_insurance_long.csv"</span>)</span>
<span id="cb22-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(choice_long, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  choice_set alternative premium deductible network_large choice
1      100_1           A     200        500             0      1
2      100_1           B     300        500             0      0
3      100_2           A     300       1500             1      0
4      100_2           B     200        500             0      1
5      100_3           A     300       1500             0      0</code></pre>
</div>
</div>
</section>
<section id="variables-in-the-choice-data" class="slide level2">
<h2>Variables in the Choice Data</h2>
<p>The dataset contains <strong>one row per alternative per choice set per respondent</strong>:</p>
<div style="font-size: 90%">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: center;">Type</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>choice_set</code></td>
<td style="text-align: center;">ID</td>
<td style="text-align: left;">Unique ID for each choice set (combines respondent and set number)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>alternative</code></td>
<td style="text-align: center;">ID</td>
<td style="text-align: left;">Plan label within the set (e.g., Plan A / Plan B)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>premium</code></td>
<td style="text-align: center;">Continuous ($)</td>
<td style="text-align: left;">Monthly premium ($200 or $300)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>deductible</code></td>
<td style="text-align: center;">Continuous ($)</td>
<td style="text-align: left;">Annual deductible ($500 or $1,500)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>network_large</code></td>
<td style="text-align: center;">Dummy (0/1)</td>
<td style="text-align: left;"><code>1</code> = Large network, <code>0</code> = Small network</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>choice</code></td>
<td style="text-align: center;">Outcome (0/1)</td>
<td style="text-align: left;"><code>1</code> if the respondent picked this alternative, <code>0</code> otherwise</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="step-1-indexing-the-data" class="slide level2">
<h2>Step 1: Indexing the Data</h2>
<ul>
<li>Before we can run a multinomial logistic regression, we need to tell R how the data is structured.</li>
<li><code>dfidx()</code> indexes the long-format data so R knows which rows belong to the same choice set and which column marks the chosen alternative.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a aria-hidden="true" tabindex="-1"></a>choice_mlogit <span class="ot">&lt;-</span> <span class="fu">dfidx</span>(choice_long,</span>
<span id="cb24-2"><a aria-hidden="true" tabindex="-1"></a>                       <span class="at">shape =</span> <span class="st">"long"</span>,           <span class="co"># one row per alternative</span></span>
<span id="cb24-3"><a aria-hidden="true" tabindex="-1"></a>                       <span class="at">choice =</span> <span class="st">"choice"</span>,         <span class="co"># column indicating chosen (1/0)</span></span>
<span id="cb24-4"><a aria-hidden="true" tabindex="-1"></a>                       <span class="at">idx =</span> <span class="fu">c</span>(<span class="st">"choice_set"</span>,      <span class="co"># groups alternatives into same set</span></span>
<span id="cb24-5"><a aria-hidden="true" tabindex="-1"></a>                               <span class="st">"alternative"</span>))    <span class="co"># identifies each alternative (A, B) within the choice set</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="step-2-model-estimation" class="slide level2">
<h2>Step 2: Model Estimation</h2>
<ul>
<li>With the data indexed, we can estimate the multinomial logit model using <code>mlogit()</code>. We regress <code>choice</code> on the plan attributes</li>
<li>The <code>| 0</code> drops alternative-specific intercepts since we only care about attribute effects.
<ul>
<li>The intercept captures any baseline preference for B over A when all attributes are equal. We drop it here because Plan A/B are arbitrary labels.</li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a aria-hidden="true" tabindex="-1"></a>model_mlogit_ins <span class="ot">&lt;-</span> <span class="fu">mlogit</span>(choice <span class="sc">~</span> premium <span class="sc">+</span> deductible <span class="sc">+</span> network_large <span class="sc">|</span> <span class="dv">0</span>,</span>
<span id="cb25-2"><a aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> choice_mlogit)</span>
<span id="cb25-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_mlogit_ins)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>

</section>
<section id="step-2-model-estimation-output" class="slide level2 output-location-slide"><h2>Step 2: Model Estimation</h2><div class="cell output-location-slide">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
mlogit(formula = choice ~ premium + deductible + network_large | 
    0, data = choice_mlogit, method = "nr")

Frequencies of alternatives:choice
      A       B 
0.52375 0.47625 

nr method
5 iterations, 0h:0m:0s 
g'(-H)^-1g = 8E-06 
successive function values within tolerance limits 

Coefficients :
                 Estimate  Std. Error  z-value  Pr(&gt;|z|)    
premium       -0.01372071  0.00120040 -11.4301 &lt; 2.2e-16 ***
deductible    -0.00063955  0.00011105  -5.7590 8.464e-09 ***
network_large  0.81453864  0.11329822   7.1893 6.510e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Log-Likelihood: -437.03</code></pre>
</div>
</div></section><section id="interpreting-choice-based-coefficients" class="slide level2">
<h2>Interpreting Choice-Based Coefficients</h2>
<p>The regression coefficients are log odds ratios, and they are used as part-worth utilities in the choice model:</p>
<ul>
<li class="fragment"><strong>Premium</strong> (-0.0137): Each $1 increase in premium <strong>decreases</strong> utility by 0.0137 points</li>
<li class="fragment"><strong>Deductible</strong> (-0.0006): Each $1 increase in deductible <strong>decreases</strong> utility by 0.0006 points</li>
<li class="fragment"><strong>network_large</strong> (0.8145): Large network <strong>increases</strong> utility by 0.8145 points</li>
</ul>
<div class="fragment">
<p><br></p>
<p>Higher utility → higher probability of being chosen, but the relationship is <strong>nonlinear</strong> (exponential).</p>
</div>
</section>
<section id="attribute-importance-choice-based" class="slide level2">
<h2>Attribute Importance (Choice-Based)</h2>
<p><strong>Same formula as before</strong>: for each attribute, compute the utility range across its levels (<span class="math inline">\(|\beta| \times\)</span> level spread), then divide by the total range across all attributes.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a aria-hidden="true" tabindex="-1"></a>coef_choice <span class="ot">&lt;-</span> <span class="fu">coef</span>(model_mlogit_ins)</span>
<span id="cb27-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a aria-hidden="true" tabindex="-1"></a>range_premium_c <span class="ot">&lt;-</span> <span class="fu">abs</span>(coef_choice[<span class="st">"premium"</span>] <span class="sc">*</span> (<span class="dv">300</span> <span class="sc">-</span> <span class="dv">200</span>))</span>
<span id="cb27-4"><a aria-hidden="true" tabindex="-1"></a>range_deductible_c <span class="ot">&lt;-</span> <span class="fu">abs</span>(coef_choice[<span class="st">"deductible"</span>] <span class="sc">*</span> (<span class="dv">1500</span> <span class="sc">-</span> <span class="dv">500</span>))</span>
<span id="cb27-5"><a aria-hidden="true" tabindex="-1"></a>range_network_c <span class="ot">&lt;-</span> <span class="fu">abs</span>(coef_choice[<span class="st">"network_large"</span>] <span class="sc">*</span> <span class="dv">1</span>)</span>
<span id="cb27-6"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a aria-hidden="true" tabindex="-1"></a>total_range_c <span class="ot">&lt;-</span> range_premium_c <span class="sc">+</span> range_deductible_c <span class="sc">+</span> range_network_c</span>
<span id="cb27-8"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a aria-hidden="true" tabindex="-1"></a>importance_choice_ins <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-10"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">attribute =</span> <span class="fu">c</span>(<span class="st">"Monthly Premium"</span>, <span class="st">"Annual Deductible"</span>, <span class="st">"Network Size"</span>),</span>
<span id="cb27-11"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">utility_range =</span> <span class="fu">c</span>(range_premium_c, range_deductible_c, range_network_c),</span>
<span id="cb27-12"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">importance_pct =</span> <span class="fu">c</span>(range_premium_c, range_deductible_c, range_network_c) <span class="sc">/</span> total_range_c <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb27-13"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-14"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-15"><a aria-hidden="true" tabindex="-1"></a>importance_choice_ins</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                      attribute utility_range importance_pct
premium         Monthly Premium     1.3720706       48.54902
deductible    Annual Deductible     0.6395459       22.62954
network_large      Network Size     0.8145386       28.82144</code></pre>
</div>
</div>
</section>
<section id="attribute-importance-choice-based-visualization" class="slide level2">
<h2>Attribute Importance (Choice-Based): Visualization</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(importance_choice_ins, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(attribute, importance_pct),</span>
<span id="cb29-2"><a aria-hidden="true" tabindex="-1"></a>                                   <span class="at">y =</span> importance_pct)) <span class="sc">+</span></span>
<span id="cb29-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb29-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb29-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(<span class="fu">round</span>(importance_pct, <span class="dv">2</span>), <span class="st">"%"</span>)),</span>
<span id="cb29-6"><a aria-hidden="true" tabindex="-1"></a>            <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.1</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb29-7"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Attribute Importance: Health Insurance Plan Selection"</span>,</span>
<span id="cb29-8"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Choice-Based Conjoint Analysis"</span>,</span>
<span id="cb29-9"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb29-10"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Relative Importance (%)"</span>,</span>
<span id="cb29-11"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Importance = utility range as % of total range"</span>) <span class="sc">+</span></span>
<span id="cb29-12"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb29-13"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>)) <span class="sc">+</span></span>
<span id="cb29-14"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="fu">max</span>(importance_choice_ins<span class="sc">$</span>importance_pct) <span class="sc">*</span> <span class="fl">1.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Slide14_files/figure-revealjs/fig-choice-importance-1.png" id="fig-choice-importance" width="864" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;2
</p></section>
<section id="willingness-to-pay-choice-based" class="slide level2">
<h2>Willingness-to-Pay (Choice-Based)</h2>
<p><strong>Same formula as rating-based</strong>:</p>
<p><span class="math display">\[\text{WTP} = -\frac{\beta_{\text{attribute}}}{\beta_{\text{cost}}}\]</span></p>
<div class="fragment">
<p><br></p>
<ul>
<li>In our example, the denominator is <span class="math inline">\(\beta_{\text{premium}}\)</span>, which tells us how much utility you lose per extra dollar in premium.</li>
<li>Dividing the utility gain of an attribute by that “utility cost of a dollar” converts the gain into dollars.</li>
</ul>
</div>
</section>
<section id="wtp-estimates-choice-based" class="slide level2">
<h2>WTP Estimates (Choice-Based)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the relevant coefficients</span></span>
<span id="cb30-2"><a aria-hidden="true" tabindex="-1"></a>beta_premium_c    <span class="ot">&lt;-</span> coef_choice[<span class="st">"premium"</span>]</span>
<span id="cb30-3"><a aria-hidden="true" tabindex="-1"></a>beta_deductible_c <span class="ot">&lt;-</span> coef_choice[<span class="st">"deductible"</span>]</span>
<span id="cb30-4"><a aria-hidden="true" tabindex="-1"></a>beta_network_c    <span class="ot">&lt;-</span> coef_choice[<span class="st">"network_large"</span>]</span>
<span id="cb30-5"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a aria-hidden="true" tabindex="-1"></a><span class="co"># WTP = -(utility gain) / (utility cost per $1 of premium)</span></span>
<span id="cb30-7"><a aria-hidden="true" tabindex="-1"></a>wtp_network_c    <span class="ot">&lt;-</span> <span class="sc">-</span>beta_network_c <span class="sc">/</span> beta_premium_c</span>
<span id="cb30-8"><a aria-hidden="true" tabindex="-1"></a>wtp_deductible_c <span class="ot">&lt;-</span> <span class="sc">-</span>(beta_deductible_c <span class="sc">*</span> <span class="sc">-</span><span class="dv">1000</span>) <span class="sc">/</span> beta_premium_c</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Attribute</th>
<th style="text-align: center;">WTP per Month</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Large Network (vs.&nbsp;Small)</td>
<td style="text-align: center;">$59.37</td>
</tr>
<tr class="even">
<td style="text-align: center;">$1,000 Lower Deductible</td>
<td style="text-align: center;">$46.61</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="market-share-choice-based" class="slide level2 scrollable">
<h2>Market Share (Choice-Based)</h2>
<p>Unlike rating-based conjoint (which uses proportional allocation), choice-based conjoint applies the <strong>multinomial logit formula</strong> directly:</p>
<p><span class="math display">\[P(\text{Choose } i) = \frac{e^{V_i}}{\sum_{j=1}^{J} e^{V_j}}\]</span></p>
<p>Two steps:</p>
<ol type="1">
<li>Compute the <strong>systematic utility</strong> <span class="math inline">\(V_i\)</span> of each plan from its attributes: <span class="math inline">\(V_i = \beta_{\text{premium}} \cdot \text{premium}_i + \beta_{\text{deductible}} \cdot \text{deductible}_i + \beta_{\text{network}} \cdot \text{network}_i\)</span></li>
<li>Plug the utilities into the logit formula to get each plan’s predicted <strong>choice share</strong>.</li>
</ol>
</section>
<section id="market-share-computing-utilities" class="slide level2">
<h2>Market Share: Computing Utilities</h2>
<p>Let’s compare two hypothetical plans:</p>
<ul>
<li><strong>Plan A</strong>: $250 premium, $500 deductible, Large network</li>
<li><strong>Plan B</strong>: $200 premium, $1,500 deductible, Small network</li>
</ul>
<p><strong>Step 1</strong>: Compute the systematic utility <span class="math inline">\(V_i\)</span> for each plan by plugging in the attribute levels and coefficients:</p>
<p><br></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a aria-hidden="true" tabindex="-1"></a>utility_A_c <span class="ot">&lt;-</span> coef_choice[<span class="st">"premium"</span>] <span class="sc">*</span> <span class="dv">250</span> <span class="sc">+</span></span>
<span id="cb31-2"><a aria-hidden="true" tabindex="-1"></a>               coef_choice[<span class="st">"deductible"</span>] <span class="sc">*</span> <span class="dv">500</span> <span class="sc">+</span></span>
<span id="cb31-3"><a aria-hidden="true" tabindex="-1"></a>               coef_choice[<span class="st">"network_large"</span>] <span class="sc">*</span> <span class="dv">1</span></span>
<span id="cb31-4"><a aria-hidden="true" tabindex="-1"></a>utility_B_c <span class="ot">&lt;-</span> coef_choice[<span class="st">"premium"</span>] <span class="sc">*</span> <span class="dv">200</span> <span class="sc">+</span></span>
<span id="cb31-5"><a aria-hidden="true" tabindex="-1"></a>               coef_choice[<span class="st">"deductible"</span>] <span class="sc">*</span> <span class="dv">1500</span> <span class="sc">+</span></span>
<span id="cb31-6"><a aria-hidden="true" tabindex="-1"></a>               coef_choice[<span class="st">"network_large"</span>] <span class="sc">*</span> <span class="dv">0</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="market-share-applying-the-logit-formula" class="slide level2">
<h2>Market Share: Applying the Logit Formula</h2>
<p><strong>Step 2</strong>: Convert utilities into choice probabilities using the multinomial logit formula:</p>
<p><span class="math display">\[P(\text{Choose } i) = \frac{e^{V_i}}{\sum_{j=1}^{J} e^{V_j}}\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a aria-hidden="true" tabindex="-1"></a>share_A_c <span class="ot">&lt;-</span> <span class="fu">exp</span>(utility_A_c) <span class="sc">/</span> (<span class="fu">exp</span>(utility_A_c) <span class="sc">+</span> <span class="fu">exp</span>(utility_B_c))</span>
<span id="cb32-2"><a aria-hidden="true" tabindex="-1"></a>share_B_c <span class="ot">&lt;-</span> <span class="fu">exp</span>(utility_B_c) <span class="sc">/</span> (<span class="fu">exp</span>(utility_A_c) <span class="sc">+</span> <span class="fu">exp</span>(utility_B_c))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Plan</th>
<th style="text-align: center;">Utility</th>
<th style="text-align: center;">Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Plan A ($250, $500 ded, Large)</td>
<td style="text-align: center;">-2.94</td>
<td style="text-align: center;">68.3%</td>
</tr>
<tr class="even">
<td style="text-align: center;">Plan B ($200, $1500 ded, Small)</td>
<td style="text-align: center;">-3.7</td>
<td style="text-align: center;">31.7%</td>
</tr>
</tbody>
</table>
</div>
</section></section>
<section>
<section id="practice-choice-based-conjoint" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>5. Practice: Choice-Based Conjoint</h1>

</section>
<section id="practice-2-primary-care-clinic-selection" class="slide level2">
<h2>Practice 2: Primary Care Clinic Selection</h2>
<p><strong>Scenario</strong>: A health system is redesigning its primary care network and wants to understand what drives patients to choose one clinic over another. In a choice survey, patients are shown pairs of hypothetical clinic profiles and asked to pick the one they would visit.</p>
<div class="fragment">
<p><strong>Four key attributes</strong> vary across clinics:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Attribute</th>
<th style="text-align: center;">Level 1</th>
<th style="text-align: center;">Level 2</th>
<th style="text-align: center;">Why It Matters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Distance</td>
<td style="text-align: center;">5 min</td>
<td style="text-align: center;">25 min</td>
<td style="text-align: center;">Travel burden / access</td>
</tr>
<tr class="even">
<td style="text-align: center;">Appointment Wait</td>
<td style="text-align: center;">Same-week</td>
<td style="text-align: center;">3 weeks</td>
<td style="text-align: center;">Timeliness of care</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Provider Type</td>
<td style="text-align: center;">MD</td>
<td style="text-align: center;">NP</td>
<td style="text-align: center;">Perceived expertise / scope</td>
</tr>
<tr class="even">
<td style="text-align: center;">Copay</td>
<td style="text-align: center;">$25</td>
<td style="text-align: center;">$50</td>
<td style="text-align: center;">Out-of-pocket cost</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p>Using these choices, we’ll estimate part-worths, attribute importance, WTP, and predict market share for competing clinic designs.</p>
</div>
</section>
<section id="practice-2-load-data" class="slide level2">
<h2>Practice 2: Load Data</h2>
<p>Load the dataset using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a aria-hidden="true" tabindex="-1"></a>clinic_long <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week14_practice_data2_long.csv"</span>)</span>
<span id="cb33-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(clinic_long, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  choice_set alternative distance_5min wait_sameweek provider_md copay choice
1      100_1           A             1             0           1    50      1
2      100_1           B             0             0           1    25      0
3      100_2           A             0             0           1    25      0
4      100_2           B             1             0           0    25      1
5      100_3           A             0             1           1    50      1</code></pre>
</div>
</div>
</section>
<section id="practice-2-variables" class="slide level2">
<h2>Practice 2: Variables</h2>
<p>Each row is one clinic alternative within a choice set:</p>
<div style="font-size: 90%">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: center;">Type</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>choice_set</code></td>
<td style="text-align: center;">ID</td>
<td style="text-align: left;">Unique ID for each choice set (combines respondent and set number)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>alternative</code></td>
<td style="text-align: center;">ID</td>
<td style="text-align: left;">Clinic label within the set (e.g., Clinic A / Clinic B)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>distance_nearby</code></td>
<td style="text-align: center;">Dummy (0/1)</td>
<td style="text-align: left;"><code>1</code> = 5-minute distance, <code>0</code> = 25-minute distance</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>wait_sameweek</code></td>
<td style="text-align: center;">Dummy (0/1)</td>
<td style="text-align: left;"><code>1</code> = same-week appointment, <code>0</code> = 3-week wait</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>provider_md</code></td>
<td style="text-align: center;">Dummy (0/1)</td>
<td style="text-align: left;"><code>1</code> = MD, <code>0</code> = NP</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>copay</code></td>
<td style="text-align: center;">Continuous ($)</td>
<td style="text-align: left;">Out-of-pocket cost per visit ($25 or $50)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>choice</code></td>
<td style="text-align: center;">Outcome (0/1)</td>
<td style="text-align: left;"><code>1</code> if the respondent picked this alternative, <code>0</code> otherwise</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="practice-2-tasks-14" class="slide level2">
<h2>Practice 2: Tasks (1/4)</h2>
<p><strong>Task 1</strong>: Index data and estimate model</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a aria-hidden="true" tabindex="-1"></a>clinic_mlogit <span class="ot">&lt;-</span> <span class="fu">dfidx</span>(clinic_long,</span>
<span id="cb35-2"><a aria-hidden="true" tabindex="-1"></a>                       <span class="at">shape =</span> <span class="st">"___"</span>, <span class="at">choice =</span> <span class="st">"___"</span>,</span>
<span id="cb35-3"><a aria-hidden="true" tabindex="-1"></a>                       <span class="at">idx =</span> <span class="fu">c</span>(<span class="st">"___"</span>, <span class="st">"___"</span>))</span>
<span id="cb35-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a aria-hidden="true" tabindex="-1"></a>model_clinic <span class="ot">&lt;-</span> <span class="fu">mlogit</span>(choice <span class="sc">~</span> ___ <span class="sc">+</span> ___ <span class="sc">+</span> ___ <span class="sc">+</span> ___ <span class="sc">|</span> <span class="dv">0</span>,</span>
<span id="cb35-6"><a aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> clinic_mlogit)</span>
<span id="cb35-7"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_clinic)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="practice-2-tasks-24" class="slide level2">
<h2>Practice 2: Tasks (2/4)</h2>
<p><strong>Task 2</strong>: Calculate attribute importance</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a aria-hidden="true" tabindex="-1"></a>coef_clinic <span class="ot">&lt;-</span> <span class="fu">coef</span>(model_clinic)</span>
<span id="cb36-2"><a aria-hidden="true" tabindex="-1"></a>range_distance <span class="ot">&lt;-</span> <span class="fu">abs</span>(coef_clinic[<span class="st">"___"</span>] <span class="sc">*</span> <span class="dv">1</span>)</span>
<span id="cb36-3"><a aria-hidden="true" tabindex="-1"></a>range_wait <span class="ot">&lt;-</span> <span class="fu">abs</span>(coef_clinic[<span class="st">"___"</span>] <span class="sc">*</span> <span class="dv">1</span>)</span>
<span id="cb36-4"><a aria-hidden="true" tabindex="-1"></a>range_provider <span class="ot">&lt;-</span> <span class="fu">abs</span>(coef_clinic[<span class="st">"___"</span>] <span class="sc">*</span> <span class="dv">1</span>)</span>
<span id="cb36-5"><a aria-hidden="true" tabindex="-1"></a>range_copay <span class="ot">&lt;-</span> <span class="fu">abs</span>(coef_clinic[<span class="st">"___"</span>] <span class="sc">*</span> (<span class="dv">50</span> <span class="sc">-</span> <span class="dv">25</span>))</span>
<span id="cb36-6"><a aria-hidden="true" tabindex="-1"></a>total_range <span class="ot">&lt;-</span> range_distance <span class="sc">+</span> range_wait <span class="sc">+</span> range_provider <span class="sc">+</span> range_copay</span>
<span id="cb36-7"><a aria-hidden="true" tabindex="-1"></a>importance_clinic <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb36-8"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">attribute =</span> <span class="fu">c</span>(<span class="st">"Distance"</span>, <span class="st">"Appointment Wait"</span>, <span class="st">"Provider Type"</span>, <span class="st">"Copay"</span>),</span>
<span id="cb36-9"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">importance_pct =</span> <span class="fu">c</span>(range_distance, range_wait, range_provider, range_copay) <span class="sc">/</span> total_range <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb36-10"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-11"><a aria-hidden="true" tabindex="-1"></a>importance_clinic</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="practice-2-tasks-34" class="slide level2">
<h2>Practice 2: Tasks (3/4)</h2>
<p><strong>Task 3</strong>: Calculate WTP</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a aria-hidden="true" tabindex="-1"></a>wtp_nearby <span class="ot">&lt;-</span> <span class="sc">-</span>coef_clinic[<span class="st">"___"</span>] <span class="sc">/</span> coef_clinic[<span class="st">"___"</span>]</span>
<span id="cb37-2"><a aria-hidden="true" tabindex="-1"></a>wtp_sameweek <span class="ot">&lt;-</span> <span class="sc">-</span>coef_clinic[<span class="st">"___"</span>] <span class="sc">/</span> coef_clinic[<span class="st">"___"</span>]</span>
<span id="cb37-3"><a aria-hidden="true" tabindex="-1"></a>wtp_md <span class="ot">&lt;-</span> <span class="sc">-</span>coef_clinic[<span class="st">"___"</span>] <span class="sc">/</span> coef_clinic[<span class="st">"___"</span>]</span>
<span id="cb37-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"WTP for Nearby Clinic: $"</span>, <span class="fu">round</span>(wtp_nearby, <span class="dv">2</span>), <span class="st">" per visit</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb37-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"WTP for Same-week Appt: $"</span>, <span class="fu">round</span>(wtp_sameweek, <span class="dv">2</span>), <span class="st">" per visit</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb37-6"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"WTP for MD vs NP: $"</span>, <span class="fu">round</span>(wtp_md, <span class="dv">2</span>), <span class="st">" per visit</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="practice-2-tasks-44" class="slide level2">
<h2>Practice 2: Tasks (4/4)</h2>
<p><strong>Task 4</strong>: Predict market shares for two competing clinic designs:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Attribute</th>
<th style="text-align: center;"><strong>Clinic A</strong></th>
<th style="text-align: center;"><strong>Clinic B</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Distance</td>
<td style="text-align: center;">5 min</td>
<td style="text-align: center;">25 min</td>
</tr>
<tr class="even">
<td style="text-align: center;">Appointment Wait</td>
<td style="text-align: center;">Same-week</td>
<td style="text-align: center;">3 weeks</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Provider Type</td>
<td style="text-align: center;">NP</td>
<td style="text-align: center;">MD</td>
</tr>
<tr class="even">
<td style="text-align: center;">Copay</td>
<td style="text-align: center;">$50</td>
<td style="text-align: center;">$25</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a aria-hidden="true" tabindex="-1"></a>utility_A_clinic <span class="ot">&lt;-</span> coef_clinic[<span class="st">"distance_5min"</span>] <span class="sc">*</span> <span class="dv">1</span> <span class="sc">+</span> coef_clinic[<span class="st">"wait_sameweek"</span>] <span class="sc">*</span> <span class="dv">1</span> <span class="sc">+</span></span>
<span id="cb38-2"><a aria-hidden="true" tabindex="-1"></a>                    coef_clinic[<span class="st">"provider_md"</span>] <span class="sc">*</span> <span class="dv">0</span> <span class="sc">+</span> coef_clinic[<span class="st">"copay"</span>] <span class="sc">*</span> <span class="dv">50</span></span>
<span id="cb38-3"><a aria-hidden="true" tabindex="-1"></a>utility_B_clinic <span class="ot">&lt;-</span> coef_clinic[<span class="st">"distance_5min"</span>] <span class="sc">*</span> <span class="dv">0</span> <span class="sc">+</span> coef_clinic[<span class="st">"wait_sameweek"</span>] <span class="sc">*</span> <span class="dv">0</span> <span class="sc">+</span></span>
<span id="cb38-4"><a aria-hidden="true" tabindex="-1"></a>                    coef_clinic[<span class="st">"provider_md"</span>] <span class="sc">*</span> <span class="dv">1</span> <span class="sc">+</span> coef_clinic[<span class="st">"copay"</span>] <span class="sc">*</span> <span class="dv">25</span></span>
<span id="cb38-5"><a aria-hidden="true" tabindex="-1"></a>share_A_clinic <span class="ot">&lt;-</span> _____ <span class="sc">/</span> (<span class="fu">exp</span>(utility_A_clinic) <span class="sc">+</span> <span class="fu">exp</span>(utility_B_clinic))</span>
<span id="cb38-6"><a aria-hidden="true" tabindex="-1"></a>share_B_clinic <span class="ot">&lt;-</span> _____ <span class="sc">/</span> (<span class="fu">exp</span>(utility_A_clinic) <span class="sc">+</span> <span class="fu">exp</span>(utility_B_clinic))</span>
<span id="cb38-7"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Clinic A share: "</span>, <span class="fu">round</span>(share_A_clinic <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb38-8"><a aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Clinic B share: "</span>, <span class="fu">round</span>(share_B_clinic <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>), <span class="st">"%</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section></section>
<section>
<section id="summary" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Summary</h1>

</section>
<section id="method-comparison" class="slide level2">
<h2>Method Comparison</h2>
<table class="caption-top">
<colgroup>
<col style="width: 24%">
<col style="width: 36%">
<col style="width: 39%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Aspect</th>
<th style="text-align: center;">Rating-Based</th>
<th style="text-align: center;">Choice-Based</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Data Collection</td>
<td style="text-align: center;">Rate profiles (1-10)</td>
<td style="text-align: center;">Choose from a set</td>
</tr>
<tr class="even">
<td style="text-align: center;">Analysis</td>
<td style="text-align: center;">OLS regression</td>
<td style="text-align: center;">Multinomial logit</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Market Share</td>
<td style="text-align: center;">Proportional allocation</td>
<td style="text-align: center;">Multinomial logit formula</td>
</tr>
<tr class="even">
<td style="text-align: center;">Realism</td>
<td style="text-align: center;">Lower</td>
<td style="text-align: center;">Higher</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Complexity</td>
<td style="text-align: center;">Simpler</td>
<td style="text-align: center;">Requires data reshaping</td>
</tr>
</tbody>
</table>
</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<ul>
<li class="fragment"><strong>Part-worth utilities</strong> (regression coefficients) tell us how much each attribute level contributes to overall preference</li>
<li class="fragment"><strong>Attribute importance</strong> is calculated from the range of utilities (the wider the range, the more influence)</li>
<li class="fragment"><strong>WTP</strong> converts utility into dollar values: <span class="math inline">\(\text{WTP} = -\beta_{\text{attribute}} / \beta_{\text{cost}}\)</span> (requires a monetary attribute such as premium, copay, or price)</li>
<li class="fragment"><strong>Market share simulation</strong> predicts splits across competing options using proportional allocation (rating) or the multinomial logit formula (choice)</li>
<li class="fragment"><strong>Data structure matters</strong>: Choice-based requires long-format data with proper indexing</li>
<li class="fragment"><strong>The managerial insight</strong>: Conjoint transforms subjective preferences into quantitative evidence for pricing, product design, and strategic decisions</li>
</ul>
</section>
<section id="assignments" class="slide level2 scrollable">
<h2>Assignments</h2>
<ol type="1">
<li><strong>Week 15 Reflection</strong>: Please share your thoughts on the lecture</li>
</ol>
<ul>
<li>3 interesting things</li>
<li>3 confusing or unclear things</li>
</ul>
<div class="fragment">
<p><br> 2. <strong>Lab Assignment 7</strong>: Conjoint Analysis</p>
<p><br></p>
<p>Both are due by 11:59 PM on Sunday, April 26.</p>
</div>
</section>
<section id="references" class="slide level2">
<h2>References</h2>
<div style="font-size: 80%">
<ul>
<li>Green, P. E., &amp; Srinivasan, V. (1990). Conjoint analysis in marketing: New developments with implications for research and practice. <em>Journal of Marketing</em>, 54(4), 3-19.</li>
<li>McFadden, D. (1974). Conditional logit analysis of qualitative choice behavior. In P. Zarembka (Ed.), <em>Frontiers in Econometrics</em> (pp.&nbsp;105-142). Academic Press.</li>
<li>Sinaiko, A. D., &amp; Hirth, R. A. (2011). Consumers, health insurance and dominated choices. <em>Journal of Health Economics</em>, 30(2), 450-457.</li>
<li>Savira, F., Robinson, S., Toll, K., Spark, L., Thomas, E., Nesbitt, J., Frean, I., &amp; Norman, R. (2023). Consumer preferences for telehealth in Australia: A discrete choice experiment. <em>PLOS ONE</em>, 18(3), e0283821.</li>
</ul>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Week 15 | Conjoint Analysis</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>