<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-02-16">

<title>Mean Comparison 2: One-Way and Repeated-Measures ANOVA – Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-7b997789b8c97d15811d7b52a81c6dd1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026)</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../../index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mba642-spring-26/mba642-spring-26.github.io/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Mean Comparison 2: One-Way and Repeated-Measures ANOVA</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-to-anova" id="toc-introduction-to-anova" class="nav-link active" data-scroll-target="#introduction-to-anova">Introduction to ANOVA</a>
  <ul class="collapse">
  <li><a href="#why-anova-matters" id="toc-why-anova-matters" class="nav-link" data-scroll-target="#why-anova-matters">Why ANOVA Matters?</a></li>
  <li><a href="#the-problem-with-multiple-t-tests" id="toc-the-problem-with-multiple-t-tests" class="nav-link" data-scroll-target="#the-problem-with-multiple-t-tests">The Problem with Multiple t-tests</a>
  <ul class="collapse">
  <li><a href="#familywise-error-rate" id="toc-familywise-error-rate" class="nav-link" data-scroll-target="#familywise-error-rate">Familywise Error Rate</a></li>
  <li><a href="#anova-solves-this-problem" id="toc-anova-solves-this-problem" class="nav-link" data-scroll-target="#anova-solves-this-problem">ANOVA Solves This Problem</a></li>
  </ul></li>
  <li><a href="#overview-of-anova-types" id="toc-overview-of-anova-types" class="nav-link" data-scroll-target="#overview-of-anova-types">Overview of ANOVA Types</a></li>
  </ul></li>
  <li><a href="#one-way-anova" id="toc-one-way-anova" class="nav-link" data-scroll-target="#one-way-anova">1. One-Way ANOVA</a>
  <ul class="collapse">
  <li><a href="#what-is-it" id="toc-what-is-it" class="nav-link" data-scroll-target="#what-is-it">What is it?</a>
  <ul class="collapse">
  <li><a href="#key-components" id="toc-key-components" class="nav-link" data-scroll-target="#key-components">Key Components</a></li>
  </ul></li>
  <li><a href="#when-to-use-it" id="toc-when-to-use-it" class="nav-link" data-scroll-target="#when-to-use-it">When to Use It</a></li>
  <li><a href="#scenario-1-patient-satisfaction-across-hospital-departments" id="toc-scenario-1-patient-satisfaction-across-hospital-departments" class="nav-link" data-scroll-target="#scenario-1-patient-satisfaction-across-hospital-departments">Scenario 1: Patient Satisfaction Across Hospital Departments</a></li>
  <li><a href="#the-formula" id="toc-the-formula" class="nav-link" data-scroll-target="#the-formula">The Formula</a>
  <ul class="collapse">
  <li><a href="#understanding-the-f-statistic" id="toc-understanding-the-f-statistic" class="nav-link" data-scroll-target="#understanding-the-f-statistic">Understanding the F-Statistic</a></li>
  </ul></li>
  <li><a href="#example-patient-satisfaction-by-department" id="toc-example-patient-satisfaction-by-department" class="nav-link" data-scroll-target="#example-patient-satisfaction-by-department">Example: Patient Satisfaction by Department</a></li>
  <li><a href="#visualizing-group-differences" id="toc-visualizing-group-differences" class="nav-link" data-scroll-target="#visualizing-group-differences">Visualizing Group Differences</a></li>
  <li><a href="#visualizing-the-f-distribution-under-the-null-hypothesis" id="toc-visualizing-the-f-distribution-under-the-null-hypothesis" class="nav-link" data-scroll-target="#visualizing-the-f-distribution-under-the-null-hypothesis">Visualizing the F-Distribution under the Null Hypothesis</a>
  <ul class="collapse">
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses">Hypotheses</a></li>
  <li><a href="#interpretation-of-the-graph" id="toc-interpretation-of-the-graph" class="nav-link" data-scroll-target="#interpretation-of-the-graph">Interpretation of the graph</a></li>
  </ul></li>
  <li><a href="#conducting-one-way-anova-in-r" id="toc-conducting-one-way-anova-in-r" class="nav-link" data-scroll-target="#conducting-one-way-anova-in-r">Conducting One-Way ANOVA in R</a>
  <ul class="collapse">
  <li><a href="#interpreting-the-anova-table" id="toc-interpreting-the-anova-table" class="nav-link" data-scroll-target="#interpreting-the-anova-table">Interpreting the ANOVA Table</a></li>
  <li><a href="#conclusion-from-anova" id="toc-conclusion-from-anova" class="nav-link" data-scroll-target="#conclusion-from-anova">Conclusion from ANOVA</a></li>
  </ul></li>
  <li><a href="#post-hoc-tests-tukeys-hsd" id="toc-post-hoc-tests-tukeys-hsd" class="nav-link" data-scroll-target="#post-hoc-tests-tukeys-hsd">Post-Hoc Tests: Tukey’s HSD</a>
  <ul class="collapse">
  <li><a href="#what-is-tukeys-hsd" id="toc-what-is-tukeys-hsd" class="nav-link" data-scroll-target="#what-is-tukeys-hsd">What is Tukey’s HSD?</a></li>
  <li><a href="#conducting-tukeys-hsd-in-r-using-emmeans" id="toc-conducting-tukeys-hsd-in-r-using-emmeans" class="nav-link" data-scroll-target="#conducting-tukeys-hsd-in-r-using-emmeans">Conducting Tukey’s HSD in R Using emmeans</a></li>
  <li><a href="#interpreting-tukeys-hsd-output" id="toc-interpreting-tukeys-hsd-output" class="nav-link" data-scroll-target="#interpreting-tukeys-hsd-output">Interpreting Tukey’s HSD Output</a></li>
  <li><a href="#practice-activity-1-staff-training-programs" id="toc-practice-activity-1-staff-training-programs" class="nav-link" data-scroll-target="#practice-activity-1-staff-training-programs">Practice Activity 1: Staff Training Programs</a></li>
  </ul></li>
  <li><a href="#example-2-comparing-care-coordination-models" id="toc-example-2-comparing-care-coordination-models" class="nav-link" data-scroll-target="#example-2-comparing-care-coordination-models">Example 2: Comparing Care Coordination Models</a>
  <ul class="collapse">
  <li><a href="#interpreting-the-anova-results" id="toc-interpreting-the-anova-results" class="nav-link" data-scroll-target="#interpreting-the-anova-results">Interpreting the ANOVA Results</a></li>
  <li><a href="#post-hoc-analysis-pairwise-comparisons" id="toc-post-hoc-analysis-pairwise-comparisons" class="nav-link" data-scroll-target="#post-hoc-analysis-pairwise-comparisons">Post-Hoc Analysis: Pairwise Comparisons</a></li>
  <li><a href="#detailed-interpretation-of-pairwise-comparisons" id="toc-detailed-interpretation-of-pairwise-comparisons" class="nav-link" data-scroll-target="#detailed-interpretation-of-pairwise-comparisons">Detailed Interpretation of Pairwise Comparisons</a></li>
  <li><a href="#practice-activity-2-hospital-operating-costs" id="toc-practice-activity-2-hospital-operating-costs" class="nav-link" data-scroll-target="#practice-activity-2-hospital-operating-costs">Practice Activity 2: Hospital Operating Costs</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#repeated-measures-anova" id="toc-repeated-measures-anova" class="nav-link" data-scroll-target="#repeated-measures-anova">2. Repeated-Measures ANOVA</a>
  <ul class="collapse">
  <li><a href="#what-is-it-1" id="toc-what-is-it-1" class="nav-link" data-scroll-target="#what-is-it-1">What is it?</a></li>
  <li><a href="#when-to-use-it-1" id="toc-when-to-use-it-1" class="nav-link" data-scroll-target="#when-to-use-it-1">When to Use It</a></li>
  <li><a href="#scenario-1-diabetes-management-program" id="toc-scenario-1-diabetes-management-program" class="nav-link" data-scroll-target="#scenario-1-diabetes-management-program">Scenario 1: Diabetes Management Program</a>
  <ul class="collapse">
  <li><a href="#background-and-context" id="toc-background-and-context" class="nav-link" data-scroll-target="#background-and-context">Background and Context</a></li>
  <li><a href="#the-outcome-measure-hba1c" id="toc-the-outcome-measure-hba1c" class="nav-link" data-scroll-target="#the-outcome-measure-hba1c">The Outcome Measure: HbA1c</a></li>
  <li><a href="#study-design" id="toc-study-design" class="nav-link" data-scroll-target="#study-design">Study Design</a></li>
  <li><a href="#why-use-repeated-measures-anova" id="toc-why-use-repeated-measures-anova" class="nav-link" data-scroll-target="#why-use-repeated-measures-anova">Why Use Repeated-Measures ANOVA?</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">Research Questions</a></li>
  </ul></li>
  <li><a href="#the-formula-1" id="toc-the-formula-1" class="nav-link" data-scroll-target="#the-formula-1">The Formula</a>
  <ul class="collapse">
  <li><a href="#formulas-for-sum-of-squares-components" id="toc-formulas-for-sum-of-squares-components" class="nav-link" data-scroll-target="#formulas-for-sum-of-squares-components">Formulas for Sum of Squares Components</a></li>
  <li><a href="#calculating-the-f-statistic" id="toc-calculating-the-f-statistic" class="nav-link" data-scroll-target="#calculating-the-f-statistic">Calculating the F-Statistic</a></li>
  </ul></li>
  <li><a href="#example-diabetes-management-program" id="toc-example-diabetes-management-program" class="nav-link" data-scroll-target="#example-diabetes-management-program">Example: Diabetes Management Program</a></li>
  <li><a href="#visualizing-repeated-measures-data" id="toc-visualizing-repeated-measures-data" class="nav-link" data-scroll-target="#visualizing-repeated-measures-data">Visualizing Repeated Measures Data</a></li>
  <li><a href="#conducting-repeated-measures-anova-in-r" id="toc-conducting-repeated-measures-anova-in-r" class="nav-link" data-scroll-target="#conducting-repeated-measures-anova-in-r">Conducting Repeated-Measures ANOVA in R</a>
  <ul class="collapse">
  <li><a href="#interpreting-the-output" id="toc-interpreting-the-output" class="nav-link" data-scroll-target="#interpreting-the-output">Interpreting the Output</a></li>
  <li><a href="#conclusion-and-interpretation" id="toc-conclusion-and-interpretation" class="nav-link" data-scroll-target="#conclusion-and-interpretation">Conclusion and Interpretation</a></li>
  </ul></li>
  <li><a href="#post-hoc-tests-for-repeated-measures" id="toc-post-hoc-tests-for-repeated-measures" class="nav-link" data-scroll-target="#post-hoc-tests-for-repeated-measures">Post-Hoc Tests for Repeated Measures</a>
  <ul class="collapse">
  <li><a href="#interpreting-post-hoc-results" id="toc-interpreting-post-hoc-results" class="nav-link" data-scroll-target="#interpreting-post-hoc-results">Interpreting Post-Hoc Results</a></li>
  <li><a href="#practice-activity-3-pain-management-follow-up" id="toc-practice-activity-3-pain-management-follow-up" class="nav-link" data-scroll-target="#practice-activity-3-pain-management-follow-up">Practice Activity 3: Pain Management Follow-up</a></li>
  </ul></li>
  <li><a href="#example-2-staff-burnout-across-shift-schedules" id="toc-example-2-staff-burnout-across-shift-schedules" class="nav-link" data-scroll-target="#example-2-staff-burnout-across-shift-schedules">Example 2: Staff Burnout Across Shift Schedules</a>
  <ul class="collapse">
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  <li><a href="#practice-activity-4-employee-engagement-survey" id="toc-practice-activity-4-employee-engagement-survey" class="nav-link" data-scroll-target="#practice-activity-4-employee-engagement-survey">Practice Activity 4: Employee Engagement Survey</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a>
  <ul class="collapse">
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways">Key Takeaways</a></li>
  </ul></li>
  <li><a href="#references-and-further-reading" id="toc-references-and-further-reading" class="nav-link" data-scroll-target="#references-and-further-reading">References and Further Reading</a>
  <ul class="collapse">
  <li><a href="#statistical-methods" id="toc-statistical-methods" class="nav-link" data-scroll-target="#statistical-methods">Statistical Methods</a></li>
  <li><a href="#healthcare-applications" id="toc-healthcare-applications" class="nav-link" data-scroll-target="#healthcare-applications">Healthcare Applications</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mean Comparison 2: One-Way and Repeated-Measures ANOVA</h1>
<p class="subtitle lead">MBA642: Business Analytics in Healthcare Management</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 16, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction-to-anova" class="level1">
<h1>Introduction to ANOVA</h1>
<section id="why-anova-matters" class="level2">
<h2 class="anchored" data-anchor-id="why-anova-matters">Why ANOVA Matters?</h2>
<p>We frequently need to compare outcomes across <strong>more than two groups</strong>. Let’s think about these scenarios:</p>
<ul>
<li>Comparing patient satisfaction scores across <strong>five different hospital departments</strong></li>
<li>Evaluating readmission rates among <strong>three different care coordination models</strong></li>
<li>Assessing staff performance across <strong>four different training programs</strong></li>
<li>Tracking patient outcomes at <strong>multiple time points</strong> during recovery</li>
</ul>
<p>While t-tests are excellent for comparing two groups (independent-samples t-test) or two related measures such as pre- and post-intervention scores (paired t-test), they cannot handle these multi-group or multi-timepoint comparisons. This is where <strong>Analysis of Variance (ANOVA)</strong> becomes essential. <strong>One-way ANOVA</strong> extends the independent-samples t-test to three or more groups, and <strong>repeated-measures ANOVA</strong> extends the paired t-test to three or more time points or related conditions—all in <strong>a single test</strong>.</p>
</section>
<section id="the-problem-with-multiple-t-tests" class="level2">
<h2 class="anchored" data-anchor-id="the-problem-with-multiple-t-tests">The Problem with Multiple t-tests</h2>
<p>You might wonder why not just run multiple t-tests to compare each pair of groups? This approach is tempting but fundamentally flawed due to the <strong>familywise error rate</strong> problem.</p>
<section id="familywise-error-rate" class="level3">
<h3 class="anchored" data-anchor-id="familywise-error-rate">Familywise Error Rate</h3>
<p>Each time we conduct a statistical test at α = 0.05, we accept a 5% chance of making a Type I error (false positive; concluding there’s a difference when there isn’t one). When we perform multiple tests, these error rates increase.</p>
<p>The probability of Type I error across multiple tests is:</p>
<p><span class="math display">\[P(\text{at least one Type I error}) = 1 - (1 - \alpha)^k\]</span></p>
<p>Where <span class="math inline">\(k\)</span> is the number of comparisons.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture06_files/figure-html/error-rate-demo-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>For example, with just 4 groups, you would need 6 pairwise t-tests. The familywise error rate becomes: <span class="math display">\[1 - (0.95)^6 = 0.265 = 26.5\%\]</span></p>
<p>This means you have a 26.5% chance of finding at least one “significant” difference by pure chance, which is way far from the 5% we intended!</p>
</section>
<section id="anova-solves-this-problem" class="level3">
<h3 class="anchored" data-anchor-id="anova-solves-this-problem">ANOVA Solves This Problem</h3>
<p>ANOVA tests all groups simultaneously with a <strong>single test</strong>, maintaining the Type I error rate at our desired α level (in our class, 5%). If ANOVA finds a significant difference, we then use <strong>post-hoc tests</strong> with appropriate corrections to identify which specific groups differ.</p>
</section>
</section>
<section id="overview-of-anova-types" class="level2">
<h2 class="anchored" data-anchor-id="overview-of-anova-types">Overview of ANOVA Types</h2>
<p>This document covers two fundamental ANOVA designs:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 38%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>ANOVA Type</th>
<th>Purpose</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>One-Way ANOVA</strong></td>
<td>Compare means across 3+ independent groups</td>
<td>Comparing satisfaction scores across 4 hospital departments</td>
</tr>
<tr class="even">
<td><strong>Repeated-Measures ANOVA</strong></td>
<td>Compare means across 3+ related measurements on the same subjects</td>
<td>Tracking pain scores at baseline, 1 month, 3 months, and 6 months</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="one-way-anova" class="level1">
<h1>1. One-Way ANOVA</h1>
<section id="what-is-it" class="level2">
<h2 class="anchored" data-anchor-id="what-is-it">What is it?</h2>
<p>A <strong>one-way ANOVA</strong> (Analysis of Variance) tests whether there are statistically significant differences among the means of three or more independent groups. The “one-way” refers to having one independent variable (factor) with multiple levels (groups).</p>
<p>ANOVA actually analyzes <strong>variance</strong> to make inferences about <strong>means</strong>. It works by partitioning the total variability in the data into:</p>
<ol type="1">
<li><strong>Between-group variance</strong>: Differences among group means</li>
<li><strong>Within-group variance</strong>: Differences among individuals within groups</li>
</ol>
<p>If the between-group variance is substantially larger than the within-group variance, we conclude that the group means are significantly different.</p>
<section id="key-components" class="level3">
<h3 class="anchored" data-anchor-id="key-components">Key Components</h3>
<ul>
<li><strong>One independent variable</strong> (factor) with 3+ levels</li>
<li><strong>Independent groups</strong>: Each observation belongs to only one group</li>
<li><strong>Continuous dependent variable</strong>: The outcome measure</li>
</ul>
</section>
</section>
<section id="when-to-use-it" class="level2">
<h2 class="anchored" data-anchor-id="when-to-use-it">When to Use It</h2>
<p>One-way ANOVA is appropriate whenever you need to compare means across three or more distinct, unrelated groups:</p>
<ul>
<li>Comparing <strong>patient outcomes</strong> across different treatment protocols</li>
<li>Evaluating <strong>staff performance</strong> across multiple departments</li>
<li>Comparing <strong>operational metrics</strong> across several facilities</li>
<li>Assessing <strong>patient satisfaction</strong> across various service lines</li>
<li>Comparing <strong>cost efficiency</strong> across different care models</li>
</ul>
</section>
<section id="scenario-1-patient-satisfaction-across-hospital-departments" class="level2">
<h2 class="anchored" data-anchor-id="scenario-1-patient-satisfaction-across-hospital-departments">Scenario 1: Patient Satisfaction Across Hospital Departments</h2>
<p>A hospital administrator wants to evaluate patient satisfaction across <strong>four departments</strong>: Emergency, Cardiology, Orthopedics, and Oncology. Each department has implemented different patient experience initiatives, and leadership wants to know if satisfaction levels differ significantly.</p>
</section>
<section id="the-formula" class="level2">
<h2 class="anchored" data-anchor-id="the-formula">The Formula</h2>
<p>The one-way ANOVA calculates an <strong>F-statistic</strong>:</p>
<p><span class="math display">\[F = \frac{\text{Between-group variance}}{\text{Within-group variance}} = \frac{MS_{between}}{MS_{within}}\]</span></p>
<p>Where:</p>
<ul>
<li><p><strong>Mean Square Between</strong> (<span class="math inline">\(MS_{between}\)</span>): Average variance among group means <span class="math display">\[MS_{between} = \frac{SS_{between}}{df_{between}} = \frac{\sum_{j=1}^{k} n_j(\bar{X}_j - \bar{X}_{grand})^2}{k-1}\]</span></p></li>
<li><p><strong>Mean Square Within</strong> (<span class="math inline">\(MS_{within}\)</span>): Average variance within groups <span class="math display">\[MS_{within} = \frac{SS_{within}}{df_{within}} = \frac{\sum_{j=1}^{k}\sum_{i=1}^{n_j}(X_{ij} - \bar{X}_j)^2}{N-k}\]</span></p></li>
</ul>
<p>Where:</p>
<ul>
<li><p><span class="math inline">\(k\)</span> = number of groups</p></li>
<li><p><span class="math inline">\(n_j\)</span> = sample size of group <span class="math inline">\(j\)</span></p></li>
<li><p><span class="math inline">\(N\)</span> = total sample size</p></li>
<li><p><span class="math inline">\(\bar{X}_j\)</span> = mean of group <span class="math inline">\(j\)</span></p></li>
<li><p><span class="math inline">\(\bar{X}_{grand}\)</span> = overall mean (grand mean)</p></li>
</ul>
<section id="understanding-the-f-statistic" class="level3">
<h3 class="anchored" data-anchor-id="understanding-the-f-statistic">Understanding the F-Statistic</h3>
<p>The F-statistic is a <strong>ratio</strong>:</p>
<p><img src="./images/image1.png" class="img-fluid"></p>
<ul>
<li>When variance between groups is larger than variance within groups, F-statistic will be large</li>
<li>When variance between groups is smaller than variance within groups, F-statistic will be small</li>
</ul>
</section>
</section>
<section id="example-patient-satisfaction-by-department" class="level2">
<h2 class="anchored" data-anchor-id="example-patient-satisfaction-by-department">Example: Patient Satisfaction by Department</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Patient satisfaction Data </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>satisfaction_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week06_satisfaction.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Summary Statistics by Department</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Department</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cardiology</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">7.99</td>
<td style="text-align: right;">0.56</td>
</tr>
<tr class="even">
<td style="text-align: left;">Emergency</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">7.51</td>
<td style="text-align: right;">0.37</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oncology</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">8.13</td>
<td style="text-align: right;">0.77</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orthopedics</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">7.76</td>
<td style="text-align: right;">0.33</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="visualizing-group-differences" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-group-differences">Visualizing Group Differences</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(satisfaction_data, <span class="fu">aes</span>(<span class="at">x =</span> department, <span class="at">y =</span> score, <span class="at">fill =</span> department)) <span class="sc">+</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Patient Satisfaction by Department"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Department"</span>, <span class="at">y =</span> <span class="st">"Satisfaction Score (1-10)"</span>) <span class="sc">+</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>p1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture06_files/figure-html/oneway-viz1-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="visualizing-the-f-distribution-under-the-null-hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-f-distribution-under-the-null-hypothesis">Visualizing the F-Distribution under the Null Hypothesis</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture06_files/figure-html/oneway-fdist-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<section id="hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="hypotheses">Hypotheses</h3>
<ul>
<li><strong>Null hypothesis</strong> (<span class="math inline">\(H_0\)</span>): All group means are equal (<span class="math inline">\(\mu_1 = \mu_2 = \mu_3 = \mu_4\)</span>)</li>
<li><strong>Alternative hypothesis</strong> (<span class="math inline">\(H_A\)</span>): At least one group mean is different from the others</li>
</ul>
</section>
<section id="interpretation-of-the-graph" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-the-graph">Interpretation of the graph</h3>
<ul>
<li>The density plot shows the F-distribution under the null hypothesis.</li>
<li>The red line indicates the calculated F-statistic, and the shaded gray area indicates the rejection region.</li>
<li>The area to the right of the calculated F-statistic (under the curve) is the p-value.</li>
<li>If the F-statistic falls in the rejection region, we reject the null hypothesis and conclude that there are significant differences among the group means.</li>
<li>However, a significant ANOVA result does not tell us <strong>which</strong> specific groups differ from each other. To identify where the differences lie, we need to conduct <strong>post-hoc analysis</strong> while controlling for the familywise error rate.</li>
</ul>
</section>
</section>
<section id="conducting-one-way-anova-in-r" class="level2">
<h2 class="anchored" data-anchor-id="conducting-one-way-anova-in-r">Conducting One-Way ANOVA in R</h2>
<p>As we now understand the basic concept of ANOVA, let’s conduct one-way ANOVA in R. In R, you can conduct a one-way ANOVA by using the <code>aov(y ~ x, data = data)</code> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform one-way ANOVA</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>anova_result <span class="ot">&lt;-</span> <span class="fu">aov</span>(score <span class="sc">~</span> department, <span class="at">data =</span> satisfaction_data)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_result)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value  Pr(&gt;F)   
department   3  4.451  1.4838   5.143 0.00272 **
Residuals   76 21.928  0.2885                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="interpreting-the-anova-table" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-the-anova-table">Interpreting the ANOVA Table</h3>
<ul>
<li><p><strong>Df (Degrees of Freedom)</strong>:</p>
<ul>
<li>Between groups: <span class="math inline">\(k - 1 = 4 - 1 = 3\)</span></li>
<li>Within groups: <span class="math inline">\(N - k = 80 - 4 = 76\)</span></li>
</ul></li>
<li><p><strong>Sum Sq (Sum of Squares)</strong>: The amount of variation attributed to each source. The factor row (e.g., <code>department</code>) shows variation <strong>due to group differences</strong>, while the <code>Residuals</code> row shows variation <strong>within groups</strong> (individual differences not explained by group membership)</p></li>
<li><p><strong>Mean Sq (Mean Square)</strong>: Sum of Squares divided by degrees of freedom</p></li>
<li><p><strong>F value</strong>: The test statistic (ratio of between-group to within-group variance)</p></li>
<li><p><strong>Pr(&gt;F)</strong>: The p-value (the probability of observing this F-value if all group means were truly equal)</p></li>
</ul>
</section>
<section id="conclusion-from-anova" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-from-anova">Conclusion from ANOVA</h3>
<p>With F = 5.14 and p &lt; 0.05, we <strong>reject the null hypothesis</strong>. There are statistically significant differences in patient satisfaction among the four departments.</p>
<p><strong>But which departments differ from each other?</strong> The ANOVA tells us that differences exist but not where they are. For this, we need <strong>post-hoc tests</strong>.</p>
</section>
</section>
<section id="post-hoc-tests-tukeys-hsd" class="level2">
<h2 class="anchored" data-anchor-id="post-hoc-tests-tukeys-hsd">Post-Hoc Tests: Tukey’s HSD</h2>
<p>When ANOVA is significant, we use <strong>post-hoc tests</strong> to identify which specific groups differ. <strong>Tukey’s Honest Significant Difference (HSD)</strong> test compares all possible pairs while controlling the familywise error rate.</p>
<section id="what-is-tukeys-hsd" class="level3">
<h3 class="anchored" data-anchor-id="what-is-tukeys-hsd">What is Tukey’s HSD?</h3>
<p>Tukey’s HSD is designed to solve a specific problem: <strong>How do we compare all pairs of groups while maintaining our overall Type I error rate at α = 0.05?</strong></p>
<p><strong>Key features:</strong></p>
<ol type="1">
<li><p><strong>Tests all pairwise comparisons</strong>: For k groups, it tests all <span class="math inline">\(\frac{k(k-1)}{2}\)</span> possible pairs</p>
<ul>
<li>4 groups → 6 comparisons</li>
<li>5 groups → 10 comparisons</li>
</ul></li>
<li><p><strong>Controls familywise error rate</strong>: Your overall chance of making at least one Type I error stays at 5% across ALL comparisons (not 5% per comparison)</p></li>
<li><p><strong>Uses the studentized range distribution</strong>: More appropriate than t-distribution for multiple comparisons</p></li>
</ol>
<p><strong>The HSD critical value:</strong></p>
<p><span class="math display">\[HSD = q_{\alpha, k, df_{error}} \times \sqrt{\frac{MS_{within}}{n}}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(q_{\alpha, k, df_{error}}\)</span> = critical value from studentized range distribution</li>
<li><span class="math inline">\(MS_{within}\)</span> = mean square error from ANOVA</li>
<li><span class="math inline">\(n\)</span> = sample size per group</li>
<li><span class="math inline">\(k\)</span> = number of groups</li>
</ul>
<p><strong>If the absolute difference between two group means exceeds HSD, that difference is statistically significant.</strong></p>
</section>
<section id="conducting-tukeys-hsd-in-r-using-emmeans" class="level3">
<h3 class="anchored" data-anchor-id="conducting-tukeys-hsd-in-r-using-emmeans">Conducting Tukey’s HSD in R Using emmeans</h3>
<ul>
<li><p>Now let’s use the <code>emmeans</code> package, which is the modern standard for post-hoc testing. This gives us the estimated marginal means (EMMs), which are the adjusted means for each group.</p></li>
<li><p>Then, we need to specify the pairwise comparisons using the <code>pairs()</code> function and the <code>adjust = "tukey"</code> argument to apply Tukey’s HSD adjustment.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Calculate estimated marginal means</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>emm_dept <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(anova_result, <span class="sc">~</span> department)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>emm_dept</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> department  emmean   SE df lower.CL upper.CL
 Cardiology    7.99 0.12 76     7.75     8.23
 Emergency     7.51 0.12 76     7.27     7.75
 Oncology      8.13 0.12 76     7.89     8.37
 Orthopedics   7.75 0.12 76     7.52     7.99

Confidence level used: 0.95 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Perform pairwise comparisons with Tukey adjustment</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>tukey_pairs <span class="ot">&lt;-</span> <span class="fu">pairs</span>(emm_dept, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>tukey_pairs</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                 estimate   SE df t.ratio p.value
 Cardiology - Emergency      0.480 0.17 76   2.826  0.0300
 Cardiology - Oncology      -0.140 0.17 76  -0.824  0.8428
 Cardiology - Orthopedics    0.235 0.17 76   1.384  0.5135
 Emergency - Oncology       -0.620 0.17 76  -3.650  0.0026
 Emergency - Orthopedics    -0.245 0.17 76  -1.442  0.4773
 Oncology - Orthopedics      0.375 0.17 76   2.208  0.1304

P value adjustment: tukey method for comparing a family of 4 estimates </code></pre>
</div>
</div>
</section>
<section id="interpreting-tukeys-hsd-output" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-tukeys-hsd-output">Interpreting Tukey’s HSD Output</h3>
<p>Each row in the output shows a pairwise comparison:</p>
<ul>
<li><strong>contrast</strong>: Which two groups are being compared</li>
<li><strong>estimate</strong>: Difference between group means</li>
<li><strong>SE</strong>: Standard error of the difference</li>
<li><strong>df</strong>: Degrees of freedom</li>
<li><strong>t.ratio</strong>: Test statistic</li>
<li><strong>p.value</strong>: Adjusted p-value (controlling for multiple comparisons)</li>
</ul>
<p><strong>Decision rule:</strong></p>
<ul>
<li>If <strong>p.value &lt; 0.05</strong>, those groups are significantly different</li>
</ul>
<p><strong>Key findings from our analysis:</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Significant Pairwise Differences (p &lt; 0.05)</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Comparison</th>
<th style="text-align: center;">Difference</th>
<th style="text-align: center;">Adjusted p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Cardiology - Emergency</td>
<td style="text-align: center;">0.48</td>
<td style="text-align: center;">0.0300</td>
</tr>
<tr class="even">
<td style="text-align: center;">Emergency - Oncology</td>
<td style="text-align: center;">-0.62</td>
<td style="text-align: center;">0.0026</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="practice-activity-1-staff-training-programs" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="practice-activity-1-staff-training-programs">Practice Activity 1: Staff Training Programs</h3>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Try It Yourself!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Complete the following practice activity by replacing the <code>___</code> blanks with appropriate values or function names. Run each chunk to verify your analysis and answer the interpretation questions.</p>
<p><strong>After 10 minutes</strong>, we’ll continue with the next example.</p>
</div>
</div>
<section id="scenario-case" class="level4">
<h4 class="anchored" data-anchor-id="scenario-case">Scenario Case</h4>
<ul>
<li><p>A hospital compares the effectiveness of <strong>three different training programs</strong> for improving nurse medication safety scores (out of 100). These scores assess nurses’ competency in safe medication handling, including correct dosage identification, drug interaction awareness, and proper administration procedures.</p></li>
<li><p>Research on simulation-based and blended learning approaches has shown significant improvements in medication safety competency for nurses.</p></li>
<li><p><strong>Programs</strong>:</p>
<ul>
<li><strong>Traditional</strong>: Classroom lectures and written materials</li>
<li><strong>Simulation</strong>: Hands-on practice with realistic patient scenarios</li>
<li><strong>Blended</strong>: Combination of online modules, in-person sessions, and simulation</li>
</ul></li>
<li><p><strong>Research Question</strong>: Do the three training programs result in different medication safety competency scores?</p></li>
</ul>
</section>
<section id="dataset" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="dataset">Dataset</h4>
<p>Load the dataset using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Training program Data</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>training_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week06_training_data.csv"</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># View first few rows</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(training_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X score     program
1 1    78 Traditional
2 2    82 Traditional
3 3    75 Traditional
4 4    80 Traditional
5 5    77 Traditional
6 6    83 Traditional</code></pre>
</div>
</div>
</section>
<section id="task-1.1-explore-the-data" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="task-1.1-explore-the-data">Task 1.1: Explore the Data</h4>
<p>Before running ANOVA, let’s examine summary statistics:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean and SD by program</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> training_data <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(___) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">round</span>(<span class="fu">mean</span>(___), <span class="dv">2</span>),</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">round</span>(<span class="fu">sd</span>(___), <span class="dv">2</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Question</strong>: Which program appears to have the highest mean score? Do the means look different enough to suggest a real difference?</p>
</section>
<section id="task-1.2-visualize-the-comparison" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="task-1.2-visualize-the-comparison">Task 1.2: Visualize the Comparison</h4>
<p>Create a boxplot comparing scores across the three programs:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create boxplot</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> training_data, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> ___, <span class="at">y =</span> ___, <span class="at">fill =</span> ___)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Medication Safety Scores by Training Program"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"___"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Safety Score (out of 100)"</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Question</strong>: Based on the boxplot, do you see differences in the median scores across programs? Do any programs show more variability (wider boxes)?</p>
</section>
<section id="task-1.3-conduct-one-way-anova" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="task-1.3-conduct-one-way-anova">Task 1.3: Conduct One-Way ANOVA</h4>
<p>Now run the ANOVA to test if the differences are statistically significant:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform one-way ANOVA</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>anova_training <span class="ot">&lt;-</span> <span class="fu">aov</span>(___ <span class="sc">~</span> ___, <span class="at">data =</span> training_data)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display ANOVA table</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(___)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions</strong>:</p>
<ol type="1">
<li>What is the F-statistic?</li>
<li>What is the p-value?</li>
<li>Is the result statistically significant at α = 0.05?</li>
<li>What is your conclusion?</li>
</ol>
</section>
<section id="task-1.4-post-hoc-tests" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="task-1.4-post-hoc-tests">Task 1.4: Post-Hoc Tests</h4>
<p>Since ANOVA is significant, run Tukey’s HSD to identify which programs differ:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate estimated marginal means</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>emm_training <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(___, <span class="sc">~</span> ___)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>emm_training</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairwise comparisons with Tukey adjustment</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>tukey_training <span class="ot">&lt;-</span> <span class="fu">pairs</span>(___, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>tukey_training</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions</strong>:</p>
<ol type="1">
<li>Which pairwise comparisons are statistically significant (p &lt; 0.05)?</li>
<li>Which training program appears most effective?</li>
<li>What is the practical significance of these differences?</li>
</ol>
</section>
</section>
</section>
<section id="example-2-comparing-care-coordination-models" class="level2">
<h2 class="anchored" data-anchor-id="example-2-comparing-care-coordination-models">Example 2: Comparing Care Coordination Models</h2>
<ul>
<li><p>A health system wants to evaluate <strong>three different care coordination models</strong> for managing patients with chronic conditions. They measure 30-day readmission rates (%) across facilities using each model.</p></li>
<li><p>Studies have shown that different care coordination approaches produce varying outcomes, with community health worker interventions and transition care coordinator models demonstrating significant reductions in hospital readmissions. The comparative effectiveness of different models remains an important question for resource allocation.</p></li>
</ul>
<p><strong>Model A: Nurse-Led Telephone Follow-Up</strong></p>
<ul>
<li>Registered nurses call patients within 48 hours of discharge</li>
<li>Phone-based medication reconciliation and education</li>
<li>Identification of red flags or concerning symptoms</li>
<li>Lowest resource intensity but limited ability to assess home environment</li>
<li>Relies on patient self-report</li>
</ul>
<p><strong>Model B: Community Health Worker (CHW) Home Visits</strong></p>
<ul>
<li>Trained community health workers conduct in-person home visits within 72 hours</li>
<li>Visual assessment of home environment, medication compliance, and social determinants</li>
<li>Can connect patients to community resources (food, transportation, social services)</li>
<li>Cultural concordance often improves trust and communication</li>
<li>Higher resource intensity than phone calls</li>
</ul>
<p><strong>Model C: Integrated Care Team with Digital Monitoring</strong></p>
<ul>
<li>Multidisciplinary team (nurse, pharmacist, social worker) coordinates care</li>
<li>Patients receive remote monitoring devices (blood pressure, weight, pulse oximetry)</li>
<li>Daily automated data transmission to care team</li>
<li>Algorithm-driven alerts trigger proactive interventions</li>
<li>Weekly team huddles to review high-risk patients</li>
<li>Highest resource intensity but most comprehensive approach</li>
</ul>
<p><strong>Do these three care coordination models differ significantly in their effectiveness at reducing 30-day hospital readmissions?</strong></p>
<p>Let’s load the dataset using the code below and visually inspect the average readmission rates across the three models:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load 30-day readmission rates (%) by care coordination model</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>readmission_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week06_readmission_data.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(readmission_data, <span class="fu">aes</span>(<span class="at">x =</span> model, <span class="at">y =</span> rate, <span class="at">fill =</span> model)) <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"30-Day Readmission Rates by Care Coordination Model"</span>,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Care Model"</span>, <span class="at">y =</span> <span class="st">"Readmission Rate (%)"</span>) <span class="sc">+</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture06_files/figure-html/oneway-viz2-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Model A’s median readmission rate is the highest, while Model C’s median readmission rate is the lowest.</li>
<li>Are these three Models’ average readmission rates significantly different? Let’s test this by running a one-way ANOVA.</li>
</ul>
<p><strong>Hypotheses:</strong></p>
<ul>
<li><span class="math inline">\(H_0\)</span>: All three models have equal mean readmission rates (<span class="math inline">\(\mu_A = \mu_B = \mu_C\)</span>)</li>
<li><span class="math inline">\(H_A\)</span>: At least one model’s mean readmission rate is different from the others</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform ANOVA</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>anova_readmit <span class="ot">&lt;-</span> <span class="fu">aov</span>(rate <span class="sc">~</span> model, <span class="at">data =</span> readmission_data)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_readmit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)    
model        2 209.91  104.95   183.3 &lt;2e-16 ***
Residuals   57  32.63    0.57                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="interpreting-the-anova-results" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-the-anova-results">Interpreting the ANOVA Results</h3>
<ul>
<li><p>With F = 183.32 and p &lt; 0.05, we <strong>reject the null hypothesis</strong>. There are statistically significant differences in 30-day readmission rates among the three care coordination models (i.e., at least one model’s mean readmission rate differs from the others).</p></li>
<li><p><strong>Observed mean readmission rates:</strong></p>
<ul>
<li>Model A (Nurse Phone): 13.17%</li>
<li>Model B (CHW Visits): 10.67%</li>
<li>Model C (Integrated): 8.6%</li>
</ul></li>
<li><p><strong>But which specific models differ from each other?</strong> Let’s examine the post-hoc tests.</p></li>
</ul>
</section>
<section id="post-hoc-analysis-pairwise-comparisons" class="level3">
<h3 class="anchored" data-anchor-id="post-hoc-analysis-pairwise-comparisons">Post-Hoc Analysis: Pairwise Comparisons</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Post-hoc test using emmeans</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>emm_readmit <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(anova_readmit, <span class="sc">~</span> model)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>tukey_readmit <span class="ot">&lt;-</span> <span class="fu">pairs</span>(emm_readmit, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>tukey_readmit</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                                   estimate    SE df t.ratio p.value
 Model A: Nurse Phone - Model B: CHW Visits     2.50 0.239 57  10.448 &lt;0.0001
 Model A: Nurse Phone - Model C: Integrated     4.58 0.239 57  19.120 &lt;0.0001
 Model B: CHW Visits - Model C: Integrated      2.08 0.239 57   8.672 &lt;0.0001

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
</section>
<section id="detailed-interpretation-of-pairwise-comparisons" class="level3">
<h3 class="anchored" data-anchor-id="detailed-interpretation-of-pairwise-comparisons">Detailed Interpretation of Pairwise Comparisons</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tukey HSD Pairwise Comparisons</caption>
<colgroup>
<col style="width: 40%">
<col style="width: 29%">
<col style="width: 16%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Comparison</th>
<th style="text-align: center;">Difference (percentage points)</th>
<th style="text-align: center;">Adjusted p-value</th>
<th style="text-align: center;">Significant?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Model A: Nurse Phone - Model B: CHW Visits</td>
<td style="text-align: center;">2.50</td>
<td style="text-align: center;">&lt;.001</td>
<td style="text-align: center;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: center;">Model A: Nurse Phone - Model C: Integrated</td>
<td style="text-align: center;">4.57</td>
<td style="text-align: center;">&lt;.001</td>
<td style="text-align: center;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Model B: CHW Visits - Model C: Integrated</td>
<td style="text-align: center;">2.07</td>
<td style="text-align: center;">&lt;.001</td>
<td style="text-align: center;">Yes</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br> <strong>Key findings from Tukey’s HSD:</strong></p>
<ol type="1">
<li><p><strong>Model B vs.&nbsp;Model A</strong>: Community health worker home visits (Model B) reduce readmission rates by approximately 2.5 <strong>percentage points</strong> compared to nurse-led telephone follow-up (Model A), and this difference is statistically significant (p &lt; 0.05).</p></li>
<li><p><strong>Model C vs.&nbsp;Model A</strong>: The integrated care team with digital monitoring (Model C) reduces readmission rates by approximately 4.57 <strong>percentage points</strong> compared to Model A, showing the largest improvement (p &lt; 0.001).</p></li>
<li><p><strong>Model C vs.&nbsp;Model B</strong>: Model C also significantly outperforms Model B, reducing readmissions by approximately 2.07 <strong>percentage points</strong> (p &lt; 0.05).</p></li>
</ol>
</section>
<section id="practice-activity-2-hospital-operating-costs" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="practice-activity-2-hospital-operating-costs">Practice Activity 2: Hospital Operating Costs</h3>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Try It Yourself!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Complete the following practice activity by replacing the <code>___</code> blanks with appropriate values or function names. This will help you practice with a different dataset involving cost analysis across hospital types.</p>
</div>
</div>
<section id="scenario-case-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="scenario-case-1">Scenario Case</h4>
<ul>
<li><p>Compare average cost per patient discharge ($) across <strong>four different hospital types</strong>.</p></li>
<li><p>Hospital costs vary significantly by ownership type and facility characteristics, with meaningful differences observed between academic, community, and specialty hospitals.</p></li>
<li><p><strong>Hospital Types</strong>:</p>
<ul>
<li><strong>Academic Medical</strong>: Large teaching hospitals affiliated with medical schools</li>
<li><strong>Community</strong>: Non-teaching hospitals serving local populations</li>
<li><strong>Critical Access</strong>: Small rural hospitals (≤25 beds) serving remote areas</li>
<li><strong>Specialty</strong>: Hospitals focused on specific conditions (cardiac, orthopedic, etc.)</li>
</ul></li>
<li><p><strong>Research Question</strong>: Do operating costs per discharge differ significantly across hospital types?</p></li>
</ul>
</section>
<section id="dataset-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="dataset-1">Dataset</h4>
<p>Load the dataset for this practice activity using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Cost per discharge by hospital type</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>cost_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week06_operating_cost.csv"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cost_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X  cost    hospital_type
1 1 15200 Academic Medical
2 2 16500 Academic Medical
3 3 14800 Academic Medical
4 4 15900 Academic Medical
5 5 16200 Academic Medical
6 6 15100 Academic Medical</code></pre>
</div>
</div>
</section>
<section id="task-2.1-summary-statistics-and-visualization" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="task-2.1-summary-statistics-and-visualization">Task 2.1: Summary Statistics and Visualization</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>cost_data <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(___) <span class="sc">%&gt;%</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_cost =</span> <span class="fu">round</span>(<span class="fu">mean</span>(___), <span class="dv">0</span>),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_cost =</span> <span class="fu">round</span>(<span class="fu">sd</span>(___), <span class="dv">0</span>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(cost_data, <span class="fu">aes</span>(<span class="at">x =</span> ___, <span class="at">y =</span> ___, <span class="at">fill =</span> ___)) <span class="sc">+</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"___"</span>,</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Hospital Type"</span>,</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Cost per Discharge ($)"</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">20</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="task-2.2-one-way-anova" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="task-2.2-one-way-anova">Task 2.2: One-Way ANOVA</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run ANOVA</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>anova_cost <span class="ot">&lt;-</span> <span class="fu">aov</span>(___ <span class="sc">~</span> ___, <span class="at">data =</span> ___)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_cost)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Question</strong>: Are the cost differences statistically significant?</p>
</section>
<section id="task-2.3-post-hoc-comparisons" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="task-2.3-post-hoc-comparisons">Task 2.3: Post-Hoc Comparisons</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimated marginal means</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>emm_cost <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(___, <span class="sc">~</span> ___)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairwise comparisons</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(___, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions</strong>:</p>
<ol type="1">
<li>Which hospital type has the highest costs? Which has the lowest?</li>
<li>Are all pairwise comparisons significant, or only some?</li>
<li>What might explain these cost differences?</li>
</ol>
<hr>
</section>
</section>
</section>
</section>
<section id="repeated-measures-anova" class="level1">
<h1>2. Repeated-Measures ANOVA</h1>
<ul>
<li><p>So far, we have compared means across <strong>independent groups</strong> (e.g., different departments, training programs, or care models) where each observation belongs to only one group.</p></li>
<li><p>Now we turn to situations where the <strong>same subjects or patients are measured multiple times</strong>. This requires a different approach that accounts for the correlation between repeated observations on the same individual.</p></li>
</ul>
<section id="what-is-it-1" class="level2">
<h2 class="anchored" data-anchor-id="what-is-it-1">What is it?</h2>
<ul>
<li><p>A <strong>repeated-measures ANOVA</strong> (also called within-subjects ANOVA) tests whether there are significant differences across three or more related measurements on the <strong>same respondents</strong>. This design is the extension of the paired t-test to situations involving more than two time points, measurements, or conditions.</p></li>
<li><p>The key advantage of repeated-measures designs is that each respondent serves as their own control, which <strong>reduces error variance</strong> and increases statistical power. By tracking the same individuals over time, we eliminate individual differences as a source of variability.</p></li>
</ul>
</section>
<section id="when-to-use-it-1" class="level2">
<h2 class="anchored" data-anchor-id="when-to-use-it-1">When to Use It</h2>
<p>Repeated-measures ANOVA is appropriate for:</p>
<ul>
<li><strong>Longitudinal studies</strong>: Tracking patients at multiple time points
<ul>
<li>Pain scores at baseline (month 0), 1 month, 3 months, 6 months</li>
<li>HbA1c levels across quarterly clinic visits</li>
</ul></li>
<li><strong>Within-subject experiments</strong>: Testing same subjects under different conditions
<ul>
<li>Response to different medication dosages</li>
<li>Performance under different shift schedules</li>
</ul></li>
<li><strong>Quality improvement tracking</strong>: Monitoring metrics over multiple periods
<ul>
<li>Hospital safety scores across quarters</li>
<li>Patient satisfaction before, during, and after initiative implementation</li>
</ul></li>
</ul>
</section>
<section id="scenario-1-diabetes-management-program" class="level2">
<h2 class="anchored" data-anchor-id="scenario-1-diabetes-management-program">Scenario 1: Diabetes Management Program</h2>
<section id="background-and-context" class="level3">
<h3 class="anchored" data-anchor-id="background-and-context">Background and Context</h3>
<p>A healthcare organization implements a comprehensive diabetes management program for patients with poorly controlled Type 2 diabetes. The program includes:</p>
<ul>
<li><strong>Monthly nurse educator visits</strong> for medication management and lifestyle coaching</li>
<li><strong>Quarterly endocrinologist consultations</strong> for treatment plan adjustments</li>
<li><strong>Continuous glucose monitoring (CGM)</strong> with remote monitoring by care team</li>
<li><strong>Nutritionist consultations</strong> for personalized meal planning</li>
<li><strong>Group support sessions</strong> for peer learning and motivation</li>
</ul>
</section>
<section id="the-outcome-measure-hba1c" class="level3">
<h3 class="anchored" data-anchor-id="the-outcome-measure-hba1c">The Outcome Measure: HbA1c</h3>
<p><strong>What is HbA1c?</strong></p>
<ul>
<li>Glycated hemoglobin (HbA1c) measures average blood glucose over the past 2-3 months</li>
<li>Reported as a percentage (e.g., 7.5%)</li>
<li><strong>Clinical targets</strong>:
<ul>
<li>Normal: &lt; 5.7%</li>
<li>Prediabetes: 5.7-6.4%</li>
<li>Diabetes: ≥ 6.5%</li>
<li>Treatment goal: &lt; 7.5%</li>
</ul></li>
<li><strong>Why it matters</strong>: Each 1% reduction in HbA1c is associated with significant reductions in diabetes complications (retinopathy, nephropathy, neuropathy)</li>
</ul>
</section>
<section id="study-design" class="level3">
<h3 class="anchored" data-anchor-id="study-design">Study Design</h3>
<p>The organization tracks <strong>HbA1c levels</strong> for 25 enrolled patients at <strong>four time points</strong>:</p>
<ul>
<li><strong>Baseline</strong>: Before program enrollment (typical range: 8-10% for poorly controlled diabetes)</li>
<li><strong>3 months</strong>: Initial follow-up (early response to intervention)</li>
<li><strong>6 months</strong>: Mid-program (sustained adherence check)</li>
<li><strong>12 months</strong>: Program completion (long-term effectiveness)</li>
</ul>
</section>
<section id="why-use-repeated-measures-anova" class="level3">
<h3 class="anchored" data-anchor-id="why-use-repeated-measures-anova">Why Use Repeated-Measures ANOVA?</h3>
<p>This is a <strong>perfect scenario</strong> for repeated-measures ANOVA because:</p>
<ol type="1">
<li><strong>Same patients tracked over time</strong>: Each patient serves as their own control</li>
<li><strong>Multiple time points</strong>: Four measurements (more than two)</li>
<li><strong>Reduces individual variability</strong>: Some patients naturally have higher HbA1c than others; repeated measures accounts for this</li>
<li><strong>Efficient use of resources</strong>: We need only 25 patients instead of 100 (25 per group × 4 groups) if we used one-way ANOVA</li>
<li><strong>Longitudinal question</strong>: We want to know if HbA1c changes over time within the same individuals</li>
</ol>
</section>
<section id="research-questions" class="level3">
<h3 class="anchored" data-anchor-id="research-questions">Research Questions</h3>
<ol type="1">
<li><p>Does HbA1c change significantly over the course of the 12-month program?</p></li>
<li><p>If significant:</p></li>
</ol>
<ul>
<li>At which time points do we see significant improvements?</li>
<li>Do patients reach the clinical target of &lt; 7.5% by 12 months?</li>
<li>Is the improvement sustained or does it plateau?</li>
</ul>
</section>
</section>
<section id="the-formula-1" class="level2">
<h2 class="anchored" data-anchor-id="the-formula-1">The Formula</h2>
<p>Repeated-measures ANOVA partitions variance differently than one-way ANOVA to account for the correlation between measurements on the same subject:</p>
<p><span class="math display">\[F = \frac{MS_{time}}{MS_{error}}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(MS_{time}\)</span> = Mean square for the time (or condition) effect</li>
<li><span class="math inline">\(MS_{error}\)</span> = Mean square for error (residual variation after removing both subject and time effects)</li>
</ul>
<section id="formulas-for-sum-of-squares-components" class="level3">
<h3 class="anchored" data-anchor-id="formulas-for-sum-of-squares-components">Formulas for Sum of Squares Components</h3>
<p>To calculate the variance components in repeated-measures ANOVA, we need these formulas:</p>
<p><strong>0. Total Sum of Squares (SS_total):</strong></p>
<p><span class="math display">\[SS_{total} = \sum_{i=1}^{n} \sum_{j=1}^{t} (X_{ij} - \bar{X}_{grand})^2\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(X_{ij}\)</span> = observation for subject <span class="math inline">\(i\)</span> at time point <span class="math inline">\(j\)</span></li>
<li><span class="math inline">\(\bar{X}_{grand}\)</span> = overall grand mean (across all subjects and all time points)</li>
<li><span class="math inline">\(n\)</span> = number of subjects</li>
<li><span class="math inline">\(t\)</span> = number of time points</li>
</ul>
<p>This measures total variation in all observations from the grand mean. This is the “starting point” that we partition into components.</p>
<p><strong>1. Sum of Squares for Time Effect (SS_time):</strong></p>
<p><span class="math display">\[SS_{time} = n \sum_{j=1}^{t} (\bar{X}_j - \bar{X}_{grand})^2\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(n\)</span> = number of subjects (the weighting factor; each time point mean is based on <span class="math inline">\(n\)</span> observations)</li>
<li><span class="math inline">\(t\)</span> = number of time points</li>
<li><span class="math inline">\(\bar{X}_j\)</span> = mean at time point <span class="math inline">\(j\)</span> (averaging across all subjects)</li>
<li><span class="math inline">\(\bar{X}_{grand}\)</span> = overall grand mean (across all subjects and all time points)</li>
</ul>
<p>This measures how much the time point means differ from the overall mean. We multiply by <span class="math inline">\(n\)</span> because each time point’s mean represents <span class="math inline">\(n\)</span> subjects.</p>
<p><strong>2. Sum of Squares Between-Subjects (SS_subjects):</strong></p>
<p><span class="math display">\[SS_{subjects} = t \sum_{i=1}^{n} (\bar{X}_i - \bar{X}_{grand})^2\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(t\)</span> = number of time points (the weighting factor; each subject’s mean is based on <span class="math inline">\(t\)</span> observations)</li>
<li><span class="math inline">\(\bar{X}_i\)</span> = mean for subject <span class="math inline">\(i\)</span> (averaging across all time points)</li>
</ul>
<p>This measures how much individual subjects differ from the overall mean. We multiply by <span class="math inline">\(t\)</span> because each subject’s mean represents <span class="math inline">\(t\)</span> observations. This component gets <strong>removed from the error term</strong>, which is the key advantage of repeated-measures designs!</p>
<p><strong>3. Sum of Squares Error (SS_error):</strong></p>
<p><span class="math display">\[SS_{error} = SS_{total} - SS_{subjects} - SS_{time}\]</span></p>
<p>Or, calculated directly:</p>
<p><span class="math display">\[SS_{error} = \sum_{i=1}^{n} \sum_{j=1}^{t} (X_{ij} - \bar{X}_i - \bar{X}_j + \bar{X}_{grand})^2\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(X_{ij}\)</span> = observation for subject <span class="math inline">\(i\)</span> at time <span class="math inline">\(j\)</span></li>
<li><span class="math inline">\(\bar{X}_i\)</span> = mean for subject <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(\bar{X}_j\)</span> = mean for time <span class="math inline">\(j\)</span></li>
<li><span class="math inline">\(\bar{X}_{grand}\)</span> = grand mean</li>
</ul>
<p>This measures random variation left over after removing both subject differences and time effects.</p>
<p>Notice that <span class="math inline">\(SS_{error}\)</span> is calculated by subtracting out both subject means AND time means. This is why it’s smaller than one-way ANOVA error (we’ve removed the between-subjects variance!)</p>
</section>
<section id="calculating-the-f-statistic" class="level3">
<h3 class="anchored" data-anchor-id="calculating-the-f-statistic">Calculating the F-Statistic</h3>
<p>The F-statistic tests whether the time effect is larger than random error:</p>
<p><span class="math display">\[F = \frac{MS_{time}}{MS_{error}} = \frac{SS_{time}/df_{time}}{SS_{error}/df_{error}}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(df_{time} = t - 1\)</span> (number of time points minus 1)</li>
<li><span class="math inline">\(df_{error} = (n-1) \times (t-1)\)</span> (subjects - 1) × (time points - 1)</li>
</ul>
<p><strong>Hypotheses:</strong></p>
<ul>
<li><span class="math inline">\(H_0\)</span>: All time point means are equal (<span class="math inline">\(\mu_{baseline} = \mu_{3mo} = \mu_{6mo} = \mu_{12mo}\)</span>)</li>
<li><span class="math inline">\(H_A\)</span>: At least one time point mean is different from the others</li>
</ul>
<p><strong>Interpretation:</strong></p>
<ul>
<li>Similar to one-way ANOVA, as the variation across time points is getting larger (vs.&nbsp;smaller), the F-statistic is getting larger (vs.&nbsp;smaller).</li>
<li>If the F-statistic is large enough, we reject the null hypothesis and conclude that there is a significant change in HbA1c over time.</li>
</ul>
</section>
</section>
<section id="example-diabetes-management-program" class="level2">
<h2 class="anchored" data-anchor-id="example-diabetes-management-program">Example: Diabetes Management Program</h2>
<p>Let’s look at the following example. Load the dataset using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load HbA1c levels (%) for 25 patients at 4 time points</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>diabetes_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week06_diabetes.csv"</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert time to factor with meaningful labels</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>diabetes_data <span class="ot">&lt;-</span> diabetes_data <span class="sc">%&gt;%</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">time =</span> <span class="fu">factor</span>(time, </span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Baseline"</span>, <span class="st">"3 Months"</span>, <span class="st">"6 Months"</span>, <span class="st">"12 Months"</span>)), </span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">patient_id =</span> <span class="fu">factor</span>(patient_id)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>HbA1c Summary Statistics by Time Point</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Time Point</th>
<th style="text-align: center;">n</th>
<th style="text-align: center;">Mean HbA1c (%)</th>
<th style="text-align: center;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Baseline</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">8.24</td>
<td style="text-align: center;">0.77</td>
</tr>
<tr class="even">
<td style="text-align: center;">3 Months</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">7.76</td>
<td style="text-align: center;">0.80</td>
</tr>
<tr class="odd">
<td style="text-align: center;">6 Months</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">7.47</td>
<td style="text-align: center;">0.82</td>
</tr>
<tr class="even">
<td style="text-align: center;">12 Months</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">7.17</td>
<td style="text-align: center;">1.02</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="visualizing-repeated-measures-data" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-repeated-measures-data">Visualizing Repeated Measures Data</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spaghetti plot showing individual trajectories</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(diabetes_data, <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> hba1c, <span class="at">group =</span> patient_id)) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">"gray50"</span>) <span class="sc">+</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">linewidth =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Individual Patient HbA1c Trajectories"</span>,</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Red line shows mean across all patients"</span>,</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Time Point"</span>, <span class="at">y =</span> <span class="st">"HbA1c (%)"</span>) <span class="sc">+</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture06_files/figure-html/repeated-viz1-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The summary statistics and the trajectory plot show a <strong>downward trend</strong> in mean HbA1c across the four time points, from 8.24% at Baseline to 7.17% at 12 Months.</li>
<li>Each gray line represents an individual patient’s trajectory, and the red line shows the overall group mean. Most patients show a consistent decline over time.</li>
<li>Our remaining question is <strong>whether these changes are statistically significant</strong>. Let’s test this with a repeated-measures ANOVA.</li>
</ul>
</section>
<section id="conducting-repeated-measures-anova-in-r" class="level2">
<h2 class="anchored" data-anchor-id="conducting-repeated-measures-anova-in-r">Conducting Repeated-Measures ANOVA in R</h2>
<ul>
<li>We can also use the <code>aov()</code> function to perform a repeated-measures ANOVA.</li>
<li>For repeated-measures ANOVA, we additionally need to specify the error term to account for the within-subjects design.</li>
<li>The error term is specified as <code>Error(patient_id/time)</code>, which tells R that each patient (<code>patient_id</code>) is measured repeatedly across <code>time</code>. This partitions the error into between-subjects and within-subjects components, so the time effect is tested appropriately.</li>
</ul>
<p><strong>Hypotheses:</strong></p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Mean HbA1c is equal across all four time points (<span class="math inline">\(\mu_{baseline} = \mu_{3mo} = \mu_{6mo} = \mu_{12mo}\)</span>)</li>
<li><span class="math inline">\(H_A\)</span>: At least one time point’s mean HbA1c differs from the others</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Repeated-measures ANOVA</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Error(patient_id/time) specifies that time is within subjects</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>rm_anova <span class="ot">&lt;-</span> <span class="fu">aov</span>(hba1c <span class="sc">~</span> time <span class="sc">+</span> <span class="fu">Error</span>(patient_id<span class="sc">/</span>time), <span class="at">data =</span> diabetes_data)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rm_anova)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: patient_id
          Df Sum Sq Mean Sq F value Pr(&gt;F)
Residuals 24  66.02   2.751               

Error: patient_id:time
          Df Sum Sq Mean Sq F value Pr(&gt;F)    
time       3 15.497   5.166   84.81 &lt;2e-16 ***
Residuals 72  4.385   0.061                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<section id="interpreting-the-output" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-the-output">Interpreting the Output</h3>
<p><strong>Understanding the R Output:</strong></p>
<ul>
<li><strong>time row</strong>: Tests whether mean HbA1c differs across time points</li>
<li><strong>Df = 3</strong>: Degrees of freedom for time (4 time points - 1)</li>
<li><strong>F value</strong>: Ratio of time effect variance to residual variance</li>
<li><strong>Pr(&gt;F)</strong>: p-value for the time effect</li>
</ul>
</section>
<section id="conclusion-and-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-and-interpretation">Conclusion and Interpretation</h3>
<ul>
<li><p>With a significant F-test (p &lt; 0.05), we <strong>reject the null hypothesis</strong>. HbA1c levels changed significantly over the course of the 12-month diabetes management program.</p></li>
<li><p>Overall, 1.07 percentage points were improved.</p>
<ul>
<li>Patients started with poorly controlled diabetes (average 8.24%)</li>
<li>By 6 and 12 months, average HbA1c achieved the treatment goal of &lt;7.5%</li>
<li>This magnitude of reduction is associated with meaningful decreases in long-term complications</li>
</ul></li>
</ul>
<p><strong>But which specific time points differ?</strong> We need post-hoc tests to determine when significant improvements occurred, whether the improvement continues, or plateaus.</p>
</section>
</section>
<section id="post-hoc-tests-for-repeated-measures" class="level2">
<h2 class="anchored" data-anchor-id="post-hoc-tests-for-repeated-measures">Post-Hoc Tests for Repeated Measures</h2>
<ul>
<li><p>To identify which time points differ, we use pairwise comparisons with p-value adjustment.</p></li>
<li><p>We can use the same <code>emmeans</code> and <code>pairs</code> functions as before.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract estimated marginal means</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>emm_time <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(rm_anova, <span class="sc">~</span> time)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>emm_time</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> time      emmean    SE   df lower.CL upper.CL
 Baseline    8.24 0.171 27.2     7.89     8.59
 3 Months    7.76 0.171 27.2     7.41     8.11
 6 Months    7.47 0.171 27.2     7.12     7.82
 12 Months   7.17 0.171 27.2     6.82     7.52

Warning: EMMs are biased unless design is perfectly balanced 
Confidence level used: 0.95 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairwise comparisons with Tukey adjustment</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(emm_time, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast             estimate     SE df t.ratio p.value
 Baseline - 3 Months     0.480 0.0698 72   6.876 &lt;0.0001
 Baseline - 6 Months     0.768 0.0698 72  11.002 &lt;0.0001
 Baseline - 12 Months    1.068 0.0698 72  15.300 &lt;0.0001
 3 Months - 6 Months     0.288 0.0698 72   4.126  0.0006
 3 Months - 12 Months    0.588 0.0698 72   8.424 &lt;0.0001
 6 Months - 12 Months    0.300 0.0698 72   4.298  0.0003

P value adjustment: tukey method for comparing a family of 4 estimates </code></pre>
</div>
</div>
<section id="interpreting-post-hoc-results" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-post-hoc-results">Interpreting Post-Hoc Results</h3>
<ul>
<li><p>The emmeans output shows pairwise comparisons for all time point combinations. Significant values (p.value &lt; 0.05) indicate that those time points have significantly different mean HbA1c levels.</p></li>
<li><p><strong>First section (emmeans):</strong> shows estimated marginal mean HbA1c at each time point.</p></li>
<li><p><strong>Second section (pairwise comparisons):</strong></p>
<ul>
<li><strong>contrast</strong>: Which two time points are being compared</li>
<li><strong>estimate</strong>: Difference between the two time point means</li>
<li><strong>SE</strong>: Standard error of the difference</li>
<li><strong>df</strong>: Degrees of freedom</li>
<li><strong>t.ratio</strong>: Test statistic</li>
<li><strong>p.value</strong>: Adjusted p-value (controlling for multiple comparisons)</li>
</ul></li>
<li><p>The results show that the diabetes management program <strong>significantly reduced</strong> HbA1c levels at each time point compared to baseline (all p &lt; 0.05). Furthermore, the differences between consecutive time points (3 vs.&nbsp;6 months, 6 vs.&nbsp;12 months) are also significant, suggesting that improvement occurs <strong>continuously</strong> throughout the 12-month period rather than plateauing.</p></li>
</ul>
</section>
<section id="practice-activity-3-pain-management-follow-up" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="practice-activity-3-pain-management-follow-up">Practice Activity 3: Pain Management Follow-up</h3>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Try It Yourself!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Complete the following practice activity by replacing the <code>___</code> blanks with appropriate values or function names. This will help you practice conducting repeated-measures ANOVA with longitudinal data.</p>
</div>
</div>
<section id="scenario" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="scenario">Scenario</h4>
<ul>
<li><p>A pain clinic measures pain intensity (0-10 VAS scale) for 20 chronic pain patients at <strong>five time points</strong> during a 6-month treatment program.</p></li>
<li><p>The Visual Analogue Scale (VAS) is a validated, reliable tool for assessing chronic pain intensity over time.</p></li>
<li><p>Pain perceptions measured across the following time points:</p>
<ul>
<li><strong>Baseline</strong>: Before treatment starts</li>
<li><strong>Month 1</strong>: Early treatment phase</li>
<li><strong>Month 2</strong>: Continued intervention</li>
<li><strong>Month 4</strong>: Mid-term follow-up</li>
<li><strong>Month 6</strong>: End of program</li>
</ul></li>
<li><p>The question we want to answer is <strong>whether pain intensity decreases significantly</strong> over the course of the treatment program.</p></li>
</ul>
</section>
<section id="dataset-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="dataset-2">Dataset</h4>
<p>Load the dataset using the code below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Pain scores at 5 time points for 20 patients</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>pain_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week06_pain_management.csv"</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert time to factor with correct order, and patient_id to factor</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>pain_data <span class="ot">&lt;-</span> pain_data <span class="sc">%&gt;%</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">time =</span> <span class="fu">factor</span>(time, </span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Baseline"</span>, <span class="st">"Month 1"</span>, <span class="st">"Month 2"</span>, <span class="st">"Month 4"</span>, <span class="st">"Month 6"</span>)), <span class="co"># make time variable as factor</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">patient_id =</span> <span class="fu">factor</span>(patient_id) <span class="co"># make patient_id as factor</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="task-3.1-summary-statistics-by-time" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="task-3.1-summary-statistics-by-time">Task 3.1: Summary Statistics by Time</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate mean pain at each time point</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>pain_data <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(___) <span class="sc">%&gt;%</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_pain =</span> <span class="fu">round</span>(<span class="fu">mean</span>(___), <span class="dv">2</span>),</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd_pain =</span> <span class="fu">round</span>(<span class="fu">sd</span>(___), <span class="dv">2</span>)</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Question</strong>: Looking at the means, does pain appear to decrease over time?</p>
</section>
<section id="task-3.2-visualize-trajectories" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="task-3.2-visualize-trajectories">Task 3.2: Visualize Trajectories</h4>
<p>Create a “spaghetti plot” showing individual patient pain trajectories:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spaghetti plot with individual lines and overall mean</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pain_data, <span class="fu">aes</span>(<span class="at">x =</span> ___, <span class="at">y =</span> ___, <span class="at">group =</span> ___)) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">"gray50"</span>) <span class="sc">+</span>  <span class="co"># Individual patient lines</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>,  <span class="co"># Overall mean line</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">linewidth =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"___"</span>,</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Red line shows mean across all patients"</span>,</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Time Point"</span>,</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Pain Intensity (VAS 0-10)"</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Question</strong>: Do most patients show a declining trend? Are there any patients who don’t improve?</p>
</section>
<section id="task-3.3-repeated-measures-anova" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="task-3.3-repeated-measures-anova">Task 3.3: Repeated-Measures ANOVA</h4>
<p>Now test if the changes are statistically significant:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Repeated-measures ANOVA</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>rm_anova_pain <span class="ot">&lt;-</span> <span class="fu">aov</span>(___ <span class="sc">~</span> ___ <span class="sc">+</span> <span class="fu">Error</span>(___<span class="sc">/</span>___), <span class="at">data =</span> pain_data)</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display results</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rm_anova_pain)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions</strong>:</p>
<ol type="1">
<li>What is the F-value for the time effect?</li>
<li>What is the p-value?</li>
<li>Is there a significant change in pain over time?</li>
</ol>
</section>
<section id="task-3.4-post-hoc-tests-for-time-points" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="task-3.4-post-hoc-tests-for-time-points">Task 3.4: Post-Hoc Tests for Time Points</h4>
<p>Identify which time points differ significantly:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimated marginal means by time</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>emm_pain <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(___, <span class="sc">~</span> ___)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>emm_pain</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairwise comparisons</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(___, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions</strong>:</p>
<ol type="1">
<li>At which time point is pain significantly lower than baseline?</li>
<li>Is there continued improvement from Month 4 to Month 6?</li>
<li>What do these results suggest about the treatment timeline?</li>
</ol>
<hr>
</section>
</section>
</section>
<section id="example-2-staff-burnout-across-shift-schedules" class="level2">
<h2 class="anchored" data-anchor-id="example-2-staff-burnout-across-shift-schedules">Example 2: Staff Burnout Across Shift Schedules</h2>
<ul>
<li><p>A hospital HR department wants to study nurse burnout using the Maslach Burnout Inventory (MBI) emotional exhaustion subscale (score range: 0-54).</p></li>
<li><p>They measure the <strong>same 20 nurses</strong> under three different shift schedules:</p>
<ul>
<li><strong>Schedule A</strong>: Traditional 8-hour shifts</li>
<li><strong>Schedule B</strong>: 12-hour shifts</li>
<li><strong>Schedule C</strong>: Flexible self-scheduling (nurses choose their own shift times and lengths)</li>
</ul></li>
<li><p>Multiple studies have examined the relationship between shift hours and nurse burnout, with research across multiple countries and care settings showing significant associations between shift length and burnout levels.</p></li>
<li><p>Each nurse works under each schedule for one month, with washout periods between.</p></li>
</ul>
<p>Let’s load the dataset and visually inspect the pattern:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load burnout scores for 20 nurses under 3 shift schedules</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>burnout_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week06_burnout.csv"</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert schedule to factor with correct order</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>burnout_data <span class="ot">&lt;-</span> burnout_data <span class="sc">%&gt;%</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">schedule =</span> <span class="fu">factor</span>(schedule, </span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>                      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"A: 8-hour"</span>, <span class="st">"B: 12-hour"</span>, <span class="st">"C: Flexible"</span>)),</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">nurse_id =</span> <span class="fu">factor</span>(nurse_id)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spaghetti plot</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(burnout_data, <span class="fu">aes</span>(<span class="at">x =</span> schedule, <span class="at">y =</span> burnout, <span class="at">group =</span> nurse_id)) <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">"gray50"</span>) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">linewidth =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Individual Nurse Burnout Scores"</span>,</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Shift Schedule"</span>, <span class="at">y =</span> <span class="st">"Burnout Score (MBI)"</span>) <span class="sc">+</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>p1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture06_files/figure-html/repeated-viz2-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>There are variations in Burnout scores across the three shift schedules (Schedule B &gt; Schedule A &gt; Schedule C).</li>
<li>Now, let’s check whether the difference is statistically significant using repeated-measures ANOVA.</li>
</ul>
<p><strong>Hypotheses:</strong></p>
<ul>
<li><span class="math inline">\(H_0\)</span>: Mean burnout scores are equal across all three shift schedules (<span class="math inline">\(\mu_A = \mu_B = \mu_C\)</span>)</li>
<li><span class="math inline">\(H_A\)</span>: At least one shift schedule’s mean burnout score differs from the others</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Repeated-measures ANOVA</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>rm_anova_burnout <span class="ot">&lt;-</span> <span class="fu">aov</span>(burnout <span class="sc">~</span> schedule <span class="sc">+</span> <span class="fu">Error</span>(nurse_id<span class="sc">/</span>schedule),</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> burnout_data)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rm_anova_burnout)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: nurse_id
          Df Sum Sq Mean Sq F value Pr(&gt;F)
Residuals 19    617   32.47               

Error: nurse_id:schedule
          Df Sum Sq Mean Sq F value Pr(&gt;F)    
schedule   2 1690.1   845.1    5474 &lt;2e-16 ***
Residuals 38    5.9     0.2                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Post-hoc tests</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>emm_schedule <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(rm_anova_burnout, <span class="sc">~</span> schedule)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(emm_schedule, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                   estimate    SE df t.ratio p.value
 (A: 8-hour) - (B: 12-hour)     -6.6 0.124 38 -53.118 &lt;0.0001
 (A: 8-hour) - C: Flexible       6.4 0.124 38  51.508 &lt;0.0001
 (B: 12-hour) - C: Flexible     13.0 0.124 38 104.626 &lt;0.0001

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<ul>
<li><p>The highly significant F-test indicates that burnout levels differ across shift schedules (at least one shift schedule’s mean burnout score differs from the others).</p></li>
<li><p>Post-hoc tests reveal that:</p>
<ul>
<li>Flexible scheduling (C) results in significantly lower burnout than both traditional (A) and 12-hour (B) shifts</li>
<li>12-hour shifts (B) result in significantly higher burnout than 8-hour shifts (A)</li>
</ul></li>
<li><p><strong>Management implications</strong>: These findings suggest that offering flexible self-scheduling could be an effective strategy to reduce nurse burnout. Lower burnout can be associated with reduced turnover (saving recruitment and training costs), fewer medical errors, and improved patient satisfaction scores.</p></li>
</ul>
</section>
<section id="practice-activity-4-employee-engagement-survey" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="practice-activity-4-employee-engagement-survey">Practice Activity 4: Employee Engagement Survey</h3>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Try It Yourself! (10 minutes)
</div>
</div>
<div class="callout-body-container callout-body">
<p>This final practice will help you solidify your understanding of repeated-measures designs. This time, you’ll conduct the <strong>entire analysis independently</strong> following the same structure as Practice Activity 3.</p>
</div>
</div>
<section id="scenario-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="scenario-1">Scenario</h4>
<ul>
<li><p>An HR department surveys nurse engagement quarterly over one year (4 time points; across 4 quarters: Q1, Q2, Q3, and Q4).</p></li>
<li><p>Engagement scores (1-100) capture nurses’ emotional commitment, motivation, and connection to their work (e.g., feeling energized, finding purpose in patient care, and being fully focused during shifts).</p></li>
<li><p>We want to understand whether nurse engagement changes significantly across the four quarters.</p></li>
</ul>
</section>
<section id="dataset-3" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="dataset-3">Dataset</h4>
<p>Load the dataset using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Engagement scores (1-100) for 25 nurses over 4 quarters</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>engagement_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week06_engagement.csv"</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>engagement_data <span class="ot">&lt;-</span> engagement_data <span class="sc">%&gt;%</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">quarter =</span> <span class="fu">factor</span>(quarter, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Q1"</span>, <span class="st">"Q2"</span>, <span class="st">"Q3"</span>, <span class="st">"Q4"</span>)), </span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">nurse_id =</span> <span class="fu">factor</span>(nurse_id)</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="task-4.1-complete-analysis" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="task-4.1-complete-analysis">Task 4.1: Complete Analysis</h4>
<p>Conduct the entire analysis independently! Follow these steps:</p>
<ol type="1">
<li>Calculate summary statistics by quarter</li>
<li>Create a visualization (spaghetti plot or boxplot)</li>
<li>Run repeated-measures ANOVA</li>
<li>Interpret the F-test</li>
<li>If significant, run post-hoc tests</li>
<li>Draw conclusions</li>
</ol>
<p><strong>Hint</strong>: Follow the same structure as Practice Activity 3.</p>
<p><strong>Questions</strong>:</p>
<ol type="1">
<li>Does engagement change significantly over the year?</li>
<li>If yes, which quarters differ from each other?</li>
<li>What recommendations would you make to HR based on these results?</li>
</ol>
<hr>
</section>
</section>
</section>
</section>
<section id="summary" class="level1">
<h1>Summary</h1>
<section id="key-takeaways" class="level2">
<h2 class="anchored" data-anchor-id="key-takeaways">Key Takeaways</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 33%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Purpose</th>
<th>Key Points</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>One-Way ANOVA</strong></td>
<td>Compare means across 3+ independent groups</td>
<td>Single factor, between-subjects design</td>
</tr>
<tr class="even">
<td><strong>Repeated-Measures ANOVA</strong></td>
<td>Compare means across 3+ related measurements</td>
<td>Same subjects, within-subjects design</td>
</tr>
<tr class="odd">
<td><strong>Post-Hoc Tests</strong></td>
<td>Identify which specific groups differ</td>
<td>Use after significant ANOVA, adjusts for multiple comparisons</td>
</tr>
</tbody>
</table>
<ul>
<li><p><strong>One-way ANOVA</strong> enables evidence-based comparisons across multiple departments, facilities, treatment protocols, or patient populations simultaneously while controlling Type I error.</p></li>
<li><p><strong>Repeated-measures ANOVA</strong> is essential for evaluating longitudinal programs and interventions, tracking patient outcomes over time, measuring the effectiveness of quality improvement initiatives, or assessing staff development programs.</p></li>
<li><p><strong>Post-hoc tests</strong> ensure that when you identify “significant differences,” you can understand exactly where those differences lie, enabling targeted action rather than broad, unfocused interventions.</p></li>
</ul>
<hr>
</section>
</section>
<section id="references-and-further-reading" class="level1">
<h1>References and Further Reading</h1>
<section id="statistical-methods" class="level2">
<h2 class="anchored" data-anchor-id="statistical-methods">Statistical Methods</h2>
<ul>
<li>Field, A. (2018). <em>Discovering Statistics Using IBM SPSS Statistics</em> (5th ed.). SAGE Publications.</li>
<li>Navarro, D. (2019). <em>Learning Statistics with R</em>. Available online.</li>
<li>Maxwell, S. E., &amp; Delaney, H. D. (2004). <em>Designing Experiments and Analyzing Data</em> (2nd ed.). Psychology Press.</li>
<li>Wickham, H., &amp; Grolemund, G. (2017). <em>R for Data Science</em>. O’Reilly Media.</li>
</ul>
</section>
<section id="healthcare-applications" class="level2">
<h2 class="anchored" data-anchor-id="healthcare-applications">Healthcare Applications</h2>
<p>Examples are motivated by the following:</p>
<ul>
<li><p>Assessing Patient Satisfaction with Hospital Services. (2025). <em>Healthcare (Basel)</em>. https://pmc.ncbi.nlm.nih.gov/articles/PMC11988329/</p></li>
<li><p>Effect of Community Health Workers on 30-Day Hospital Readmissions. (2021). <em>JAMA Network Open</em>. https://jamanetwork.com/journals/jamanetworkopen/fullarticle/2780265</p></li>
<li><p>Medication Safety Simulation Training for Anesthesia Professionals. (2025). <em>Clinical Simulation in Nursing</em>. https://www.nursingsimulation.org/article/S1876-1399(24)00152-X/fulltext</p></li>
<li><p>Improved Glycemic Control With a Digital Health Intervention in Adults With Type 2 Diabetes. (2021). <em>JMIR Diabetes</em>. https://diabetes.jmir.org/2021/2/e28033/</p></li>
<li><p>Association of 12 h Shifts and Nurses’ Job Satisfaction, Burnout and Intention to Leave. (2015). <em>BMJ Open</em>. https://pmc.ncbi.nlm.nih.gov/articles/PMC4577950/</p></li>
<li><p>Visual Analogue Scale. <em>Physiopedia</em>. https://www.physio-pedia.com/Visual_Analogue_Scale</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>