<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-02-09">

<title>Mean Comparison 1: t-Tests – Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-604a5dd36684a50abe6acf259e8a2828.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026)</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../../index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mba642-spring-26/mba642-spring-26.github.io/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Mean Comparison 1: t-Tests</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction-to-t-tests" id="toc-introduction-to-t-tests" class="nav-link active" data-scroll-target="#introduction-to-t-tests">Introduction to t-tests</a>
  <ul class="collapse">
  <li><a href="#why-t-tests-matter" id="toc-why-t-tests-matter" class="nav-link" data-scroll-target="#why-t-tests-matter">Why t-tests Matter</a></li>
  <li><a href="#overview-of-the-three-t-test-types" id="toc-overview-of-the-three-t-test-types" class="nav-link" data-scroll-target="#overview-of-the-three-t-test-types">Overview of the Three t-Test Types</a></li>
  </ul></li>
  <li><a href="#datasets-for-today" id="toc-datasets-for-today" class="nav-link" data-scroll-target="#datasets-for-today">Datasets for Today</a>
  <ul class="collapse">
  <li><a href="#dataset-variables" id="toc-dataset-variables" class="nav-link" data-scroll-target="#dataset-variables">Dataset Variables</a>
  <ul class="collapse">
  <li><a href="#hospital_ops-demonstration-data" id="toc-hospital_ops-demonstration-data" class="nav-link" data-scroll-target="#hospital_ops-demonstration-data"><code>hospital_ops</code> (Demonstration Data)</a></li>
  <li><a href="#patient_outcomes-practice-data" id="toc-patient_outcomes-practice-data" class="nav-link" data-scroll-target="#patient_outcomes-practice-data"><code>patient_outcomes</code> (Practice Data)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#one-sample-t-test" id="toc-one-sample-t-test" class="nav-link" data-scroll-target="#one-sample-t-test">1. One-Sample t-Test</a>
  <ul class="collapse">
  <li><a href="#what-is-it" id="toc-what-is-it" class="nav-link" data-scroll-target="#what-is-it">What is it?</a>
  <ul class="collapse">
  <li><a href="#key-components" id="toc-key-components" class="nav-link" data-scroll-target="#key-components">Key Components</a></li>
  </ul></li>
  <li><a href="#when-to-use-it" id="toc-when-to-use-it" class="nav-link" data-scroll-target="#when-to-use-it">When to Use It</a></li>
  <li><a href="#one-sample-t-test-scenario-ed-waiting-times" id="toc-one-sample-t-test-scenario-ed-waiting-times" class="nav-link" data-scroll-target="#one-sample-t-test-scenario-ed-waiting-times">One-Sample t-test Scenario: ED Waiting Times</a></li>
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses">Hypotheses</a></li>
  <li><a href="#the-formula" id="toc-the-formula" class="nav-link" data-scroll-target="#the-formula">The Formula</a>
  <ul class="collapse">
  <li><a href="#understanding-the-formula" id="toc-understanding-the-formula" class="nav-link" data-scroll-target="#understanding-the-formula">Understanding the Formula</a></li>
  </ul></li>
  <li><a href="#example-calculation" id="toc-example-calculation" class="nav-link" data-scroll-target="#example-calculation">Example Calculation</a></li>
  <li><a href="#visualizing-the-data" id="toc-visualizing-the-data" class="nav-link" data-scroll-target="#visualizing-the-data">Visualizing the Data</a></li>
  <li><a href="#visualizing-the-null-distribution" id="toc-visualizing-the-null-distribution" class="nav-link" data-scroll-target="#visualizing-the-null-distribution">Visualizing the Null Distribution</a></li>
  <li><a href="#conducting-one-sample-t-test-in-r" id="toc-conducting-one-sample-t-test-in-r" class="nav-link" data-scroll-target="#conducting-one-sample-t-test-in-r">Conducting one-sample t-test in R</a>
  <ul class="collapse">
  <li><a href="#interpreting-the-output" id="toc-interpreting-the-output" class="nav-link" data-scroll-target="#interpreting-the-output">Interpreting the Output</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#practice-one-sample-t-test" id="toc-practice-one-sample-t-test" class="nav-link" data-scroll-target="#practice-one-sample-t-test">✏️ Practice: One-Sample t-Test</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#independent-samples-t-test" id="toc-independent-samples-t-test" class="nav-link" data-scroll-target="#independent-samples-t-test">2. Independent-Samples t-test</a>
  <ul class="collapse">
  <li><a href="#what-is-it-1" id="toc-what-is-it-1" class="nav-link" data-scroll-target="#what-is-it-1">What is it?</a>
  <ul class="collapse">
  <li><a href="#key-requirements" id="toc-key-requirements" class="nav-link" data-scroll-target="#key-requirements">Key Requirements</a></li>
  <li><a href="#why-independent" id="toc-why-independent" class="nav-link" data-scroll-target="#why-independent">Why “Independent”?</a></li>
  </ul></li>
  <li><a href="#when-to-use-it-1" id="toc-when-to-use-it-1" class="nav-link" data-scroll-target="#when-to-use-it-1">When to Use It</a></li>
  <li><a href="#independent-samples-t-test-scenario-comparing-patient-intake-systems" id="toc-independent-samples-t-test-scenario-comparing-patient-intake-systems" class="nav-link" data-scroll-target="#independent-samples-t-test-scenario-comparing-patient-intake-systems">Independent-Samples t-test Scenario: Comparing Patient Intake Systems</a></li>
  <li><a href="#hypotheses-1" id="toc-hypotheses-1" class="nav-link" data-scroll-target="#hypotheses-1">Hypotheses</a></li>
  <li><a href="#the-formula-1" id="toc-the-formula-1" class="nav-link" data-scroll-target="#the-formula-1">The Formula</a>
  <ul class="collapse">
  <li><a href="#understanding-the-formula-1" id="toc-understanding-the-formula-1" class="nav-link" data-scroll-target="#understanding-the-formula-1">Understanding the Formula</a></li>
  </ul></li>
  <li><a href="#example-comparing-hospital-intake-times" id="toc-example-comparing-hospital-intake-times" class="nav-link" data-scroll-target="#example-comparing-hospital-intake-times">Example: Comparing Hospital Intake Times</a></li>
  <li><a href="#visualizing-the-data-1" id="toc-visualizing-the-data-1" class="nav-link" data-scroll-target="#visualizing-the-data-1">Visualizing the Data</a></li>
  <li><a href="#visualizing-the-null-distribution-1" id="toc-visualizing-the-null-distribution-1" class="nav-link" data-scroll-target="#visualizing-the-null-distribution-1">Visualizing the Null Distribution</a></li>
  <li><a href="#conducting-in-r" id="toc-conducting-in-r" class="nav-link" data-scroll-target="#conducting-in-r">Conducting in R</a>
  <ul class="collapse">
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  <li><a href="#practice-independent-samples-t-test" id="toc-practice-independent-samples-t-test" class="nav-link" data-scroll-target="#practice-independent-samples-t-test">✏️ Practice: Independent-Samples t-Test</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#paired-samples-t-test" id="toc-paired-samples-t-test" class="nav-link" data-scroll-target="#paired-samples-t-test">3. Paired-Samples T-Test</a>
  <ul class="collapse">
  <li><a href="#what-is-it-2" id="toc-what-is-it-2" class="nav-link" data-scroll-target="#what-is-it-2">What is it?</a>
  <ul class="collapse">
  <li><a href="#key-characteristic" id="toc-key-characteristic" class="nav-link" data-scroll-target="#key-characteristic">Key Characteristic</a></li>
  <li><a href="#why-use-paired-data" id="toc-why-use-paired-data" class="nav-link" data-scroll-target="#why-use-paired-data">Why Use Paired Data?</a></li>
  </ul></li>
  <li><a href="#when-to-use-it-2" id="toc-when-to-use-it-2" class="nav-link" data-scroll-target="#when-to-use-it-2">When to Use It</a></li>
  <li><a href="#paired-samples-t-test-scenario-pain-management-protocol" id="toc-paired-samples-t-test-scenario-pain-management-protocol" class="nav-link" data-scroll-target="#paired-samples-t-test-scenario-pain-management-protocol">Paired-Samples t-test Scenario: Pain Management Protocol</a></li>
  <li><a href="#hypotheses-2" id="toc-hypotheses-2" class="nav-link" data-scroll-target="#hypotheses-2">Hypotheses</a></li>
  <li><a href="#the-formula-2" id="toc-the-formula-2" class="nav-link" data-scroll-target="#the-formula-2">The Formula</a>
  <ul class="collapse">
  <li><a href="#understanding-the-formula-2" id="toc-understanding-the-formula-2" class="nav-link" data-scroll-target="#understanding-the-formula-2">Understanding the Formula</a></li>
  </ul></li>
  <li><a href="#example-pain-management-protocol" id="toc-example-pain-management-protocol" class="nav-link" data-scroll-target="#example-pain-management-protocol">Example: Pain Management Protocol</a></li>
  <li><a href="#visualizing-paired-data" id="toc-visualizing-paired-data" class="nav-link" data-scroll-target="#visualizing-paired-data">Visualizing Paired Data</a></li>
  <li><a href="#visualizing-the-null-distribution-2" id="toc-visualizing-the-null-distribution-2" class="nav-link" data-scroll-target="#visualizing-the-null-distribution-2">Visualizing the Null Distribution</a></li>
  <li><a href="#conducting-in-r-1" id="toc-conducting-in-r-1" class="nav-link" data-scroll-target="#conducting-in-r-1">Conducting in R</a>
  <ul class="collapse">
  <li><a href="#interpretation-1" id="toc-interpretation-1" class="nav-link" data-scroll-target="#interpretation-1">Interpretation</a></li>
  <li><a href="#practice-paired-samples-t-test" id="toc-practice-paired-samples-t-test" class="nav-link" data-scroll-target="#practice-paired-samples-t-test">✏️ Practice: Paired-Samples t-test</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#choosing-the-right-t-test" id="toc-choosing-the-right-t-test" class="nav-link" data-scroll-target="#choosing-the-right-t-test">Choosing the Right t-test</a>
  <ul class="collapse">
  <li><a href="#decision-flowchart" id="toc-decision-flowchart" class="nav-link" data-scroll-target="#decision-flowchart">Decision Flowchart</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#references-and-further-reading" id="toc-references-and-further-reading" class="nav-link" data-scroll-target="#references-and-further-reading">References and Further Reading</a>
  <ul class="collapse">
  <li><a href="#statistical-methods" id="toc-statistical-methods" class="nav-link" data-scroll-target="#statistical-methods">Statistical Methods</a></li>
  <li><a href="#healthcare-applications" id="toc-healthcare-applications" class="nav-link" data-scroll-target="#healthcare-applications">Healthcare Applications</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Mean Comparison 1: t-Tests</h1>
<p class="subtitle lead">MBA642: Business Analytics in Healthcare Management</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction-to-t-tests" class="level1">
<h1>Introduction to t-tests</h1>
<section id="why-t-tests-matter" class="level2">
<h2 class="anchored" data-anchor-id="why-t-tests-matter">Why t-tests Matter</h2>
<p>t-tests are among the most fundamental and widely-used statistical tools that allow us to make data-driven decisions by comparing means and determining whether observed differences are simply due to chance or not.</p>
<p><strong>Consider this scenario</strong>:</p>
<blockquote class="blockquote">
<p>A hospital administrator notices that their emergency department’s average waiting time appears to be 52 minutes, while the regional standard is 45 minutes. Is this 7-minute difference a systematic problem that needs addressing, or could it simply be random variation in the data? This is exactly the type of question that t-tests help us answer.</p>
</blockquote>
<p>t-tests are to <strong>compare means</strong>. Specifically, they determine whether observed <strong>mean differences</strong> are statistically significant—that is, whether the differences we see in our sample data likely reflect true differences in the population, or whether they could have occurred simply by chance. This distinction is critical because acting on random noise can waste resources, while ignoring real problems can harm outcomes.</p>
</section>
<section id="overview-of-the-three-t-test-types" class="level2">
<h2 class="anchored" data-anchor-id="overview-of-the-three-t-test-types">Overview of the Three t-Test Types</h2>
<p>There are three types of t-tests, each designed for different research scenarios:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Test Type</th>
<th>Purpose</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>One-sample</strong></td>
<td>Compare a sample mean to a known or hypothesized value</td>
<td>Testing if average wait time differs from a 45-minute standard</td>
</tr>
<tr class="even">
<td><strong>Independent-samples</strong></td>
<td>Compare means from two separate, unrelated groups</td>
<td>Comparing processing times between two different intake systems</td>
</tr>
<tr class="odd">
<td><strong>Paired-samples</strong></td>
<td>Compare two related measurements on the same subjects</td>
<td>Measuring scores before and after an intervention</td>
</tr>
</tbody>
</table>
<ul>
<li>The following sections will explain each test in detail, with worked examples and R code that you can apply to your own data.</li>
</ul>
<hr>
</section>
</section>
<section id="datasets-for-today" class="level1">
<h1>Datasets for Today</h1>
<ul>
<li><p>We’ll use two datasets throughout this lecture: one for demonstrations and one for practice activities.</p></li>
<li><p>Load the datasets and required packagesusing the code below.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(parameters)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Demonstration dataset</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>hospital_ops <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week05_demo_data.csv"</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Practice dataset</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>patient_outcomes <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week05_practice_data.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="dataset-variables" class="level2">
<h2 class="anchored" data-anchor-id="dataset-variables">Dataset Variables</h2>
<section id="hospital_ops-demonstration-data" class="level3">
<h3 class="anchored" data-anchor-id="hospital_ops-demonstration-data"><code>hospital_ops</code> (Demonstration Data)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>patient_id</code></td>
<td>Unique patient identifier</td>
</tr>
<tr class="even">
<td><code>ed_wait_time</code></td>
<td>ED waiting time (minutes)</td>
</tr>
<tr class="odd">
<td><code>intake_hospital</code></td>
<td>Hospital system (A=Digital, B=Paper)</td>
</tr>
<tr class="even">
<td><code>intake_time</code></td>
<td>Patient intake processing time (minutes)</td>
</tr>
<tr class="odd">
<td><code>pain_before</code>, <code>pain_after</code></td>
<td>Pain scores (0-10 scale)</td>
</tr>
</tbody>
</table>
</section>
<section id="patient_outcomes-practice-data" class="level3">
<h3 class="anchored" data-anchor-id="patient_outcomes-practice-data"><code>patient_outcomes</code> (Practice Data)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>patient_id</code></td>
<td>Unique patient identifier</td>
</tr>
<tr class="even">
<td><code>satisfaction</code></td>
<td>Patient satisfaction (1-10 scale)</td>
</tr>
<tr class="odd">
<td><code>protocol_group</code></td>
<td>Clinical protocol (New = Enhanced Recovery, Standard = Standard Care)</td>
</tr>
<tr class="even">
<td><code>length_of_stay</code></td>
<td>Hospital stay (days)</td>
</tr>
<tr class="odd">
<td><code>bp_before</code>, <code>bp_after</code></td>
<td>Systolic blood pressure (mmHg)</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
</section>
<section id="one-sample-t-test" class="level1">
<h1>1. One-Sample t-Test</h1>
<section id="what-is-it" class="level2">
<h2 class="anchored" data-anchor-id="what-is-it">What is it?</h2>
<p>A <strong>one-sample t-test</strong> is a statistical procedure that compares a sample mean to a known or hypothesized population value. It answers a fundamental question:</p>
<ul>
<li><em>Is our sample mean significantly different from a specific benchmark, or could the difference we observe be due to random chance?</em></li>
</ul>
<p>This test is particularly useful when you have <strong>a single group of observations</strong> and want to compare their average to some external standard or target value. For example, if there is a law regarding a maximum acceptable waiting time, or if industry benchmarks establish expected performance levels, the one-sample t-test helps you determine whether your organization is meeting those standards.</p>
<section id="key-components" class="level3">
<h3 class="anchored" data-anchor-id="key-components">Key Components</h3>
<ul>
<li><strong>One group</strong> of observations (your sample data)</li>
<li><strong>One comparison value</strong> (a benchmark, standard, target, or known or hypothesized mean)</li>
</ul>
<p>The test works by calculating how far your sample mean deviates from the comparison value, relative to the variability in your data. If this deviation is large enough, we conclude that the difference is unlikely to have occurred by chance alone.</p>
</section>
</section>
<section id="when-to-use-it" class="level2">
<h2 class="anchored" data-anchor-id="when-to-use-it">When to Use It</h2>
<p>The one-sample t-test is appropriate whenever you need to compare your data against a fixed reference point. Common scenarios include:</p>
<ul>
<li>Comparing performance against <strong>national or industry benchmarks</strong>
<ul>
<li>e.g.,) average length of stay compared to national average</li>
</ul></li>
<li>Testing if outcomes meet <strong>target levels</strong> set by management or regulators
<ul>
<li>e.g.,) patient satisfaction scores vs.&nbsp;a target of 8.0</li>
</ul></li>
<li>Evaluating if measurements achieve <strong>recommended standards</strong>
<ul>
<li>e.g.,) medication dosages achieving target blood levels</li>
</ul></li>
<li>Assessing if operational metrics meet <strong>regulatory requirements</strong>
<ul>
<li>e.g.,) waiting times vs.&nbsp;regulatory standards</li>
</ul></li>
</ul>
</section>
<section id="one-sample-t-test-scenario-ed-waiting-times" class="level2">
<h2 class="anchored" data-anchor-id="one-sample-t-test-scenario-ed-waiting-times">One-Sample t-test Scenario: ED Waiting Times</h2>
<ul>
<li><p>Imagine you are an administrator at a hospital where the regional average emergency department waiting time is <strong>45 minutes</strong>. Recently, you’ve received complaints that patients are waiting too long. To investigate, you randomly sample 30 patients and record their waiting times.</p></li>
<li><p>Your <strong>sample</strong> shows an average waiting time of <strong>52 minutes</strong>. But before concluding that there’s a problem (i.e., the hospital is underperforming), you need to ask:</p>
<ul>
<li>Is this difference of 7 minutes statistically significant, or could it simply be due to the natural variation we’d expect when taking a random sample?</li>
</ul></li>
<li><p>This is precisely what the one-sample t-test will help us determine.</p></li>
</ul>
</section>
<section id="hypotheses" class="level2">
<h2 class="anchored" data-anchor-id="hypotheses">Hypotheses</h2>
<p>For our ED waiting times scenario, we set up our hypotheses as:</p>
<ul>
<li><strong>Null Hypothesis (H₀)</strong>: μ = 45 (The hospital’s mean waiting time equals the 45-minute regional standard)</li>
<li><strong>Alternative Hypothesis (H₁)</strong>: μ ≠ 45 (The hospital’s mean waiting time differs from the standard)</li>
</ul>
<p>The t-test will help us decide whether to reject H₀ based on our sample data.</p>
</section>
<section id="the-formula" class="level2">
<h2 class="anchored" data-anchor-id="the-formula">The Formula</h2>
<p>The t-statistic is calculated as:</p>
<p><span class="math display">\[t = \frac{\bar{X} - \mu_0}{s / \sqrt{n}}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\bar{X}\)</span>: sample mean (e.g., 52 minutes in our scenario)</li>
<li><span class="math inline">\(\mu_0\)</span>: hypothesized/known mean (e.g., 45-minute benchmark)</li>
<li><span class="math inline">\(s\)</span>: sample standard deviation (measures the spread of your data)</li>
<li><span class="math inline">\(n\)</span>: sample size (e.g., 30 patients in our scenario)</li>
</ul>
<section id="understanding-the-formula" class="level3">
<h3 class="anchored" data-anchor-id="understanding-the-formula">Understanding the Formula</h3>
<p>The t-statistic essentially measures <strong>how many standard errors</strong> the sample mean is away from the hypothesized value. Let’s break this down:</p>
<ul>
<li><p>The <strong>numerator</strong> (<span class="math inline">\(\bar{X} - \mu_0\)</span>) represents the difference between what we observed and what we expected under the null hypothesis. A larger difference suggests our sample may come from a population with a different mean.</p></li>
<li><p>The <strong>denominator</strong> (<span class="math inline">\(s / \sqrt{n}\)</span>) is the <strong>standard error of the mean</strong>, which tells us how much variability we’d expect in sample means due to random sampling. Dividing by this standardizes our difference, allowing us to assess whether it’s large relative to the expected sampling variation.</p></li>
</ul>
<p>A t-statistic close to zero means our sample mean is close to the benchmark. A t-statistic far from zero (either positive or negative) means our sample mean differs substantially from the benchmark, relative to the variability in our data.</p>
</section>
</section>
<section id="example-calculation" class="level2">
<h2 class="anchored" data-anchor-id="example-calculation">Example Calculation</h2>
<p>Let’s work through a concrete example using our demonstration dataset. We have waiting times from 30 randomly selected ED patients:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract ED waiting times from our dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>waiting_times <span class="ot">&lt;-</span> hospital_ops<span class="sc">$</span>ed_wait_time</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>mu_0 <span class="ot">&lt;-</span> <span class="dv">45</span>  <span class="co"># benchmark (regional average)</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate statistics</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(waiting_times)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>x_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(waiting_times)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">sd</span>(waiting_times)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate t-statistic manually</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>t_stat <span class="ot">&lt;-</span> (x_bar <span class="sc">-</span> mu_0) <span class="sc">/</span> (s <span class="sc">/</span> <span class="fu">sqrt</span>(n))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Sample size: 30</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample mean: 46.2 minutes</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample SD: 2.61 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Standard error: 0.48</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>t-statistic: 2.52</code></pre>
</div>
</div>
<p>The t-statistic tells us how many standard errors our sample mean (approximately 46 minutes) is away from the benchmark (45 minutes). A large absolute t-value suggests the difference is unlikely to be due to chance.</p>
</section>
<section id="visualizing-the-data" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-data">Visualizing the Data</h2>
<p>Before running a statistical test, it’s always good practice to <strong>visualize your data</strong>. A histogram helps us understand the distribution of ED waiting times:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hospital_ops, <span class="fu">aes</span>(<span class="at">x =</span> ed_wait_time)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mu_0, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> x_bar, <span class="at">color =</span> <span class="st">"darkgreen"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> mu_0 <span class="sc">-</span> <span class="fl">0.5</span>, <span class="at">y =</span> <span class="dv">7</span>, <span class="at">label =</span> <span class="st">"Benchmark</span><span class="sc">\n</span><span class="st">(45 min)"</span>, </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> x_bar <span class="sc">+</span> <span class="fl">0.5</span>, <span class="at">y =</span> <span class="dv">7</span>, <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"Sample Mean</span><span class="sc">\n</span><span class="st">("</span>, <span class="fu">round</span>(x_bar, <span class="dv">1</span>), <span class="st">" min)"</span>), </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"darkgreen"</span>, <span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of ED Waiting Times"</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparing sample mean (green) to benchmark (red dashed)"</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Waiting Time (minutes)"</span>, <span class="at">y =</span> <span class="st">"Number of Patients"</span>) <span class="sc">+</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture05_files/figure-html/one-sample-histogram-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The visualization shows that most waiting times cluster between 42-50 minutes, and our sample mean (green line) is clearly above the 45-minute benchmark (red dashed line).</p>
</section>
<section id="visualizing-the-null-distribution" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-null-distribution">Visualizing the Null Distribution</h2>
<p>Visualizing what we would expect to see <strong>if the null hypothesis were true</strong> (i.e., if the true population mean really were 45 minutes) helps us understand hypothesis testing. This is called the <strong>null distribution</strong>.</p>
<p>The graph below shows the t-distribution under the null hypothesis. The gray shaded areas in the tails represent the <strong>rejection regions</strong>; if our calculated t-statistic falls in these regions, we reject the null hypothesis at the α = 0.05 significance level.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture05_files/figure-html/one-sample-viz-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Notice that our calculated t-statistic (the red vertical line) falls into the right rejection region. This tells us visually that our sample mean is significantly different from the benchmark (i.e., such an extreme result would be very unlikely if the true mean were actually 45 minutes).</p>
</section>
<section id="conducting-one-sample-t-test-in-r" class="level2">
<h2 class="anchored" data-anchor-id="conducting-one-sample-t-test-in-r">Conducting one-sample t-test in R</h2>
<p>In practice, we use R’s built-in <code>t.test()</code> function rather than calculating everything manually. This function handles all the computations and provides a complete summary of results:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform one-sample t-test</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(hospital_ops<span class="sc">$</span>ed_wait_time, <span class="at">mu =</span> <span class="dv">45</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">parameters</span>(result)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>One Sample t-test

Parameter    |  Mean | mu | Difference |         95% CI | t(29) |     p
-----------------------------------------------------------------------
ed_wait_time | 46.20 | 45 |       1.20 | [45.23, 47.17] |  2.52 | 0.017

Alternative hypothesis: true mean is not equal to 45</code></pre>
</div>
</div>
<section id="interpreting-the-output" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-the-output">Interpreting the Output</h3>
<p>Let’s break down what each part of the output means:</p>
<ul>
<li><p><strong>t-statistic</strong> (2.52): This measures how far our sample mean is from the hypothesized value in standard error units. Our value is quite large, indicating a substantial deviation.</p></li>
<li><p><strong>df</strong> (degrees of freedom = 29): This equals n - 1 and determines the shape of the t-distribution used for calculating the p-value.</p></li>
<li><p><strong>p-value</strong> (0.0174): This is the probability of observing a t-statistic as extreme as ours (or more extreme) if the null hypothesis were true. Our very small p-value indicates this would be extremely unlikely.</p></li>
<li><p><strong>95% confidence interval</strong> [45.23, 47.17]: We are 95% confident that the true population mean lies within this range. Because 45 is <strong>not</strong> contained in this interval, we can reject the null hypothesis.</p></li>
<li><p><strong>Sample mean</strong> (46.2): The average of our observed waiting times.</p></li>
</ul>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>Since the p-value is much less than 0.05, we <strong>reject the null hypothesis</strong>. The evidence strongly suggests that the hospital’s average ED waiting time is significantly higher than the 45-minute regional standard. This finding warrants investigation into the causes of the longer wait times and potential interventions to address the issue.</p>
</section>
<section id="practice-one-sample-t-test" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="practice-one-sample-t-test">✏️ Practice: One-Sample t-Test</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Your Turn! (5 minutes)
</div>
</div>
<div class="callout-body-container callout-body">
<p>A clinic wants to test if their average patient satisfaction score differs from the national average of <strong>8.0</strong> (out of 10). Use the <code>patient_outcomes</code> dataset.</p>
<p><strong>Step 1: Explore the data</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract satisfaction scores from patient_outcomes</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>satisfaction_scores <span class="ot">&lt;-</span> patient_outcomes<span class="sc">$</span>___</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate descriptive statistics</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Sample size:"</span>, <span class="fu">length</span>(satisfaction_scores), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Sample mean:"</span>, <span class="fu">mean</span>(satisfaction_scores), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Sample SD:"</span>, <span class="fu">sd</span>(satisfaction_scores), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Step 2: Visualize the data</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a histogram with benchmark line</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(patient_outcomes, <span class="fu">aes</span>(<span class="at">x =</span> ___)) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">8.0</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Patient Satisfaction Scores"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Satisfaction Score"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Step 3: Perform the t-test</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill in the blanks (replace ___ with appropriate values)</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>result_satisfaction <span class="ot">&lt;-</span> <span class="fu">t.test</span>(___, <span class="at">mu =</span> ___)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">parameters</span>(result_satisfaction)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions</strong>:</p>
<ol type="1">
<li>Based on the p-value, is there a significant difference from the national average?</li>
</ol>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="independent-samples-t-test" class="level1">
<h1>2. Independent-Samples t-test</h1>
<section id="what-is-it-1" class="level2">
<h2 class="anchored" data-anchor-id="what-is-it-1">What is it?</h2>
<p>An <strong>independent-samples t-test</strong> (also called a two-sample t-test) compares means from two different, unrelated groups to determine if they are significantly different from each other. Unlike the one-sample t-test where we compare against a fixed benchmark, here we’re asking:</p>
<ul>
<li><em>Are these two group means significantly different from each other, or could the observed difference be due to random variation?</em></li>
</ul>
<p>This test is fundamental for comparing any two distinct groups, such as different treatment groups, different facilities, different time periods, or any other meaningful categorization. The key requirement is that the groups must be <strong>independent</strong>, meaning that the observations in one group have no relationship to the observations in the other group.</p>
<section id="key-requirements" class="level3">
<h3 class="anchored" data-anchor-id="key-requirements">Key Requirements</h3>
<ul>
<li><strong>Two independent groups</strong>: The observations in one group must be completely unrelated to those in the other group. (e.g., the behavior of patients at Hospital A does not influence the behavior of patients at Hospital B)</li>
<li><strong>Continuous outcome variable</strong>: The variable you’re measuring (e.g., processing time, satisfaction score, length of stay) must be measured on a continuous scale.</li>
</ul>
</section>
<section id="why-independent" class="level3">
<h3 class="anchored" data-anchor-id="why-independent">Why “Independent”?</h3>
<p>The term “independent” distinguishes this test from the paired-samples t-test, which we will talk about next. In an independent-samples design, each observation belongs to only one group, and there’s no natural pairing between observations across groups. If you measured the same patients before and after treatment, that would require a paired test instead.</p>
</section>
</section>
<section id="when-to-use-it-1" class="level2">
<h2 class="anchored" data-anchor-id="when-to-use-it-1">When to Use It</h2>
<p>The independent-samples t-test is appropriate whenever you want to compare two separate groups. Common scenarios include:</p>
<ul>
<li><strong>Comparing treatments</strong>: Is a new drug more effective than the standard treatment?</li>
<li><strong>Comparing facilities or departments</strong>: Does one hospital have shorter wait times than another?</li>
<li><strong>Intervention studies</strong>: Did the intervention group have better outcomes than the control group?</li>
<li><strong>Demographic comparisons</strong>: Do outcomes differ between urban and rural facilities?</li>
</ul>
</section>
<section id="independent-samples-t-test-scenario-comparing-patient-intake-systems" class="level2">
<h2 class="anchored" data-anchor-id="independent-samples-t-test-scenario-comparing-patient-intake-systems">Independent-Samples t-test Scenario: Comparing Patient Intake Systems</h2>
<p>Imagine your health system is considering whether to invest in digital intake systems (the registration process when patients first arrive) across all facilities. Currently, Hospital A uses a digital tablet-based intake system, while Hospital B uses traditional paper forms. Before making a system-wide investment, leadership wants to know:</p>
<ul>
<li><strong>Does the digital system actually result in faster processing times?</strong></li>
</ul>
<p>You collect processing time data from 20 randomly selected patients at each hospital. The question is whether any difference you observe represents a significant difference in system efficiency, or whether it could simply be due to natural variation in processing times.</p>
</section>
<section id="hypotheses-1" class="level2">
<h2 class="anchored" data-anchor-id="hypotheses-1">Hypotheses</h2>
<p>For our intake systems comparison:</p>
<ul>
<li><strong>Null Hypothesis (H₀)</strong>: μ₁ = μ₂ (Mean processing time is the same for both systems)</li>
<li><strong>Alternative Hypothesis (H₁)</strong>: μ₁ ≠ μ₂ (Mean processing times differ between systems)</li>
</ul>
<p>The t-test will help us decide whether the observed difference is statistically significant.</p>
</section>
<section id="the-formula-1" class="level2">
<h2 class="anchored" data-anchor-id="the-formula-1">The Formula</h2>
<p>The t-statistic for an independent-samples t-test is calculated as:</p>
<p><span class="math display">\[t = \frac{\bar{X}_1 - \bar{X}_2}{s_p\sqrt{\frac{1}{n_1} + \frac{1}{n_2}}}\]</span></p>
<p>Where the <strong>pooled standard deviation</strong> is:</p>
<p><span class="math display">\[s_p = \sqrt{\frac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1 + n_2 - 2}}\]</span></p>
<section id="understanding-the-formula-1" class="level3">
<h3 class="anchored" data-anchor-id="understanding-the-formula-1">Understanding the Formula</h3>
<ul>
<li><p><strong>Numerator</strong> (<span class="math inline">\(\bar{X}_1 - \bar{X}_2\)</span>): The difference between the two sample means, which is the effect we are trying to evaluate.</p></li>
<li><p><strong>Denominator</strong>: The standard error of the difference between means. This combines the information about variability from both groups to estimate how much variation we would expect in the difference between sample means due to random sampling.</p></li>
<li><p><strong>Pooled standard deviation</strong> (<span class="math inline">\(s_p\)</span>): This is a weighted average of the two groups’ standard deviations. We “pool” them because we assume both groups have the same population variance (homogeneity of variance assumption). The pooling gives more weight to the larger sample.</p></li>
</ul>
<p>The resulting t-statistic tells us how many standard errors the observed difference is from zero (i.e., no difference; the same mean in both groups). A large absolute t-value suggests the groups significantly differ.</p>
</section>
</section>
<section id="example-comparing-hospital-intake-times" class="level2">
<h2 class="anchored" data-anchor-id="example-comparing-hospital-intake-times">Example: Comparing Hospital Intake Times</h2>
<p>Let’s analyze the processing times from our demonstration dataset using the two hospitals:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract data from our dataset</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>hospital_A <span class="ot">&lt;-</span> hospital_ops<span class="sc">$</span>intake_time[hospital_ops<span class="sc">$</span>intake_hospital <span class="sc">==</span> <span class="st">"A_Digital"</span>]</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>hospital_B <span class="ot">&lt;-</span> hospital_ops<span class="sc">$</span>intake_time[hospital_ops<span class="sc">$</span>intake_hospital <span class="sc">==</span> <span class="st">"B_Paper"</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Hospital A (Digital):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Mean: 14.53 minutes</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  SD: 1.3 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  n: 15 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Hospital B (Paper):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Mean: 16.53 minutes</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  SD: 1.64 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  n: 15 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Difference between two sample means: -2 minutes</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Pooled Standard Deviation: 1.48 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>t-value: -3.7 </code></pre>
</div>
</div>
</section>
<section id="visualizing-the-data-1" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-data-1">Visualizing the Data</h2>
<p>Before running our t-test, let’s visualize the distribution of processing times for both hospitals:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create grouped data for visualization</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>intake_viz <span class="ot">&lt;-</span> hospital_ops <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hospital_label =</span> <span class="fu">ifelse</span>(intake_hospital <span class="sc">==</span> <span class="st">"A_Digital"</span>, </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"A: Digital System"</span>, <span class="st">"B: Paper Forms"</span>))</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot with individual points</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(intake_viz, <span class="fu">aes</span>(<span class="at">x =</span> hospital_label, <span class="at">y =</span> intake_time, <span class="at">fill =</span> hospital_label)) <span class="sc">+</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Patient Intake Processing Times by System"</span>,</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparing digital (A) vs. paper (B) intake systems"</span>,</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Hospital System"</span>, <span class="at">y =</span> <span class="st">"Processing Time (minutes)"</span>) <span class="sc">+</span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture05_files/figure-html/independent-viz-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p>The box plot clearly shows that Hospital A (digital system) has lower and less variable processing times than Hospital B (paper forms).</p>
</section>
<section id="visualizing-the-null-distribution-1" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-null-distribution-1">Visualizing the Null Distribution</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture05_files/figure-html/independent-null-dist-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="conducting-in-r" class="level2">
<h2 class="anchored" data-anchor-id="conducting-in-r">Conducting in R</h2>
<p>We can conduct an independent-samples t-test using <code>t.test()</code> with two groups:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform independent samples t-test</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co"># var.equal = TRUE uses pooled variance (Student's t-test)</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>result_ind <span class="ot">&lt;-</span> <span class="fu">t.test</span>(hospital_A, hospital_B, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="fu">parameters</span>(result_ind)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Two Sample t-test

Parameter1 | Parameter2 | Mean_Parameter1 | Mean_Parameter2 | Difference
------------------------------------------------------------------------
hospital_A | hospital_B |           14.53 |           16.53 |      -2.00

Parameter1 |         95% CI | t(28) |      p
--------------------------------------------
hospital_A | [-3.11, -0.89] | -3.70 | &lt; .001

Alternative hypothesis: true difference in means is not equal to 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative syntax using formula</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># result_ind_oneset &lt;- t.test(intake_time ~ intake_hospital, data = hospital_ops, var.equal = TRUE)</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># parameters(result_ind_oneset)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<ul>
<li><strong>Mean difference</strong>: -2 minutes</li>
<li><strong>t-statistic</strong>: -3.7</li>
<li><strong>p-value</strong>: 0.0009416</li>
<li><strong>Conclusion</strong>: Since p-value &lt; 0.05, we reject the null hypothesis. The digital intake system (Hospital A) has significantly shorter processing times than the paper system (Hospital B).</li>
</ul>
</section>
<section id="practice-independent-samples-t-test" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="practice-independent-samples-t-test">✏️ Practice: Independent-Samples t-Test</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Your Turn! (5 minutes)
</div>
</div>
<div class="callout-body-container callout-body">
<p>A hospital wants to compare the length of stay (in days) between patients receiving a new <strong>Enhanced Recovery Protocol (ERP)</strong> (which focuses on early mobilization and nutrition to speed up recovery) versus <strong>Standard Care</strong>. Use the <code>patient_outcomes</code> dataset.</p>
<p><strong>Step 1: Explore the data</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract length of stay by group</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>new_protocol <span class="ot">&lt;-</span> patient_outcomes<span class="sc">$</span>length_of_stay[patient_outcomes<span class="sc">$</span>protocol_group <span class="sc">==</span> <span class="st">"___"</span>]</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>standard_care <span class="ot">&lt;-</span> patient_outcomes<span class="sc">$</span>length_of_stay[patient_outcomes<span class="sc">$</span>protocol_group <span class="sc">==</span> <span class="st">"___"</span>]</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate descriptive statistics for both groups</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"New Protocol: Mean ="</span>, <span class="fu">round</span>(<span class="fu">mean</span>(new_protocol), <span class="dv">2</span>), <span class="st">"days</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Standard Care: Mean ="</span>, <span class="fu">round</span>(<span class="fu">mean</span>(standard_care), <span class="dv">2</span>), <span class="st">"days</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Difference:"</span>, <span class="fu">round</span>(<span class="fu">mean</span>(new_protocol) <span class="sc">-</span> <span class="fu">mean</span>(standard_care), <span class="dv">2</span>), <span class="st">"days</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Step 2: Visualize the data</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a box plot comparing both groups</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(patient_outcomes, <span class="fu">aes</span>(<span class="at">x =</span> ___, <span class="at">y =</span> ___, <span class="at">fill =</span> ___)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Length of Stay by Discharge Protocol"</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Protocol Type"</span>, <span class="at">y =</span> <span class="st">"Length of Stay (days)"</span>) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Step 3: Perform the t-test</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill in the blanks</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>result_los <span class="ot">&lt;-</span> <span class="fu">t.test</span>(___, ___, <span class="at">var.equal =</span> ___)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># or result_los &lt;- t.test(___ ~ ___, data = ___, var.equal = ___)</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="fu">parameters</span>(result_los)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions</strong>:</p>
<ol type="1">
<li>Is the difference in length of stay statistically significant?</li>
<li>Should the hospital adopt the new discharge protocol based on these results?</li>
</ol>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="paired-samples-t-test" class="level1">
<h1>3. Paired-Samples T-Test</h1>
<section id="what-is-it-2" class="level2">
<h2 class="anchored" data-anchor-id="what-is-it-2">What is it?</h2>
<p>A <strong>paired-samples t-test</strong> (also called a dependent t-test or matched-pairs t-test) compares two related measurements on the same subjects or matched pairs. Unlike the independent-samples t-test where we compare different groups of people, here we’re asking:</p>
<ul>
<li><em>Is there a significant change within the same individuals between two time points, conditions, or measures?</em></li>
</ul>
<p>This test is particularly powerful because by measuring <strong>the same subjects</strong> twice, we can control for individual differences. Each person serves as their own control, which reduces variability and increases our ability to detect true effects.</p>
<section id="key-characteristic" class="level3">
<h3 class="anchored" data-anchor-id="key-characteristic">Key Characteristic</h3>
<p>The data comes in <strong>pairs</strong>, which means each subject has exactly two measurements that are linked. For example:</p>
<ul>
<li>The same patient measured before and after treatment</li>
<li>The same clinic’s performance in January vs.&nbsp;June</li>
<li>Twins where one receives treatment and the other serves as control</li>
</ul>
</section>
<section id="why-use-paired-data" class="level3">
<h3 class="anchored" data-anchor-id="why-use-paired-data">Why Use Paired Data?</h3>
<p>The paired design is statistically more powerful than an independent design because it eliminates the variability across respondents. For example, if we compare pain scores between a treatment group and control group (independent design), differences in pain tolerance between individuals add noise to our data. But if we measure each person’s pain before and after treatment (paired design), individual differences cancel out, and we are only looking at how much each person’s pain perceptions changed.</p>
</section>
</section>
<section id="when-to-use-it-2" class="level2">
<h2 class="anchored" data-anchor-id="when-to-use-it-2">When to Use It</h2>
<p>The paired-samples t-test is appropriate whenever your measurements are somehow related:</p>
<ul>
<li><strong>Before-and-after studies</strong> (same respondent):
<ul>
<li>Pre-treatment vs.&nbsp;post-treatment outcomes</li>
<li>Before vs.&nbsp;after policy implementation</li>
<li>Baseline vs.&nbsp;follow-up measurements</li>
</ul></li>
<li><strong>Matched pairs design</strong>:
<ul>
<li>Twin studies (comparing outcomes between twins)</li>
<li>Matched control studies (subjects paired on key characteristics)</li>
</ul></li>
<li><strong>Within-subject comparisons</strong>:
<ul>
<li>Two treatments tested on the same patient (crossover design)</li>
<li>Morning vs.&nbsp;evening measurements on the same individuals</li>
<li>Left eye vs.&nbsp;right eye comparisons</li>
</ul></li>
</ul>
</section>
<section id="paired-samples-t-test-scenario-pain-management-protocol" class="level2">
<h2 class="anchored" data-anchor-id="paired-samples-t-test-scenario-pain-management-protocol">Paired-Samples t-test Scenario: Pain Management Protocol</h2>
<p>A hospital implemented <strong>a new non-pharmacological pain management protocol</strong> (integrating guided imagery and music therapy) and wants to evaluate its effectiveness. Rather than comparing different groups of patients (which would introduce confounding variables like age, health status, or pain tolerance), the hospital measures pain scores (0-10 scale) for 30 patients <strong>before</strong> and <strong>after</strong> receiving the protocol.</p>
<p>The key question is: <strong>Did the protocol significantly reduce pain?</strong></p>
<p>By using the same patients as their own controls, we can isolate the effect of the protocol from individual differences in pain perception and tolerance.</p>
</section>
<section id="hypotheses-2" class="level2">
<h2 class="anchored" data-anchor-id="hypotheses-2">Hypotheses</h2>
<p>For our pain management protocol evaluation:</p>
<ul>
<li><strong>Null Hypothesis (H₀)</strong>: μ_D = 0 (The mean difference in pain scores is zero—no change)</li>
<li><strong>Alternative Hypothesis (H₁)</strong>: μ_D ≠ 0 (The mean difference is not zero—pain scores changed)</li>
</ul>
</section>
<section id="the-formula-2" class="level2">
<h2 class="anchored" data-anchor-id="the-formula-2">The Formula</h2>
<p>The paired t-test analyzes the <strong>differences</strong> between paired observations:</p>
<p><span class="math display">\[t = \frac{\bar{D}}{s_D / \sqrt{n}}\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\bar{D}\)</span>: mean of the differences (average change across all subjects)</li>
<li><span class="math inline">\(s_D\)</span>: standard deviation of the differences (variability in how much individuals changed)</li>
<li><span class="math inline">\(n\)</span>: number of pairs (number of subjects)</li>
</ul>
<section id="understanding-the-formula-2" class="level3">
<h3 class="anchored" data-anchor-id="understanding-the-formula-2">Understanding the Formula</h3>
<p>Notice that this formula is essentially identical to the one-sample t-test formula! This is because the paired t-test is really just a one-sample t-test performed on the <strong>differences</strong>. We’re testing whether the mean difference is significantly different from zero.</p>
<p>Instead of working with two sets of measurements (e.g., average before - average after), we <strong>first calculate the difference for each pair</strong> (e.g., Before - After for each patient). Then we examine whether the average of these differences significantly different from zero.</p>
<ul>
<li>If the mean difference is close to zero → no significant difference</li>
<li>If the mean difference is far from zero (relative to variability) → significant difference</li>
</ul>
<p>This approach is powerful because it accounts for individual baseline differences. A patient who starts with severe pain and a patient who starts with mild pain are compared only to themselves.</p>
</section>
</section>
<section id="example-pain-management-protocol" class="level2">
<h2 class="anchored" data-anchor-id="example-pain-management-protocol">Example: Pain Management Protocol</h2>
<p>Let’s analyze the pain scores from our demonstration dataset:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract pain scores from our dataset</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>before <span class="ot">&lt;-</span> hospital_ops<span class="sc">$</span>pain_before</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>after <span class="ot">&lt;-</span> hospital_ops<span class="sc">$</span>pain_after</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Before treatment:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Mean: 7.1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  SD: 0.71 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>After treatment:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Mean: 6.7</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  SD: 1.09 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Differences (Before - After):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  Mean: 0.4</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  SD: 0.77 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>t-value: 2.84 </code></pre>
</div>
</div>
</section>
<section id="visualizing-paired-data" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-paired-data">Visualizing Paired Data</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture05_files/figure-html/paired-viz-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="visualizing-the-null-distribution-2" class="level2">
<h2 class="anchored" data-anchor-id="visualizing-the-null-distribution-2">Visualizing the Null Distribution</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lecture05_files/figure-html/paired-null-dist-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="conducting-in-r-1" class="level2">
<h2 class="anchored" data-anchor-id="conducting-in-r-1">Conducting in R</h2>
<p>We can conduct a paired-sample t-test using <code>t.test()</code> function with the <code>paired = TRUE</code> argument:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform paired samples t-test</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>result_paired <span class="ot">&lt;-</span> <span class="fu">t.test</span>(before, after, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="fu">parameters</span>(result_paired)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Paired t-test

Parameter | Group | Difference | t(29) |     p |       95% CI
-------------------------------------------------------------
before    | after |       0.40 |  2.84 | 0.008 | [0.11, 0.69]

Alternative hypothesis: true mean difference is not equal to 0</code></pre>
</div>
</div>
<section id="interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-1">Interpretation</h3>
<ul>
<li><strong>Mean difference</strong>: 0.4 points</li>
<li><strong>t-statistic</strong>: 2.845</li>
<li><strong>p-value</strong>: 0.008068</li>
<li><strong>Conclusion</strong>: Since p-value &lt; 0.05, we reject the null hypothesis. The pain management protocol significantly reduced pain scores.</li>
</ul>
</section>
<section id="practice-paired-samples-t-test" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="practice-paired-samples-t-test">✏️ Practice: Paired-Samples t-test</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Your Turn! (5 minutes)
</div>
</div>
<div class="callout-body-container callout-body">
<p>A health clinic wants to evaluate the effectiveness of a <strong>lifestyle intervention program</strong> (a 12-week program including dietary modification and weekly exercise coaching) on reducing systolic blood pressure. Use the <code>patient_outcomes</code> dataset.</p>
<p><strong>Step 1: Explore the data</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract blood pressure data from patient_outcomes</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>bp_before <span class="ot">&lt;-</span> patient_outcomes<span class="sc">$</span>___</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>bp_after <span class="ot">&lt;-</span> patient_outcomes<span class="sc">$</span>___</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate descriptive statistics</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Before: Mean ="</span>, <span class="fu">round</span>(<span class="fu">mean</span>(bp_before), <span class="dv">2</span>), <span class="st">"mmHg</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"After: Mean ="</span>, <span class="fu">round</span>(<span class="fu">mean</span>(bp_after), <span class="dv">2</span>), <span class="st">"mmHg</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Mean difference:"</span>, <span class="fu">round</span>(<span class="fu">mean</span>(bp_before <span class="sc">-</span> bp_after), <span class="dv">2</span>), <span class="st">"mmHg</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Step 2: Visualize the data</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a before/after comparison plot</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="co"># First, reshape data for plotting</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>bp_plot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">patient_id =</span> <span class="fu">rep</span>(patient_outcomes<span class="sc">$</span>patient_id, <span class="dv">2</span>),</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">time =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Before"</span>, <span class="st">"After"</span>), <span class="at">each =</span> <span class="fu">nrow</span>(patient_outcomes)), </span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Before"</span>, <span class="st">"After"</span>)),</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">bp =</span> <span class="fu">c</span>(patient_outcomes<span class="sc">$</span>bp_before, patient_outcomes<span class="sc">$</span>bp_after)</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the spaghetti plot</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(bp_plot_data, <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> bp, <span class="at">group =</span> patient_id)) <span class="sc">+</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">"gray40"</span>) <span class="sc">+</span></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> time), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>, </span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>               <span class="at">linewidth =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>, </span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Blood Pressure Before vs. After Intervention"</span>,</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"Systolic BP (mmHg)"</span>) <span class="sc">+</span></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Step 3: Perform the t-test</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill in the blanks</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>result_bp <span class="ot">&lt;-</span> <span class="fu">t.test</span>(___, ___, <span class="at">paired =</span> ___)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">parameters</span>(result_bp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions</strong>:</p>
<ol type="1">
<li>Is the change in blood pressure statistically significant?</li>
<li>Would you recommend this lifestyle intervention program for blood pressure management?</li>
</ol>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="choosing-the-right-t-test" class="level1">
<h1>Choosing the Right t-test</h1>
<section id="decision-flowchart" class="level2">
<h2 class="anchored" data-anchor-id="decision-flowchart">Decision Flowchart</h2>
<p>Use this guide to select the appropriate t-test:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 39%">
<col style="width: 5%">
<col style="width: 25%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Question</th>
<th style="text-align: left;">If…</th>
<th style="text-align: left;">t-Test Type</th>
<th style="text-align: left;">R Function</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Comparing to a known standard/benchmark?</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">One-sample t-test</td>
<td style="text-align: left;">t.test(x, mu = value)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Two separate/independent groups?</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Independent-samples t-test</td>
<td style="text-align: left;">t.test(x, y, var.equal = TRUE)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Same subjects measured twice?</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">Paired-samples t-test</td>
<td style="text-align: left;">t.test(x, y, paired = TRUE)</td>
</tr>
</tbody>
</table>
</div>
</div>
<hr>
</section>
</section>
<section id="summary" class="level1">
<h1>Summary</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 32%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Purpose</th>
<th>Key Points</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>One-sample</strong></td>
<td>Compare mean to benchmark</td>
<td>Single group, known standard</td>
</tr>
<tr class="even">
<td><strong>Independent</strong></td>
<td>Compare two group means</td>
<td>Separate groups, no overlap</td>
</tr>
<tr class="odd">
<td><strong>Paired</strong></td>
<td>Compare related measurements</td>
<td>Same subjects, before/after</td>
</tr>
</tbody>
</table>
<ul>
<li><p><strong>One-sample t-tests</strong> help evaluate whether your organization meets industry standards or benchmarks.</p></li>
<li><p><strong>Independent-samples t-tests</strong> enable evidence-based comparisons between different treatments, departments, or facilities.</p></li>
<li><p><strong>Paired-samples t-tests</strong> are essential for evaluating the effectiveness of interventions and quality improvement initiatives.</p></li>
</ul>
<hr>
</section>
<section id="references-and-further-reading" class="level1">
<h1>References and Further Reading</h1>
<section id="statistical-methods" class="level2">
<h2 class="anchored" data-anchor-id="statistical-methods">Statistical Methods</h2>
<ul>
<li>Field, A. (2018). <em>Discovering Statistics Using IBM SPSS Statistics</em> (5th ed.). SAGE Publications.</li>
<li>Navarro, D. (2019). <em>Learning Statistics with R</em>. Available online.</li>
<li>Wickham, H., &amp; Grolemund, G. (2017). <em>R for Data Science</em>. O’Reilly Media.</li>
</ul>
</section>
<section id="healthcare-applications" class="level2">
<h2 class="anchored" data-anchor-id="healthcare-applications">Healthcare Applications</h2>
<p>Examples are motivated by the followings:</p>
<ul>
<li><p>United States Emergency Department Performance on Wait Time and Length of Visit. (2009). <em>PMC</em>. https://pmc.ncbi.nlm.nih.gov/articles/PMC2830619/</p></li>
<li><p>Assessing Patient Satisfaction with Hospital Services: Perspectives from Bihor County Emergency Hospital, Romania. (2025). <em>PMC</em>. https://pmc.ncbi.nlm.nih.gov/articles/PMC11988329/</p></li>
<li><p>The Impact of Electronic Health Records on Time Efficiency of Physicians and Nurses: A Systematic Review. (2005). <em>PMC</em>. https://pmc.ncbi.nlm.nih.gov/articles/PMC1205599/</p></li>
<li><p>Reducing the Length of Stay by Enhancing the Patient Discharge Process: Using Quality Improvement Tools to Optimize Hospital Efficiency. (2021). <em>PMC</em>. https://pmc.ncbi.nlm.nih.gov/articles/PMC10229011/</p></li>
<li><p>Studying Protocol-Based Pain Management in the Emergency Department. (2017). <em>PMC</em>. https://pmc.ncbi.nlm.nih.gov/articles/PMC5663136/</p></li>
<li><p>Comprehensive Lifestyle Modification and Blood Pressure Control: A Review of the PREMIER Trial. (2004). <em>PMC</em>. https://pmc.ncbi.nlm.nih.gov/articles/PMC8109651/</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>