<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="">
  <meta name="dcterms.date" content="2026-02-11">
  <title>Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026) – Mean Comparison 1: t-tests</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-001d2e75a049d726abecbf04d74aec57.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Mean Comparison 1: <em>t</em>-tests</h1>
  <p class="subtitle">Week 05</p>

<div class="quarto-title-authors">
</div>

  <p class="date">2026-02-11</p>
</section>
<section>
<section id="introduction" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Introduction</h1>

</section>
<section id="why-t-tests-matter" class="slide level2">
<h2>Why <em>t</em>-tests Matter</h2>
<p><strong>Let’s think about this scenario:</strong></p>
<blockquote>
<p><em>A hospital administrator notices their emergency department’s average waiting time (from randomly selected 30 patients) is <strong>52 minutes</strong>, while the regional standard is <strong>45 minutes</strong>.</em></p>
</blockquote>
<div class="fragment">
<p><br> A <strong>key question</strong> we need to understand is:</p>
<ul>
<li><em>Is this 7-minute difference a real problem, or just random variation?</em></li>
</ul>
</div>
<div class="fragment">
<p><br> This is exactly what <em>t</em>-tests help us answer!</p>
</div>
</section>
<section id="why-t-tests-matter-1" class="slide level2">
<h2>Why <em>t</em>-tests Matter</h2>
<p><em>t</em>-tests determine whether observed differences are <strong>statistically significant</strong>.</p>
<ul>
<li class="fragment">They examine whether differences in our sample likely reflect <strong>true differences</strong> in the population</li>
<li class="fragment">Or whether they could have occurred simply <strong>by chance</strong></li>
</ul>
<div class="fragment">
<p><br> This distinction is critical:</p>
<ul>
<li class="fragment">Acting on noise wastes resources</li>
<li class="fragment">Ignoring real problems harms outcomes</li>
</ul>
</div>
</section>
<section id="todays-learning-goals" class="slide level2 scrollable">
<h2>Today’s Learning Goals</h2>
<p>By the end of this lecture, you will be able to:</p>
<ol type="1">
<li class="fragment"><strong>Identify</strong> which <em>t</em>-test to use for different scenarios</li>
<li class="fragment"><strong>Conduct</strong> <em>t</em>-tests in R using the <code>t.test()</code> function</li>
<li class="fragment"><strong>Visualize</strong> mean comparison relationships using <code>ggplot2</code></li>
<li class="fragment"><strong>Interpret</strong> <em>t</em>-test results and make data-driven conclusions</li>
</ol>
</section>
<section id="t-tests-in-healthcare-management" class="slide level2">
<h2><em>t</em>-tests in Healthcare Management</h2>
<p>Real-world applications where <em>t</em>-tests drive decisions:</p>
<ul>
<li class="fragment"><strong>Quality Improvement</strong>: Is our patient satisfaction score meeting the target?</li>
<li class="fragment"><strong>Operational Efficiency</strong>: Does electronic intake reduce processing time vs.&nbsp;paper?</li>
<li class="fragment"><strong>Clinical Outcomes</strong>: Did the new pain management protocol improve patient outcomes?</li>
<li class="fragment"><strong>Resource Planning</strong>: Is our average length of stay different from the national benchmark?</li>
</ul>
</section>
<section id="overview-three-types-of-t-tests" class="slide level2">
<h2>Overview: Three Types of T-Tests</h2>
<table class="caption-top">
<colgroup>
<col style="width: 37%">
<col style="width: 31%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th>Test Type</th>
<th>Purpose</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>One-sample</strong></td>
<td>Compare sample mean to a benchmark</td>
<td>ED wait time vs.&nbsp;45-min standard</td>
</tr>
<tr class="even">
<td><strong>Independent-samples</strong></td>
<td>Compare means from two separate groups</td>
<td>Digital vs.&nbsp;paper intake systems</td>
</tr>
<tr class="odd">
<td><strong>Paired-samples</strong></td>
<td>Compare two related measurements</td>
<td>Before vs.&nbsp;after an intervention</td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="datasets-for-today" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Datasets for Today</h1>

</section>
<section id="loading-the-data" class="slide level2">
<h2>Loading the Data</h2>
<p>First, let’s load the required packages:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages</span></span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(parameters)</span>
<span id="cb1-5"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb1-7"><a aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We’ll use two datasets throughout this lecture:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Demonstration dataset</span></span>
<span id="cb2-2"><a aria-hidden="true" tabindex="-1"></a>hospital_ops <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week05_demo_data.csv"</span>)</span>
<span id="cb2-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Practice dataset</span></span>
<span id="cb2-5"><a aria-hidden="true" tabindex="-1"></a>patient_outcomes <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week05_practice_data.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="demonstration-data-hospital_ops" class="slide level2">
<h2>Demonstration Data: <code>hospital_ops</code></h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>patient_id</code></td>
<td>Unique patient identifier</td>
</tr>
<tr class="even">
<td><code>ed_wait_time</code></td>
<td>ED waiting time (minutes)</td>
</tr>
<tr class="odd">
<td><code>intake_hospital</code></td>
<td>Hospital system (A=Digital, B=Paper)</td>
</tr>
<tr class="even">
<td><code>intake_time</code></td>
<td>Patient intake processing time (minutes)</td>
</tr>
<tr class="odd">
<td><code>pain_before</code>, <code>pain_after</code></td>
<td>Pain scores (0-10 scale)</td>
</tr>
</tbody>
</table>
</section>
<section id="practice-data-patient_outcomes" class="slide level2">
<h2>Practice Data: <code>patient_outcomes</code></h2>
<table class="caption-top">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>patient_id</code></td>
<td>Unique patient identifier</td>
</tr>
<tr class="even">
<td><code>satisfaction</code></td>
<td>Patient satisfaction (1-10 scale)</td>
</tr>
<tr class="odd">
<td><code>protocol_group</code></td>
<td>Clinical protocol (New = Enhanced Recovery, Standard = Standard Care)</td>
</tr>
<tr class="even">
<td><code>length_of_stay</code></td>
<td>Hospital stay (days)</td>
</tr>
<tr class="odd">
<td><code>bp_before</code>, <code>bp_after</code></td>
<td>Systolic blood pressure (mmHg)</td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="one-sample-t-test" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>1. One-Sample <em>t</em>-test</h1>

</section>
<section id="what-is-a-one-sample-t-test" class="slide level2">
<h2>What is a One-Sample <em>t</em>-test?</h2>
<p>A <strong>one-sample <em>t</em>-test</strong> compares a sample mean to a known or hypothesized population mean or value.</p>
<div class="fragment">
<p><br> <strong>Key Question</strong>: <em>Is our sample mean significantly different from a benchmark?</em></p>
</div>
<div class="fragment">
<p><br> <strong>Key Components</strong>:</p>
<ul>
<li><strong>One group</strong> of observations (your sample data)</li>
<li><strong>One comparison value</strong> (a known or hypothesized population mean, benchmark, standard, or target)</li>
</ul>
</div>
</section>
<section id="when-to-use-it" class="slide level2">
<h2>When to Use It</h2>
<p>The one-sample t-test is appropriate when comparing against a fixed reference:</p>
<ul>
<li class="fragment">Performance vs.&nbsp;<strong>industry benchmarks</strong> (e.g., length of stay vs.&nbsp;national average)</li>
<li class="fragment">Outcomes vs.&nbsp;<strong>target levels</strong> (e.g., satisfaction scores vs.&nbsp;target of 8.0)</li>
<li class="fragment">Metrics vs.&nbsp;<strong>regulatory requirements</strong> (e.g., readmission rates vs.&nbsp;CMS standards)</li>
</ul>
</section>
<section id="one-sample-t-test-scenario-emergency-department-waiting-times" class="slide level2">
<h2>One-Sample <em>t</em>-test Scenario: <br> Emergency Department Waiting Times</h2>
<ul>
<li>Imagine you are an administrator at a hospital where the regional average emergency department waiting time is <strong>45 minutes</strong>.</li>
</ul>
<div class="fragment">
<ul>
<li>Recently, you’ve received complaints that patients are waiting too long. To investigate, you randomly sample 30 patients and record their waiting times.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li><strong>The key question</strong>:
<ul>
<li>Is this difference statistically significant, or could it simply be due to natural variation in the data?</li>
</ul></li>
</ul>
</div>
</section>
<section id="a-quick-review-of-null-hypothesis-testing" class="slide level2">
<h2>A Quick Review of Null Hypothesis Testing</h2>

<img data-src="images/image1.png" width="300" class="r-stretch"><div class="fragment">
<p>Two competing explanations for the difference:</p>
<ul>
<li class="fragment"><strong>Explanation 1</strong> (H<sub>1</sub>): The hospital’s mean waiting time is longer than 45 minutes</li>
<li class="fragment"><strong>Explanation 2</strong> (H₀): The hospital’s mean waiting time is 45 minutes (but coincidentally, the sample mean is higher than 45 minutes)</li>
</ul>
</div>
</section>
<section id="hypotheses" class="slide level2">
<h2>Hypotheses</h2>
<p>For our ED waiting times scenario:</p>
<ul>
<li><strong>Null Hypothesis (H₀)</strong>: μ = 45 (The hospital’s mean waiting time equals the 45-minute regional standard)</li>
<li><strong>Alternative Hypothesis (H₁)</strong>: μ ≠ 45 (The hospital’s mean waiting time differs from the standard)</li>
</ul>
<div class="fragment">
<p>The <em>t</em>-test will help us decide whether to reject H₀ based on our sample data.</p>
</div>
</section>
<section id="the-formula" class="slide level2">
<h2>The Formula</h2>
<p>The t-statistic is calculated as:</p>
<p><span class="math display">\[t = \frac{\bar{X} - \mu_0}{s / \sqrt{n}}\]</span></p>
<div class="fragment">
<p>Where:</p>
<ul>
<li><span class="math inline">\(\bar{X}\)</span>: sample mean (e.g., 52 minutes in our scenario)</li>
<li><span class="math inline">\(\mu_0\)</span>: hypothesized/known mean (e.g., 45-minute benchmark)</li>
<li><span class="math inline">\(s\)</span>: sample standard deviation (measures the spread of your data)</li>
<li><span class="math inline">\(n\)</span>: sample size (e.g., 30 patients in our scenario)</li>
</ul>
</div>
</section>
<section id="understanding-the-formula" class="slide level2">
<h2>Understanding the Formula</h2>
<p><strong>Numerator</strong> (<span class="math inline">\(\bar{X} - \mu_0\)</span>):</p>
<ul>
<li>The difference between observed and expected under the null hypothesis</li>
</ul>
<div class="fragment">
<p><strong>Denominator</strong> (<span class="math inline">\(s / \sqrt{n}\)</span>):</p>
<ul>
<li>The <strong>standard error of the mean</strong></li>
<li>Tells us expected variability in sample means</li>
</ul>
</div>
<div class="fragment">
<p><strong>Interpretation</strong>:</p>
<ul>
<li>t ≈ 0 → sample mean close to benchmark</li>
<li>|t| large → sample mean far from benchmark</li>
</ul>
</div>
</section>
<section id="demonstration-extract-the-data-and-calculation" class="slide level2">
<h2>Demonstration: <br> Extract the Data and Calculation</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Extract ED waiting times from our dataset</span></span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a>waiting_times <span class="ot">&lt;-</span> hospital_ops<span class="sc">$</span>ed_wait_time <span class="co"># getting wait time data</span></span>
<span id="cb3-3"><a aria-hidden="true" tabindex="-1"></a>mu_0 <span class="ot">&lt;-</span> <span class="dv">45</span>  <span class="co"># benchmark (regional average)</span></span>
<span id="cb3-4"><a aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(waiting_times) <span class="co"># sample size</span></span>
<span id="cb3-5"><a aria-hidden="true" tabindex="-1"></a>x_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(waiting_times) <span class="co"># sample mean</span></span>
<span id="cb3-6"><a aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">sd</span>(waiting_times) <span class="co"># sample standard deviation</span></span>
<span id="cb3-7"><a aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> s <span class="sc">/</span> <span class="fu">sqrt</span>(n) <span class="co"># standard error of the mean</span></span>
<span id="cb3-8"><a aria-hidden="true" tabindex="-1"></a>t_stat <span class="ot">&lt;-</span> (x_bar <span class="sc">-</span> mu_0) <span class="sc">/</span> se <span class="co"># t-statistic</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<p>Our t-statistic (2.52) tells us how many standard errors our sample mean is from the benchmark.</p>
</div>
</section>
<section id="visualizing-the-data" class="slide level2">
<h2>Visualizing the Data</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hospital_ops, <span class="fu">aes</span>(<span class="at">x =</span> ed_wait_time)) <span class="sc">+</span></span>
<span id="cb4-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">1</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb4-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> mu_0, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb4-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> x_bar, <span class="at">color =</span> <span class="st">"darkgreen"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> mu_0 <span class="sc">-</span> <span class="fl">0.5</span>, <span class="at">y =</span> <span class="dv">7</span>, <span class="at">label =</span> <span class="st">"Benchmark</span><span class="sc">\n</span><span class="st">(45 min)"</span>, </span>
<span id="cb4-6"><a aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">hjust =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb4-7"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> x_bar <span class="sc">+</span> <span class="fl">0.5</span>, <span class="at">y =</span> <span class="dv">7</span>, <span class="at">label =</span> <span class="fu">paste0</span>(<span class="st">"Sample Mean</span><span class="sc">\n</span><span class="st">("</span>, <span class="fu">round</span>(x_bar, <span class="dv">1</span>), <span class="st">" min)"</span>), </span>
<span id="cb4-8"><a aria-hidden="true" tabindex="-1"></a>           <span class="at">color =</span> <span class="st">"darkgreen"</span>, <span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb4-9"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of ED Waiting Times"</span>,</span>
<span id="cb4-10"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparing sample mean (green) to benchmark (red dashed)"</span>,</span>
<span id="cb4-11"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Waiting Time (minutes)"</span>, <span class="at">y =</span> <span class="st">"Number of Patients"</span>) <span class="sc">+</span></span>
<span id="cb4-12"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Slide05_files/figure-revealjs/one-sample-histogram-1.png" width="768" class="r-stretch"></section>
<section id="visualizing-the-null-distribution" class="slide level2">
<h2>Visualizing the Null Distribution</h2>

<img data-src="Slide05_files/figure-revealjs/one-sample-viz-1.png" width="864" class="r-stretch"></section>
<section id="interpreting-the-visualization" class="slide level2">
<h2>Interpreting the Visualization</h2>
<ul>
<li class="fragment"><strong>Gray shaded areas</strong>: Rejection regions (α = 0.05)</li>
<li class="fragment"><strong>Red vertical line</strong>: Our calculated t-statistic</li>
<li class="fragment"><strong>Result</strong>: Our t falls in the rejection region!</li>
<li class="fragment"><strong>Meaning</strong>: This result would be unlikely if the true mean were 45 minutes (i.e., the null is true)</li>
</ul>
</section>
<section id="demonstration-using-t.test-in-r" class="slide level2">
<h2>Demonstration: Using t.test() in R</h2>
<ul>
<li>We can run one-sample t-test using the <code>t.test()</code> function in R.
<ul>
<li>one group’s mean vs a known or hypothesized mean</li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Perform one-sample t-test</span></span>
<span id="cb5-2"><a aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">t.test</span>(hospital_ops<span class="sc">$</span>ed_wait_time, <span class="at">mu =</span> <span class="dv">45</span>)</span>
<span id="cb5-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">parameters</span>(result)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>One Sample t-test

Parameter    |  Mean | mu | Difference |         95% CI | t(29) |     p
-----------------------------------------------------------------------
ed_wait_time | 46.20 | 45 |       1.20 | [45.23, 47.17] |  2.52 | 0.017

Alternative hypothesis: true mean is not equal to 45</code></pre>
</div>
</div>
</section>
<section id="components-of-the-output" class="slide level2">
<h2>Components of the Output</h2>
<ul>
<li><strong><em>t</em>-statistic</strong> (2.52): Distance from benchmark in SE units</li>
<li><strong>df</strong> (29): Degrees of freedom (n - 1)</li>
<li><strong><em>p</em>-value</strong> (0.017): Probability of seeing this or more extreme result if null is true</li>
<li><strong>95% CI</strong> [45.23, 47.17]: Range for the true mean</li>
</ul>
</section>
<section id="interpreting-the-results" class="slide level2">
<h2>Interpreting the Results</h2>
<p><strong>Key findings</strong>:</p>
<ul>
<li class="fragment">The <em>p</em>-value is less than 0.05, so we <strong>reject the null hypothesis</strong> — the observed difference is unlikely due to chance alone</li>
<li class="fragment">The 45-minute benchmark is NOT within the 95% confidence interval, which further confirms that the true mean is significantly different from 45</li>
<li class="fragment"><strong>Conclusion</strong>: The evidence strongly suggests that the hospital’s average ED waiting time is significantly higher than the 45-minute regional standard
<ul>
<li class="fragment">Need to investigate causes and potential interventions for the longer wait times.</li>
</ul></li>
</ul>
</section>
<section id="practice-one-sample-t-test" class="slide level2">
<h2>Practice: One-Sample <em>t</em>-test</h2>
<p>A clinic wants to test if their average patient satisfaction score differs from the national average of <strong>8.0</strong> (out of 10). Use the <code>patient_outcomes</code> dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Fill in the blanks (replace ___ with appropriate values)</span></span>
<span id="cb7-2"><a aria-hidden="true" tabindex="-1"></a>satisfaction_scores <span class="ot">&lt;-</span> patient_outcomes<span class="sc">$</span>___</span>
<span id="cb7-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Perform the t-test</span></span>
<span id="cb7-5"><a aria-hidden="true" tabindex="-1"></a>result_satisfaction <span class="ot">&lt;-</span> <span class="fu">t.test</span>(___, <span class="at">mu =</span> ___)</span>
<span id="cb7-6"><a aria-hidden="true" tabindex="-1"></a><span class="fu">parameters</span>(result_satisfaction)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><br> <strong>Question</strong>: Is the average satisfaction significantly different from the target?</p>
</section></section>
<section>
<section id="independent-samples-t-test" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>2. Independent-Samples <em>t</em>-test</h1>

</section>
<section id="what-is-an-independent-samples-t-test" class="slide level2">
<h2>What is an Independent-Samples <em>t</em>-test?</h2>
<p>An <strong>independent-samples <em>t</em>-test</strong> compares means from two different, unrelated groups.</p>
<div class="fragment">
<p><br> <strong>Key Question</strong>: <em>Are these two group means significantly different from each other?</em></p>
</div>
<div class="fragment">
<p><br> <strong>Key Requirements</strong>:</p>
<ul>
<li><strong>Two independent groups</strong> (observations unrelated; grouping variable)</li>
<li><strong>Continuous outcome variable</strong></li>
</ul>
</div>
</section>
<section id="when-to-use-it-1" class="slide level2">
<h2>When to Use It</h2>
<p>The independent-samples t-test is appropriate when comparing <strong>two separate, independent groups</strong>:</p>
<ul>
<li class="fragment"><strong>Comparing treatments</strong>: New drug vs.&nbsp;standard treatment</li>
<li class="fragment"><strong>Comparing facilities</strong>: One hospital vs.&nbsp;another (Hospital A vs.&nbsp;Hospital B)</li>
<li class="fragment"><strong>Intervention studies</strong>: Intervention group vs.&nbsp;control group</li>
<li class="fragment"><strong>Demographic comparisons</strong>: Urban vs.&nbsp;rural outcomes</li>
</ul>
</section>
<section id="independent-samples-t-test-scenario-comparing-intake-systems" class="slide level2">
<h2>Independent-Samples t-test Scenario: <br> Comparing Intake Systems</h2>
<p><strong>Situation</strong>: Your health system is considering digital intake systems.</p>
<ul>
<li><strong>Hospital A</strong>: <em>Digital</em> tablet-based intake</li>
<li><strong>Hospital B</strong>: Traditional <em>paper</em> forms</li>
</ul>
<div class="fragment">
<p><br> <strong>Question</strong>: Does the digital system result in faster processing times?</p>
</div>
<div class="fragment">
<p><br> You collect processing time data from 15 randomly selected patients at each hospital to determine whether the difference represents a real efficiency gain.</p>
</div>
</section>
<section id="hypotheses-1" class="slide level2">
<h2>Hypotheses</h2>
<p>For our intake systems comparison:</p>
<ul>
<li><strong>Null Hypothesis (H₀)</strong>: μ₁ = μ₂ (Mean processing time is the same for both systems)</li>
<li><strong>Alternative Hypothesis (H₁)</strong>: μ₁ ≠ μ₂ (Mean processing times differ between systems)</li>
</ul>
<div class="fragment">
<p>The <em>t</em>-test will help us decide whether the observed difference is statistically significant.</p>
</div>
</section>
<section id="the-formula-1" class="slide level2">
<h2>The Formula</h2>
<p><span class="math display">\[t = \frac{\bar{X}_1 - \bar{X}_2}{s_p\sqrt{\frac{1}{n_1} + \frac{1}{n_2}}}\]</span></p>
<div class="fragment">
<p><strong>Pooled standard deviation</strong>:</p>
<p><span class="math display">\[s_p = \sqrt{\frac{(n_1-1)s_1^2 + (n_2-1)s_2^2}{n_1 + n_2 - 2}}\]</span></p>
</div>
</section>
<section id="understanding-the-formula-1" class="slide level2">
<h2>Understanding the Formula</h2>
<p><strong>Numerator</strong> (<span class="math inline">\(\bar{X}_1 - \bar{X}_2\)</span>):</p>
<ul>
<li>The difference between the two sample means</li>
</ul>
<div class="fragment">
<p><strong>Denominator</strong>:</p>
<ul>
<li>Standard error of the difference between means</li>
<li>Combines variability from both groups</li>
</ul>
</div>
<div class="fragment">
<p><strong>Pooled SD</strong> (<span class="math inline">\(s_p\)</span>):</p>
<ul>
<li>Weighted average of both groups’ SDs</li>
<li>Assumes equal population variances</li>
</ul>
</div>
</section>
<section id="demonstration-extract-the-data" class="slide level2">
<h2>Demonstration: Extract the Data</h2>
<p>First, let’s get each hospital’s intake time data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Extract data from our dataset</span></span>
<span id="cb8-2"><a aria-hidden="true" tabindex="-1"></a>hospital_A <span class="ot">&lt;-</span> hospital_ops<span class="sc">$</span>intake_time[hospital_ops<span class="sc">$</span>intake_hospital <span class="sc">==</span> <span class="st">"A_Digital"</span>]</span>
<span id="cb8-3"><a aria-hidden="true" tabindex="-1"></a>hospital_B <span class="ot">&lt;-</span> hospital_ops<span class="sc">$</span>intake_time[hospital_ops<span class="sc">$</span>intake_hospital <span class="sc">==</span> <span class="st">"B_Paper"</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s check descriptive statistics for each hospital.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Hospital A: Digital </span></span>
<span id="cb9-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(hospital_A) <span class="co"># average intake time in minutes</span></span>
<span id="cb9-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(hospital_A)   <span class="co"># standard deviation of intake time in minutes</span></span>
<span id="cb9-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(hospital_A) <span class="co"># number of patients</span></span>
<span id="cb9-5"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Hospital B: Paper</span></span>
<span id="cb9-7"><a aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(hospital_B) <span class="co"># average intake time in minutes</span></span>
<span id="cb9-8"><a aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(hospital_B)   <span class="co"># standard deviation of intake time in minutes</span></span>
<span id="cb9-9"><a aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(hospital_B) <span class="co"># number of patients</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="visualizing-group-differences" class="slide level2">
<h2>Visualizing Group Differences</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Create grouped data for visualization</span></span>
<span id="cb10-2"><a aria-hidden="true" tabindex="-1"></a>intake_viz <span class="ot">&lt;-</span> hospital_ops <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hospital_label =</span> <span class="fu">ifelse</span>(intake_hospital <span class="sc">==</span> <span class="st">"A_Digital"</span>, </span>
<span id="cb10-4"><a aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"A: Digital System"</span>, <span class="st">"B: Paper Forms"</span>))</span>
<span id="cb10-5"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Box plot with individual points</span></span>
<span id="cb10-7"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(intake_viz, <span class="fu">aes</span>(<span class="at">x =</span> hospital_label, <span class="at">y =</span> intake_time, <span class="at">fill =</span> hospital_label)) <span class="sc">+</span></span>
<span id="cb10-8"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb10-9"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb10-10"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Patient Intake Processing Times by System"</span>,</span>
<span id="cb10-11"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparing digital (A) vs. paper (B) intake systems"</span>,</span>
<span id="cb10-12"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Hospital System"</span>, <span class="at">y =</span> <span class="st">"Processing Time (minutes)"</span>) <span class="sc">+</span></span>
<span id="cb10-13"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb10-14"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb10-15"><a aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Slide05_files/figure-revealjs/independent-viz-1.png" width="864" class="r-stretch"></section>
<section id="visualizing-the-null-distribution-1" class="slide level2">
<h2>Visualizing the Null Distribution</h2>

<img data-src="Slide05_files/figure-revealjs/independent-null-1.png" width="864" class="r-stretch"></section>
<section id="demonstration-using-t.test-in-r-1" class="slide level2">
<h2>Demonstration: Using t.test() in R</h2>
<p>Same as one-sample t-test, we can use t.test() function in R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Perform independent samples t-test</span></span>
<span id="cb11-2"><a aria-hidden="true" tabindex="-1"></a><span class="co"># var.equal = TRUE uses pooled variance (Student's t-test)</span></span>
<span id="cb11-3"><a aria-hidden="true" tabindex="-1"></a>result_ind <span class="ot">&lt;-</span> <span class="fu">t.test</span>(hospital_A, hospital_B, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-4"><a aria-hidden="true" tabindex="-1"></a><span class="co"># alternatively: t.test(intake_time ~ intake_hospital, data = hospital_ops, var.equal = TRUE)</span></span>
<span id="cb11-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">parameters</span>(result_ind)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Two Sample t-test

Parameter1 | Parameter2 | Mean_Parameter1 | Mean_Parameter2 | Difference
------------------------------------------------------------------------
hospital_A | hospital_B |           14.53 |           16.53 |      -2.00

Parameter1 |         95% CI | t(28) |      p
--------------------------------------------
hospital_A | [-3.11, -0.89] | -3.70 | &lt; .001

Alternative hypothesis: true difference in means is not equal to 0</code></pre>
</div>
</div>
</section>
<section id="components-of-the-output-1" class="slide level2">
<h2>Components of the Output</h2>
<ul>
<li><strong><em>t</em>-statistic</strong> (-3.7): Distance between the two group means in SE units</li>
<li><strong>df</strong> (28): Degrees of freedom (n₁ + n₂ - 2)</li>
<li><strong><em>p</em>-value</strong> (0.00094): Probability of seeing this or more extreme result if null is true</li>
<li><strong>95% CI</strong> [-3.11, -0.89]: Range for the true difference in means</li>
</ul>
</section>
<section id="interpreting-the-results-1" class="slide level2">
<h2>Interpreting the Results</h2>
<p><strong>Key findings</strong>:</p>
<ul>
<li class="fragment">The <em>p</em>-value is less than 0.05, so we <strong>reject the null hypothesis</strong> — the observed difference between the two groups is unlikely due to chance alone</li>
<li class="fragment">Zero is NOT within the 95% confidence interval, which further confirms that the true difference in means is significantly different from zero</li>
<li class="fragment"><strong>Conclusion</strong>: The digital intake system (Hospital A) has <strong>significantly shorter</strong> processing times than the paper system (Hospital B)
<ul>
<li class="fragment">This supports investing in digital intake systems across the health system.</li>
</ul></li>
</ul>
</section>
<section id="practice-independent-samples-t-test" class="slide level2">
<h2>Practice: Independent-Samples <em>t</em>-test</h2>
<p>A hospital wants to compare the length of stay (in days) between patients receiving a new <strong>Enhanced Recovery Protocol (ERP)</strong> versus <strong>Standard Care</strong>. Use the <code>patient_outcomes</code> dataset and test this hypothesis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Fill in the blanks</span></span>
<span id="cb13-2"><a aria-hidden="true" tabindex="-1"></a>new_protocol <span class="ot">&lt;-</span> patient_outcomes<span class="sc">$</span>length_of_stay[patient_outcomes<span class="sc">$</span>protocol_group <span class="sc">==</span> <span class="st">"___"</span>]</span>
<span id="cb13-3"><a aria-hidden="true" tabindex="-1"></a>standard_care <span class="ot">&lt;-</span> patient_outcomes<span class="sc">$</span>length_of_stay[patient_outcomes<span class="sc">$</span>protocol_group <span class="sc">==</span> <span class="st">"___"</span>]</span>
<span id="cb13-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Perform the t-test</span></span>
<span id="cb13-6"><a aria-hidden="true" tabindex="-1"></a>result_los <span class="ot">&lt;-</span> <span class="fu">t.test</span>(___, ___, <span class="at">var.equal =</span> ___)</span>
<span id="cb13-7"><a aria-hidden="true" tabindex="-1"></a><span class="co"># alternatively:result_los &lt;- t.test(___ ~ ___, data = ___, var.equal = ___)</span></span>
<span id="cb13-8"><a aria-hidden="true" tabindex="-1"></a><span class="fu">parameters</span>(result_los)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><br> <strong>Question</strong>: Is the difference in length of stay statistically significant?</p>
</section></section>
<section>
<section id="paired-samples-t-test" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>3. Paired-Samples <em>t</em>-test</h1>

</section>
<section id="what-is-a-paired-samples-t-test" class="slide level2">
<h2>What is a Paired-Samples <em>t</em>-test?</h2>
<p>A <strong>paired-samples <em>t</em>-test</strong> compares two related measurements on the same subjects.</p>
<div class="fragment">
<p><br> <strong>Key Question</strong>: <em>Is there a significant change within the same individuals?</em></p>
</div>
<div class="fragment">
<p><br> <strong>Key Characteristic</strong>:</p>
<ul>
<li>Data comes in <strong>pairs</strong> (each subject/patient has two linked measurements)</li>
</ul>
</div>
</section>
<section id="why-use-paired-data" class="slide level2">
<h2>Why Use Paired Data?</h2>
<p><strong>Key Advantage</strong>: Each person serves as their own control!</p>
<ul>
<li>Eliminates variability between individuals</li>
<li>Increases statistical power to detect true effects</li>
<li>More efficient use of data</li>
</ul>
</section>
<section id="when-to-use-it-2" class="slide level2">
<h2>When to Use It</h2>
<p>The paired-samples <em>t</em>-test is appropriate for related measurements:</p>
<ul>
<li class="fragment"><strong>Before-and-after studies</strong>: Pre-treatment vs.&nbsp;post-treatment</li>
<li class="fragment"><strong>Matched pairs</strong>: Twins, matched controls</li>
<li class="fragment"><strong>Within-subject comparisons</strong>: Two conditions on the same patient</li>
</ul>
</section>
<section id="paired-samples-t-test-scenario-pain-management-protocol" class="slide level2">
<h2>Paired-Samples <em>t</em>-test Scenario: <br> Pain Management Protocol</h2>
<p><strong>Situation</strong>: A hospital implemented a new <strong>non-pharmacological pain management protocol</strong> (integrating guided imagery and music therapy).</p>
<div class="fragment">
<p><br> To evaluate effectiveness, they measure pain scores (0-10 scale) for 30 patients <strong>before</strong> and <strong>after</strong> the protocol.</p>
</div>
<div class="fragment">
<p><br> <strong>Question</strong>: Did the protocol significantly reduce pain?</p>
</div>
</section>
<section id="hypotheses-2" class="slide level2">
<h2>Hypotheses</h2>
<p>For our pain management protocol evaluation:</p>
<ul>
<li><strong>Null Hypothesis (H₀)</strong>: μ_D = 0 (The mean difference in pain scores is zero — no change)</li>
<li><strong>Alternative Hypothesis (H₁)</strong>: μ_D ≠ 0 (The mean difference is not zero — pain scores changed)</li>
</ul>
<div class="fragment">
<p>The <em>t</em>-test will help us determine whether the protocol had a significant effect.</p>
</div>
</section>
<section id="the-formula-2" class="slide level2">
<h2>The Formula</h2>
<p>The paired <em>t</em>-test analyzes <strong>differences</strong> between paired observations:</p>
<p><span class="math display">\[t = \frac{\bar{D}}{s_D / \sqrt{n}}\]</span></p>
<div class="fragment">
<p>Where:</p>
<ul>
<li><span class="math inline">\(\bar{D}\)</span>: mean of the differences</li>
<li><span class="math inline">\(s_D\)</span>: standard deviation of the differences</li>
<li><span class="math inline">\(n\)</span>: number of pairs</li>
</ul>
</div>
</section>
<section id="paired-samples-t-test-demonstration" class="slide level2">
<h2>Paired-Samples <em>t</em>-test Demonstration</h2>
<p>Let’s first get the pain scores from our dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Extract pain scores from our dataset</span></span>
<span id="cb14-2"><a aria-hidden="true" tabindex="-1"></a>before <span class="ot">&lt;-</span> hospital_ops<span class="sc">$</span>pain_before</span>
<span id="cb14-3"><a aria-hidden="true" tabindex="-1"></a>after <span class="ot">&lt;-</span> hospital_ops<span class="sc">$</span>pain_after</span>
<span id="cb14-4"><a aria-hidden="true" tabindex="-1"></a>differences <span class="ot">&lt;-</span> before <span class="sc">-</span> after</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s check descriptive statistics of the pain scores.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Before Treatment </span></span>
<span id="cb15-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(before)</span>
<span id="cb15-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(before)</span>
<span id="cb15-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a aria-hidden="true" tabindex="-1"></a><span class="co"># After Treatment</span></span>
<span id="cb15-6"><a aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(after)</span>
<span id="cb15-7"><a aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(after)</span>
<span id="cb15-8"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Before - After</span></span>
<span id="cb15-10"><a aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(differences)</span>
<span id="cb15-11"><a aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(differences)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="visualizing-paired-data" class="slide level2">
<h2>Visualizing Paired Data</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-hidden="true" tabindex="-1"></a>pain_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb16-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">patient =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">30</span>, <span class="dv">2</span>),</span>
<span id="cb16-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">time =</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Before"</span>, <span class="st">"After"</span>), <span class="at">each =</span> <span class="dv">30</span>),</span>
<span id="cb16-4"><a aria-hidden="true" tabindex="-1"></a>                <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Before"</span>, <span class="st">"After"</span>)),</span>
<span id="cb16-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">score =</span> <span class="fu">c</span>(before, after)</span>
<span id="cb16-6"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-7"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pain_data, <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> score, <span class="at">group =</span> patient)) <span class="sc">+</span></span>
<span id="cb16-9"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="st">"gray30"</span>) <span class="sc">+</span></span>
<span id="cb16-10"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> time), <span class="at">size =</span> <span class="dv">2</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb16-11"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"line"</span>,</span>
<span id="cb16-12"><a aria-hidden="true" tabindex="-1"></a>               <span class="at">linewidth =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb16-13"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="fu">aes</span>(<span class="at">group =</span> <span class="dv">1</span>), <span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"point"</span>,</span>
<span id="cb16-14"><a aria-hidden="true" tabindex="-1"></a>               <span class="at">size =</span> <span class="dv">4</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb16-15"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Individual Patient Pain Scores"</span>,</span>
<span id="cb16-16"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Red line shows mean change"</span>,</span>
<span id="cb16-17"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"Pain Score (0-10)"</span>) <span class="sc">+</span></span>
<span id="cb16-18"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb16-19"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb16-20"><a aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Slide05_files/figure-revealjs/paired-viz-1.png" width="672" class="r-stretch"></section>
<section id="interpreting-the-paired-plot" class="slide level2">
<h2>Interpreting the Paired Plot</h2>
<ul>
<li class="fragment"><strong>Gray lines</strong>: Individual patient changes (some improved, some didn’t)</li>
<li class="fragment"><strong>Red line</strong>: Overall mean change</li>
<li class="fragment"><strong>Downward slope</strong>: Average pain decreased after treatment</li>
</ul>
</section>
<section id="visualizing-the-null-distribution-2" class="slide level2">
<h2>Visualizing the Null Distribution</h2>

<img data-src="Slide05_files/figure-revealjs/paired-null-1.png" width="864" class="r-stretch"></section>
<section id="demonstration-using-t.test-in-r-2" class="slide level2">
<h2>Demonstration: Using t.test() in R</h2>
<p>Same as other t-tests, we can use <code>t.test()</code> function with <code>paired = TRUE</code> option.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Perform paired samples t-test</span></span>
<span id="cb17-2"><a aria-hidden="true" tabindex="-1"></a>result_paired <span class="ot">&lt;-</span> <span class="fu">t.test</span>(before, after, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span>
<span id="cb17-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">parameters</span>(result_paired)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Paired t-test

Parameter | Group | Difference | t(29) |     p |       95% CI
-------------------------------------------------------------
before    | after |       0.40 |  2.84 | 0.008 | [0.11, 0.69]

Alternative hypothesis: true mean difference is not equal to 0</code></pre>
</div>
</div>
</section>
<section id="components-of-the-output-2" class="slide level2">
<h2>Components of the Output</h2>
<ul>
<li><strong><em>t</em>-statistic</strong> (2.84): Distance of the mean difference from zero in SE units</li>
<li><strong>df</strong> (29): Degrees of freedom (n - 1)</li>
<li><strong><em>p</em>-value</strong> (0.0081): Probability of seeing this or more extreme result if null is true</li>
<li><strong>95% CI</strong> [0.11, 0.69]: Range for the true mean difference</li>
</ul>
</section>
<section id="interpreting-the-results-2" class="slide level2">
<h2>Interpreting the Results</h2>
<p><strong>Key findings</strong>:</p>
<ul>
<li class="fragment">The <em>p</em>-value is less than 0.05, so we <strong>reject the null hypothesis</strong> — the observed change in pain scores is unlikely due to chance alone</li>
<li class="fragment">Zero is NOT within the 95% confidence interval, which further confirms that the true mean difference is significantly different from zero</li>
<li class="fragment"><strong>Conclusion</strong>: The non-pharmacological pain management protocol <strong>significantly reduced</strong> pain scores
<ul>
<li class="fragment">This supports expanding the protocol to other departments or patient populations.</li>
</ul></li>
</ul>
</section>
<section id="practice-paired-samples-t-test" class="slide level2">
<h2>Practice: Paired-Samples <em>t</em>-test</h2>
<p>A health clinic wants to evaluate the effectiveness of a <strong>lifestyle intervention program</strong> (12-week program with dietary modification and exercise coaching) on reducing blood pressure. Use the <code>patient_outcomes</code> dataset and test the hypothesis that the intervention program reduces blood pressure.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Fill in the blanks</span></span>
<span id="cb19-2"><a aria-hidden="true" tabindex="-1"></a>bp_before <span class="ot">&lt;-</span> patient_outcomes<span class="sc">$</span>___</span>
<span id="cb19-3"><a aria-hidden="true" tabindex="-1"></a>bp_after <span class="ot">&lt;-</span> patient_outcomes<span class="sc">$</span>___</span>
<span id="cb19-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Perform the t-test</span></span>
<span id="cb19-6"><a aria-hidden="true" tabindex="-1"></a>result_bp <span class="ot">&lt;-</span> <span class="fu">t.test</span>(___, ___, <span class="at">paired =</span> ___)</span>
<span id="cb19-7"><a aria-hidden="true" tabindex="-1"></a><span class="fu">parameters</span>(result_bp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><br> <strong>Question</strong>: Is the change in blood pressure statistically significant?</p>
</section></section>
<section>
<section id="choosing-the-right-t-test" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Choosing the Right <em>t</em>-test</h1>

</section>
<section id="decision-flowchart" class="slide level2">
<h2>Decision Flowchart</h2>
<p>Use this guide to select the appropriate t-test:</p>
<div class="smaller">
<table class="caption-top">
<colgroup>
<col style="width: 30%">
<col style="width: 33%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Question</th>
<th>If Yes…</th>
<th>R Function</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Comparing to a benchmark?</td>
<td><strong>One-sample</strong></td>
<td><code>t.test(x, mu = value)</code></td>
</tr>
<tr class="even">
<td>Two separate groups?</td>
<td><strong>Independent-samples</strong></td>
<td><code>t.test(x, y, var.equal = TRUE)</code></td>
</tr>
<tr class="odd">
<td>Same subjects, twice?</td>
<td><strong>Paired-samples</strong></td>
<td><code>t.test(x, y, paired = TRUE)</code></td>
</tr>
</tbody>
</table>
</div>
<ul>
<li class="fragment"><p><strong>“Is our average wait time different from the 45-minute standard?”</strong> → One-sample</p></li>
<li class="fragment"><p><strong>“Do patients at Hospital A have shorter stays than Hospital B?”</strong> → Independent-samples</p></li>
<li class="fragment"><p><strong>“Did patient satisfaction improve after our intervention?”</strong> → Paired-samples</p></li>
</ul>
</section></section>
<section>
<section id="summary" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Summary</h1>

</section>
<section id="key-takeaways" class="slide level2 scrollable">
<h2>Key Takeaways</h2>
<ol type="1">
<li class="fragment"><strong>One-sample t-tests</strong>: Evaluate if you meet standards or benchmarks</li>
<li class="fragment"><strong>Independent-samples t-tests</strong>: Compare different treatments, departments, or facilities</li>
<li class="fragment"><strong>Paired-samples t-tests</strong>: Evaluate effectiveness of interventions</li>
<li class="fragment"><strong>All t-tests</strong>: Use <code>t.test()</code> in R with appropriate arguments</li>
</ol>
</section>
<section id="assignments" class="slide level2 scrollable">
<h2>Assignments</h2>
<ol type="1">
<li><strong>Reflection</strong>: Share your thoughts on the lecture
<ul>
<li>3 interesting things</li>
<li>3 confusing things</li>
</ul></li>
<li><strong>Practice</strong>: Complete <code>week05_practice.qmd</code>
<ul>
<li>Apply each t-test type to new scenarios</li>
<li><strong>Due</strong>: Check Canvas for deadline</li>
</ul></li>
</ol>
</section></section>
<section>
<section id="references" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>References</h1>

</section>
<section id="statistical-methods" class="slide level2">
<h2>Statistical Methods</h2>
<ul>
<li>Statistical Analysis for Health Data Science with SAS and R: Chapter 3</li>
<li>Field, A. (2018). <em>Discovering Statistics Using IBM SPSS Statistics</em> (5th ed.). SAGE Publications.</li>
<li><a href="https://learningstatisticswithr.com/lsr-0.6.pdf" target="_blank">Navarro, D. (2019). <em>Learning Statistics with R: Chapter 13</em>.</a></li>
</ul>
</section>
<section id="healthcare-applications" class="slide level2">
<h2>Healthcare Applications</h2>
<ul>
<li>Horwitz, L. I., Green, J., &amp; Bradley, E. H. (2010). US emergency department performance on wait time and length of visit. Annals of emergency medicine, 55(2), 133-141.</li>
<li>Middel, B. (2008). The impact of electronic health records on time efficiency of physicians and nurses: a systematic review1. Nederlands Tijdschrift voor Evidence Based Practice, 6(1), 14-16.</li>
<li>Patil, A., Srinivasarangan, M., Ravindra, P., &amp; Mundada, H. (2017). Studying protocol-based pain management in the emergency department. Journal of emergencies, trauma, and shock, 10(4), 180-188.</li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Week 5 | Mean Comparison: <em>t</em>-tests</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>