<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-03-23">

<title>Linear Regression 1: Simple and Multiple Linear Regression – Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-7b997789b8c97d15811d7b52a81c6dd1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026)</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../../index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mba642-spring-26/mba642-spring-26.github.io/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Linear Regression 1: Simple and Multiple Linear Regression</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#from-correlation-to-regression" id="toc-from-correlation-to-regression" class="nav-link" data-scroll-target="#from-correlation-to-regression">From Correlation to Regression</a></li>
  <li><a href="#why-linear-regression-matters" id="toc-why-linear-regression-matters" class="nav-link" data-scroll-target="#why-linear-regression-matters">Why Linear Regression Matters</a></li>
  <li><a href="#overview-of-linear-regression-types" id="toc-overview-of-linear-regression-types" class="nav-link" data-scroll-target="#overview-of-linear-regression-types">Overview of Linear Regression Types</a></li>
  </ul></li>
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression">Simple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#what-is-it" id="toc-what-is-it" class="nav-link" data-scroll-target="#what-is-it">What is it?</a></li>
  <li><a href="#when-to-use-it" id="toc-when-to-use-it" class="nav-link" data-scroll-target="#when-to-use-it">When to Use It</a></li>
  <li><a href="#the-concept" id="toc-the-concept" class="nav-link" data-scroll-target="#the-concept">The Concept</a>
  <ul class="collapse">
  <li><a href="#the-model-equation" id="toc-the-model-equation" class="nav-link" data-scroll-target="#the-model-equation">The Model Equation</a></li>
  </ul></li>
  <li><a href="#the-ordinary-least-squares-ols-method" id="toc-the-ordinary-least-squares-ols-method" class="nav-link" data-scroll-target="#the-ordinary-least-squares-ols-method">The Ordinary Least Squares (OLS) Method</a>
  <ul class="collapse">
  <li><a href="#how-ols-works" id="toc-how-ols-works" class="nav-link" data-scroll-target="#how-ols-works">How OLS Works</a></li>
  </ul></li>
  <li><a href="#using-the-fitted-model-for-predictions" id="toc-using-the-fitted-model-for-predictions" class="nav-link" data-scroll-target="#using-the-fitted-model-for-predictions">Using the Fitted Model for Predictions</a></li>
  <li><a href="#example-case-patient-satisfaction-and-wait-time" id="toc-example-case-patient-satisfaction-and-wait-time" class="nav-link" data-scroll-target="#example-case-patient-satisfaction-and-wait-time">Example Case: Patient Satisfaction and Wait Time</a>
  <ul class="collapse">
  <li><a href="#background-and-context" id="toc-background-and-context" class="nav-link" data-scroll-target="#background-and-context">Background and Context</a></li>
  <li><a href="#loading-the-dataset" id="toc-loading-the-dataset" class="nav-link" data-scroll-target="#loading-the-dataset">Loading the Dataset</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a></li>
  <li><a href="#fitting-the-simple-linear-regression-model" id="toc-fitting-the-simple-linear-regression-model" class="nav-link" data-scroll-target="#fitting-the-simple-linear-regression-model">Fitting the Simple Linear Regression Model</a></li>
  <li><a href="#the-fitted-regression-equation" id="toc-the-fitted-regression-equation" class="nav-link" data-scroll-target="#the-fitted-regression-equation">The Fitted Regression Equation</a></li>
  <li><a href="#interpreting-the-results" id="toc-interpreting-the-results" class="nav-link" data-scroll-target="#interpreting-the-results">Interpreting the Results</a></li>
  <li><a href="#making-predictions" id="toc-making-predictions" class="nav-link" data-scroll-target="#making-predictions">Making Predictions</a></li>
  <li><a href="#practice-1-simple-linear-regression" id="toc-practice-1-simple-linear-regression" class="nav-link" data-scroll-target="#practice-1-simple-linear-regression">Practice 1: Simple Linear Regression</a></li>
  <li><a href="#scenario" id="toc-scenario" class="nav-link" data-scroll-target="#scenario">Scenario</a></li>
  <li><a href="#data-loading" id="toc-data-loading" class="nav-link" data-scroll-target="#data-loading">Data Loading</a></li>
  <li><a href="#task-1.1-visualize-the-relationship" id="toc-task-1.1-visualize-the-relationship" class="nav-link" data-scroll-target="#task-1.1-visualize-the-relationship">Task 1.1: Visualize the Relationship</a></li>
  <li><a href="#task-1.2-fit-the-simple-linear-regression-model" id="toc-task-1.2-fit-the-simple-linear-regression-model" class="nav-link" data-scroll-target="#task-1.2-fit-the-simple-linear-regression-model">Task 1.2: Fit the Simple Linear Regression Model</a></li>
  <li><a href="#task-1.3-make-predictions" id="toc-task-1.3-make-predictions" class="nav-link" data-scroll-target="#task-1.3-make-predictions">Task 1.3: Make Predictions</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression">Multiple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#what-is-it-1" id="toc-what-is-it-1" class="nav-link" data-scroll-target="#what-is-it-1">What is it?</a></li>
  <li><a href="#when-to-use-it-1" id="toc-when-to-use-it-1" class="nav-link" data-scroll-target="#when-to-use-it-1">When to Use It</a></li>
  <li><a href="#extending-to-multiple-predictors" id="toc-extending-to-multiple-predictors" class="nav-link" data-scroll-target="#extending-to-multiple-predictors">Extending to Multiple Predictors</a>
  <ul class="collapse">
  <li><a href="#the-model-equation-1" id="toc-the-model-equation-1" class="nav-link" data-scroll-target="#the-model-equation-1">The Model Equation</a></li>
  </ul></li>
  <li><a href="#an-example-case-hospital-length-of-stay" id="toc-an-example-case-hospital-length-of-stay" class="nav-link" data-scroll-target="#an-example-case-hospital-length-of-stay">An Example Case: Hospital Length of Stay</a>
  <ul class="collapse">
  <li><a href="#background-and-context-1" id="toc-background-and-context-1" class="nav-link" data-scroll-target="#background-and-context-1">Background and Context</a></li>
  <li><a href="#loading-the-dataset-1" id="toc-loading-the-dataset-1" class="nav-link" data-scroll-target="#loading-the-dataset-1">Loading the Dataset</a></li>
  <li><a href="#exploratory-data-analysis-1" id="toc-exploratory-data-analysis-1" class="nav-link" data-scroll-target="#exploratory-data-analysis-1">Exploratory Data Analysis</a></li>
  <li><a href="#fitting-the-multiple-linear-regression-model" id="toc-fitting-the-multiple-linear-regression-model" class="nav-link" data-scroll-target="#fitting-the-multiple-linear-regression-model">Fitting the Multiple Linear Regression Model</a></li>
  <li><a href="#interpreting-the-results-1" id="toc-interpreting-the-results-1" class="nav-link" data-scroll-target="#interpreting-the-results-1">Interpreting the Results</a></li>
  <li><a href="#practical-application-predicting-los" id="toc-practical-application-predicting-los" class="nav-link" data-scroll-target="#practical-application-predicting-los">Practical Application: Predicting LOS</a></li>
  <li><a href="#practice-2-multiple-linear-regression" id="toc-practice-2-multiple-linear-regression" class="nav-link" data-scroll-target="#practice-2-multiple-linear-regression">Practice 2: Multiple Linear Regression</a></li>
  <li><a href="#scenario-1" id="toc-scenario-1" class="nav-link" data-scroll-target="#scenario-1">Scenario</a></li>
  <li><a href="#loading-the-dataset-2" id="toc-loading-the-dataset-2" class="nav-link" data-scroll-target="#loading-the-dataset-2">Loading the Dataset</a></li>
  <li><a href="#task-2.1-fit-the-multiple-regression-model" id="toc-task-2.1-fit-the-multiple-regression-model" class="nav-link" data-scroll-target="#task-2.1-fit-the-multiple-regression-model">Task 2.1: Fit the Multiple Regression Model</a></li>
  <li><a href="#task-2.2-compare-model-fit" id="toc-task-2.2-compare-model-fit" class="nav-link" data-scroll-target="#task-2.2-compare-model-fit">Task 2.2: Compare Model Fit</a></li>
  <li><a href="#task-2.3-make-predictions" id="toc-task-2.3-make-predictions" class="nav-link" data-scroll-target="#task-2.3-make-predictions">Task 2.3: Make Predictions</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#model-assumptions-and-diagnostics" id="toc-model-assumptions-and-diagnostics" class="nav-link" data-scroll-target="#model-assumptions-and-diagnostics">Model Assumptions and Diagnostics</a>
  <ul class="collapse">
  <li><a href="#key-assumptions-of-linear-regression" id="toc-key-assumptions-of-linear-regression" class="nav-link" data-scroll-target="#key-assumptions-of-linear-regression">Key Assumptions of Linear Regression</a>
  <ul class="collapse">
  <li><a href="#linearity" id="toc-linearity" class="nav-link" data-scroll-target="#linearity">1. Linearity</a></li>
  <li><a href="#independence-of-observations" id="toc-independence-of-observations" class="nav-link" data-scroll-target="#independence-of-observations">2. Independence of Observations</a></li>
  <li><a href="#homoscedasticity-equal-variance" id="toc-homoscedasticity-equal-variance" class="nav-link" data-scroll-target="#homoscedasticity-equal-variance">3. Homoscedasticity (Equal Variance)</a></li>
  <li><a href="#normality-of-residuals" id="toc-normality-of-residuals" class="nav-link" data-scroll-target="#normality-of-residuals">4. Normality of Residuals</a></li>
  <li><a href="#no-perfect-multicollinearity-multiple-regression-only" id="toc-no-perfect-multicollinearity-multiple-regression-only" class="nav-link" data-scroll-target="#no-perfect-multicollinearity-multiple-regression-only">5. No (Perfect) Multicollinearity (Multiple Regression Only)</a></li>
  <li><a href="#summary-which-plot-checks-which-assumption" id="toc-summary-which-plot-checks-which-assumption" class="nav-link" data-scroll-target="#summary-which-plot-checks-which-assumption">Summary: Which Plot Checks Which Assumption?</a></li>
  </ul></li>
  <li><a href="#diagnostic-plots" id="toc-diagnostic-plots" class="nav-link" data-scroll-target="#diagnostic-plots">Diagnostic Plots</a>
  <ul class="collapse">
  <li><a href="#interpreting-the-two-standard-diagnostic-plots" id="toc-interpreting-the-two-standard-diagnostic-plots" class="nav-link" data-scroll-target="#interpreting-the-two-standard-diagnostic-plots">Interpreting the Two Standard Diagnostic Plots</a></li>
  </ul></li>
  <li><a href="#checking-for-multicollinearity" id="toc-checking-for-multicollinearity" class="nav-link" data-scroll-target="#checking-for-multicollinearity">Checking for Multicollinearity</a>
  <ul class="collapse">
  <li><a href="#variance-inflation-factor-vif" id="toc-variance-inflation-factor-vif" class="nav-link" data-scroll-target="#variance-inflation-factor-vif">Variance Inflation Factor (VIF)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a>
  <ul class="collapse">
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways">Key Takeaways</a>
  <ul class="collapse">
  <li><a href="#simple-vs.-multiple-linear-regression" id="toc-simple-vs.-multiple-linear-regression" class="nav-link" data-scroll-target="#simple-vs.-multiple-linear-regression">Simple vs.&nbsp;Multiple Linear Regression</a></li>
  <li><a href="#how-ols-finds-the-best-line" id="toc-how-ols-finds-the-best-line" class="nav-link" data-scroll-target="#how-ols-finds-the-best-line">How OLS Finds the Best Line</a></li>
  <li><a href="#model-fit-r²" id="toc-model-fit-r²" class="nav-link" data-scroll-target="#model-fit-r²">Model Fit: R²</a></li>
  <li><a href="#making-predictions-1" id="toc-making-predictions-1" class="nav-link" data-scroll-target="#making-predictions-1">Making Predictions</a></li>
  <li><a href="#interpreting-coefficients" id="toc-interpreting-coefficients" class="nav-link" data-scroll-target="#interpreting-coefficients">Interpreting Coefficients</a></li>
  <li><a href="#multicollinearity" id="toc-multicollinearity" class="nav-link" data-scroll-target="#multicollinearity">Multicollinearity</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#references-and-further-reading" id="toc-references-and-further-reading" class="nav-link" data-scroll-target="#references-and-further-reading">References and Further Reading</a>
  <ul class="collapse">
  <li><a href="#statistical-methods" id="toc-statistical-methods" class="nav-link" data-scroll-target="#statistical-methods">Statistical Methods</a></li>
  <li><a href="#healthcare-applications" id="toc-healthcare-applications" class="nav-link" data-scroll-target="#healthcare-applications">Healthcare Applications</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Linear Regression 1: Simple and Multiple Linear Regression</h1>
<p class="subtitle lead">MBA642: Business Analytics in Healthcare Management</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 23, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<section id="from-correlation-to-regression" class="level2">
<h2 class="anchored" data-anchor-id="from-correlation-to-regression">From Correlation to Regression</h2>
<p>In Week 8, we used correlation to answer whether there is a relationship between nurse staffing hours and patient satisfaction (e.g., r = 0.85).</p>
<p><strong>Linear regression extends this</strong> by answering more detailed questions:</p>
<ul>
<li><em>How many points does satisfaction increase for each additional nursing hour?</em> (quantifying the relationship)</li>
<li><em>If we increase staffing to 8 hours per patient day, what satisfaction score can we expect?</em> (making predictions)</li>
<li><em>Among wait time, staffing, and facility age, which factors significantly explain patient satisfaction?</em> (identifying key drivers)</li>
<li><em>Does staffing still matter after controlling for facility age and patient severity?</em> (controlling for confounding variables)</li>
</ul>
</section>
<section id="why-linear-regression-matters" class="level2">
<h2 class="anchored" data-anchor-id="why-linear-regression-matters">Why Linear Regression Matters</h2>
<p>Healthcare managers frequently encounter situations where understanding relationships between variables is crucial for decision-making:</p>
<ul>
<li><strong>Resource allocation</strong>: How does nurse staffing level affect patient outcomes?</li>
<li><strong>Cost management</strong>: What factors drive hospital readmission costs?</li>
<li><strong>Quality improvement</strong>: How does patient wait time impact satisfaction scores?</li>
<li><strong>Performance prediction</strong>: Can we predict length of stay based on patient characteristics?</li>
</ul>
<p>Linear regression provides a powerful framework to:</p>
<ol type="1">
<li><strong>Quantify relationships</strong> between variables (e.g., “For every additional nurse per patient, satisfaction increases by X points”)</li>
<li><strong>Test hypotheses</strong> about whether relationships are statistically significant</li>
<li><strong>Make predictions</strong> about future outcomes</li>
<li><strong>Identify key drivers</strong> (among multiple factors, determine which significantly explain the outcome)</li>
<li><strong>Control for confounding variables</strong> when examining effects of interest</li>
</ol>
</section>
<section id="overview-of-linear-regression-types" class="level2">
<h2 class="anchored" data-anchor-id="overview-of-linear-regression-types">Overview of Linear Regression Types</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Type</th>
<th style="text-align: center;">Predictors</th>
<th style="text-align: left;">Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Simple Linear Regression</td>
<td style="text-align: center;">1</td>
<td style="text-align: left;">Patient age → Length of stay</td>
</tr>
<tr class="even">
<td style="text-align: left;">Multiple Linear Regression</td>
<td style="text-align: center;">2+</td>
<td style="text-align: left;">Patient age + Severity + Insurance → Length of stay</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="simple-linear-regression" class="level1">
<h1>Simple Linear Regression</h1>
<section id="what-is-it" class="level2">
<h2 class="anchored" data-anchor-id="what-is-it">What is it?</h2>
<p>Simple linear regression models the relationship between <strong>one independent variable (X)</strong> and <strong>one dependent variable (Y)</strong> using a linear model (straight line). It is the foundation for understanding more complex regression models, and allows us to quantify how changes in one variable are associated with changes in another.</p>
</section>
<section id="when-to-use-it" class="level2">
<h2 class="anchored" data-anchor-id="when-to-use-it">When to Use It</h2>
<p>You can use simple linear regression when you want to:</p>
<ul>
<li>Examine the (linear) relationship between two continuous variables</li>
<li>Predict an outcome based on a single predictor</li>
<li>Quantify the strength and direction of a linear relationship</li>
<li>Test whether a relationship is statistically significant</li>
</ul>
</section>
<section id="the-concept" class="level2">
<h2 class="anchored" data-anchor-id="the-concept">The Concept</h2>
<p>Simple linear regression finds the “best-fitting” line (linear model) through the data points using a method called Ordinary Least Squares (OLS).</p>
<section id="the-model-equation" class="level3">
<h3 class="anchored" data-anchor-id="the-model-equation">The Model Equation</h3>
<p>The simple linear regression model is expressed as:</p>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 X_i + \epsilon_i\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(Y_i\)</span> (Dependent Variable; DV): The outcome we want to predict or explain. <em>(e.g., patient satisfaction score)</em></li>
<li><span class="math inline">\(X_i\)</span> (Independent Variable; IV): The predictor we use to explain the outcome. <em>(e.g., wait time in minutes)</em></li>
<li><span class="math inline">\(\beta_0\)</span> (Intercept): The predicted value of Y when X = 0. <em>(Think of it as the starting point of the regression line)</em></li>
<li><span class="math inline">\(\beta_1\)</span> (Regression Coefficient; Slope): The change in Y for a one-unit increase in X. <em>(i.e., For each one-unit increase in X, how much does Y change)</em></li>
<li><span class="math inline">\(\epsilon_i\)</span> (Residual): The difference between an observed value and the model’s prediction <em>(i.e., the “leftover” the model does not explain)</em></li>
</ul>
<p>The following diagram shows how all components of the regression equation relate to each other using a simple example with three data points:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-regression-components" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-regression-components-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lecture11_files/figure-html/fig-regression-components-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-regression-components-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: All components of the regression equation shown together
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="the-ordinary-least-squares-ols-method" class="level2">
<h2 class="anchored" data-anchor-id="the-ordinary-least-squares-ols-method">The Ordinary Least Squares (OLS) Method</h2>
<section id="how-ols-works" class="level3">
<h3 class="anchored" data-anchor-id="how-ols-works">How OLS Works</h3>
<p>The shape of a linear model (with one predictor) is determined by two components: the intercept and the slope.</p>
<p>The question we have now is: how do we define the “best” linear model given data? If we find a linear model that has the smallest <em>squared</em> differences between our predictions and the actual outcome values, we can say that the model is the best linear model.</p>
<p>Linear regression finds this “best” line by minimizing the <strong>residual sum of squares (RSS)</strong>, also called the sum of squared residuals:</p>
<p><span class="math display">\[RSS = \sum_{i=1}^{n} (Y_i - \hat{Y}_i)^2 = \sum_{i=1}^{n} \epsilon_i^2\]</span></p>
<p>Where <span class="math inline">\(Y_i\)</span> is the observed value and <span class="math inline">\(\hat{Y}_i\)</span> is the predicted value for observation <span class="math inline">\(i\)</span>.</p>
<p>Why squared residuals?</p>
<ol type="1">
<li>Squaring ensures positive and negative errors don’t cancel out</li>
<li>Squaring penalizes larger errors more heavily</li>
<li>Leads to closed-form mathematical solutions</li>
</ol>
<p>The figure below shows three different lines fitted to the same data. Each line has a different intercept and slope, producing different residuals (red dashed lines) and therefore different RSS values.</p>
<p>Notice that the OLS line (right panel) has the <strong>smallest RSS</strong>. No other intercept-slope pair can produce a smaller sum of squared residuals.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ols-comparison" class="quarto-float quarto-figure quarto-figure-center anchored" width="864">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ols-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lecture11_files/figure-html/fig-ols-comparison-1.png" id="fig-ols-comparison" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-ols-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="using-the-fitted-model-for-predictions" class="level2">
<h2 class="anchored" data-anchor-id="using-the-fitted-model-for-predictions">Using the Fitted Model for Predictions</h2>
<p>Once OLS finds the best-fitting line by estimating <span class="math inline">\(\beta_0\)</span> (intercept) and <span class="math inline">\(\beta_1\)</span> (slope), we can use the fitted model to make predictions for new observations.</p>
<p><strong>The prediction equation</strong> is:</p>
<p><span class="math display">\[\hat{Y} = \hat{\beta}_0 + \hat{\beta}_1 X\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\hat{Y}\)</span> = Predicted value of the dependent variable</li>
<li><span class="math inline">\(\hat{\beta}_0\)</span> = Estimated intercept from the fitted model</li>
<li><span class="math inline">\(\hat{\beta}_1\)</span> = Estimated slope from the fitted model</li>
<li><span class="math inline">\(X\)</span> = Value of the independent variable for which we want to make a prediction</li>
</ul>
<p>The “hat” notation (^) indicates these are <strong>estimated</strong> values from our sample data, not the true population parameters. We use the estimated coefficients to predict outcomes for:</p>
<ol type="1">
<li><strong>Observations within our dataset</strong> to assess model fit</li>
<li><strong>New observations</strong> to forecast outcomes based on predictor values</li>
<li><strong>Hypothetical scenarios</strong> to evaluate “what if” questions (e.g., “What if we reduce wait time to 30 minutes?”)</li>
</ol>
<p>Let’s see this in action with a real healthcare example.</p>
<hr>
</section>
<section id="example-case-patient-satisfaction-and-wait-time" class="level2">
<h2 class="anchored" data-anchor-id="example-case-patient-satisfaction-and-wait-time">Example Case: Patient Satisfaction and Wait Time</h2>
<section id="background-and-context" class="level3">
<h3 class="anchored" data-anchor-id="background-and-context">Background and Context</h3>
<p>Research has consistently shown that emergency department wait times are negatively associated with patient satisfaction. A 2021 study (Abass et al.) found that being informed about waiting time showed a moderately strong positive correlation with patients’ overall rating, highlighting the importance of wait time management for patient experience.</p>
<p>Let’s examine whether emergency department wait time affects patient satisfaction scores using synthetic data that mirrors these real-world relationships.</p>
</section>
<section id="loading-the-dataset" class="level3">
<h3 class="anchored" data-anchor-id="loading-the-dataset">Loading the Dataset</h3>
<p>Run the code below to load the dataset and ruquired packages:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Load synthetic ED data</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>ed_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week11_ed_data.csv"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview the data</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ed_data, <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    X patient_id wait_time_minutes satisfaction_score
1   1          1                55               63.2
2   2          2                23               78.5
3   3          3                48               73.7
4   4          4                43               71.8
5   5          5                32               76.8
6   6          6                 5               96.1
7   7          7                30               67.3
8   8          8                25               70.1
9   9          9                47               66.1
10 10         10                36               73.3</code></pre>
</div>
</div>
</section>
<section id="exploratory-data-analysis" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h3>
<p>Before running regression, always visualize your data. Let’s take a look at the pattern using a scatterplot.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-eda-simple" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eda-simple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lecture11_files/figure-html/fig-eda-simple-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-eda-simple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Relationship between ED wait time and patient satisfaction
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="fitting-the-simple-linear-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="fitting-the-simple-linear-regression-model">Fitting the Simple Linear Regression Model</h3>
<p>Let’s fit the simple linear regression model to quantify the relationship. We can fit a linear model using the <code>lm()</code> function in R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>model_simple <span class="ot">&lt;-</span> <span class="fu">lm</span>(satisfaction_score <span class="sc">~</span> wait_time_minutes, <span class="at">data =</span> ed_data)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display model summary</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_simple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = satisfaction_score ~ wait_time_minutes, data = ed_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-21.2114  -5.0646  -0.5653   4.5972  16.9139 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       85.11385    1.39594   60.97   &lt;2e-16 ***
wait_time_minutes -0.38228    0.02849  -13.42   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.01 on 148 degrees of freedom
Multiple R-squared:  0.5489,    Adjusted R-squared:  0.5458 
F-statistic: 180.1 on 1 and 148 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="the-fitted-regression-equation" class="level3">
<h3 class="anchored" data-anchor-id="the-fitted-regression-equation">The Fitted Regression Equation</h3>
<p>Based on the model output above, we can write our fitted regression equation with the estimated coefficients:</p>
<p><span class="math display">\[\widehat{\text{Satisfaction}} = 85.11 + (-0.382) \times \text{Wait Time}\]</span></p>
<p>Or more generally:</p>
<p><span class="math display">\[\hat{Y}_i = 85.11 + (-0.382) \times X_i\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\hat{Y}_i\)</span> = Predicted patient satisfaction score for patient <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(X_i\)</span> = Wait time in minutes for patient <span class="math inline">\(i\)</span></li>
<li>85.11 = Estimated intercept (<span class="math inline">\(\hat{\beta}_0\)</span>)</li>
<li>-0.382 = Estimated slope (<span class="math inline">\(\hat{\beta}_1\)</span>)</li>
</ul>
</section>
<section id="interpreting-the-results" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-the-results">Interpreting the Results</h3>
<p>Let’s break down the output systematically:</p>
<section id="the-intercept" class="level4">
<h4 class="anchored" data-anchor-id="the-intercept">1. The Intercept</h4>
<p><strong>Value</strong>: β₀ = 85.11</p>
<p><strong>Interpretation</strong>: When wait time is 0 minutes, the predicted patient satisfaction score is 85.11 points. This represents the baseline satisfaction when there is no wait.</p>
<p><em>Note</em>: Intercepts should be interpreted cautiously. If zero falls outside the range of observed X values (e.g., if no patient had a 0-minute wait), the intercept is an extrapolation and may not represent a realistic scenario. Here, a 0-minute wait is plausible, so the interpretation is reasonable.</p>
</section>
<section id="the-slope-regression-coefficient" class="level4">
<h4 class="anchored" data-anchor-id="the-slope-regression-coefficient">2. The Slope (Regression Coefficient)</h4>
<p><strong>Value</strong>: β₁ = -0.382</p>
<p><strong>Interpretation</strong>:</p>
<ol type="1">
<li><p><strong>Direction</strong>: The coefficient is <strong>negative</strong> (-0.382), indicating that longer wait times are associated with <strong>lower</strong> satisfaction scores.</p></li>
<li><p><strong>Magnitude</strong>: For every <strong>one-minute increase</strong> in wait time, patient satisfaction decreases by <strong>0.382 points</strong> (on the 0-100 scale).</p></li>
<li><p><strong>Statistical Significance</strong>: In regression, the null and alternative hypotheses for each coefficient are:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1 = 0\)</span> (no linear relationship between X and Y)</li>
<li><span class="math inline">\(H_1\)</span>: <span class="math inline">\(\beta_1 \neq 0\)</span> (a linear relationship between X and Y)</li>
</ul>
<p>The p-value is &lt; 2.2e-16, which is less than 0.05. We <strong>reject the null hypothesis</strong> (there is a linear relationship between X and Y).</p></li>
</ol>
</section>
<section id="model-fit-r-squared" class="level4">
<h4 class="anchored" data-anchor-id="model-fit-r-squared">3. Model Fit (R-squared)</h4>
<p><strong>R² = 0.549</strong></p>
<p>R² indicates the amount of the variance in the outcome variable explained by the model. In this case, wait time explains <strong>54.9%</strong> of the variance in patient satisfaction scores. The remaining 45.1% is attributable to other factors not included in this model (e.g., staff friendliness, treatment effectiveness, facility cleanliness).</p>
<p>To understand R² visually, let’s see how the regression model explains more variance compared to simply using the mean:</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-rsquared-concept" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rsquared-concept-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lecture11_files/figure-html/fig-rsquared-concept-1.png" class="img-fluid figure-img" width="960">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rsquared-concept-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: R² measures how much variance is explained by the regression model
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>Left plot</strong>: Without any predictors, we’d predict every patient’s satisfaction as the mean (dark green line). The purple lines show how far each observation deviates from this mean. This is the <strong>total variance (TSS)</strong> we want to explain.</p></li>
<li><p><strong>Right plot</strong>: With wait time as a predictor, the regression line (blue) does a better job. The red dashed lines show the remaining errors (residuals). This is the <strong>residual variance (RSS)</strong> left unexplained.</p></li>
<li><p><strong>R² = 1 - (RSS/TSS)</strong> = The proportion of total variance that our model explains. An R² of 0.549 means the regression model explains 54.9% of the variance in patient satisfaction compared to just using the mean.</p></li>
</ul>
</section>
</section>
<section id="making-predictions" class="level3">
<h3 class="anchored" data-anchor-id="making-predictions">Making Predictions</h3>
<p>One powerful application of regression is predicting outcomes for new observations. Let’s assume that we have new patients and their waiting times.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict satisfaction for specific wait times </span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># New data need to be data frame or a list</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>new_patients <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">wait_time_minutes =</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">30</span>, <span class="dv">45</span>, <span class="dv">60</span>, <span class="dv">90</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(new_patients)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  wait_time_minutes
1                15
2                30
3                45
4                60
5                90</code></pre>
</div>
</div>
<p>By using the <code>predict()</code> function we can get predicted satisfaction scores for these new patients based on their wait times.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get predicted satisfaction scores</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>new_patients<span class="sc">$</span>predicted_score <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_simple, <span class="at">newdata =</span> new_patients)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>new_patients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  wait_time_minutes predicted_score
1                15        79.37971
2                30        73.64557
3                45        67.91144
4                60        62.17730
5                90        50.70902</code></pre>
</div>
</div>
<section id="manual-calculation-example" class="level4">
<h4 class="anchored" data-anchor-id="manual-calculation-example">Manual Calculation Example</h4>
<p>Let’s manually calculate one prediction to understand what the <code>predict()</code> function is doing. We’ll predict satisfaction for a patient with a <strong>45-minute wait time</strong>.</p>
<p><strong>Step 1: Recall the fitted equation</strong></p>
<p><span class="math display">\[\widehat{\text{Satisfaction}} = 85.11 + (-0.382) \times \text{Wait Time}\]</span></p>
<p><strong>Step 2: Substitute and calculate</strong></p>
<p>For Wait Time = 45 minutes:</p>
<p><span class="math display">\[\widehat{\text{Satisfaction}} = 85.11 + (-0.382) \times 45 = 67.91\]</span></p>
<p>The predicted satisfaction score for a patient with a 45-minute wait is <strong>67.91</strong> points. You can verify this matches the value in the prediction table above!</p>
</section>
<section id="practical-application" class="level4">
<h4 class="anchored" data-anchor-id="practical-application">Practical Application</h4>
<p>If your ED currently has an average wait time of 60 minutes and you implement process improvements to reduce it to 30 minutes, the model predicts satisfaction would increase by approximately 11.46 points. Since each additional minute of wait time decreases satisfaction by 0.382 points, a 30-minute reduction corresponds to a meaningful improvement in patient experience.</p>
</section>
</section>
<section id="practice-1-simple-linear-regression" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="practice-1-simple-linear-regression">Practice 1: Simple Linear Regression</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Your Turn!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Practice fitting and interpreting simple linear regression models on your own using a different healthcare scenario.</p>
</div>
</div>
</section>
<section id="scenario" class="level3">
<h3 class="anchored" data-anchor-id="scenario">Scenario</h3>
<p>You are analyzing the relationship between <strong>nurse staffing levels</strong> and <strong>patient mortality rates</strong> across 100 hospitals. Hospital administrators want to know <strong>whether having more nurses per patient reduces mortality rates</strong>.</p>
<p>This question has important implications for staffing policies and patient safety. If the data show that higher nurse-to-patient ratios are associated with lower mortality, hospital administrators could use the regression results to justify hiring additional nursing staff, estimate how much mortality might decrease with a specific staffing increase, and make evidence-based budget decisions that balance costs against patient outcomes.</p>
</section>
<section id="data-loading" class="level3">
<h3 class="anchored" data-anchor-id="data-loading">Data Loading</h3>
<p>Run this code to load the dataset:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading dataset</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>simple_practice_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week11_practice_data1.csv"</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview data</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(simple_practice_data, <span class="dv">5</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X hospital_id nurses_per_patient mortality_rate
1 1           1               1.99          10.10
2 2           2               2.46           6.51
3 3           3               1.95          11.13
4 4           4               2.69           6.06
5 5           5               1.33           7.15</code></pre>
</div>
</div>
<p><strong>Dataset Variables:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>hospital_id</code></td>
<td>Unique hospital identifier</td>
<td>Numeric</td>
</tr>
<tr class="even">
<td><code>nurses_per_patient</code></td>
<td>Ratio of nurses to patients (higher = better staffing)</td>
<td>Numeric (continuous)</td>
</tr>
<tr class="odd">
<td><code>mortality_rate</code></td>
<td>Hospital mortality rate (deaths per 100 patients)</td>
<td>Numeric (continuous)</td>
</tr>
</tbody>
</table>
</section>
<section id="task-1.1-visualize-the-relationship" class="level3">
<h3 class="anchored" data-anchor-id="task-1.1-visualize-the-relationship">Task 1.1: Visualize the Relationship</h3>
<p>Before fitting a model, create a scatterplot to visualize the relationship between nurse staffing and mortality rates.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill in the blanks</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ___, <span class="fu">aes</span>(<span class="at">x =</span> ___, <span class="at">y =</span> ___)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"___"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"darkred"</span>) <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Nurse Staffing vs. Mortality Rate"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Nurses per Patient"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Mortality Rate (%)"</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Question</strong>: Based on the scatterplot, do you expect a positive or negative relationship? Why?</p>
</section>
<section id="task-1.2-fit-the-simple-linear-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="task-1.2-fit-the-simple-linear-regression-model">Task 1.2: Fit the Simple Linear Regression Model</h3>
<p>Now fit a simple linear regression model predicting <code>mortality_rate</code> from <code>nurses_per_patient</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill in the blanks</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>model_simple_practice <span class="ot">&lt;-</span> <span class="fu">lm</span>(___ <span class="sc">~</span> ___, <span class="at">data =</span> ___)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the summary</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(___)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions:</strong></p>
<ol type="1">
<li>What is the <strong>intercept</strong>? What does it represent in this context?</li>
<li>What is the <strong>slope</strong> coefficient for <code>nurses_per_patient</code>?
<ul>
<li><strong>Direction</strong>: Is it positive or negative? What does this mean?</li>
<li><strong>Magnitude</strong>: If a hospital increases staffing by 1 nurse per patient, how much does mortality rate change?</li>
<li><strong>Significance</strong>: Is the p-value less than 0.05?</li>
</ul></li>
<li>What is the <strong>R²</strong> value? What percentage of variance in mortality rates is explained by nurse staffing?</li>
</ol>
</section>
<section id="task-1.3-make-predictions" class="level3">
<h3 class="anchored" data-anchor-id="task-1.3-make-predictions">Task 1.3: Make Predictions</h3>
<p>Use your fitted model to predict mortality rates for hospitals with different staffing levels.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create new data for prediction (fill in the blank)</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>new_hospitals <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">nurses_per_patient =</span> <span class="fu">c</span>(<span class="fl">1.0</span>, <span class="fl">1.5</span>, <span class="fl">2.0</span>, <span class="fl">2.5</span>, <span class="fl">3.0</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions (fill in the blank)</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>new_hospitals<span class="sc">$</span>predicted_mortality <span class="ot">=</span> <span class="fu">predict</span>(___, <span class="at">newdata =</span> ___)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>new_hospitals</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Question</strong>: A hospital currently has 1.5 nurses per patient and wants to reduce mortality. If they increase staffing to 2.5 nurses per patient, how much would you expect mortality to decrease?</p>
<hr>
</section>
</section>
</section>
<section id="multiple-linear-regression" class="level1">
<h1>Multiple Linear Regression</h1>
<p>Now that we’ve seen how to model the relationship between a single predictor and an outcome, the next question we would have is <em>What happens when multiple factors influence the outcome simultaneously?</em> In healthcare, outcomes are rarely driven by a single variable. Patient satisfaction depends on more than just wait time, and length of stay depends on more than just age. Multiple linear regression addresses this reality.</p>
<section id="what-is-it-1" class="level2">
<h2 class="anchored" data-anchor-id="what-is-it-1">What is it?</h2>
<p>Multiple linear regression extends simple regression to model the relationship between <strong>multiple independent variables</strong> and <strong>one dependent variable</strong>. It allows us to examine how several predictors <strong><em>simultaneously</em></strong> influence an outcome.</p>
</section>
<section id="when-to-use-it-1" class="level2">
<h2 class="anchored" data-anchor-id="when-to-use-it-1">When to Use It</h2>
<p>Use multiple linear regression when you need to:</p>
<ul>
<li>Include <strong>multiple predictors</strong> to better explain variance in an outcome</li>
<li><strong>Control for confounding variables</strong> when examining specific relationships</li>
<li>Compare <strong>the relative importance</strong> of different factors</li>
<li>Make predictions based on multiple characteristics simultaneously</li>
</ul>
</section>
<section id="extending-to-multiple-predictors" class="level2">
<h2 class="anchored" data-anchor-id="extending-to-multiple-predictors">Extending to Multiple Predictors</h2>
<section id="the-model-equation-1" class="level3">
<h3 class="anchored" data-anchor-id="the-model-equation-1">The Model Equation</h3>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \cdots + \beta_k X_{ki} + \epsilon_i\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> = Intercept</li>
<li><span class="math inline">\(\beta_1, \beta_2, \ldots, \beta_k\)</span> = Regression coefficients for each predictor</li>
<li><span class="math inline">\(X_{1i}, X_{2i}, \ldots, X_{ki}\)</span> = Values of predictors for observation <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(\epsilon_i\)</span> = Residual</li>
</ul>
<p>In multiple regression, each coefficient represents the effect of that variable <strong>holding all other variables constant</strong> (also called the “partial” or “conditional” effect).</p>
</section>
</section>
<section id="an-example-case-hospital-length-of-stay" class="level2">
<h2 class="anchored" data-anchor-id="an-example-case-hospital-length-of-stay">An Example Case: Hospital Length of Stay</h2>
<section id="background-and-context-1" class="level3">
<h3 class="anchored" data-anchor-id="background-and-context-1">Background and Context</h3>
<p>A 2022 systematic review identified age, comorbidities, and severity as the most frequently cited predictors of hospital length of stay across 15 studies. Understanding these factors is crucial for healthcare operations and resource planning.</p>
<p>Let’s predict hospital length of stay (LOS) based on three key patient characteristics using synthetic data that reflects these evidence-based relationships:</p>
<ol type="1">
<li><strong>Age</strong> - Patient age in years</li>
<li><strong>Severity Score</strong> - Illness severity on a 1-10 scale</li>
<li><strong>Number of Comorbidities</strong> - Count of concurrent chronic conditions</li>
</ol>
</section>
<section id="loading-the-dataset-1" class="level3">
<h3 class="anchored" data-anchor-id="loading-the-dataset-1">Loading the Dataset</h3>
<p>Let’s load the dataset using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading the dataset</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>hospital_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week11_hospital_data.csv"</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hospital_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X patient_id age severity_score num_comorbidities length_of_stay
1 1          1  64            7.1                 2           11.9
2 2          2  75            5.6                 1            7.9
3 3          3  61            5.9                 1            8.3
4 4          4  56            1.6                 1            5.8
5 5          5  83            6.7                 1           10.8</code></pre>
</div>
</div>
</section>
<section id="exploratory-data-analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="exploratory-data-analysis-1">Exploratory Data Analysis</h3>
<p>Before fitting the model, let’s visually explore the distributions of our variables and their pairwise relationships.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairs plot for continuous variables</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># To use ggpairs(), you need to install the GGally package.</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="co"># wrap() customizes what each section of the matrix displays:</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   "smooth"     = scatterplot with a trend line</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co">#   "cor"        = correlation coefficient (numeric summary)</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co">#   "densityDiag" = density curve (distribution shape)</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>hospital_data <span class="sc">%&gt;%</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(age, severity_score, num_comorbidities, length_of_stay) <span class="sc">%&gt;%</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggpairs</span>(</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">lower =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"smooth"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">linewidth =</span> <span class="fl">0.5</span>)),</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">upper =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"cor"</span>, <span class="at">size =</span> <span class="dv">3</span>)),</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">diag =</span> <span class="fu">list</span>(<span class="at">continuous =</span> <span class="fu">wrap</span>(<span class="st">"densityDiag"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>))</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-eda-multiple" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eda-multiple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lecture11_files/figure-html/fig-eda-multiple-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-eda-multiple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Pairwise relationships between predictors and length of stay
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="fitting-the-multiple-linear-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="fitting-the-multiple-linear-regression-model">Fitting the Multiple Linear Regression Model</h3>
<p>Let’s fit the linear model. Same as simple linear regression, we can use the <code>lm()</code> function in R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit multiple regression model</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>model_multiple <span class="ot">&lt;-</span> <span class="fu">lm</span>(length_of_stay <span class="sc">~</span> age <span class="sc">+</span> severity_score <span class="sc">+</span> num_comorbidities,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> hospital_data)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Display summary</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_multiple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length_of_stay ~ age + severity_score + num_comorbidities, 
    data = hospital_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.5147 -0.9968  0.0364  1.1500  3.6581 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       1.312040   0.376488   3.485 0.000567 ***
age               0.040739   0.005269   7.732 1.67e-13 ***
severity_score    0.623629   0.033959  18.364  &lt; 2e-16 ***
num_comorbidities 0.793316   0.064185  12.360  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.556 on 296 degrees of freedom
Multiple R-squared:  0.6482,    Adjusted R-squared:  0.6446 
F-statistic: 181.8 on 3 and 296 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="interpreting-the-results-1" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-the-results-1">Interpreting the Results</h3>
<p>Each coefficient represents the effect of that variable <strong>while holding all other variables constant</strong>.</p>
<ol type="1">
<li><p><strong>Intercept (β₀ = 1.31)</strong>: The predicted length of stay for a patient who is 0 years old, has a severity score of 0, and has 0 comorbidities. This value is not practically meaningful but is mathematically necessary.</p></li>
<li><p><strong>Age (β₁ = 0.041)</strong>: Holding severity and comorbidities constant, each additional year of age is associated with a <strong>0.041-day increase</strong> in length of stay.</p></li>
<li><p><strong>Severity Score (β₂ = 0.624)</strong>: Holding age and comorbidities constant, each one-point increase in severity score is associated with a <strong>0.62-day increase</strong> in length of stay.</p></li>
<li><p><strong>Number of Comorbidities (β₃ = 0.793)</strong>: Holding age and severity constant, each additional comorbidity is associated with a <strong>0.79-day increase</strong> in length of stay.</p></li>
</ol>
<section id="model-fit-r²-and-adjusted-r²" class="level4">
<h4 class="anchored" data-anchor-id="model-fit-r²-and-adjusted-r²">Model Fit (R² and Adjusted R²)</h4>
<p>From the <code>summary()</code> output above:</p>
<ul>
<li><strong>R² = 0.648</strong>: 64.8% of variance in LOS is explained by the model</li>
<li><strong>Adjusted R² = 0.645</strong>: Adjusted R² penalizes for the number of predictors and is preferred when comparing models with different numbers of variables</li>
</ul>
<p><strong>Why Adjusted R²?</strong> Regular R² can only increase (or stay the same) when you add more predictors, even if those predictors have no real relationship with the outcome. Adjusted R² penalizes for the number of predictors, so it only increases if a new predictor significantly improves the model. This makes it a fairer metric for comparing models with different numbers of variables.</p>
</section>
</section>
<section id="practical-application-predicting-los" class="level3">
<h3 class="anchored" data-anchor-id="practical-application-predicting-los">Practical Application: Predicting LOS</h3>
<p>Now let’s use our fitted model to predict length of stay for different patient profiles. This demonstrates how the model can support clinical decision-making and resource planning. Let’s assume that we have several new patients and their characteristics as below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create example patients with different characteristics</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>example_patients <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">c</span>(<span class="dv">35</span>, <span class="dv">75</span>, <span class="dv">50</span>, <span class="dv">80</span>),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">severity_score =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">8</span>, <span class="dv">7</span>),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">num_comorbidities =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>example_patients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  age severity_score num_comorbidities
1  35              2                 0
2  75              5                 2
3  50              8                 3
4  80              7                 5</code></pre>
</div>
</div>
<p>Let’s get the predicted LOS. We can do this using the <code>predict()</code> function in R.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>example_patients<span class="sc">$</span>predicted_los <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_multiple, <span class="at">newdata =</span> example_patients)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>example_patients </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  age severity_score num_comorbidities predicted_los
1  35              2                 0      3.985179
2  75              5                 2      9.072276
3  50              8                 3     10.717993
4  80              7                 5     12.903179</code></pre>
</div>
</div>
<section id="manual-calculation-example-1" class="level4">
<h4 class="anchored" data-anchor-id="manual-calculation-example-1">Manual Calculation Example</h4>
<p>Let’s manually calculate one prediction to understand how multiple regression works. We’ll predict LOS for the <strong>second patient</strong> in the table above (Age = 75, Severity = 5, Comorbidities = 2).</p>
<p><strong>Step 1: Write the fitted regression equation</strong></p>
<p>First, recall our fitted model equation with estimated coefficients:</p>
<p><span class="math display">\[\widehat{\text{LOS}} = 1.31 + 0.041 \times \text{Age} + 0.624 \times \text{Severity} + 0.793 \times \text{Comorbidities}\]</span></p>
<p>Or in general notation:</p>
<p><span class="math display">\[\hat{Y} = \hat{\beta}_0 + \hat{\beta}_1 X_1 + \hat{\beta}_2 X_2 + \hat{\beta}_3 X_3\]</span></p>
<p>Where:</p>
<ul>
<li><span class="math inline">\(\hat{Y}\)</span> = Predicted length of stay</li>
<li><span class="math inline">\(X_1\)</span> = Age (years)</li>
<li><span class="math inline">\(X_2\)</span> = Severity score (1-10)</li>
<li><span class="math inline">\(X_3\)</span> = Number of comorbidities</li>
<li><span class="math inline">\(\hat{\beta}_0\)</span> = 1.31 (Intercept)</li>
<li><span class="math inline">\(\hat{\beta}_1\)</span> = 0.041 (Age coefficient)</li>
<li><span class="math inline">\(\hat{\beta}_2\)</span> = 0.624 (Severity coefficient)</li>
<li><span class="math inline">\(\hat{\beta}_3\)</span> = 0.793 (Comorbidity coefficient)</li>
</ul>
<p><strong>Step 2: Substitute and calculate</strong></p>
<p>For the “Elderly, Moderate” patient (Age = 75, Severity = 5, Comorbidities = 2):</p>
<p><span class="math display">\[\widehat{\text{LOS}} = 1.31 + 0.041 \times 75 + 0.624 \times 5 + 0.793 \times 2 = 9.07\]</span></p>
<p>The predicted length of stay is <strong>9.07 days</strong>. You can verify this matches the value in the prediction result above!</p>
</section>
</section>
<section id="practice-2-multiple-linear-regression" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="practice-2-multiple-linear-regression">Practice 2: Multiple Linear Regression</h3>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Your Turn!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Practice building and interpreting multiple regression models with a new scenario.</p>
</div>
</div>
</section>
<section id="scenario-1" class="level3">
<h3 class="anchored" data-anchor-id="scenario-1">Scenario</h3>
<p>You are now analyzing <strong>patient satisfaction scores</strong> across hospitals. You hypothesize that satisfaction is influenced by multiple factors:</p>
<ul>
<li><strong>Wait time</strong> (minutes): Longer waits → lower satisfaction</li>
<li><strong>Nurse staffing</strong> (nurses per patient): Better staffing → higher satisfaction</li>
<li><strong>Facility age</strong> (years): Older facilities → lower satisfaction</li>
</ul>
<p>Your task is to build a multiple regression model to understand how these factors simultaneously influence patient satisfaction.</p>
</section>
<section id="loading-the-dataset-2" class="level3">
<h3 class="anchored" data-anchor-id="loading-the-dataset-2">Loading the Dataset</h3>
<p>Run this code to load the practice dataset:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading the dataset</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>multiple_practice_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week11_practice_data2.csv"</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview data</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(multiple_practice_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X hospital_id wait_time_min nurse_ratio facility_age_years satisfaction_score
1 1           1            47        3.50                 28               70.0
2 2           2            47        3.36                 37               67.9
3 3           3            36        1.83                 38               66.1
4 4           4            67        3.02                 24               58.9
5 5           5            20        2.42                  9               75.3</code></pre>
</div>
</div>
<p><strong>Dataset Variables:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>hospital_id</code></td>
<td>Unique hospital identifier</td>
<td>Numeric</td>
</tr>
<tr class="even">
<td><code>wait_time_min</code></td>
<td>Average patient wait time (minutes)</td>
<td>Numeric (continuous)</td>
</tr>
<tr class="odd">
<td><code>nurse_ratio</code></td>
<td>Nurses per patient ratio</td>
<td>Numeric (continuous)</td>
</tr>
<tr class="even">
<td><code>facility_age_years</code></td>
<td>Age of hospital building (years)</td>
<td>Numeric (continuous)</td>
</tr>
<tr class="odd">
<td><code>satisfaction_score</code></td>
<td>Average patient satisfaction (0-100 scale)</td>
<td>Numeric (continuous)</td>
</tr>
</tbody>
</table>
</section>
<section id="task-2.1-fit-the-multiple-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="task-2.1-fit-the-multiple-regression-model">Task 2.1: Fit the Multiple Regression Model</h3>
<p>Fit a multiple regression model predicting <code>satisfaction_score</code> from all three predictors: <code>wait_time_min</code>, <code>nurse_ratio</code>, and <code>facility_age_years</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill in the blanks</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>model_multiple_practice <span class="ot">&lt;-</span> <span class="fu">lm</span>(___ <span class="sc">~</span> ___ <span class="sc">+</span> ___ <span class="sc">+</span> ___, <span class="at">data =</span> ___)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the summary</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(___)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions:</strong></p>
<ol type="1">
<li><p>What is the coefficient for <strong>wait_time_min</strong>? Holding nurse ratio and facility age constant, what happens to satisfaction when wait time increases by 1 minute? Is this effect statistically significant (p &lt; 0.05)?</p></li>
<li><p>What is the coefficient for <strong>nurse_ratio</strong>? Holding wait time and facility age constant, what happens to satisfaction when nurse staffing increases by 1 nurse per patient? Is this effect statistically significant?</p></li>
<li><p>What is the coefficient for <strong>facility_age_years</strong>? Holding wait time and nurse ratio constant, what happens to satisfaction for each additional year of facility age? Is this effect statistically significant?</p></li>
</ol>
</section>
<section id="task-2.2-compare-model-fit" class="level3">
<h3 class="anchored" data-anchor-id="task-2.2-compare-model-fit">Task 2.2: Compare Model Fit</h3>
<p>Compare the multiple regression model to a simple regression model that only includes <code>wait_time_min</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit simple model with only wait time (fill in the blank)</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>model_simple_wait <span class="ot">&lt;-</span> <span class="fu">lm</span>(___ <span class="sc">~</span> ___, <span class="at">data =</span> multiple_practice_data)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare R-squared values</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Simple model R²:"</span>, <span class="fu">round</span>(<span class="fu">summary</span>(___)<span class="sc">$</span>r.squared, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Multiple model R²:"</span>, <span class="fu">round</span>(<span class="fu">summary</span>(___)<span class="sc">$</span>r.squared, <span class="dv">3</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Question</strong>: How much additional variance is explained by adding nurse ratio and facility age to the model? Is the multiple regression model better?</p>
</section>
<section id="task-2.3-make-predictions" class="level3">
<h3 class="anchored" data-anchor-id="task-2.3-make-predictions">Task 2.3: Make Predictions</h3>
<p>Use your multiple regression model to predict satisfaction for two different hospital scenarios.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create new hospital new_hospitals_multi (fill in the blanks)</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>new_hospitals_multi <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">wait_time_min =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">70</span>),         <span class="co"># Short vs. long wait</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">nurse_ratio =</span> <span class="fu">c</span>(<span class="fl">3.5</span>, <span class="fl">1.8</span>),         <span class="co"># High vs. low staffing</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">facility_age_years =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">35</span>)      <span class="co"># New vs. old facility</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions (fill in the blank)</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>new_hospitals_multi<span class="sc">$</span>predicted_satisfaction <span class="ot">&lt;-</span> <span class="fu">predict</span>(___, <span class="at">newdata =</span> ___)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>new_hospitals_multi</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Question</strong>: What is the difference in predicted satisfaction between the best-case and worst-case scenarios? What does this tell you about the combined impact of these factors?</p>
<hr>
</section>
</section>
</section>
<section id="model-assumptions-and-diagnostics" class="level1">
<h1>Model Assumptions and Diagnostics</h1>
<section id="key-assumptions-of-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="key-assumptions-of-linear-regression">Key Assumptions of Linear Regression</h2>
<p>Linear regression relies on several assumptions. Understanding these assumptions helps ensure valid statistical inference and reliable predictions.</p>
<section id="linearity" class="level3">
<h3 class="anchored" data-anchor-id="linearity">1. Linearity</h3>
<ul>
<li>The relationship between predictor(s) and outcome is linear.</li>
<li>If the true relationship is curved but we fit a straight line, predictions will be systematically biased.</li>
<li>We can visually check by drawing a scatterplot.</li>
<li><strong>If violated</strong>, consider transforming variables (log, square root) or using polynomial terms.</li>
</ul>
</section>
<section id="independence-of-observations" class="level3">
<h3 class="anchored" data-anchor-id="independence-of-observations">2. Independence of Observations</h3>
<ul>
<li>Each observation’s residual is unrelated to others’ residuals.</li>
<li>Correlated errors (e.g., repeated measures, clustered data) underestimate standard errors, making p-values too small.</li>
<li>Know your data structure and study design (longitudinal? clustered?)</li>
<li><strong>If violated</strong>, use mixed models, clustered standard errors, or time-series methods.</li>
</ul>
</section>
<section id="homoscedasticity-equal-variance" class="level3">
<h3 class="anchored" data-anchor-id="homoscedasticity-equal-variance">3. Homoscedasticity (Equal Variance)</h3>
<ul>
<li>Variance of residuals is constant across all fitted values.</li>
<li>Unequal variance (heteroscedasticity) makes standard errors unreliable and confidence intervals inaccurate.</li>
<li>We can visually inspect by drawing a Residuals vs Fitted plot (vertical spread should be roughly equal across x-axis)</li>
<li><strong>If violated</strong>, use robust standard errors or transform Y.</li>
</ul>
</section>
<section id="normality-of-residuals" class="level3">
<h3 class="anchored" data-anchor-id="normality-of-residuals">4. Normality of Residuals</h3>
<ul>
<li>Residuals follow a normal distribution.</li>
<li>Critical for valid p-values and confidence intervals</li>
<li>We can visually inspect using a Q-Q plot (points should follow the diagonal line)</li>
<li><strong>If violated</strong>, consider transforming Y or using robust methods.</li>
</ul>
</section>
<section id="no-perfect-multicollinearity-multiple-regression-only" class="level3">
<h3 class="anchored" data-anchor-id="no-perfect-multicollinearity-multiple-regression-only">5. No (Perfect) Multicollinearity (Multiple Regression Only)</h3>
<ul>
<li>Predictors are not highly correlated with each other.</li>
<li>High correlation between predictors inflates standard errors, making coefficients unstable and hard to interpret.</li>
<li>We can check the Variance Inflation Factor (VIF; VIF &gt; 10 indicates problematic multicollinearity)</li>
<li><strong>If violated</strong>, remove redundant predictors, combine correlated predictors, or use penalized regression (we will cover this later in the semester).</li>
</ul>
<hr>
</section>
<section id="summary-which-plot-checks-which-assumption" class="level3">
<h3 class="anchored" data-anchor-id="summary-which-plot-checks-which-assumption">Summary: Which Plot Checks Which Assumption?</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Assumption</th>
<th>Primary Diagnostic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Linearity</strong></td>
<td>Residuals vs Fitted (look for no pattern)</td>
</tr>
<tr class="even">
<td><strong>Independence</strong></td>
<td>Know your study design</td>
</tr>
<tr class="odd">
<td><strong>Homoscedasticity</strong></td>
<td>Residuals vs Fitted (equal vertical spread)</td>
</tr>
<tr class="even">
<td><strong>Normality</strong></td>
<td>Q-Q plot</td>
</tr>
<tr class="odd">
<td><strong>Multicollinearity</strong></td>
<td>VIF values (not a plot)</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="diagnostic-plots" class="level2">
<h2 class="anchored" data-anchor-id="diagnostic-plots">Diagnostic Plots</h2>
<p>We can draw diagnostic plots by using the <code>plot()</code> function in R.</p>
<ul>
<li><code>which = 1</code>: Residuals vs Fitted</li>
<li><code>which = 2</code>: Q-Q plot</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create diagnostic plots</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))  <span class="co"># 1 row, 2 columns</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_multiple, <span class="at">which =</span> <span class="dv">1</span>) <span class="co"># Residual vs. fitted plot</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_multiple, <span class="at">which =</span> <span class="dv">2</span>) <span class="co"># Q-Q plot</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))  <span class="co"># Reset to default</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-diagnostics" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diagnostics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lecture11_files/figure-html/fig-diagnostics-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagnostics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Regression diagnostic plots
</figcaption>
</figure>
</div>
</div>
</div>
<section id="interpreting-the-two-standard-diagnostic-plots" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-the-two-standard-diagnostic-plots">Interpreting the Two Standard Diagnostic Plots</h3>
<p><strong>Plot 1: Residuals vs Fitted (left)</strong></p>
<ul>
<li><strong>What to look for</strong>: Random scatter around horizontal line at 0</li>
<li><strong>What it checks</strong>: Linearity and homoscedasticity</li>
<li><strong>Good sign</strong>: No pattern, equal spread across x-axis</li>
<li><strong>Red flags</strong>:
<ul>
<li>Curved pattern = non-linearity</li>
<li>Funnel shape = heteroscedasticity</li>
</ul></li>
</ul>
<p><strong>Plot 2: Normal Q-Q (Quantile-Quantile; right)</strong></p>
<ul>
<li>A Q-Q plot compares the distribution of your residuals to a theoretical normal distribution.</li>
<li><strong>What to look for</strong>: Points following the diagonal reference line</li>
<li><strong>What it checks</strong>: Normality of residuals</li>
<li>Points close around the diagonal indicate residuals are normally distributed</li>
</ul>
</section>
</section>
<section id="checking-for-multicollinearity" class="level2">
<h2 class="anchored" data-anchor-id="checking-for-multicollinearity">Checking for Multicollinearity</h2>
<p>Multicollinearity occurs when predictors are highly correlated, which can:</p>
<ul>
<li>Inflate standard errors</li>
<li>Make individual coefficients unstable</li>
<li>Lead to counterintuitive results</li>
</ul>
<section id="variance-inflation-factor-vif" class="level3">
<h3 class="anchored" data-anchor-id="variance-inflation-factor-vif">Variance Inflation Factor (VIF)</h3>
<p>VIF quantifies how much multicollinearity inflates the variance of regression coefficients.</p>
<p><strong>How VIF works</strong>:</p>
<p>For each predictor <span class="math inline">\(X_j\)</span>:</p>
<ol type="1">
<li>Regress <span class="math inline">\(X_j\)</span> on all other predictors</li>
<li>Get <span class="math inline">\(R^2_j\)</span> from that regression (how well other predictors explain <span class="math inline">\(X_j\)</span>)</li>
<li>Calculate: <span class="math inline">\(\text{VIF}_j = \frac{1}{1 - R^2_j}\)</span></li>
</ol>
<ul>
<li><strong>Rule of Thumb</strong>: VIF &gt; 10 (or Tolerance &lt; 0.1) indicates problematic multicollinearity.</li>
</ul>
<p>We can get VIF values by using the <code>vif()</code> function in R (to use it, we first need to load the package <code>car</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate VIF</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>vif_values <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">vif</span>(model_multiple)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>vif_values</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              age    severity_score num_comorbidities 
         1.001982          1.003890          1.002301 </code></pre>
</div>
</div>
<p>As all of them are less than 10, they are not highly correlated with each other.</p>
<hr>
</section>
</section>
</section>
<section id="summary" class="level1">
<h1>Summary</h1>
<section id="key-takeaways" class="level2">
<h2 class="anchored" data-anchor-id="key-takeaways">Key Takeaways</h2>
<section id="simple-vs.-multiple-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="simple-vs.-multiple-linear-regression">Simple vs.&nbsp;Multiple Linear Regression</h3>
<ul>
<li><strong>Simple regression</strong>: Examines how one factor relates to an outcome (“If X increases by 1, how much does Y change?”)</li>
<li><strong>Multiple regression</strong>: Examines how several factors together relate to an outcome, showing each factor’s unique contribution while holding others constant</li>
</ul>
</section>
<section id="how-ols-finds-the-best-line" class="level3">
<h3 class="anchored" data-anchor-id="how-ols-finds-the-best-line">How OLS Finds the Best Line</h3>
<ul>
<li>Ordinary Least Squares (OLS) finds the line that minimizes the sum of squared residuals</li>
<li>“Residuals” = vertical distance between actual data points and the fitted line</li>
</ul>
</section>
<section id="model-fit-r²" class="level3">
<h3 class="anchored" data-anchor-id="model-fit-r²">Model Fit: R²</h3>
<ul>
<li>R² tells you what percentage of variation your model explains</li>
<li>Adjusted R² is better for multiple regression (accounts for number of predictors)</li>
<li>Higher is better, but context matters</li>
</ul>
</section>
<section id="making-predictions-1" class="level3">
<h3 class="anchored" data-anchor-id="making-predictions-1">Making Predictions</h3>
<ul>
<li>Use fitted models to predict outcomes for new situations</li>
<li>Useful for “what-if” scenarios and planning</li>
</ul>
</section>
<section id="interpreting-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-coefficients">Interpreting Coefficients</h3>
<p>Ask three questions for each coefficient:</p>
<ol type="1">
<li><strong>Direction</strong>: Positive or negative relationship?</li>
<li><strong>Magnitude</strong>: How large is the effect practically?</li>
<li><strong>Significance</strong>: Is p &lt; 0.05? (But practical significance matters too!)</li>
</ol>
<p>In multiple regression, coefficients show effects <strong>while controlling for other variables</strong>.</p>
</section>
<section id="multicollinearity" class="level3">
<h3 class="anchored" data-anchor-id="multicollinearity">Multicollinearity</h3>
<ul>
<li>When predictors are highly correlated, coefficients become unstable and can even flip signs</li>
<li><strong>Check</strong>: VIF &gt; 10 indicates problems</li>
<li><strong>Solution</strong>: Remove or combine correlated predictors</li>
</ul>
<hr>
</section>
</section>
</section>
<section id="references-and-further-reading" class="level1">
<h1>References and Further Reading</h1>
<section id="statistical-methods" class="level2">
<h2 class="anchored" data-anchor-id="statistical-methods">Statistical Methods</h2>
<ul>
<li>James, G., Witten, D., Hastie, T., &amp; Tibshirani, R. (2021). <em>An Introduction to Statistical Learning with Applications in R</em> (2nd ed.). Springer.</li>
<li>Fox, J. (2015). <em>Applied Regression Analysis and Generalized Linear Models</em> (3rd ed.). SAGE Publications.</li>
<li>Gelman, A., &amp; Hill, J. (2006). <em>Data Analysis Using Regression and Multilevel/Hierarchical Models</em>. Cambridge University Press.</li>
</ul>
</section>
<section id="healthcare-applications" class="level2">
<h2 class="anchored" data-anchor-id="healthcare-applications">Healthcare Applications</h2>
<p>Examples are motivated by the following:</p>
<ul>
<li><p>Abass, G., Asery, A., Al Badr, A., AlMaghlouth, A., AlOtaiby, S., &amp; Heena, H. (2021). Patient satisfaction with the emergency department services at an academic teaching hospital. <em>Journal of Family Medicine and Primary Care</em>, 10(4), 1718-1725.</p></li>
<li><p>Stone, K., Zwiggelaar, R., Jones, P., &amp; Mac Parthaláin, N. (2022). A systematic review of the prediction of hospital length of stay: Towards a unified framework. <em>PLOS Digital Health</em>, 1(4), e0000017.</p></li>
<li><p>McHugh, M. D., Aiken, L. H., Sloane, D. M., Windsor, C., Douglas, C., &amp; Yates, P. (2021). Effects of nurse-to-patient ratio legislation on nurse staffing and patient mortality, readmissions, and length of stay: a prospective study in a panel of hospitals. <em>The Lancet</em>, 397(10288), 1905-1913.</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>