<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="">
  <meta name="dcterms.date" content="2026-03-25">
  <title>Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026) – Linear Regression 1:   Simple and Multiple Linear Regression</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-65c0fb729604bfe8efe950e5016ef687.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Linear Regression 1: <br> Simple and Multiple Linear Regression</h1>
  <p class="subtitle">Week 11</p>

<div class="quarto-title-authors">
</div>

  <p class="date">2026-03-25</p>
</section>
<section id="learning-goals" class="slide level2 scrollable">
<h2>Learning Goals</h2>
<p>By the end of this lecture, you will be able to:</p>
<ol type="1">
<li class="fragment"><strong>Understand</strong> when linear regression is used and how it works</li>
<li class="fragment"><strong>Fit</strong> simple and multiple linear regression models in R using <code>lm()</code></li>
<li class="fragment"><strong>Interpret</strong> regression coefficients (direction, magnitude, significance)</li>
<li class="fragment"><strong>Make predictions</strong> for new observations using fitted models</li>
<li class="fragment"><strong>Identify</strong> multicollinearity using VIF and understand how to handle it</li>
</ol>
</section>
<section id="from-correlation-to-regression" class="slide level2">
<h2>From Correlation to Regression</h2>
<p>In Week 8, we used correlation to answer:</p>
<ul>
<li><em>“Is there a relationship between nurse staffing hours and patient satisfaction?”</em></li>
</ul>
<div class="fragment">
<p><br> <strong>Linear regression extends this</strong> by answering more actionable questions:</p>
<ul>
<li class="fragment"><em>How many points does satisfaction change for each additional nursing hour?</em></li>
<li class="fragment"><em>If we increase staffing to 8 hours per patient day, what satisfaction score can we expect?</em></li>
<li class="fragment"><em>Among wait time, staffing, and facility age, which factors significantly explain patient satisfaction?</em></li>
</ul>
</div>
</section>
<section id="types-of-linear-regression" class="slide level2">
<h2>Types of Linear Regression</h2>
<p>Linear regression models the linear relationship between independent variables (IV) and a dependent variable (DV):</p>
<ul>
<li>e.g., <em>Are older patients more likely to have longer lengths of stay (LOS)?</em>
<ul>
<li><strong>Dependent variable (Y)</strong>: The outcome we want to predict or explain (LOS)</li>
<li><strong>Independent variable(s) (X)</strong>: The predictor(s) we use to explain Y (age)</li>
</ul></li>
</ul>
<div class="fragment">
<p>The number of independent variables determines the type of regression:</p>
<ul>
<li><strong>Simple Linear Regression</strong>: One predictor → outcome <br> <em>(e.g., Patient age → LOS)</em></li>
<li><strong>Multiple Linear Regression</strong>: Two or more predictors → outcome <br> <em>(e.g., Age + Severity + Insurance → LOS)</em></li>
</ul>
</div>
</section>
<section>
<section id="simple-linear-regression" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Simple Linear Regression</h1>

</section>
<section id="what-is-simple-linear-regression" class="slide level2">
<h2>What Is Simple Linear Regression?</h2>
<p>Simple linear regression models the relationship between <strong>one independent variable (X)</strong> and <strong>one dependent variable (Y)</strong> using a straight line (linear model).</p>
<div class="fragment">
<p><br></p>
<p><strong>When to use it:</strong></p>
<ul>
<li class="fragment">Quantify the strength and direction of a linear relationship between two continuous variables</li>
<li class="fragment">Predict an outcome based on a single predictor</li>
<li class="fragment">Test whether a linear relationship is statistically significant</li>
</ul>
</div>
</section>
<section id="the-model-equation" class="slide level2">
<h2>The Model Equation</h2>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 X_i + \epsilon_i\]</span></p>
<p><br></p>
<ul>
<li><span class="math inline">\(Y_i\)</span> = <strong>Dependent variable</strong>: the outcome we predict (e.g., satisfaction score)</li>
<li><span class="math inline">\(X_i\)</span> = <strong>Independent variable</strong>: the predictor (e.g., wait time)</li>
<li><span class="math inline">\(\beta_0\)</span> = <strong>Intercept (a or b₀)</strong>: predicted Y when X = 0 (The starting point)</li>
<li><span class="math inline">\(\beta_1\)</span> = <strong>Slope (b or b₁)</strong>: change in Y per one-unit increase in X (“How much does Y change?”)</li>
<li><span class="math inline">\(\epsilon_i\)</span> = <strong>Residual</strong>: observed <span class="math inline">\(Y_i\)</span> − predicted <span class="math inline">\(Y_i\)</span> (<span class="math inline">\(\hat{Y}_i\)</span>)</li>
</ul>
</section>
<section id="the-ols-method" class="slide level2">
<h2>The OLS Method</h2>
<p>Linear regression finds the “best” line by minimizing the <strong>residual sum of squares (RSS)</strong>:</p>
<p><span class="math display">\[RSS = \sum_{i=1}^{n} (Y_i - \hat{Y}_i)^2 = \sum_{i=1}^{n} \epsilon_i^2\]</span></p>
<div class="fragment">
<p><br></p>
<p>Let’s take a look at how the OLS method works in simple linear regression.</p>
</div>
</section>
<section id="the-prediction-line" class="slide level2">
<h2>The Prediction Line</h2>

<img data-src="images/image1.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="the-intercept" class="slide level2">
<h2>The Intercept</h2>

<img data-src="images/image2.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="the-slope" class="slide level2">
<h2>The Slope</h2>

<img data-src="images/image3.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="slope-direction" class="slide level2">
<h2>Slope Direction</h2>

<img data-src="images/image4.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="putting-it-all-together" class="slide level2">
<h2>Putting It All Together</h2>

<img data-src="images/image5.png" class="quarto-figure quarto-figure-center r-stretch"></section>
<section id="the-ols-method-visual-summary" class="slide level2">
<h2>The OLS Method — Visual Summary</h2>

<img data-src="images/image6.png" class="quarto-figure quarto-figure-center r-stretch"><p><a href="https://colab.research.google.com/drive/1nG-NqRsae74jqjgqxeFLATML3tD25q5K?usp=sharing" target="_blank">OLS simulation</a></p>
</section>
<section id="interpreting-the-slope-β₁" class="slide level2">
<h2>Interpreting the Slope (β₁)</h2>
<p>Now that we have the best-fit line, <strong>the slope (β₁)</strong> tells us:</p>
<ul>
<li><strong>Direction</strong>:
<ul>
<li>β₁ &gt; 0: positive relationship</li>
<li>β₁ &lt; 0: negative relationship</li>
</ul></li>
<li><strong>Magnitude</strong>: How much Y changes for each one-unit increase in X</li>
<li><strong>Statistical significance</strong>: Whether the relationship likely exists in the population</li>
</ul>
</section>
<section id="using-the-fitted-model-for-predictions" class="slide level2 scrollable">
<h2>Using the Fitted Model for Predictions</h2>
<p>Once OLS estimates <span class="math inline">\(\beta_0\)</span> (intercept) and <span class="math inline">\(\beta_1\)</span> (slope), we can predict outcomes:</p>
<p><span class="math display">\[\hat{Y} = \hat{\beta}_0 + \hat{\beta}_1 X\]</span></p>
<div class="fragment">
<p><br></p>
<p>The “hat” notation (^) indicates <strong>estimated</strong> values from our sample data.</p>
</div>
<div class="fragment">
<p>We use the fitted model to:</p>
<ol type="1">
<li class="fragment"><strong>Assess model fit</strong>: predictions for observations in our dataset</li>
<li class="fragment"><strong>Forecast outcomes</strong>: predictions for new observations</li>
<li class="fragment"><strong>Evaluate “what if” questions</strong>: hypothetical scenarios</li>
</ol>
</div>
</section>
<section id="example-case-ed-wait-time-patient-satisfaction" class="slide level2">
<h2>Example Case: <br> ED Wait Time &amp; Patient Satisfaction</h2>
<p><strong>Background</strong>: Research has consistently shown that ED wait times are negatively associated with patient satisfaction. A 2021 study (Abass et al.) found that being informed about waiting time showed a moderately strong positive correlation with patients’ overall rating.</p>
<div class="fragment">
<p><br></p>
<p>Let’s build a regression model to quantify how much ED wait time impacts patient satisfaction scores, and use it to make predictions.</p>
</div>
</section>
<section id="load-the-data" class="slide level2">
<h2>Load the Data</h2>
<p>Let’s load the required packages and dataset using the code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a aria-hidden="true" tabindex="-1"></a>ed_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week11_ed_data.csv"</span>)</span>
<span id="cb1-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ed_data, <span class="dv">5</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X patient_id wait_time_minutes satisfaction_score
1 1          1                55               63.2
2 2          2                23               78.5
3 3          3                48               73.7
4 4          4                43               71.8
5 5          5                32               76.8</code></pre>
</div>
</div>
</section>
<section id="exploratory-data-analysis" class="slide level2">
<h2>Exploratory Data Analysis</h2>
<p>Before running regression, always visualize your data:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ed_data, <span class="fu">aes</span>(<span class="at">x =</span> wait_time_minutes, <span class="at">y =</span> satisfaction_score)) <span class="sc">+</span></span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb3-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"darkred"</span>, <span class="at">fill =</span> <span class="st">"pink"</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Wait Time (minutes)"</span>,</span>
<span id="cb3-6"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Patient Satisfaction Score (0-100)"</span>,</span>
<span id="cb3-7"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"ED Wait Time vs. Patient Satisfaction"</span></span>
<span id="cb3-8"><a aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb3-9"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Slide11_files/figure-revealjs/fig-eda-simple-1.png" id="fig-eda-simple" width="864" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;1
</p></section>
<section id="fitting-the-simple-linear-regression-model" class="slide level2">
<h2>Fitting the Simple Linear Regression Model</h2>
<p>We use the <code>lm(DV ~ IV, data)</code> function in R:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-hidden="true" tabindex="-1"></a>model_simple <span class="ot">&lt;-</span> <span class="fu">lm</span>(satisfaction_score <span class="sc">~</span> wait_time_minutes, <span class="at">data =</span> ed_data)</span>
<span id="cb4-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_simple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = satisfaction_score ~ wait_time_minutes, data = ed_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-21.2114  -5.0646  -0.5653   4.5972  16.9139 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       85.11385    1.39594   60.97   &lt;2e-16 ***
wait_time_minutes -0.38228    0.02849  -13.42   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.01 on 148 degrees of freedom
Multiple R-squared:  0.5489,    Adjusted R-squared:  0.5458 
F-statistic: 180.1 on 1 and 148 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="the-fitted-regression-equation" class="slide level2">
<h2>The Fitted Regression Equation</h2>
<p>Based on the model output, our fitted equation is:</p>
<p><span class="math display">\[\widehat{\text{Satisfaction}} = 85.11 + (-0.382) \times \text{Wait Time}\]</span></p>
<p><br></p>
<p>OLS found that when β₀ = 85.11 and β₁ = -0.382, the residual sum of squares (RSS) is minimized (i.e., this is the best-fitting line!)</p>
</section>
<section id="interpreting-the-results" class="slide level2">
<h2>Interpreting the Results</h2>
<p><strong>1. The Intercept</strong>: β₀ = 85.11</p>
<ul>
<li>When wait time is 0 minutes, predicted satisfaction is 85.11 points</li>
</ul>
<div class="fragment">
<p><strong>2. The Slope</strong>: β₁ = -0.382</p>
<ul>
<li class="fragment">The effect of wait time on satisfaction score</li>
<li class="fragment"><strong>Direction</strong>: Negative (longer waits -&gt; <strong>lower</strong> satisfaction)</li>
<li class="fragment"><strong>Magnitude</strong>: Each additional minute decreases satisfaction by <strong>0.382 points</strong></li>
<li class="fragment"><strong>Significance</strong>: p = &lt; 2.2e-16 (&lt; 0.05) → <strong>statistically significant</strong></li>
</ul>
</div>
<div class="fragment">
<p><strong>3. R² = 0.549</strong></p>
<ul>
<li>Wait time explains <strong>54.9%</strong> of the variance in satisfaction</li>
</ul>
</div>
</section>
<section id="visualizing-r²" class="slide level2">
<h2>Visualizing R²</h2>

<img data-src="Slide11_files/figure-revealjs/fig-rsquared-concept-1.png" id="fig-rsquared-concept" width="1152" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;2
</p></section>
<section id="making-predictions-by-hand" class="slide level2">
<h2>Making Predictions: By Hand</h2>
<p>Let’s predict satisfaction for a patient with a <strong>45-minute wait</strong>:</p>
<p><strong>Step 1</strong>: Recall the fitted equation</p>
<p><span class="math display">\[\widehat{\text{Satisfaction}} = 85.11 + (-0.382) \times \text{Wait Time}\]</span></p>
<div class="fragment">
<p><strong>Step 2</strong>: Plug in the value (X = 45)</p>
<p><span class="math display">\[\widehat{\text{Satisfaction}} = 85.11 + (-0.382) \times 45\]</span></p>
</div>
<div class="fragment">
<p><strong>Step 3</strong>: Calculate</p>
<p><span class="math display">\[\widehat{\text{Satisfaction}} = 67.91\]</span></p>
<p>The predicted satisfaction score for a patient with a 45-minute wait is <strong>67.91</strong> points.</p>
</div>
</section>
<section id="making-predictions-in-r" class="slide level2">
<h2>Making Predictions: In R</h2>
<p>R makes this easier with the <code>predict()</code> function:</p>
<ul>
<li>Let’s assume that we have 5 new patients and their wait times are 15, 30, 45, 60, and 90 minutes, respectively.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a aria-hidden="true" tabindex="-1"></a>new_patients <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb6-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">wait_time_minutes =</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">30</span>, <span class="dv">45</span>, <span class="dv">60</span>, <span class="dv">90</span>)</span>
<span id="cb6-3"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a aria-hidden="true" tabindex="-1"></a>new_patients<span class="sc">$</span>predicted_score <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_simple, <span class="at">newdata =</span> new_patients)</span>
<span id="cb6-6"><a aria-hidden="true" tabindex="-1"></a>new_patients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  wait_time_minutes predicted_score
1                15        79.37971
2                30        73.64557
3                45        67.91144
4                60        62.17730
5                90        50.70902</code></pre>
</div>
</div>
</section>
<section id="practice-1-simple-linear-regression" class="slide level2">
<h2>Practice 1: Simple Linear Regression</h2>
<p><strong>Scenario</strong>: You are analyzing the relationship between <strong>nurse staffing levels</strong> and <strong>patient mortality rates</strong> across 100 hospitals.</p>
<p><br></p>
<p>The question we want to answer is:</p>
<ul>
<li><em>Does having more nurses per patient reduce mortality rates?</em></li>
<li><em>If so, by how much does mortality change for each additional nurse per patient?</em></li>
</ul>
</section>
<section id="practice-1-load-data" class="slide level2">
<h2>Practice 1: Load Data</h2>
<p>Load the data using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-hidden="true" tabindex="-1"></a>simple_practice_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week11_practice_data1.csv"</span>)</span>
<span id="cb8-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(simple_practice_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X hospital_id nurses_per_patient mortality_rate
1 1           1               1.99          10.10
2 2           2               2.46           6.51
3 3           3               1.95          11.13
4 4           4               2.69           6.06
5 5           5               1.33           7.15</code></pre>
</div>
</div>
</section>
<section id="practice-1-tasks-12" class="slide level2">
<h2>Practice 1: Tasks (1/2)</h2>
<p><strong>Task 1.1</strong>: Visualize the relationship</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> ___, <span class="fu">aes</span>(<span class="at">x =</span> ___, <span class="at">y =</span> ___)) <span class="sc">+</span></span>
<span id="cb10-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"___"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"darkred"</span>) <span class="sc">+</span></span>
<span id="cb10-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Nurse Staffing vs. Mortality Rate"</span>,</span>
<span id="cb10-5"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Nurses per Patient"</span>, <span class="at">y =</span> <span class="st">"Mortality Rate (%)"</span>) <span class="sc">+</span></span>
<span id="cb10-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<p><strong>Task 1.2</strong>: Fit the model and interpret</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-hidden="true" tabindex="-1"></a>model_simple_practice <span class="ot">&lt;-</span> <span class="fu">lm</span>(___ <span class="sc">~</span> ___, <span class="at">data =</span> ___)</span>
<span id="cb11-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(___)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions:</strong> What is the intercept? What is the slope (direction, magnitude, significance)? What is the R²?</p>
</div>
</section>
<section id="practice-1-tasks-22" class="slide level2">
<h2>Practice 1: Tasks (2/2)</h2>
<p><strong>Task 1.3</strong>: Make predictions</p>
<p>Assume that we have 5 new hospitals and their nurse staffing levels are 1.0, 1.5, 2.0, 2.5, and 3.0 nurses per patient, respectively. Predict their mortality rates.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a aria-hidden="true" tabindex="-1"></a>new_hospitals <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb12-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">nurses_per_patient =</span> <span class="fu">c</span>(<span class="fl">1.0</span>, <span class="fl">1.5</span>, <span class="fl">2.0</span>, <span class="fl">2.5</span>, <span class="fl">3.0</span>)</span>
<span id="cb12-3"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a aria-hidden="true" tabindex="-1"></a>new_hospitals<span class="sc">$</span>predicted_mortality <span class="ot">&lt;-</span> <span class="fu">predict</span>(___, <span class="at">newdata =</span> ___)</span>
<span id="cb12-6"><a aria-hidden="true" tabindex="-1"></a>new_hospitals</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section></section>
<section>
<section id="multiple-linear-regression" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Multiple Linear Regression</h1>

</section>
<section id="from-simple-to-multiple-regression" class="slide level2">
<h2>From Simple to Multiple Regression</h2>
<p>Now that we’ve modeled the relationship between a single predictor and an outcome, a natural question arises:</p>
<div class="fragment">
<ul>
<li><em>What happens when multiple factors influence the outcome simultaneously?</em></li>
</ul>
</div>
<div class="fragment">
<p><br></p>
<p>In healthcare, outcomes are rarely driven by a single variable:</p>
<ul>
<li class="fragment">Patient satisfaction depends on more than just wait time</li>
<li class="fragment">Length of stay depends on more than just age</li>
<li class="fragment">Multiple linear regression addresses this reality</li>
</ul>
</div>
</section>
<section id="what-is-multiple-linear-regression" class="slide level2">
<h2>What Is Multiple Linear Regression?</h2>
<p>Multiple linear regression extends simple regression to model the relationship between <strong>multiple independent variables</strong> and <strong>one dependent variable</strong>.</p>
<div class="fragment">
<p><br></p>
<p><strong>When to use it:</strong></p>
<ul>
<li class="fragment">Include multiple predictors to better explain variance in an outcome</li>
<li class="fragment"><strong>Control for confounding variables</strong> when examining specific relationships</li>
<li class="fragment">Make predictions based on multiple characteristics simultaneously</li>
</ul>
</div>
</section>
<section id="the-model-equation-1" class="slide level2">
<h2>The Model Equation</h2>
<p><span class="math display">\[Y_i = \beta_0 + \beta_1 X_{1i} + \beta_2 X_{2i} + \cdots + \beta_k X_{ki} + \epsilon_i\]</span></p>
<div class="fragment">
<p><br></p>
<p><strong>Example</strong>: Predicting patient satisfaction from care quality and wait time:</p>
<p><span class="math display">\[\widehat{\text{Satisfaction}} = \beta_0 + \beta_1 \times \text{Care Quality} + \beta_2 \times \text{Wait Time}\]</span></p>
<ul>
<li><strong>β₁</strong> is the effect of care quality on satisfaction (expected to be <strong>positive</strong>)</li>
<li><strong>β₂</strong> is the effect of wait time on satisfaction (expected to be <strong>negative</strong>)</li>
</ul>
</div>
</section>
<section id="ols-in-multiple-linear-regression" class="slide level2">
<h2>OLS in Multiple Linear Regression</h2>

<img data-src="images/image7.png" class="quarto-figure quarto-figure-center r-stretch"><p><a href="https://colab.research.google.com/drive/1n5ll8aGXbxS3V6Zv0SiqIeM_XQJF9b32?usp=sharing" target="_blank">OLS Simulation</a></p>
</section>
<section id="example-case-hospital-length-of-stay" class="slide level2 scrollable">
<h2>Example Case: Hospital Length of Stay</h2>
<p><strong>Background</strong>: A 2022 systematic review (Stone et al.) identified age, comorbidities, and severity as the most frequently cited predictors of hospital length of stay across 15 studies.</p>
<div class="fragment">
<p><br></p>
<p>Let’s predict hospital LOS based on three key patient characteristics:</p>
<ol type="1">
<li class="fragment"><strong>Age</strong>: Patient age in years</li>
<li class="fragment"><strong>Severity Score</strong>: Illness severity on a 1-10 scale</li>
<li class="fragment"><strong>Number of Comorbidities</strong>: Count of concurrent chronic conditions</li>
</ol>
</div>
</section>
<section id="load-the-data-1" class="slide level2">
<h2>Load the Data</h2>
<p>Let’s load the dataset using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-hidden="true" tabindex="-1"></a>hospital_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week11_hospital_data.csv"</span>)</span>
<span id="cb13-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hospital_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X patient_id age severity_score num_comorbidities length_of_stay
1 1          1  64            7.1                 2           11.9
2 2          2  75            5.6                 1            7.9
3 3          3  61            5.9                 1            8.3
4 4          4  56            1.6                 1            5.8
5 5          5  83            6.7                 1           10.8</code></pre>
</div>
</div>
</section>
<section id="fitting-the-multiple-regression-model" class="slide level2">
<h2>Fitting the Multiple Regression Model</h2>
<p>Just like simple regression, we use the <code>lm()</code> function:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a aria-hidden="true" tabindex="-1"></a>model_multiple <span class="ot">&lt;-</span> <span class="fu">lm</span>(length_of_stay <span class="sc">~</span> age <span class="sc">+</span> severity_score <span class="sc">+</span> num_comorbidities,</span>
<span id="cb15-2"><a aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> hospital_data)</span>
<span id="cb15-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_multiple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length_of_stay ~ age + severity_score + num_comorbidities, 
    data = hospital_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.5147 -0.9968  0.0364  1.1500  3.6581 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       1.312040   0.376488   3.485 0.000567 ***
age               0.040739   0.005269   7.732 1.67e-13 ***
severity_score    0.623629   0.033959  18.364  &lt; 2e-16 ***
num_comorbidities 0.793316   0.064185  12.360  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.556 on 296 degrees of freedom
Multiple R-squared:  0.6482,    Adjusted R-squared:  0.6446 
F-statistic: 181.8 on 3 and 296 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="interpreting-the-coefficients" class="slide level2 scrollable">
<h2>Interpreting the Coefficients</h2>
<p>In multiple linear regression, each coefficient indicates the effect of the predictor <strong>holding all other variables constant</strong>:</p>
<ol type="1">
<li class="fragment"><strong>Intercept (β₀ = 1.31)</strong>: Predicted LOS when all predictors = 0 (not practically meaningful)</li>
<li class="fragment"><strong>Age (β₁ = 0.041)</strong>: Each additional year of age → <strong>0.041-day increase</strong> in LOS</li>
<li class="fragment"><strong>Severity (β₂ = 0.624)</strong>: Each one-point increase → <strong>0.624-day increase</strong> in LOS</li>
<li class="fragment"><strong>Comorbidities (β₃ = 0.793)</strong>: Each additional comorbidity → <strong>0.793-day increase</strong> in LOS</li>
</ol>
</section>
<section id="model-fit-r²-vs.-adjusted-r²" class="slide level2">
<h2>Model Fit: R² vs.&nbsp;Adjusted R²</h2>
<p>From the <code>summary()</code> output above:</p>
<ul>
<li><strong>R² = 0.648</strong>: 64.8% of variance in LOS is explained by the model</li>
<li><strong>Adjusted R² = 0.645</strong>: Adjusted R² penalizes for the number of predictors and is preferred when comparing models with different numbers of variables</li>
</ul>
<div class="fragment">
<p><br></p>
<p><strong>Why Adjusted R²?</strong></p>
<ul>
<li>Regular R² can only increase when you add more predictors, even if they have no real relationship.</li>
<li>Adjusted R² penalizes for the number of predictors. It only increases if a new predictor <strong>genuinely improves</strong> the model.</li>
</ul>
</div>
</section>
<section id="predicting-los-by-hand" class="slide level2">
<h2>Predicting LOS: By Hand</h2>
<p>Let’s predict LOS for a new patient with <strong>Age = 75, Severity = 5, Comorbidities = 2</strong>:</p>
<p><br></p>
<p><strong>Step 1</strong>: Recall the fitted equation</p>
<p><span class="math display">\[\widehat{\text{LOS}} = 1.31 + 0.041 \times \text{Age} + 0.624 \times \text{Severity} + 0.793 \times \text{Comorbidities}\]</span></p>
<div class="fragment">
<p><strong>Step 2</strong>: Plug in the values</p>
<p><span class="math display">\[\widehat{\text{LOS}} = 1.31 + 0.041 \times 75 + 0.624 \times 5 + 0.793 \times 2\]</span></p>
</div>
<div class="fragment">
<p><strong>Step 3</strong>: Calculate</p>
<p><span class="math display">\[\widehat{\text{LOS}} = 9.07 \text{ days}\]</span></p>
</div>
</section>
<section id="predicting-los-in-r" class="slide level2">
<h2>Predicting LOS: In R</h2>
<p>R makes this easier with <code>predict()</code> — let’s predict for multiple patients at once:</p>
<ul>
<li><strong>Patient 1</strong>: Age 35, severity 2, no comorbidities</li>
<li><strong>Patient 2</strong>: Age 75, severity 5, 2 comorbidities</li>
<li><strong>Patient 3</strong>: Age 50, severity 8, 3 comorbidities</li>
<li><strong>Patient 4</strong>: Age 80, severity 7, 5 comorbidities</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a aria-hidden="true" tabindex="-1"></a>example_patients <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb17-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">c</span>(<span class="dv">35</span>, <span class="dv">75</span>, <span class="dv">50</span>, <span class="dv">80</span>),</span>
<span id="cb17-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">severity_score =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">8</span>, <span class="dv">7</span>),</span>
<span id="cb17-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">num_comorbidities =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>)</span>
<span id="cb17-5"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-6"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a aria-hidden="true" tabindex="-1"></a>example_patients<span class="sc">$</span>predicted_los <span class="ot">&lt;-</span> <span class="fu">predict</span>(model_multiple, <span class="at">newdata =</span> example_patients)</span>
<span id="cb17-8"><a aria-hidden="true" tabindex="-1"></a>example_patients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="practice-2-multiple-linear-regression" class="slide level2">
<h2>Practice 2: Multiple Linear Regression</h2>
<p>We are analyzing <strong>patient satisfaction scores</strong> across hospitals, hypothesizing that satisfaction is influenced by <strong>wait time</strong>, <strong>nurse staffing</strong>, and <strong>facility age</strong>.</p>
<p><br></p>
<p>We would like to understand how wait time, nurse staffing, and facility age affect patient satisfaction by building a multiple linear regression model and using it to make predictions.</p>
</section>
<section id="practice-2-load-data" class="slide level2">
<h2>Practice 2: Load Data</h2>
<p>Load the dataset using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-hidden="true" tabindex="-1"></a>multiple_practice_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week11_practice_data2.csv"</span>)</span>
<span id="cb18-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(multiple_practice_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X hospital_id wait_time_min nurse_ratio facility_age_years satisfaction_score
1 1           1            47        3.50                 28               70.0
2 2           2            47        3.36                 37               67.9
3 3           3            36        1.83                 38               66.1
4 4           4            67        3.02                 24               58.9
5 5           5            20        2.42                  9               75.3</code></pre>
</div>
</div>
</section>
<section id="practice-2-tasks-12" class="slide level2">
<h2>Practice 2: Tasks (1/2)</h2>
<p><strong>Task 2.1</strong>: Fit the multiple regression model and interpret the results:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a aria-hidden="true" tabindex="-1"></a>model_multiple_practice <span class="ot">&lt;-</span> <span class="fu">lm</span>(___ <span class="sc">~</span> ___ <span class="sc">+</span> ___ <span class="sc">+</span> ___, <span class="at">data =</span> ___)</span>
<span id="cb20-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(___)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><br></p>
<p><strong>Questions:</strong></p>
<ul>
<li>What is the coefficient for each predictor?</li>
<li>Holding other variables constant, what happens to satisfaction?</li>
<li>Is each effect statistically significant?</li>
</ul>
</section>
<section id="practice-2-tasks-22" class="slide level2">
<h2>Practice 2: Tasks (2/2)</h2>
<p><strong>Task 2.2</strong>: Predict satisfaction for two new hospitals:</p>
<ul>
<li><strong>Hospital A</strong>: 20 min wait time, 3.5 nurse ratio, 5-year-old facility</li>
<li><strong>Hospital B</strong>: 70 min wait time, 1.8 nurse ratio, 35-year-old facility</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a aria-hidden="true" tabindex="-1"></a>new_hospitals_multi <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb21-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">wait_time_min =</span> <span class="fu">c</span>(___, ___),</span>
<span id="cb21-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">nurse_ratio =</span> <span class="fu">c</span>(___, ___),</span>
<span id="cb21-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">facility_age_years =</span> <span class="fu">c</span>(___, ___)</span>
<span id="cb21-5"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-6"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a aria-hidden="true" tabindex="-1"></a>new_hospitals_multi<span class="sc">$</span>predicted_satisfaction <span class="ot">&lt;-</span> <span class="fu">predict</span>(___, <span class="at">newdata =</span> ___)</span>
<span id="cb21-8"><a aria-hidden="true" tabindex="-1"></a>new_hospitals_multi</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="a-puzzling-case" class="slide level2">
<h2>A Puzzling Case</h2>
<p>Can we predict hospital <strong>length of stay (LOS)</strong> from the number of <strong>comorbidities</strong> and <strong>medications</strong> a patient has?</p>
<p>Let’s check this. Load the dataset using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a aria-hidden="true" tabindex="-1"></a>demo_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week11_multicollinearity.csv"</span>)</span>
<span id="cb22-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(demo_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X num_comorbidities num_medications los
1 1                 3              10 4.8
2 2                 3               8 5.5
3 3                 2               6 3.3
4 4                 1               2 5.6
5 5                 3              10 3.7</code></pre>
</div>
</div>
</section>
<section id="lets-fit-three-models" class="slide level2 scrollable">
<h2>Let’s Fit Three Models</h2>
<p>Let’s fit three models and compare:</p>
<ol type="1">
<li>Comorbidities only</li>
<li>Medications only</li>
<li>Both Comorbidities and Medications</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a aria-hidden="true" tabindex="-1"></a>model_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(los <span class="sc">~</span> num_comorbidities, <span class="at">data =</span> demo_data)</span>
<span id="cb24-2"><a aria-hidden="true" tabindex="-1"></a>model_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(los <span class="sc">~</span> num_medications, <span class="at">data =</span> demo_data)</span>
<span id="cb24-3"><a aria-hidden="true" tabindex="-1"></a>model_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(los <span class="sc">~</span> num_comorbidities <span class="sc">+</span> num_medications, <span class="at">data =</span> demo_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="model-comparison" class="slide level2">
<h2>Model Comparison</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top" style="border-collapse:collapse; border:none;">
<caption>Same Predictor, Different Results — Why?</caption>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">&nbsp;</th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Model 1: Comorbidities only</th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Model 2: Medications only</th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-top: double; font-style: normal; font-weight: bold; padding: 0.2cm;">Model 3: Both</th>
</tr>
<tr class="even">
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Predictors</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">p</td>
<td style="text-align: center; border-bottom: 1px solid; font-style: italic; font-weight: normal;">Estimates</td>
<td style="text-align: center;">p</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">(Intercept)</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.84</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">2.92</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">3.23</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Comorbidities</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.90</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">1.71</td>
<td style="text-align: center;"><strong>&lt;0.001</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">Medications</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">0.28</td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;"><strong>&lt;0.001</strong></td>
<td style="text-align: left; padding: 0.2cm; vertical-align: top;">-0.33</td>
<td style="text-align: center;"><strong>0.002</strong></td>
</tr>
<tr class="even">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">Observations</td>
<td colspan="2" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">200</td>
<td colspan="2" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">200</td>
<td colspan="2" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm; border-top: 1px solid;">200</td>
</tr>
<tr class="odd">
<td style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">R<sup>2</sup> / R<sup>2</sup> adjusted</td>
<td colspan="2" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.317 / 0.314</td>
<td colspan="2" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.218 / 0.214</td>
<td colspan="2" style="text-align: left; padding: 0.2cm; vertical-align: top; padding-top: 0.1cm; padding-bottom: 0.1cm;">0.351 / 0.345</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Notice anything strange about the <strong>Medications</strong> coefficient across models?</p>
</section>
<section id="what-happened" class="slide level2">
<h2>What Happened?</h2>
<ul>
<li class="fragment"><strong>Model 2</strong> (medications alone): Significant <strong>positive</strong> effect (+0.28)</li>
<li class="fragment"><strong>Model 3</strong> (both together): Medications coefficient <strong>changes direction</strong> (-0.33)!</li>
<li class="fragment">The same predictor tells a completely different story depending on what else is in the model</li>
</ul>
<div class="fragment">
<p><br></p>
<p><strong>Why?</strong> The two predictors are highly correlated!</p>
</div>
</section>
<section id="this-is-multicollinearity" class="slide level2">
<h2>This Is Multicollinearity</h2>
<p><strong>Multicollinearity</strong> occurs when predictors are highly correlated with each other, making it difficult to separate their individual effects.</p>
<div class="fragment">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/image8.png" class="quarto-figure quarto-figure-center"></p>
</figure>
</div>
</div>
</section>
<section id="how-to-diagnose-vif" class="slide level2">
<h2>How to Diagnose: VIF</h2>
<p>A commonly used metric is the <strong>Variance Inflation Factor (VIF)</strong>:</p>
<p><span class="math display">\[\text{VIF}_j = \frac{1}{1 - R^2_j}\]</span></p>
<p>where <span class="math inline">\(R^2_j\)</span> is the R² from regressing predictor <span class="math inline">\(j\)</span> on all other predictors.</p>
<p><strong>Rule of thumb</strong>: VIF &gt; 10 indicates problematic multicollinearity.</p>
<div class="fragment">
<p>We can get VIF using the <code>vif()</code> function from the <code>car</code> package:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb25-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a aria-hidden="true" tabindex="-1"></a>vif_values <span class="ot">&lt;-</span> <span class="fu">vif</span>(model_3)</span>
<span id="cb25-4"><a aria-hidden="true" tabindex="-1"></a>vif_values</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>num_comorbidities   num_medications 
         8.647367          8.647367 </code></pre>
</div>
</div>
</div>
</section>
<section id="how-to-handle-multicollinearity" class="slide level2">
<h2>How to Handle Multicollinearity</h2>
<p>When VIF is high, you have several options:</p>
<ul>
<li class="fragment"><strong>Keep</strong> the most theoretically important predictor and <strong>remove</strong> the redundant one</li>
<li class="fragment"><strong>Combine</strong> them into a composite measure (e.g., “patient complexity index”)</li>
<li class="fragment"><strong>Check</strong> the correlation matrix <strong>before</strong> modeling to catch it early</li>
</ul>
</section></section>
<section>
<section id="summary" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Summary</h1>

</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<ul>
<li class="fragment"><strong>Simple regression</strong>: How one factor relates to an outcome</li>
<li class="fragment"><strong>Multiple regression</strong>: How several factors <strong>together</strong> relate to an outcome, each factor’s unique contribution <strong>holding others constant</strong></li>
<li class="fragment"><strong>OLS</strong> finds the line that minimizes the sum of squared residuals</li>
<li class="fragment"><strong>R²</strong> tells you what percentage of variation your model explains; in multiple regression, use <strong>Adjusted R²</strong> which penalizes for adding unhelpful predictors</li>
<li class="fragment"><strong>Interpreting coefficients</strong>: ask three questions: Direction? Magnitude? Significant?</li>
<li class="fragment"><strong>Multicollinearity</strong> can completely mislead you about which predictors matter; check VIF</li>
</ul>
</section>
<section id="assignments" class="slide level2">
<h2>Assignments</h2>
<p><strong>Reflection</strong> (Due Sunday, March 29 by 11:59 PM):</p>
<p>Please share your thoughts on today’s lecture:</p>
<ul>
<li>3 interesting things you learned</li>
<li>3 confusing things you’d like clarified</li>
</ul>
</section>
<section id="references" class="slide level2">
<h2>References</h2>
<ul>
<li><p>Abass, G., Asery, A., Al Badr, A., AlMaghlouth, A., AlOtaiby, S., &amp; Heena, H. (2021). Patient satisfaction with the emergency department services at an academic teaching hospital. <em>Journal of Family Medicine and Primary Care</em>, <em>10</em>(4), 1718–1725.</p></li>
<li><p>Stone, K., Zwiggelaar, R., Jones, P., &amp; Mac Sherene, N. (2022). A systematic review of the prediction of hospital length of stay: Towards a unified framework. <em>PLOS Digital Health</em>, <em>1</em>(4), e0000017.</p></li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Week 11 | Linear Regression 1</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>