<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-03-30">

<title>Linear Regression 2: Dummy Variables and Interaction Effects – Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-7b997789b8c97d15811d7b52a81c6dd1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026)</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="../../index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../schedule.html"> 
<span class="menu-text">Schedule</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/mba642-spring-26/mba642-spring-26.github.io/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Linear Regression 2: Dummy Variables and Interaction Effects</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      </a>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#why-this-matters" id="toc-why-this-matters" class="nav-link" data-scroll-target="#why-this-matters">Why This Matters</a></li>
  <li><a href="#what-we-cover-today" id="toc-what-we-cover-today" class="nav-link" data-scroll-target="#what-we-cover-today">What We Cover Today</a></li>
  </ul></li>
  <li><a href="#dummy-variables-indicator-variables" id="toc-dummy-variables-indicator-variables" class="nav-link" data-scroll-target="#dummy-variables-indicator-variables">1. Dummy Variables (Indicator Variables)</a>
  <ul class="collapse">
  <li><a href="#what-is-it" id="toc-what-is-it" class="nav-link" data-scroll-target="#what-is-it">What is it?</a></li>
  <li><a href="#when-to-use-it" id="toc-when-to-use-it" class="nav-link" data-scroll-target="#when-to-use-it">When to Use It</a></li>
  <li><a href="#the-challenge-with-categorical-variables" id="toc-the-challenge-with-categorical-variables" class="nav-link" data-scroll-target="#the-challenge-with-categorical-variables">The Challenge with Categorical Variables</a></li>
  <li><a href="#binary-categorical-variables" id="toc-binary-categorical-variables" class="nav-link" data-scroll-target="#binary-categorical-variables">1.1 Binary Categorical Variables</a>
  <ul class="collapse">
  <li><a href="#dummy-variable-example-case-treatment-protocol-comparison" id="toc-dummy-variable-example-case-treatment-protocol-comparison" class="nav-link" data-scroll-target="#dummy-variable-example-case-treatment-protocol-comparison">Dummy Variable Example Case: Treatment Protocol Comparison</a></li>
  <li><a href="#fitting-the-model" id="toc-fitting-the-model" class="nav-link" data-scroll-target="#fitting-the-model">Fitting the Model</a></li>
  <li><a href="#manual-calculation-with-dummy-variables" id="toc-manual-calculation-with-dummy-variables" class="nav-link" data-scroll-target="#manual-calculation-with-dummy-variables">Manual Calculation with Dummy Variables</a></li>
  </ul></li>
  <li><a href="#multi-level-categorical-variables" id="toc-multi-level-categorical-variables" class="nav-link" data-scroll-target="#multi-level-categorical-variables">1.2 Multi-Level Categorical Variables</a>
  <ul class="collapse">
  <li><a href="#why-k-1-and-not-k" id="toc-why-k-1-and-not-k" class="nav-link" data-scroll-target="#why-k-1-and-not-k">Why k-1 and Not k?</a></li>
  <li><a href="#multi-level-categorical-variables-example-hospital-type-comparison" id="toc-multi-level-categorical-variables-example-hospital-type-comparison" class="nav-link" data-scroll-target="#multi-level-categorical-variables-example-hospital-type-comparison">Multi-Level Categorical Variables Example: Hospital Type Comparison</a></li>
  <li><a href="#fitting-the-model-with-multiple-categories" id="toc-fitting-the-model-with-multiple-categories" class="nav-link" data-scroll-target="#fitting-the-model-with-multiple-categories">Fitting the Model with Multiple Categories</a></li>
  <li><a href="#testing-comparisons-between-non-reference-categories" id="toc-testing-comparisons-between-non-reference-categories" class="nav-link" data-scroll-target="#testing-comparisons-between-non-reference-categories">Testing Comparisons Between Non-Reference Categories</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#interaction-effects" id="toc-interaction-effects" class="nav-link" data-scroll-target="#interaction-effects">2. Interaction Effects</a>
  <ul class="collapse">
  <li><a href="#what-is-it-1" id="toc-what-is-it-1" class="nav-link" data-scroll-target="#what-is-it-1">What is it?</a></li>
  <li><a href="#when-to-use-it-1" id="toc-when-to-use-it-1" class="nav-link" data-scroll-target="#when-to-use-it-1">When to Use It</a></li>
  <li><a href="#why-interactions-matter-in-healthcare" id="toc-why-interactions-matter-in-healthcare" class="nav-link" data-scroll-target="#why-interactions-matter-in-healthcare">Why Interactions Matter in Healthcare</a></li>
  <li><a href="#continuous-categorical-interaction" id="toc-continuous-categorical-interaction" class="nav-link" data-scroll-target="#continuous-categorical-interaction">2.1 Continuous × Categorical Interaction</a>
  <ul class="collapse">
  <li><a href="#example-does-staffing-effect-vary-by-hospital-ownership" id="toc-example-does-staffing-effect-vary-by-hospital-ownership" class="nav-link" data-scroll-target="#example-does-staffing-effect-vary-by-hospital-ownership">Example: Does Staffing Effect Vary by Hospital Ownership?</a></li>
  <li><a href="#visualizing-the-potential-interaction" id="toc-visualizing-the-potential-interaction" class="nav-link" data-scroll-target="#visualizing-the-potential-interaction">Visualizing the Potential Interaction</a></li>
  <li><a href="#fitting-the-interaction-model" id="toc-fitting-the-interaction-model" class="nav-link" data-scroll-target="#fitting-the-interaction-model">Fitting the Interaction Model</a></li>
  <li><a href="#interpreting-the-interaction" id="toc-interpreting-the-interaction" class="nav-link" data-scroll-target="#interpreting-the-interaction">Interpreting the Interaction</a></li>
  </ul></li>
  <li><a href="#categorical-categorical-interaction" id="toc-categorical-categorical-interaction" class="nav-link" data-scroll-target="#categorical-categorical-interaction">2.2 Categorical × Categorical Interaction</a>
  <ul class="collapse">
  <li><a href="#example-does-treatment-effect-vary-by-insurance-type" id="toc-example-does-treatment-effect-vary-by-insurance-type" class="nav-link" data-scroll-target="#example-does-treatment-effect-vary-by-insurance-type">Example: Does Treatment Effect Vary by Insurance Type?</a></li>
  <li><a href="#fitting-the-interaction-model-1" id="toc-fitting-the-interaction-model-1" class="nav-link" data-scroll-target="#fitting-the-interaction-model-1">Fitting the Interaction Model</a></li>
  <li><a href="#understanding-categorical-categorical-interactions" id="toc-understanding-categorical-categorical-interactions" class="nav-link" data-scroll-target="#understanding-categorical-categorical-interactions">Understanding Categorical × Categorical Interactions</a></li>
  </ul></li>
  <li><a href="#continuous-continuous-interaction" id="toc-continuous-continuous-interaction" class="nav-link" data-scroll-target="#continuous-continuous-interaction">2.3 Continuous × Continuous Interaction</a>
  <ul class="collapse">
  <li><a href="#example-does-pt-session-benefit-depend-on-patient-age" id="toc-example-does-pt-session-benefit-depend-on-patient-age" class="nav-link" data-scroll-target="#example-does-pt-session-benefit-depend-on-patient-age">Example: Does PT Session Benefit Depend on Patient Age?</a></li>
  <li><a href="#fitting-the-interaction-model-2" id="toc-fitting-the-interaction-model-2" class="nav-link" data-scroll-target="#fitting-the-interaction-model-2">Fitting the Interaction Model</a></li>
  <li><a href="#interpreting-continuous-continuous-interactions" id="toc-interpreting-continuous-continuous-interactions" class="nav-link" data-scroll-target="#interpreting-continuous-continuous-interactions">Interpreting Continuous × Continuous Interactions</a></li>
  <li><a href="#visualizing-continuous-continuous-interaction" id="toc-visualizing-continuous-continuous-interaction" class="nav-link" data-scroll-target="#visualizing-continuous-continuous-interaction">Visualizing Continuous × Continuous Interaction</a></li>
  </ul></li>
  <li><a href="#practice-dummy-variables-and-interaction-effects" id="toc-practice-dummy-variables-and-interaction-effects" class="nav-link" data-scroll-target="#practice-dummy-variables-and-interaction-effects">Practice: Dummy Variables and Interaction Effects</a>
  <ul class="collapse">
  <li><a href="#scenario" id="toc-scenario" class="nav-link" data-scroll-target="#scenario">Scenario</a></li>
  <li><a href="#data-loading-5" id="toc-data-loading-5" class="nav-link" data-scroll-target="#data-loading-5">Data Loading</a></li>
  <li><a href="#task-1-regression-with-multi-level-dummy-variables" id="toc-task-1-regression-with-multi-level-dummy-variables" class="nav-link" data-scroll-target="#task-1-regression-with-multi-level-dummy-variables">Task 1: Regression with Multi-Level Dummy Variables</a></li>
  <li><a href="#task-2-pairwise-comparisons" id="toc-task-2-pairwise-comparisons" class="nav-link" data-scroll-target="#task-2-pairwise-comparisons">Task 2: Pairwise Comparisons</a></li>
  <li><a href="#task-3-interaction-model" id="toc-task-3-interaction-model" class="nav-link" data-scroll-target="#task-3-interaction-model">Task 3: Interaction Model</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a>
  <ul class="collapse">
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways">Key Takeaways</a></li>
  </ul></li>
  <li><a href="#references-and-further-reading" id="toc-references-and-further-reading" class="nav-link" data-scroll-target="#references-and-further-reading">References and Further Reading</a>
  <ul class="collapse">
  <li><a href="#statistical-methods" id="toc-statistical-methods" class="nav-link" data-scroll-target="#statistical-methods">Statistical Methods</a></li>
  <li><a href="#healthcare-applications" id="toc-healthcare-applications" class="nav-link" data-scroll-target="#healthcare-applications">Healthcare Applications</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Linear Regression 2: Dummy Variables and Interaction Effects</h1>
<p class="subtitle lead">MBA642: Business Analytics in Healthcare Management</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 30, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In Week 11, we used continuous predictors (e.g., wait time, staffing hours, patient severity) to predict outcomes. But many important variables in healthcare are <strong>categorical</strong> (e.g., hospital type, insurance status, treatment protocol, or region). Additionally, the effect of one variable may <strong>depend on the value of another</strong> (interaction effects). For instance, a treatment may work differently for different patient populations.</p>
<p><strong>Dummy variables and interactions extend linear regression</strong> by answering more nuanced questions:</p>
<ul>
<li><em>Do patients in the ERAS (Enhanced Recovery After Surgery) protocol have shorter hospital stays than those in standard care, after controlling for age and severity?</em> (comparing group outcomes)</li>
<li><em>Is the effect of nurse staffing on patient satisfaction different in for-profit vs.&nbsp;non-profit hospitals?</em> (testing conditional effects)</li>
<li><em>Does treatment effectiveness vary by insurance type (if so, by how much)?</em> (quantifying group-specific effects)</li>
</ul>
<section id="why-this-matters" class="level2">
<h2 class="anchored" data-anchor-id="why-this-matters">Why This Matters</h2>
<p>Healthcare managers frequently encounter situations where understanding <strong>group differences</strong> and <strong>conditional effects</strong> is crucial for decision-making. For example:</p>
<ul>
<li><strong>Resource allocation</strong>: Do readmission rates differ across hospital types (teaching vs.&nbsp;community vs.&nbsp;critical access)?</li>
<li><strong>Cost management</strong>: Does an enhanced recovery protocol reduce length of stay compared to standard care?</li>
<li><strong>Quality improvement</strong>: Does the effect of staff training on patient satisfaction depend on hospital ownership type?</li>
</ul>
</section>
<section id="what-we-cover-today" class="level2">
<h2 class="anchored" data-anchor-id="what-we-cover-today">What We Cover Today</h2>
<p>This lecture introduces two extensions to the linear regression framework from Week 11:</p>
<ol type="1">
<li><strong>Dummy Variable Regression</strong>: Including categorical predictors in regression models
<ul>
<li>Binary categories (e.g., ERAS vs.&nbsp;Standard care)</li>
<li>Multi-level categories (e.g., Teaching vs.&nbsp;Community vs.&nbsp;Critical Access hospitals)</li>
</ul></li>
<li><strong>Interaction Effects</strong>: Testing whether the effect of one variable depends on another
<ul>
<li>Continuous × Categorical (e.g., does staffing effect vary by hospital ownership?)</li>
<li>Categorical × Categorical (e.g., does treatment effectiveness vary by insurance type?)</li>
<li>Continuous × Continuous (e.g., does PT session benefit depend on patient age?)</li>
</ul></li>
</ol>
<hr>
</section>
</section>
<section id="dummy-variables-indicator-variables" class="level1">
<h1>1. Dummy Variables (Indicator Variables)</h1>
<section id="what-is-it" class="level2">
<h2 class="anchored" data-anchor-id="what-is-it">What is it?</h2>
<p>Dummy variables (also called indicator variables) allow us to include categorical predictors in regression models, which mathematically require numerical inputs. Each dummy variable uses a simple 0 vs.&nbsp;1 coding to indicate whether an observation belongs to a particular category.</p>
<p>For a categorical variable with <strong>k categories</strong>, we create <strong>k-1 dummy variables</strong>, with one category serving as <strong>the reference group</strong> against which all others are compared.</p>
<p>For example, if we have a variable “Hospital Type” with three categories (Teaching, Community, Critical Access), we would create two dummy variables:</p>
<ul>
<li>Dummy 1: Teaching (1 if Teaching, 0 otherwise)</li>
<li>Dummy 2: Critical Access (1 if Critical Access, 0 otherwise)</li>
</ul>
<p><em>Community hospitals</em> would be the reference category (both dummies = 0).</p>
<p><strong><em>Dummy 1</em></strong> captures the difference between Teaching and Community hospitals (the reference category), while <strong><em>Dummy 2</em></strong> captures the difference between Critical Access and Community hospitals.</p>
</section>
<section id="when-to-use-it" class="level2">
<h2 class="anchored" data-anchor-id="when-to-use-it">When to Use It</h2>
<p>Use dummy variables when you need to:</p>
<ul>
<li>Include categorical predictors in regression (hospital type, insurance status, treatment group)</li>
<li>Compare outcomes across different categories while controlling for other variables</li>
<li>Test whether group differences are statistically significant</li>
<li>Quantify the magnitude of differences between categories</li>
</ul>
</section>
<section id="the-challenge-with-categorical-variables" class="level2">
<h2 class="anchored" data-anchor-id="the-challenge-with-categorical-variables">The Challenge with Categorical Variables</h2>
<p>Regression requires numerical inputs, but categorical variables are not inherently numerical. Simply assigning numbers (1, 2, 3) to categories implies an ordering and equal spacing that usually doesn’t exist.</p>
<p><strong>Solution</strong>: Create <strong>dummy variables</strong> that represent category membership using 0s and 1s.</p>
</section>
<section id="binary-categorical-variables" class="level2">
<h2 class="anchored" data-anchor-id="binary-categorical-variables">1.1 Binary Categorical Variables</h2>
<p>For a variable with <strong>two categories</strong>, we need <strong>one dummy variable</strong>. For example, if we have a categorical variable called Insurance with two categories (Insured and Uninsured), we would create one dummy variable called Insured:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Patient</th>
<th>Insurance Status</th>
<th>Dummy: Insured</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Insured</td>
<td>1</td>
</tr>
<tr class="even">
<td>2</td>
<td>Uninsured</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Insured</td>
<td>1</td>
</tr>
<tr class="even">
<td>4</td>
<td>Uninsured</td>
<td>0</td>
</tr>
</tbody>
</table>
<p>The coefficient on the dummy variable (Insured) represents the difference in the outcome between the two groups (Insured vs.&nbsp;Uninsured).</p>
<section id="dummy-variable-example-case-treatment-protocol-comparison" class="level3">
<h3 class="anchored" data-anchor-id="dummy-variable-example-case-treatment-protocol-comparison">Dummy Variable Example Case: Treatment Protocol Comparison</h3>
<section id="background-and-context" class="level4">
<h4 class="anchored" data-anchor-id="background-and-context">Background and Context</h4>
<p>Traditional surgical recovery involves extended hospital stays, which are costly and can lead to complications.</p>
<p>Enhanced Recovery After Surgery (ERAS) protocols use evidence-based practices to help patients recover faster. These include:</p>
<ul>
<li>Better pain management (using less opioid medication)</li>
<li>Getting patients moving sooner after surgery</li>
<li>Starting normal eating earlier</li>
</ul>
<p>A 2025 study found that ERAS protocols significantly reduce hospital length of stay compared to traditional care, with patients recovering and being discharged substantially earlier.</p>
<p>Let’s compare patient outcomes (length of stay) between standard care and ERAS protocols to quantify the treatment effect using a dummy variable.</p>
</section>
<section id="data-loading" class="level4">
<h4 class="anchored" data-anchor-id="data-loading">Data Loading</h4>
<p>Let’s load the dataset using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Required packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(interactions)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading the dataset</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>surgical_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week12_surgical_data.csv"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the dataset</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(surgical_data, <span class="dv">5</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X patient_id protocol age  bmi surgery_complexity length_of_stay
1 1          1 Standard  77 27.3                  3            9.8
2 2          2 Standard  56 27.1                  3           10.4
3 3          3 Standard  59 23.7                  3            9.3
4 4          4     ERAS  49 32.8                  3            9.6
5 5          5 Standard  74 23.8                  3           11.0</code></pre>
</div>
</div>
<p>The dataset includes 200 surgical patients with the following variables:</p>
<ul>
<li><code>patient_id</code>: Unique identifier for each patient (1 to 200)</li>
<li><code>protocol</code>: Treatment protocol assigned (Standard or ERAS)</li>
<li><code>age</code>: Patient age in years</li>
<li><code>bmi</code>: Body Mass Index (measure of body fat based on height and weight)</li>
<li><code>surgery_complexity</code>: Complexity level of the surgery (1 = Low, 2 = Medium, 3 = High)</li>
<li><code>length_of_stay</code>: Hospital length of stay in days (our outcome variable)</li>
</ul>
<p>The variable <code>protocol</code> is our binary categorical variable (Standard vs.&nbsp;ERAS). We’ll create a dummy variable for ERAS (1 = ERAS, 0 = Standard) to include in our regression model.</p>
<p>We can do this using the <code>factor()</code> function in R, which automatically creates the necessary dummy variable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R automatically creates dummy variables for factors</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>surgical_data <span class="ot">&lt;-</span> surgical_data <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">protocol =</span> <span class="fu">factor</span>(protocol, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Standard"</span>, <span class="st">"ERAS"</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Before fitting the model, let’s visualize the distribution of length of stay by treatment protocol:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(surgical_data, <span class="fu">aes</span>(<span class="at">x =</span> protocol, <span class="at">y =</span> length_of_stay, <span class="at">fill =</span> protocol)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Standard"</span> <span class="ot">=</span> <span class="st">"coral"</span>, <span class="st">"ERAS"</span> <span class="ot">=</span> <span class="st">"steelblue"</span>)) <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Treatment Protocol"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Length of Stay (days)"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Does ERAS Protocol Affect Length of Stay?"</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-protocol-effect" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-protocol-effect-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lecture12_files/figure-html/fig-protocol-effect-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-protocol-effect-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Distribution of length of stay by treatment protocol
</figcaption>
</figure>
</div>
</div>
</div>
<p>The boxplot suggests that ERAS patients tend to have shorter hospital stays. Let’s test this formally with regression.</p>
</section>
</section>
<section id="fitting-the-model" class="level3">
<h3 class="anchored" data-anchor-id="fitting-the-model">Fitting the Model</h3>
<p>We can fit a linear regression model using the <code>lm()</code> function in R. When we include the variable <code>protocol</code> in the model, which is a factor, R automatically creates the dummy variable for us.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>model_protocol <span class="ot">&lt;-</span> <span class="fu">lm</span>(length_of_stay <span class="sc">~</span> protocol <span class="sc">+</span> age <span class="sc">+</span> bmi <span class="sc">+</span> surgery_complexity,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> surgical_data)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_protocol)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length_of_stay ~ protocol + age + bmi + surgery_complexity, 
    data = surgical_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.5721 -0.7067 -0.0943  0.5793  3.4279 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         3.218238   0.587057   5.482 1.29e-07 ***
protocolERAS       -1.788155   0.143425 -12.468  &lt; 2e-16 ***
age                 0.027256   0.006647   4.100 6.05e-05 ***
bmi                 0.047624   0.012879   3.698 0.000283 ***
surgery_complexity  1.496551   0.086916  17.218  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.007 on 195 degrees of freedom
Multiple R-squared:  0.7347,    Adjusted R-squared:  0.7292 
F-statistic:   135 on 4 and 195 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Key Interpretation</strong>:</p>
<ul>
<li><p>The coefficient for <code>protocolERAS</code> is approximately -1.79.</p></li>
<li><p>This means that <strong>patients in the ERAS protocol have a length of stay that is 1.79 days shorter than patients in the Standard protocol, holding age, BMI, and surgery complexity constant.</strong></p></li>
<li><p>The Standard protocol is the <strong>reference category</strong> (omitted from the output). The comparison is made relative to this reference group.</p></li>
</ul>
</section>
<section id="manual-calculation-with-dummy-variables" class="level3">
<h3 class="anchored" data-anchor-id="manual-calculation-with-dummy-variables">Manual Calculation with Dummy Variables</h3>
<p>Let’s manually calculate predicted length of stay to understand how dummy variables work in the regression equation.</p>
<p><strong>Step 1: Recall the fitted equation</strong></p>
<p><span class="math inline">\(\widehat{\text{LOS}} = \beta_0 + \beta_1(\text{ERAS}) + \beta_2(\text{Age}) + \beta_3(\text{BMI}) + \beta_4(\text{Complexity})\)</span></p>
<p>where ERAS is a dummy variable:</p>
<ul>
<li>ERAS = 0 for Standard protocol</li>
<li>ERAS = 1 for ERAS protocol</li>
</ul>
<p><strong>With the fitted coefficients</strong>, this becomes:</p>
<p><span class="math inline">\(\widehat{\text{LOS}} = 3.218 + -1.788(\text{ERAS}) + 0.027(\text{Age}) + 0.048(\text{BMI}) + 1.497(\text{Complexity})\)</span></p>
<p><strong>Step 2: Substitute and calculate</strong></p>
<p>For a patient who is 65 years old, has a BMI of 30, and underwent medium complexity surgery (complexity = 2):</p>
<p><strong>Standard protocol</strong> (ERAS = 0):</p>
<p><span class="math display">\[\widehat{\text{LOS}} = 3.218 + -1.788 \times 0 + 0.027 \times 65 + 0.048 \times 30 + 1.497 \times 2 = 9.41 \text{ days}\]</span></p>
<p><strong>ERAS protocol</strong> (ERAS = 1):</p>
<p><span class="math display">\[\widehat{\text{LOS}} = 3.218 + -1.788 \times 1 + 0.027 \times 65 + 0.048 \times 30 + 1.497 \times 2 = 7.62 \text{ days}\]</span></p>
<p>The difference is <strong>-1.79 days</strong>, which is exactly the coefficient for ERAS (-1.79). This confirms that the dummy variable coefficient (<span class="math inline">\(\beta_1\)</span>) represents the difference in predicted outcomes between the two groups, holding all other variables constant.</p>
</section>
</section>
<section id="multi-level-categorical-variables" class="level2">
<h2 class="anchored" data-anchor-id="multi-level-categorical-variables">1.2 Multi-Level Categorical Variables</h2>
<p>When a categorical variable has <strong>more than two levels</strong>, we need <strong>k-1 dummy variables</strong> (where k is the number of categories).</p>
<section id="why-k-1-and-not-k" class="level3">
<h3 class="anchored" data-anchor-id="why-k-1-and-not-k">Why k-1 and Not k?</h3>
<p>Including a dummy for every category would create <strong>perfect multicollinearity</strong> (the dummy variables would sum to 1 for every observation, which is perfectly correlated with the intercept).</p>
</section>
<section id="multi-level-categorical-variables-example-hospital-type-comparison" class="level3">
<h3 class="anchored" data-anchor-id="multi-level-categorical-variables-example-hospital-type-comparison">Multi-Level Categorical Variables Example: Hospital Type Comparison</h3>
<section id="background-and-context-1" class="level4">
<h4 class="anchored" data-anchor-id="background-and-context-1">Background and Context</h4>
<p>Hospitals come in different types:</p>
<ul>
<li><strong>Teaching hospitals</strong>: Large academic medical centers that train medical residents and handle complex cases</li>
<li><strong>Community hospitals</strong>: General hospitals serving local populations</li>
<li><strong>Critical Access hospitals</strong>: Small rural hospitals in remote areas with limited resources</li>
</ul>
<p>A 2017 study examining nearly 4,500 U.S. hospitals found that readmission rates vary by hospital type, reflecting differences in patient complexity, resources, and care patterns.</p>
<p>In this example, we test whether 30-day readmission rates (the percentage of patients who return to the hospital within 30 days) differ across these hospital types.</p>
<p>Let’s compare 30-day readmission rates across three hospital types while controlling for patient characteristics and staffing levels using dummy variables.</p>
</section>
<section id="data-loading-1" class="level4">
<h4 class="anchored" data-anchor-id="data-loading-1">Data Loading</h4>
<p>Let’s load a dataset using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate hospital data</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>hospital_type_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week12_hospital_type_data.csv"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary by hospital type</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hospital_type_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X hospital_id hospital_type bed_count avg_patient_severity nurse_per_patient
1 1           1     Community       160                 2.51              4.11
2 2           2     Community       303                 2.69              2.35
3 3           3     Community        34                 2.24              4.78
4 4           4     Community       316                 1.70              3.82
5 5           5     Community       315                 1.83              3.88
  readmission_rate
1             19.0
2             21.0
3             17.0
4             17.0
5             17.5</code></pre>
</div>
</div>
<p>The dataset includes hospitals with the following variables:</p>
<ul>
<li><code>hospital_id</code>: Unique identifier for each hospital</li>
<li><code>hospital_type</code>: Type of hospital (Community, Teaching, or Critical Access)</li>
<li><code>bed_count</code>: Number of hospital beds</li>
<li><code>avg_patient_severity</code>: Average patient severity score</li>
<li><code>nurse_per_patient</code>: Nurse-to-patient ratio</li>
<li><code>readmission_rate</code>: 30-day readmission rate (our outcome variable)</li>
</ul>
<p>Before fitting the model, let’s visualize how readmission rates differ across hospital types:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hospital_type_data, <span class="fu">aes</span>(<span class="at">x =</span> hospital_type, <span class="at">y =</span> readmission_rate, <span class="at">fill =</span> hospital_type)) <span class="sc">+</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Hospital Type"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"30-Day Readmission Rate (%)"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Do Readmission Rates Differ by Hospital Type?"</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-hospital-type-explore" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hospital-type-explore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lecture12_files/figure-html/fig-hospital-type-explore-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hospital-type-explore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Distribution of readmission rates by hospital type
</figcaption>
</figure>
</div>
</div>
</div>
<p>The boxplot suggests differences in readmission rates across hospital types. Let’s use regression to test these differences formally while controlling for patient severity and staffing.</p>
</section>
</section>
<section id="fitting-the-model-with-multiple-categories" class="level3">
<h3 class="anchored" data-anchor-id="fitting-the-model-with-multiple-categories">Fitting the Model with Multiple Categories</h3>
<p>Before fitting the model, let’s make the variable <code>hospital_type</code> as a factor with “Community” as the reference category using the <code>factor()</code> function. We will put “Community” first in the <code>levels</code> argument to ensure it is the reference category.</p>
<p>This will create two dummy variables:</p>
<ul>
<li><code>hospital_typeTeaching</code>: 1 if the hospital is a teaching hospital, 0 otherwise</li>
<li><code>hospital_typeCritical Access</code>: 1 if the hospital is a critical access hospital, 0 otherwise</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>hospital_type_data <span class="ot">&lt;-</span> hospital_type_data <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">hospital_type =</span> <span class="fu">factor</span>(hospital_type, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Community"</span>, <span class="st">"Teaching"</span>, <span class="st">"Critical Access"</span>))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We can fit a linear regression model using the <code>lm()</code> function in R. When we include the variable <code>hospital_type</code> in the model, which is a factor, R automatically creates the dummy variables for us.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>model_hospital <span class="ot">&lt;-</span> <span class="fu">lm</span>(readmission_rate <span class="sc">~</span> hospital_type <span class="sc">+</span> avg_patient_severity <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                     nurse_per_patient, <span class="at">data =</span> hospital_type_data)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_hospital)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = readmission_rate ~ hospital_type + avg_patient_severity + 
    nurse_per_patient, data = hospital_type_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.3053 -1.2590  0.0879  1.3945  5.0647 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   15.5766     0.6934  22.466  &lt; 2e-16 ***
hospital_typeTeaching         -2.3559     0.2942  -8.009 4.68e-14 ***
hospital_typeCritical Access   3.2578     0.2999  10.864  &lt; 2e-16 ***
avg_patient_severity           2.2348     0.2180  10.251  &lt; 2e-16 ***
nurse_per_patient             -0.8597     0.1589  -5.411 1.49e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.909 on 245 degrees of freedom
Multiple R-squared:  0.6199,    Adjusted R-squared:  0.6137 
F-statistic: 99.88 on 4 and 245 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><strong>Interpretation</strong>:</p>
<ul>
<li><strong>Reference Category</strong>: Community hospitals (omitted from output)</li>
<li><strong>Teaching Hospitals</strong>: Readmission rate of Teaching Hospitals is 2.356 <strong>percentage points lower</strong> than Community hospitals (β = -2.356)</li>
<li><strong>Critical Access Hospitals</strong>: Readmission rate of Critical Access Hospitals is 3.258 <strong>percentage points higher</strong> than Community hospitals (β = 3.258)</li>
</ul>
</section>
<section id="testing-comparisons-between-non-reference-categories" class="level3">
<h3 class="anchored" data-anchor-id="testing-comparisons-between-non-reference-categories">Testing Comparisons Between Non-Reference Categories</h3>
<p>The regression output provides p-values for comparisons against the <strong>reference category</strong> (Community hospitals), but what about comparing Teaching vs.&nbsp;Critical Access hospitals directly?</p>
<p>We need to test whether the <strong>linear combination</strong> of coefficients is statistically significant. We can use the <code>emmeans()</code> function with the <code>pairs()</code> function for pairwise comparisons.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate estimated marginal means</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(model_hospital, <span class="sc">~</span> hospital_type)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairwise comparisons with Tukey adjustment for multiple testing</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(emm, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                    estimate    SE  df t.ratio p.value
 Community - Teaching            2.36 0.294 245   8.009 &lt;0.0001
 Community - Critical Access    -3.26 0.300 245 -10.864 &lt;0.0001
 Teaching - Critical Access     -5.61 0.344 245 -16.324 &lt;0.0001

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>This provides all pairwise comparisons with p-values:</p>
<ul>
<li><em>Teaching vs.&nbsp;Community</em></li>
<li><em>Critical Access vs.&nbsp;Community</em></li>
<li><em>Teaching vs.&nbsp;Critical Access (this is what we want!)</em></li>
</ul>
<p>Based on these tests, we can conclude whether Teaching hospitals have <strong>statistically significantly</strong> lower readmission rates than Critical Access hospitals, not just numerically lower rates.</p>
<p>Now that we can include categorical predictors in our regression models, let’s explore what happens when the effect of one variable depends on the value of another.</p>
<hr>
</section>
</section>
</section>
<section id="interaction-effects" class="level1">
<h1>2. Interaction Effects</h1>
<section id="what-is-it-1" class="level2">
<h2 class="anchored" data-anchor-id="what-is-it-1">What is it?</h2>
<p>An <strong>interaction effect</strong> occurs when the effect of one variable on the outcome <strong>depends on the value of another variable</strong> (we talked about this in two-way ANOVA). In other words, the relationship between X₁ and Y changes across different levels of X₂.</p>
<p>Mathematically, we add an interaction term that is the product of the two variables:</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 (X_1 \times X_2) + \epsilon\]</span></p>
<p>The interaction coefficient <span class="math inline">\(\beta_3\)</span> captures how the effect of <span class="math inline">\(X_1\)</span> changes across levels of <span class="math inline">\(X_2\)</span> (and vice versa).</p>
</section>
<section id="when-to-use-it-1" class="level2">
<h2 class="anchored" data-anchor-id="when-to-use-it-1">When to Use It</h2>
<p>Use interaction terms when:</p>
<ul>
<li>Theory or prior research suggests an effect should vary across groups</li>
<li>You observe different slopes for different groups in exploratory visualizations</li>
<li>You want to test whether an intervention works differently for different populations</li>
</ul>
</section>
<section id="why-interactions-matter-in-healthcare" class="level2">
<h2 class="anchored" data-anchor-id="why-interactions-matter-in-healthcare">Why Interactions Matter in Healthcare</h2>
<p>Many healthcare relationships are conditional. For example:</p>
<ul>
<li><strong>Treatment effectiveness varies by patient characteristics</strong> (e.g., a medication may work better for younger patients compared to older patients)</li>
<li><strong>Resource effects depend on hospital type</strong> (e.g., additional staffing may have different impacts in big vs.&nbsp;small hospitals)</li>
<li><strong>Policy impacts vary by region</strong> (e.g., a new telemedicine policy may affect urban and rural hospitals differently)</li>
</ul>
<p>Last week and today, we learned that independent variables can be continuous or categorical, so we can think about three possible combinations in the interaction terms:</p>
<ul>
<li>Continuous X Categorical</li>
<li>Categorical X Categorical</li>
<li>Continuous X Continuous</li>
</ul>
<p>Let’s take a look at each one by one.</p>
</section>
<section id="continuous-categorical-interaction" class="level2">
<h2 class="anchored" data-anchor-id="continuous-categorical-interaction">2.1 Continuous × Categorical Interaction</h2>
<section id="example-does-staffing-effect-vary-by-hospital-ownership" class="level3">
<h3 class="anchored" data-anchor-id="example-does-staffing-effect-vary-by-hospital-ownership">Example: Does Staffing Effect Vary by Hospital Ownership?</h3>
<section id="background-and-context-2" class="level4">
<h4 class="anchored" data-anchor-id="background-and-context-2">Background and Context</h4>
<p>Studies have found that nurse staffing levels significantly affect patient outcomes and satisfaction, though the magnitude of these effects may vary by hospital characteristics including ownership type.</p>
<p>Hospitals have different ownership structures, which can shape how staffing resources translate into patient experience:</p>
<ul>
<li><strong>For-Profit hospitals</strong>: Owned by investors, primarily focused on financial performance. Additional staff may be directed toward revenue-generating activities rather than patient interaction.</li>
<li><strong>Non-Profit hospitals</strong>: Community-owned and mission-driven, often reinvesting surplus into patient care and quality improvement programs.</li>
</ul>
<p>Thus, we might expect that additional nurses would have a bigger impact on satisfaction in non-profit hospitals if they have stronger cultures of patient-centered care.</p>
<p>Let’s test whether the effect of nurse staffing on patient satisfaction varies by ownership type (this is a continuous (staffing) × categorical (ownership type) interaction).</p>
</section>
<section id="data-loading-2" class="level4">
<h4 class="anchored" data-anchor-id="data-loading-2">Data Loading</h4>
<p>Let’s load the dataset using the code below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the dataset</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>satisfaction_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week12_satisfaction_data.csv"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(satisfaction_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X hospital_id  ownership nurse_ratio patient_volume avg_acuity
1 1           1 For-Profit        3.18            472       1.87
2 2           2 For-Profit        4.84            308       2.15
3 3           3 For-Profit        4.64            272       1.64
4 4           4 Non-Profit        5.18            673       1.88
5 5           5 For-Profit        3.21            494       2.22
  patient_satisfaction
1                 45.5
2                 57.8
3                 60.5
4                 78.5
5                 43.4</code></pre>
</div>
</div>
<p><strong>Variables in the dataset</strong>:</p>
<ul>
<li><code>hospital_id</code>: Unique identifier for each hospital (1 to 300)</li>
<li><code>ownership</code>: Hospital ownership type (For-Profit or Non-Profit)</li>
<li><code>nurse_ratio</code>: Nurse-to-patient ratio (ranging from 2 to 6)</li>
<li><code>patient_volume</code>: Annual patient volume (number of patients)</li>
<li><code>avg_acuity</code>: Average patient acuity level (1 = low, 3 = high complexity)</li>
<li><code>patient_satisfaction</code>: Patient satisfaction score on 0-100 scale (our outcome variable)</li>
</ul>
</section>
</section>
<section id="visualizing-the-potential-interaction" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-the-potential-interaction">Visualizing the Potential Interaction</h3>
<p><strong>Before running the model</strong>, always visualize to see if an interaction might exist:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(satisfaction_data, <span class="fu">aes</span>(<span class="at">x =</span> nurse_ratio, <span class="at">y =</span> patient_satisfaction,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                              <span class="at">color =</span> ownership)) <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"For-Profit"</span> <span class="ot">=</span> <span class="st">"coral"</span>, <span class="st">"Non-Profit"</span> <span class="ot">=</span> <span class="st">"steelblue"</span>)) <span class="sc">+</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Nurse-to-Patient Ratio"</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Patient Satisfaction Score"</span>,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Ownership Type"</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Does Staffing Effect Differ by Hospital Ownership?"</span>,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Different slopes suggest an interaction effect"</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-interaction-visual" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-interaction-visual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lecture12_files/figure-html/fig-interaction-visual-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-interaction-visual-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Potential interaction: different slopes suggest an interaction effect
</figcaption>
</figure>
</div>
</div>
</div>
<p>The slopes appear different. Staffing seems to have a stronger positive effect in Non-Profit hospitals than in For-Profit hospitals.</p>
</section>
<section id="fitting-the-interaction-model" class="level3">
<h3 class="anchored" data-anchor-id="fitting-the-interaction-model">Fitting the Interaction Model</h3>
<p>When we fit a model with an interaction, we can use the <code>*</code> symbol, which automatically includes both main effects and the interaction. Alternatively, we can write out the terms explicitly using <code>+</code> for main effects and <code>:</code> for the interaction.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model WITH interaction</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative syntax for interaction: nurse_ratio + ownership + nurse_ratio:ownership</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>model_interact <span class="ot">&lt;-</span> <span class="fu">lm</span>(patient_satisfaction <span class="sc">~</span> nurse_ratio <span class="sc">*</span> ownership, <span class="at">data =</span> satisfaction_data)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_interact)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = patient_satisfaction ~ nurse_ratio * ownership, 
    data = satisfaction_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-17.2744  -3.6986  -0.6034   3.6057  13.9141 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      37.5427     1.4447  25.987  &lt; 2e-16 ***
nurse_ratio                       3.2110     0.3508   9.155  &lt; 2e-16 ***
ownershipNon-Profit               3.8787     2.1405   1.812    0.071 .  
nurse_ratio:ownershipNon-Profit   2.9174     0.5203   5.607 4.72e-08 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.11 on 296 degrees of freedom
Multiple R-squared:  0.7766,    Adjusted R-squared:  0.7743 
F-statistic:   343 on 3 and 296 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="interpreting-the-interaction" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-the-interaction">Interpreting the Interaction</h3>
<p><strong>Understanding the Coefficients</strong>:</p>
<ol type="1">
<li><p><strong>Intercept (37.54)</strong>: The predicted satisfaction score for a For-Profit hospital with a nurse ratio of 0.</p></li>
<li><p><strong>nurse_ratio (3.21)</strong>: The effect of staffing on satisfaction <strong>for the reference group (For-Profit hospitals)</strong>. Each additional nurse per patient increases satisfaction by 3.21 points in For-Profit hospitals.</p></li>
<li><p><strong>ownershipNon-Profit (3.88)</strong>: The difference in satisfaction between Non-Profit and For-Profit hospitals <strong>when nurse_ratio = 0</strong> (not practically meaningful, since hospitals can’t have zero nurses). This represents the baseline difference between ownership types at zero staffing.</p></li>
<li><p><strong>nurse_ratio:ownershipNon-Profit (2.92)</strong>: <strong>THE INTERACTION TERM</strong>. This is the additional effect of staffing in Non-Profit hospitals beyond the effect in For-Profit hospitals. The positive value means the slope is steeper for Non-Profit hospitals, and the p-value shows that this difference is statistically significant.</p></li>
</ol>
<p><strong>Computing the Effect of Staffing for Each Group</strong>:</p>
<ul>
<li><strong>For-Profit hospitals</strong>: β = 3.21
<ul>
<li>Each additional nurse increases satisfaction by 3.21 points</li>
</ul></li>
<li><strong>Non-Profit hospitals</strong>: β = 3.21 + 2.92 = 6.13
<ul>
<li>Each additional nurse increases satisfaction by 6.13 points</li>
</ul></li>
</ul>
<p>The interaction reveals that the <strong>context matters</strong>. The same staffing increase produces different outcomes depending on hospital ownership structure. This is precisely what interaction effects help us understand when and where interventions work better.</p>
</section>
</section>
<section id="categorical-categorical-interaction" class="level2">
<h2 class="anchored" data-anchor-id="categorical-categorical-interaction">2.2 Categorical × Categorical Interaction</h2>
<p>Interactions can also occur between two categorical variables.</p>
<section id="example-does-treatment-effect-vary-by-insurance-type" class="level3">
<h3 class="anchored" data-anchor-id="example-does-treatment-effect-vary-by-insurance-type">Example: Does Treatment Effect Vary by Insurance Type?</h3>
<section id="background-and-context-3" class="level4">
<h4 class="anchored" data-anchor-id="background-and-context-3">Background and Context</h4>
<p>Diabetes management programs help patients control blood sugar levels (measured by HbA1c). Different programs exist:</p>
<ul>
<li><strong>Standard Care</strong>: Regular doctor visits and medication management</li>
<li><strong>Intensive Program</strong>: Structured education, nutrition counseling, and regular coaching</li>
</ul>
<p>A 2023 study on Medicare Diabetes Prevention Program found significant implementation challenges, with very limited program availability nationwide, suggesting access and effectiveness barriers vary across insurance types.</p>
<p>Additionally, access to additional support services, costs (co-pays and out-of-pocket costs), and patients’ time availability could vary by insurance type.</p>
<p>We might expect that the intensive program would show the greatest improvement for privately insured patients, who typically face fewer access barriers, while Medicaid patients may benefit less if co-pays, transportation, or scheduling challenges limit their ability to fully participate.</p>
<p>Let’s test whether an intensive diabetes program works differently for patients with different insurance types. This is a categorical (insurance type) × categorical (program type) interaction.</p>
</section>
<section id="data-loading-3" class="level4">
<h4 class="anchored" data-anchor-id="data-loading-3">Data Loading</h4>
<p>Let’s load a dataset using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>diabetes_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week12_diabetes_data.csv"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diabetes_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X patient_id         treatment insurance baseline_a1c age a1c_reduction
1 1          1     Standard Care   Private          7.2  67          0.50
2 2          2     Standard Care  Medicaid          9.2  64          1.08
3 3          3 Intensive Program  Medicaid          8.8  64          1.34
4 4          4     Standard Care  Medicaid          8.8  78          1.16
5 5          5 Intensive Program  Medicare          7.6  66          1.14</code></pre>
</div>
</div>
<p><strong>Variables in the dataset</strong>:</p>
<ul>
<li><code>patient_id</code>: Unique identifier for each patient (1 to 400)</li>
<li><code>treatment</code>: Type of diabetes program (Standard Care or Intensive Program)</li>
<li><code>insurance</code>: Insurance type (Medicare, Medicaid, or Private)</li>
<li><code>baseline_a1c</code>: Baseline HbA1c level before treatment</li>
<li><code>age</code>: Patient age in years</li>
<li><code>a1c_reduction</code>: Reduction in HbA1c after treatment (our outcome variable)</li>
</ul>
<p>Before running the model, let’s visualize whether the treatment effect appears to differ across insurance types:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(diabetes_data, <span class="fu">aes</span>(<span class="at">x =</span> insurance, <span class="at">y =</span> a1c_reduction, <span class="at">fill =</span> treatment)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Insurance Type"</span>,</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"HbA1c Reduction"</span>,</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Treatment"</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div id="fig-catcat-explore" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-catcat-explore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lecture12_files/figure-html/fig-catcat-explore-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-catcat-explore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Does treatment effectiveness vary by insurance type?
</figcaption>
</figure>
</div>
</div>
</div>
<p>The gap between Standard Care and Intensive Program appears to vary across insurance types, suggesting a potential interaction effect. Let’s test this formally.</p>
</section>
</section>
<section id="fitting-the-interaction-model-1" class="level3">
<h3 class="anchored" data-anchor-id="fitting-the-interaction-model-1">Fitting the Interaction Model</h3>
<p>First, let’s make the variables as factors using the <code>factor()</code> function.</p>
<ul>
<li>For the variable <code>treatment</code>: “Standard Care” is the reference level</li>
<li>For the variable <code>insurance</code>: “Medicaid” is the reference level</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>diabetes_data <span class="ot">&lt;-</span> diabetes_data <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">treatment =</span> <span class="fu">factor</span>(treatment, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Standard Care"</span>, <span class="st">"Intensive Program"</span>)),</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">insurance =</span> <span class="fu">factor</span>(insurance, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Medicaid"</span>, <span class="st">"Medicare"</span>, <span class="st">"Private"</span>))</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>When we put those factor variables into the model, R automatically creates the necessary dummy variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model with interaction</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative syntax: treatment + insurance + treatment:insurance</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>model_diabetes <span class="ot">&lt;-</span> <span class="fu">lm</span>(a1c_reduction <span class="sc">~</span> treatment <span class="sc">*</span> insurance,</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> diabetes_data)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_diabetes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = a1c_reduction ~ treatment * insurance, data = diabetes_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.05014 -0.27806  0.00516  0.25360  1.10986 

Coefficients:
                                             Estimate Std. Error t value
(Intercept)                                   0.90351    0.04793  18.851
treatmentIntensive Program                    0.34946    0.07038   4.965
insuranceMedicare                             0.14662    0.06801   2.156
insurancePrivate                              0.18026    0.07419   2.430
treatmentIntensive Program:insuranceMedicare  0.21778    0.09756   2.232
treatmentIntensive Program:insurancePrivate   0.70294    0.10485   6.704
                                             Pr(&gt;|t|)    
(Intercept)                                   &lt; 2e-16 ***
treatmentIntensive Program                   1.02e-06 ***
insuranceMedicare                              0.0317 *  
insurancePrivate                               0.0156 *  
treatmentIntensive Program:insuranceMedicare   0.0262 *  
treatmentIntensive Program:insurancePrivate  7.04e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4123 on 394 degrees of freedom
Multiple R-squared:  0.5039,    Adjusted R-squared:  0.4976 
F-statistic: 80.05 on 5 and 394 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="understanding-categorical-categorical-interactions" class="level3">
<h3 class="anchored" data-anchor-id="understanding-categorical-categorical-interactions">Understanding Categorical × Categorical Interactions</h3>
<p>With two categorical variables, the interaction becomes more complex. Let’s break down each coefficient:</p>
<p><strong>Understanding Each Coefficient</strong>:</p>
<p><strong>Reference Group</strong>: Standard Care + Medicaid (both reference categories)</p>
<ol type="1">
<li><p><strong>Intercept (0.904)</strong>: The predicted HbA1c reduction for patients receiving <strong>Standard Care with Medicaid insurance</strong>. This is our baseline group.</p></li>
<li><p><strong>treatmentIntensive Program (0.349)</strong>: The additional effect of the Intensive Program compared to Standard Care <strong>for Medicaid patients only</strong> (the reference insurance group).</p>
<ul>
<li>Medicaid patients in Intensive Program: 0.904 + 0.349 = 1.253 reduction</li>
</ul></li>
<li><p><strong>insuranceMedicare (0.147)</strong>: The difference between Medicare and Medicaid patients <strong>receiving Standard Care only</strong> (the reference treatment).</p>
<ul>
<li>Medicare patients in Standard Care: 0.904 + 0.147 = 1.05 reduction</li>
</ul></li>
<li><p><strong>insurancePrivate (0.18)</strong>: The difference between Private and Medicaid patients <strong>receiving Standard Care only</strong>.</p>
<ul>
<li>Private patients in Standard Care: 0.904 + 0.18 = 1.084 reduction</li>
</ul></li>
<li><p><strong>treatmentIntensive Program:insuranceMedicare (0.218)</strong>: <strong>INTERACTION TERM</strong>. This is the additional treatment effect for Medicare patients beyond what Medicaid patients experience.</p>
<ul>
<li>This tells us whether the Intensive Program works differently for Medicare vs.&nbsp;Medicaid patients</li>
<li>Medicare patients in Intensive Program: 0.904 + 0.349 + 0.147 + 0.218 = 1.617 reduction</li>
<li>A significant interaction means that the treatment effect for Medicare patients is significantly different from the treatment effect for Medicaid patients.</li>
</ul></li>
<li><p><strong>treatmentIntensive Program:insurancePrivate (0.703)</strong>: <strong>INTERACTION TERM</strong>. This is the additional treatment effect for Private insurance patients beyond what Medicaid patients experience.</p>
<ul>
<li>This tells us whether the Intensive Program works differently for Private vs.&nbsp;Medicaid patients</li>
<li>Private patients in Intensive Program: 0.904 + 0.349 + 0.18 + 0.703 = 2.136 reduction</li>
<li>A significant interaction means that the treatment effect for Private insurance patients is significantly different from the treatment effect for Medicaid patients.</li>
</ul></li>
</ol>
<p><strong>Computing Treatment Effects for Each Insurance Group</strong>:</p>
<ul>
<li><strong>Medicaid</strong>: Treatment effect = 0.349</li>
<li><strong>Medicare</strong>: Treatment effect = 0.349 + 0.218 = 0.567</li>
<li><strong>Private</strong>: Treatment effect = 0.349 + 0.703 = 1.052</li>
</ul>
<p>The Intensive Program is effective across all insurance types, but significantly more effective for Private insurance patients compared to Medicaid patients. This suggests that program effectiveness depends on insurance type.</p>
</section>
</section>
<section id="continuous-continuous-interaction" class="level2">
<h2 class="anchored" data-anchor-id="continuous-continuous-interaction">2.3 Continuous × Continuous Interaction</h2>
<p>Interactions can also occur between two continuous variables, where the effect of one continuous variable depends on the level of another continuous variable.</p>
<section id="example-does-pt-session-benefit-depend-on-patient-age" class="level3">
<h3 class="anchored" data-anchor-id="example-does-pt-session-benefit-depend-on-patient-age">Example: Does PT Session Benefit Depend on Patient Age?</h3>
<section id="background-and-context-4" class="level4">
<h4 class="anchored" data-anchor-id="background-and-context-4">Background and Context</h4>
<p>Physical therapy (PT) is commonly prescribed for musculoskeletal conditions like joint pain, post-surgery recovery, and mobility issues. Patients typically attend multiple sessions over several weeks to improve functional capacity. However, the benefit of additional sessions may not be the same for all patients:</p>
<ul>
<li><strong>Younger patients</strong>: Faster tissue repair, better baseline strength, and greater capacity to respond to exercise-based therapy</li>
<li><strong>Older patients</strong>: Slower recovery, more comorbidities, and potentially different adherence patterns that may limit their response to additional sessions</li>
</ul>
<p>We might expect that additional PT sessions would provide greater functional improvement for younger patients compared to older patients, due to differences in physiological recovery capacity.</p>
<p>Let’s test whether the effect of PT session count on functional improvement varies by patient age. This is a continuous (PT sessions) × continuous (age) interaction.</p>
</section>
<section id="data-loading-4" class="level4">
<h4 class="anchored" data-anchor-id="data-loading-4">Data Loading</h4>
<p>Let’s load a dataset using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>pt_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week12_pt_data.csv"</span>)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pt_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X patient_id pt_sessions age baseline_function function_improvement
1 1          1          16  31                53                 27.1
2 2          2          22  51                31                  0.0
3 3          3           5  30                40                  7.5
4 4          4          11  37                31                 14.6
5 5          5           5  48                49                 10.3</code></pre>
</div>
</div>
<p><strong>Variables in the dataset</strong>:</p>
<ul>
<li><code>patient_id</code>: Unique identifier for each patient (1 to 250)</li>
<li><code>pt_sessions</code>: Number of physical therapy sessions attended (4 to 24 sessions)</li>
<li><code>age</code>: Patient age in years</li>
<li><code>baseline_function</code>: Baseline functional capacity score before therapy (higher scores indicate better pre-treatment function)</li>
<li><code>function_improvement</code>: Improvement in functional capacity after therapy in points (our outcome variable)</li>
</ul>
<p><strong>Before running the model</strong>, let’s visualize whether the relationship between PT sessions and improvement appears to vary by age:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pt_data, <span class="fu">aes</span>(<span class="at">x =</span> pt_sessions, <span class="at">y =</span> function_improvement, <span class="at">color =</span> age)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_gradient</span>(<span class="at">low =</span> <span class="st">"steelblue"</span>, <span class="at">high =</span> <span class="st">"coral"</span>) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Number of PT Sessions"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Function Improvement"</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Age"</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-contcont-explore" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-contcont-explore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lecture12_files/figure-html/fig-contcont-explore-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-contcont-explore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Does PT session effectiveness vary by patient age?
</figcaption>
</figure>
</div>
</div>
</div>
<p>The color gradient suggests that younger patients (blue) tend to benefit more from additional sessions, while older patients (red) may show less improvement. Let’s test this formally.</p>
</section>
</section>
<section id="fitting-the-interaction-model-2" class="level3">
<h3 class="anchored" data-anchor-id="fitting-the-interaction-model-2">Fitting the Interaction Model</h3>
<p>Let’s fit the model using the <code>lm()</code> function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit model with interaction</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Alternative expression: pt_sessions + age + pt_sessions:age</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>model_pt <span class="ot">&lt;-</span> <span class="fu">lm</span>(function_improvement <span class="sc">~</span> pt_sessions <span class="sc">*</span> age,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> pt_data)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_pt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = function_improvement ~ pt_sessions * age, data = pt_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.9370  -3.5027  -0.1272   3.1313  15.5965 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     22.246042   3.149244   7.064 1.65e-11 ***
pt_sessions      0.820603   0.213707   3.840 0.000157 ***
age             -0.161213   0.058312  -2.765 0.006130 ** 
pt_sessions:age -0.019953   0.003995  -4.995 1.12e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 5.426 on 246 degrees of freedom
Multiple R-squared:  0.641, Adjusted R-squared:  0.6366 
F-statistic: 146.4 on 3 and 246 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="interpreting-continuous-continuous-interactions" class="level3">
<h3 class="anchored" data-anchor-id="interpreting-continuous-continuous-interactions">Interpreting Continuous × Continuous Interactions</h3>
<p><strong>Understanding the Coefficients</strong>:</p>
<ol type="1">
<li><p><strong>Intercept (22.25)</strong>: The predicted improvement for a patient with 0 PT sessions and age 0 (not practically meaningful).</p></li>
<li><p><strong>pt_sessions (0.82)</strong>: The effect of one additional PT session <strong>when age = 0</strong> (not practically meaningful, since we don’t have newborns in PT).</p></li>
<li><p><strong>age (-0.16)</strong>: The effect of being one year older <strong>when pt_sessions = 0</strong> (not practically meaningful, since patients with zero sessions wouldn’t be in our study).</p></li>
<li><p><strong>pt_sessions:age (-0.02)</strong>: <strong>THE INTERACTION TERM</strong>. This tells us how the effect of PT sessions changes as patients get older.</p>
<ul>
<li>The <strong>negative value</strong> means that PT sessions become less effective as age increases</li>
<li>For each additional year of age, the benefit of one PT session decreases by 0.02 points</li>
</ul></li>
</ol>
<p><strong>Computing Marginal Effects at Different Ages</strong>:</p>
<p>In interaction models, we’re interested in the <strong>marginal effect</strong>, the effect of one variable (PT sessions) at specific values of another variable (age). Because of the interaction, this marginal effect changes with age.</p>
<p>The marginal effect of PT sessions at any given age is calculated as:</p>
<p><span class="math display">\[\frac{\partial \text{Improvement}}{\partial \text{PT Sessions}} = \beta_{\text{pt\_sessions}} + \beta_{\text{interaction}} \times \text{Age}\]</span></p>
<p>Let’s calculate the marginal effect of one additional PT session at different ages:</p>
<ul>
<li><strong>Age 30</strong>: Effect = 0.82 + (30 × -0.02) = 0.22 points per session (positive = beneficial)</li>
<li><strong>Age 50</strong>: Effect = 0.82 + (50 × -0.02) = -0.18 points per session (negative = associated with worse outcomes)</li>
<li><strong>Age 70</strong>: Effect = 0.82 + (70 × -0.02) = -0.58 points per session (negative = associated with worse outcomes)</li>
</ul>
<p>The effect of PT sessions <strong>changes dramatically with age</strong>. For younger patients (age 30), additional PT sessions improve function. However, the effect becomes <strong>negative</strong> for older patients (ages 50 and 70), meaning additional sessions are associated with worse functional outcomes. This crossover pattern demonstrates how interactions can reverse the direction of an effect.</p>
</section>
<section id="visualizing-continuous-continuous-interaction" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-continuous-continuous-interaction">Visualizing Continuous × Continuous Interaction</h3>
<p>For continuous × continuous interactions, we typically show the effect at different levels of the moderator. We’ll use the <code>probe_interaction()</code> function from the <code>interactions</code> package, which makes it easy to visualize interactions and get marginal effects at different levels of a moderator:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use probe_interaction to visualize the interaction</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify custom age values: 30, 50, 70</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">probe_interaction</span>(model_pt,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">pred =</span> pt_sessions,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">modx =</span> age,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">modx.values =</span> <span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">50</span>, <span class="dv">70</span>),</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">interval =</span> <span class="cn">TRUE</span>,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">int.width =</span> <span class="fl">0.95</span>,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">x.label =</span> <span class="st">"Number of PT Sessions"</span>,</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">y.label =</span> <span class="st">"Predicted Function Improvement"</span>,</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">main.title =</span> <span class="st">"Interaction: PT Sessions × Age"</span>,</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">legend.main =</span> <span class="st">"Patient Age"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>JOHNSON-NEYMAN INTERVAL

When age is OUTSIDE the interval [31.18, 47.33], the slope of pt_sessions
is p &lt; .05.

Note: The range of observed values of age is [25.00, 80.00]

SIMPLE SLOPES ANALYSIS

Slope of pt_sessions when age = 30.00: 

  Est.   S.E.   t val.      p
------ ------ -------- ------
  0.22   0.10     2.12   0.03

Slope of pt_sessions when age = 50.00: 

   Est.   S.E.   t val.      p
------- ------ -------- ------
  -0.18   0.06    -2.90   0.00

Slope of pt_sessions when age = 70.00: 

   Est.   S.E.   t val.      p
------- ------ -------- ------
  -0.58   0.10    -5.97   0.00</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-contcont" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-contcont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Lecture12_files/figure-html/fig-contcont-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-contcont-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: PT sessions effect varies by patient age
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation of marginal effects</strong>:</p>
<ul>
<li><strong>SIMPLE SLOPES ANALYSIS</strong> (rate of change) shows the effect of PT sessions at each age level
<ul>
<li>The <strong>slope</strong> (Est.) at that age</li>
<li><strong>Standard error</strong> (S.E.) and <strong>t-statistic</strong> (t val.)</li>
<li><strong>p-value</strong> testing if the slope is significantly different from zero</li>
</ul></li>
<li>The changing slopes confirm our earlier manual calculations</li>
<li>All three slopes are statistically significant (p &lt; 0.05), but they differ in <strong>direction</strong>:
<ul>
<li>Age 30: Positive slope (0.22) = PT sessions are <strong>beneficial</strong></li>
<li>Age 50: Negative slope (-0.18) = PT sessions are <strong>associated with worse outcomes</strong></li>
<li>Age 70: More negative slope (-0.58) = PT sessions are <strong>associated with even worse outcomes</strong></li>
</ul></li>
</ul>
<p><strong>Visual interpretation</strong>: The graph clearly shows the interaction effect: The slopes change from positive to negative as age increases:</p>
<ul>
<li><strong>Positive slope for younger patients</strong>: Age 30 patients (upward sloping line) gain from each additional session</li>
<li><strong>Negative slope for middle-aged patients</strong>: Age 50 patients (downward sloping line) show worse outcomes with additional sessions</li>
<li><strong>Steeper negative slope for older patients</strong>: Age 70 patients (steeper downward slope) show even worse outcomes with additional sessions</li>
</ul>
<p>In this data, the negative slopes at older ages suggest that more PT sessions are associated with worse outcomes for older patients. In reality, this pattern would be unusual and would warrant investigation into potential confounding factors (e.g., sicker patients receiving more sessions). This example illustrates how interactions can produce crossover effects where treatment benefits reverse in different subgroups.</p>
<hr>
</section>
</section>
<section id="practice-dummy-variables-and-interaction-effects" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="practice-dummy-variables-and-interaction-effects">Practice: Dummy Variables and Interaction Effects</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Your Turn!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Practice fitting and interpreting regression models with dummy variables and interaction effects using a new healthcare scenario.</p>
</div>
</div>
<section id="scenario" class="level3">
<h3 class="anchored" data-anchor-id="scenario">Scenario</h3>
<p>You are a healthcare analyst evaluating hospital quality improvement initiatives across a national hospital network. Quality scores (0-100) measure overall hospital performance based on patient outcomes, safety, and patient experience.</p>
<p>Your organization wants to understand:</p>
<ol type="1">
<li>Whether quality scores differ across geographic <strong>regions</strong> (Midwest, Northeast, South, West), after accounting for other hospital characteristics</li>
<li>Whether <strong>IT investment</strong> (e.g., electronic health records, clinical decision support systems) affects quality differently in <strong>teaching</strong> vs.&nbsp;<strong>non-teaching</strong> hospitals</li>
</ol>
<p>This analysis will guide resource allocation and technology investment decisions across the hospital network.</p>
</section>
<section id="data-loading-5" class="level3">
<h3 class="anchored" data-anchor-id="data-loading-5">Data Loading</h3>
<p>Run this code to load the dataset:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>quality_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week12_quality_data.csv"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(quality_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X hospital_id    region teaching_status it_investment avg_los quality_score
1 1           1 Northeast    Non-Teaching           435     4.8          72.1
2 2           2   Midwest    Non-Teaching            83     4.8          50.8
3 3           3      West        Teaching           336     2.0          80.2
4 4           4 Northeast    Non-Teaching            91     4.1          55.2
5 5           5      West    Non-Teaching           278     3.9          58.1</code></pre>
</div>
</div>
<p><strong>Dataset Variables:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 43%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
<th>Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>hospital_id</code></td>
<td>Unique hospital identifier</td>
<td>Numeric</td>
</tr>
<tr class="even">
<td><code>region</code></td>
<td>Geographic region (Midwest, Northeast, South, West)</td>
<td>Categorical</td>
</tr>
<tr class="odd">
<td><code>teaching_status</code></td>
<td>Hospital type (Non-Teaching or Teaching)</td>
<td>Categorical</td>
</tr>
<tr class="even">
<td><code>it_investment</code></td>
<td>IT spending per bed ($ thousands)</td>
<td>Numeric (continuous)</td>
</tr>
<tr class="odd">
<td><code>avg_los</code></td>
<td>Average length of stay (days)</td>
<td>Numeric (continuous)</td>
</tr>
<tr class="even">
<td><code>quality_score</code></td>
<td>Hospital quality score (0-100 scale)</td>
<td>Numeric (continuous)</td>
</tr>
</tbody>
</table>
</section>
<section id="task-1-regression-with-multi-level-dummy-variables" class="level3">
<h3 class="anchored" data-anchor-id="task-1-regression-with-multi-level-dummy-variables">Task 1: Regression with Multi-Level Dummy Variables</h3>
<p>First, convert <code>region</code> to a factor with “Midwest” as the reference category. Then fit a regression model predicting <code>quality_score</code> from <code>region</code>, controlling for <code>it_investment</code> and <code>avg_los</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Convert region to a factor with Midwest as reference</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>quality_data <span class="ot">&lt;-</span> quality_data <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">region =</span> <span class="fu">factor</span>(___, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"___"</span>, <span class="st">"___"</span>, <span class="st">"___"</span>, <span class="st">"___"</span>)))</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Fit the model</span></span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>model_quality <span class="ot">&lt;-</span> <span class="fu">lm</span>(___ <span class="sc">~</span> ___ <span class="sc">+</span> ___ <span class="sc">+</span> ___, <span class="at">data =</span> ___)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: View results</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(___)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions:</strong></p>
<ol type="1">
<li>How many dummy variables were created for <code>region</code>?</li>
<li>Which region has the highest quality scores compared to the reference?</li>
<li>Are all regional differences <strong>relative to Midwest</strong> statistically significant (p &lt; 0.05)?</li>
</ol>
</section>
<section id="task-2-pairwise-comparisons" class="level3">
<h3 class="anchored" data-anchor-id="task-2-pairwise-comparisons">Task 2: Pairwise Comparisons</h3>
<p>Use <code>emmeans()</code> to compare all pairs of regions directly.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill in the blanks</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>emm_region <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(___, <span class="sc">~</span> ___)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Show estimated marginal means</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(___)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairwise comparisons</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(___, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Question:</strong> Which pair of regions has the largest difference in quality scores? Is this difference statistically significant after adjusting for multiple comparisons?</p>
</section>
<section id="task-3-interaction-model" class="level3">
<h3 class="anchored" data-anchor-id="task-3-interaction-model">Task 3: Interaction Model</h3>
<p>Fit a model with an interaction between <code>it_investment</code> and <code>teaching_status</code>, controlling for <code>region</code> and <code>avg_los</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fill in the blanks</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>model_quality_interact <span class="ot">&lt;-</span> <span class="fu">lm</span>(quality_score <span class="sc">~</span> ___ <span class="sc">*</span> ___ <span class="sc">+</span> ___ <span class="sc">+</span> ___,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">data =</span> ___)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="co"># View results</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(___)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions:</strong></p>
<ol type="1">
<li>Is the interaction between IT investment and teaching status statistically significant?</li>
<li>How much more effective is each dollar of IT investment in teaching hospitals compared to non-teaching hospitals?</li>
</ol>
<hr>
</section>
</section>
</section>
<section id="summary" class="level1">
<h1>Summary</h1>
<section id="key-takeaways" class="level2">
<h2 class="anchored" data-anchor-id="key-takeaways">Key Takeaways</h2>
<p><strong>Dummy Variables</strong>:</p>
<ul>
<li>Allow categorical predictors in regression using 0/1 coding</li>
<li>For k categories, R creates k-1 dummy variables automatically</li>
<li>Coefficients represent differences from the <strong>reference category</strong></li>
<li>Use <code>factor(x, levels = c("Reference", ...))</code> to set the reference</li>
<li>Use <code>emmeans()</code> with <code>pairs()</code> for all pairwise comparisons</li>
</ul>
<p><strong>Interaction Effects</strong>:</p>
<ul>
<li>An interaction means the effect of one variable <strong>depends on</strong> another</li>
<li>Use <code>*</code> in the formula to include both main effects and the interaction: <code>lm(y ~ x1 * x2)</code></li>
<li>Three types: Continuous × Categorical, Categorical × Categorical, Continuous × Continuous</li>
<li>With interactions present, main effects represent the effect <strong>only for the reference group</strong></li>
<li>To get the effect for other groups: add main effect + interaction coefficient</li>
</ul>
<hr>
</section>
</section>
<section id="references-and-further-reading" class="level1">
<h1>References and Further Reading</h1>
<section id="statistical-methods" class="level2">
<h2 class="anchored" data-anchor-id="statistical-methods">Statistical Methods</h2>
<ul>
<li>Gelman, A., &amp; Hill, J. (2006). <em>Data Analysis Using Regression and Multilevel/Hierarchical Models</em>. Cambridge University Press.</li>
<li>James, G., Witten, D., Hastie, T., &amp; Tibshirani, R. (2021). <em>An Introduction to Statistical Learning with Applications in R</em> (2nd ed.). Springer.</li>
<li>Fox, J. (2015). <em>Applied Regression Analysis and Generalized Linear Models</em> (3rd ed.). SAGE Publications.</li>
</ul>
</section>
<section id="healthcare-applications" class="level2">
<h2 class="anchored" data-anchor-id="healthcare-applications">Healthcare Applications</h2>
<p>Examples are motivated by the following:</p>
<ul>
<li><p>Katikam, S. M., Komari, L. K., &amp; Parimi, S. B. R. (2025). Evaluation of Enhanced Recovery After Surgery (ERAS) Protocols in Abdominal Surgery. <em>Journal of Pharmacy &amp; Bioallied Sciences</em>, 17(Suppl 2), S1805-S1807.</p></li>
<li><p>Horwitz, L. I., Bernheim, S. M., Ross, J. S., Herrin, J., Grady, J., Krumholz, H. M., &amp; Drye, E. E. (2017). Hospital characteristics associated with risk-standardized readmission rates. <em>Medical Care</em>, 55(5), 528-534. https://pmc.ncbi.nlm.nih.gov/articles/PMC5426655/</p></li>
<li><p>Turk, M. T., Jakub, K., &amp; Ritchie, N. D. (2023). Stakeholder Analysis: Medicare Diabetes Prevention Program Awareness and Implementation. <em>American Journal of Managed Care</em>, 29(6), 308-312. https://pmc.ncbi.nlm.nih.gov/articles/PMC10287029/</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>