<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="">
  <meta name="dcterms.date" content="2026-04-01">
  <title>Business Analytics in Healthcare Hanagement (MBA 642 - Spring 2026) – Linear Regression 2:   Dummy Variables and Interaction Effects</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-9e47a048f9aa32c89095d4c894f35b02.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
  <link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Linear Regression 2: <br> Dummy Variables and Interaction Effects</h1>
  <p class="subtitle">Week 12 and Week 13</p>

<div class="quarto-title-authors">
</div>

  <p class="date">2026-04-01</p>
</section>
<section id="todays-learning-goals" class="slide level2 scrollable">
<h2>Today’s Learning Goals</h2>
<p>By the end of this lecture, you will be able to:</p>
<ol type="1">
<li class="fragment"><strong>Create and interpret</strong> dummy variables for categorical predictors in regression (binary and multi-level)</li>
<li class="fragment"><strong>Test and interpret</strong> interaction effects in regression</li>
<li class="fragment"><strong>Compute</strong> marginal effects to describe how a predictor’s impact varies across groups</li>
</ol>
</section>
<section id="beyond-continuous-predictors" class="slide level2">
<h2>Beyond Continuous Predictors</h2>
<p>In Week 11, we used continuous predictors (e.g., wait time, staffing hours) to predict outcomes.</p>
<div class="fragment">
<p><br></p>
<p>But many important variables in healthcare are <strong>categorical</strong> (e.g., hospital type, insurance status, treatment protocol, or region).</p>
</div>
<div class="fragment">
<p>Moreover, the effect of a continuous variable can differ depending on those categories.</p>
</div>
<div class="fragment">
<p><br></p>
<p><strong>Dummy variables and interactions</strong> answer more nuanced questions:</p>
<ul>
<li class="fragment"><em>Do outcomes differ across groups, after controlling for other factors?</em></li>
<li class="fragment"><em>Does the effect of one variable change depending on the level of another?</em></li>
</ul>
</div>
</section>
<section id="why-this-matters-for-healthcare-management" class="slide level2">
<h2>Why This Matters for Healthcare Management</h2>
<p>These techniques directly support real management decisions:</p>
<ul>
<li class="fragment"><strong>Resource allocation</strong>: Should we prioritize staffing investments in non-profit hospitals, where the satisfaction payoff may be larger?</li>
<li class="fragment"><strong>Cost management</strong>: Does the Enhanced Recovery After Surgery (ERAS) protocol reduce length of stay <em>equally</em> across patient severity levels, or should we target it to specific groups?</li>
<li class="fragment"><strong>Performance benchmarking</strong>: Are we comparing hospitals fairly if we don’t account for differences in patient mix and hospital type?</li>
</ul>
</section>
<section id="todays-roadmap" class="slide level2 scrollable">
<h2>Today’s Roadmap</h2>
<ol type="1">
<li class="fragment"><strong>Dummy Variables</strong> – Including categorical predictors (binary and multi-level) in regression</li>
<li class="fragment"><strong>Interaction Effects</strong> – Testing whether the effect of one variable depends on another
<ul>
<li class="fragment">Continuous x Categorical</li>
<li class="fragment">Categorical x Categorical</li>
<li class="fragment">Continuous x Continuous</li>
</ul></li>
</ol>
</section>
<section>
<section id="dummy-variables" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>1. Dummy Variables</h1>

</section>
<section id="what-are-dummy-variables" class="slide level2">
<h2>What Are Dummy Variables?</h2>
<p>Dummy variables (indicator variables) are <strong>binary</strong> variables representing categorical group membership using 0s and 1s.</p>
<div class="fragment">
<p><br></p>
<p>For a categorical variable with <strong>k categories</strong>, we create <strong>k-1 dummy variables</strong>, with one category serving as the reference group.</p>
</div>
<div class="fragment">
<p><strong>Example</strong>: 3 Hospital Types (Teaching, Community, Critical Access) → 2 dummy variables:</p>
<ul>
<li class="fragment">Dummy 1: Teaching (1 if Teaching, 0 otherwise)</li>
<li class="fragment">Dummy 2: Critical Access (1 if Critical Access, 0 otherwise)</li>
<li class="fragment">Community = reference (both dummies = 0)</li>
</ul>
</div>
</section>
<section id="when-to-use-dummy-variables" class="slide level2">
<h2>When to Use Dummy Variables</h2>
<p>Regression requires numerical inputs, but categorical variables are not inherently numerical. Simply assigning numbers (e.g., Teaching=1, Community=2, Critical Access=3) would imply a false ordering.</p>
<div class="fragment">
<p>Dummy variables solve this by representing group membership as 0s and 1s, allowing us to:</p>
<ul>
<li class="fragment">Include <strong>categorical predictors</strong> in regression (hospital type, insurance status, treatment group)</li>
<li class="fragment">Test whether <strong>group differences</strong> are statistically significant while <em>controlling for other variables</em></li>
<li class="fragment"><strong>Quantify</strong> the magnitude of differences between categories</li>
</ul>
</div>
</section>
<section id="binary-categorical-variables" class="slide level2">
<h2>Binary Categorical Variables</h2>
<p>For a variable with <strong>two categories</strong>, we need <strong>one dummy variable</strong>:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Patient</th>
<th style="text-align: center;">Insurance Status</th>
<th style="text-align: center;">Dummy: Insured</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">Insured</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">Uninsured</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">Insured</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">Uninsured</td>
<td style="text-align: center;">0</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><br></p>
<p>The coefficient on the dummy variable represents the <strong>difference in the outcome</strong> between the two groups (Insured vs.&nbsp;Uninsured).</p>
</div>
</section>
<section id="example-case-treatment-protocol-comparison" class="slide level2">
<h2>Example Case: Treatment Protocol Comparison</h2>
<p><strong>The problem</strong>: Traditional surgical recovery involves extended hospital stays, which are costly and can lead to complications.</p>
<div class="fragment">
<p><br></p>
<p><strong>A better approach</strong>: Enhanced Recovery After Surgery (ERAS) protocols use evidence-based practices: better pain management, early mobilization, and earlier nutrition.</p>
</div>
<div class="fragment">
<p><br></p>
<p>Let’s compare patient outcomes between <strong><em>Standard care</em></strong> and <strong><em>ERAS protocols</em></strong> to quantify the treatment effect using a dummy variable.</p>
</div>
</section>
<section id="loading-packages-and-data" class="slide level2">
<h2>Loading Packages and Data</h2>
<p>Let’s load the required packages and the data using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)    <span class="co"># data wrangling and visualization</span></span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)      <span class="co"># pairwise comparisons across groups</span></span>
<span id="cb1-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(interactions) <span class="co"># visualizing interaction effects</span></span>
<span id="cb1-4"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a aria-hidden="true" tabindex="-1"></a>surgical_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week12_surgical_data.csv"</span>)</span>
<span id="cb1-6"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(surgical_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X patient_id protocol age  bmi surgery_complexity length_of_stay
1 1          1 Standard  77 27.3                  3            9.8
2 2          2 Standard  56 27.1                  3           10.4
3 3          3 Standard  59 23.7                  3            9.3
4 4          4     ERAS  49 32.8                  3            9.6
5 5          5 Standard  74 23.8                  3           11.0</code></pre>
</div>
</div>
</section>
<section id="setting-the-reference-category" class="slide level2">
<h2>Setting the Reference Category</h2>
<p>We use <code>factor()</code> to set “Standard” as the reference category:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a>surgical_data <span class="ot">&lt;-</span> surgical_data <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">protocol =</span> <span class="fu">factor</span>(protocol, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Standard"</span>, <span class="st">"ERAS"</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<p><br></p>
<ul>
<li>When we include <code>protocol</code> in the model, R <strong>automatically creates</strong> the dummy variable for us.</li>
<li>The first level specified in <code>factor()</code> (here, <code>"Standard"</code>) becomes the <strong>reference category</strong>.</li>
</ul>
</div>
</section>
<section id="visualizing-the-data" class="slide level2">
<h2>Visualizing the Data</h2>
<p>Let’s visually check the patterns in the data before fitting the model:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(surgical_data, <span class="fu">aes</span>(<span class="at">x =</span> protocol, <span class="at">y =</span> length_of_stay, <span class="at">fill =</span> protocol)) <span class="sc">+</span></span>
<span id="cb4-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb4-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb4-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb4-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Treatment Protocol"</span>,</span>
<span id="cb4-6"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Length of Stay (days)"</span>,</span>
<span id="cb4-7"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Does ERAS Protocol Affect Length of Stay?"</span></span>
<span id="cb4-8"><a aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb4-9"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb4-10"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Slide12_files/figure-revealjs/fig-protocol-effect-1.png" id="fig-protocol-effect" width="576" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;1
</p></section>
<section id="fitting-the-model" class="slide level2">
<h2>Fitting the Model</h2>
<ul>
<li>Now we can fit a linear regression model to estimate the effect of the ERAS protocol on length of stay, controlling for age, BMI, and surgery complexity</li>
<li>We can use the same <code>lm()</code> function as before, just including the <code>protocol</code> variable as a predictor</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-hidden="true" tabindex="-1"></a>model_protocol <span class="ot">&lt;-</span> <span class="fu">lm</span>(length_of_stay <span class="sc">~</span> protocol <span class="sc">+</span> age <span class="sc">+</span> bmi <span class="sc">+</span> surgery_complexity,</span>
<span id="cb5-2"><a aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> surgical_data)</span>
<span id="cb5-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_protocol)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="understanding-the-dummy-variable-output" class="slide level2">
<h2>Understanding the Dummy Variable Output</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top" style="margin-left: auto; margin-right: auto;">
<caption>Regression Results: Protocol Comparison</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">3.218</td>
<td style="text-align: right;">0.587</td>
<td style="text-align: right;">5.482</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.060</td>
<td style="text-align: right;">4.376</td>
</tr>
<tr class="even">
<td style="text-align: left;">protocolERAS</td>
<td style="text-align: right;">-1.788</td>
<td style="text-align: right;">0.143</td>
<td style="text-align: right;">-12.468</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-2.071</td>
<td style="text-align: right;">-1.505</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">0.027</td>
<td style="text-align: right;">0.007</td>
<td style="text-align: right;">4.100</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.014</td>
<td style="text-align: right;">0.040</td>
</tr>
<tr class="even">
<td style="text-align: left;">bmi</td>
<td style="text-align: right;">0.048</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">3.698</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.022</td>
<td style="text-align: right;">0.073</td>
</tr>
<tr class="odd">
<td style="text-align: left;">surgery_complexity</td>
<td style="text-align: right;">1.497</td>
<td style="text-align: right;">0.087</td>
<td style="text-align: right;">17.218</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.325</td>
<td style="text-align: right;">1.668</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Key Interpretation</strong>:</p>
<ul>
<li>The coefficient for <code>protocolERAS</code> is approximately -1.79.
<ul>
<li><strong>Patients in the ERAS protocol have 1.79 days shorter</strong> length of stay than patients in the Standard protocol, holding age, BMI, and surgery complexity constant.</li>
</ul></li>
</ul>
</section>
<section id="manual-calculation-with-dummy-variables" class="slide level2">
<h2>Manual Calculation with Dummy Variables</h2>
<p><strong>Patient profile</strong>: A 65-year-old patient with BMI of 30 and surgery complexity of 2.</p>
<div class="fragment">
<p>The fitted equation:</p>
<p><span class="math display">\[\widehat{\text{LOS}} = 3.218 + -1.788(\text{ERAS}) + 0.027(\text{Age}) + 0.048(\text{BMI}) + 1.497(\text{Complexity})\]</span></p>
</div>
<div class="fragment">
<p><strong>Standard protocol</strong> (ERAS = 0):</p>
<p><span class="math display">\[\widehat{\text{LOS}} = 3.218 + -1.788(0) + 0.027(65) + 0.048(30) + 1.497(2) = 9.41 \text{ days}\]</span></p>
</div>
<div class="fragment">
<p><strong>ERAS protocol</strong> (ERAS = 1):</p>
<p><span class="math display">\[\widehat{\text{LOS}} = 3.218 + -1.788(1) + 0.027(65) + 0.048(30) + 1.497(2) = 7.62 \text{ days}\]</span></p>
</div>
</section>
<section id="the-difference-is-exactly-the-coefficient" class="slide level2">
<h2>The Difference Is Exactly the Coefficient</h2>
<p>For the same patient (age 65, BMI 30, complexity 2):</p>
<ul>
<li><strong>Standard protocol</strong>: 9.41 days</li>
<li><strong>ERAS protocol</strong>: 7.62 days</li>
<li><strong>Difference</strong>: -1.79 days = ERAS coefficient (-1.79)</li>
</ul>
<div class="fragment">
<p><br> The dummy variable coefficient represents the difference in predicted outcomes between the two groups, holding all other variables constant. This is true <strong>regardless of the patient profile</strong> we plug in.</p>
</div>
</section></section>
<section>
<section id="multi-level-categorical-variables" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>2. Multi-Level Categorical Variables</h1>

</section>
<section id="why-k-1-dummy-variables" class="slide level2">
<h2>Why k-1 Dummy Variables?</h2>
<p>When a categorical variable has <strong>more than two levels</strong>, we need <strong>k-1 dummy variables</strong> (where k is the number of categories).</p>
<div class="fragment">
<p><br></p>
<p>Including a dummy for every category would create <strong>perfect multicollinearity</strong>.</p>
<ul>
<li>The dummy variables would sum to 1 for every observation, perfectly correlated with the intercept.</li>
</ul>
</div>
<div class="fragment">
<p><br> Each of the k-1 dummy coefficients represents the <strong>difference</strong> between that category and the reference category.</p>
</div>
</section>
<section id="example-case-hospital-type-comparison" class="slide level2">
<h2>Example Case: Hospital Type Comparison</h2>
<p><strong>Question</strong>: Do 30-day readmission rates differ across 3 hospital types?</p>
<ul>
<li class="fragment"><strong>Teaching hospitals</strong>: Large academic medical centers handling complex cases</li>
<li class="fragment"><strong>Community hospitals</strong>: General hospitals serving local populations</li>
<li class="fragment"><strong>Critical Access hospitals</strong>: Small rural hospitals with limited resources</li>
</ul>
<div class="fragment">
<p><br> Let’s compare readmission rates across these three hospital types while controlling for patient characteristics.</p>
</div>
</section>
<section id="loading-the-data" class="slide level2">
<h2>Loading the Data</h2>
<p>Let’s load the data using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a aria-hidden="true" tabindex="-1"></a>hospital_type_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week12_hospital_type_data.csv"</span>)</span>
<span id="cb6-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(hospital_type_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X hospital_id hospital_type bed_count avg_patient_severity nurse_per_patient
1 1           1     Community       160                 2.51              4.11
2 2           2     Community       303                 2.69              2.35
3 3           3     Community        34                 2.24              4.78
4 4           4     Community       316                 1.70              3.82
5 5           5     Community       315                 1.83              3.88
  readmission_rate
1             19.0
2             21.0
3             17.0
4             17.0
5             17.5</code></pre>
</div>
</div>
</section>
<section id="visualizing-the-data-1" class="slide level2">
<h2>Visualizing the Data</h2>
<p>Let’s visually inspect the pattern:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(hospital_type_data, <span class="fu">aes</span>(<span class="at">x =</span> hospital_type, <span class="at">y =</span> readmission_rate, <span class="at">fill =</span> hospital_type)) <span class="sc">+</span></span>
<span id="cb8-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb8-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb8-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb8-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Hospital Type"</span>,</span>
<span id="cb8-6"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"30-Day Readmission Rate (%)"</span>,</span>
<span id="cb8-7"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Do Readmission Rates Differ by Hospital Type?"</span></span>
<span id="cb8-8"><a aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb8-9"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb8-10"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Slide12_files/figure-revealjs/fig-hospital-type-explore-1.png" id="fig-hospital-type-explore" width="864" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;2
</p></section>
<section id="setting-reference-category-and-fitting-the-model" class="slide level2">
<h2>Setting Reference Category and Fitting the Model</h2>
<p>Let’s set the reference category to “Community”:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a aria-hidden="true" tabindex="-1"></a>hospital_type_data <span class="ot">&lt;-</span> hospital_type_data <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-3"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">hospital_type =</span> <span class="fu">factor</span>(hospital_type,</span>
<span id="cb9-4"><a aria-hidden="true" tabindex="-1"></a>                          <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Community"</span>, <span class="st">"Teaching"</span>, <span class="st">"Critical Access"</span>))</span>
<span id="cb9-5"><a aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<p>Let’s fit the model using the referenced factor variable:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-hidden="true" tabindex="-1"></a>model_hospital <span class="ot">&lt;-</span> <span class="fu">lm</span>(readmission_rate <span class="sc">~</span> hospital_type <span class="sc">+</span> avg_patient_severity <span class="sc">+</span></span>
<span id="cb10-2"><a aria-hidden="true" tabindex="-1"></a>                     nurse_per_patient, <span class="at">data =</span> hospital_type_data)</span>
<span id="cb10-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_hospital)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>
<section id="interpreting-multi-level-dummy-output" class="slide level2">
<h2>Interpreting Multi-Level Dummy Output</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top" style="margin-left: auto; margin-right: auto;">
<caption>Regression Results: Hospital Type Effect on Readmissions</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: right;">15.577</td>
<td style="text-align: right;">0.693</td>
<td style="text-align: right;">22.466</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">14.211</td>
<td style="text-align: right;">16.942</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hospital Type: Teaching</td>
<td style="text-align: right;">-2.356</td>
<td style="text-align: right;">0.294</td>
<td style="text-align: right;">-8.009</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-2.935</td>
<td style="text-align: right;">-1.776</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hospital Type: Critical Access</td>
<td style="text-align: right;">3.258</td>
<td style="text-align: right;">0.300</td>
<td style="text-align: right;">10.864</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.667</td>
<td style="text-align: right;">3.848</td>
</tr>
<tr class="even">
<td style="text-align: left;">Average Patient Severity</td>
<td style="text-align: right;">2.235</td>
<td style="text-align: right;">0.218</td>
<td style="text-align: right;">10.251</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.805</td>
<td style="text-align: right;">2.664</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nurse-to-Patient Ratio</td>
<td style="text-align: right;">-0.860</td>
<td style="text-align: right;">0.159</td>
<td style="text-align: right;">-5.411</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-1.173</td>
<td style="text-align: right;">-0.547</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="interpreting-multi-level-dummy-output-1" class="slide level2">
<h2>Interpreting Multi-Level Dummy Output</h2>
<p>Key interpretations:</p>
<ul>
<li><strong>Reference Category</strong>: Community hospitals (omitted from output)</li>
<li><strong>Teaching Hospitals</strong>: Readmission rate 2.356 percentage points <strong>lower</strong> than Community</li>
<li><strong>Critical Access Hospitals</strong>: Readmission rate 3.258 percentage points <strong>higher</strong> than Community</li>
</ul>
</section>
<section id="testing-non-reference-comparisons" class="slide level2">
<h2>Testing Non-Reference Comparisons</h2>
<p>The regression output only compares against the reference category. To compare <strong>Teaching vs.&nbsp;Critical Access</strong> directly using the <code>emmeans()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-hidden="true" tabindex="-1"></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(model_hospital, <span class="sc">~</span> hospital_type)</span>
<span id="cb11-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(emm, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                    estimate    SE  df t.ratio p.value
 Community - Teaching            2.36 0.294 245   8.009 &lt;0.0001
 Community - Critical Access    -3.26 0.300 245 -10.864 &lt;0.0001
 Teaching - Critical Access     -5.61 0.344 245 -16.324 &lt;0.0001

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
</section>
<section id="changing-the-reference-category" class="slide level2">
<h2>Changing the Reference Category</h2>
<p>You can change the reference with <code>relevel()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a aria-hidden="true" tabindex="-1"></a>hospital_type_data_reref <span class="ot">&lt;-</span> hospital_type_data <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">hospital_type =</span> <span class="fu">relevel</span>(hospital_type, <span class="at">ref =</span> <span class="st">"Teaching"</span>))</span>
<span id="cb13-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a aria-hidden="true" tabindex="-1"></a>model_reref <span class="ot">&lt;-</span> <span class="fu">lm</span>(readmission_rate <span class="sc">~</span> hospital_type <span class="sc">+</span> avg_patient_severity <span class="sc">+</span></span>
<span id="cb13-5"><a aria-hidden="true" tabindex="-1"></a>                  nurse_per_patient, <span class="at">data =</span> hospital_type_data_reref)</span>
<span id="cb13-6"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_reref)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = readmission_rate ~ hospital_type + avg_patient_severity + 
    nurse_per_patient, data = hospital_type_data_reref)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.3053 -1.2590  0.0879  1.3945  5.0647 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                   13.2207     0.7333  18.028  &lt; 2e-16 ***
hospital_typeCommunity         2.3559     0.2942   8.009 4.68e-14 ***
hospital_typeCritical Access   5.6137     0.3439  16.324  &lt; 2e-16 ***
avg_patient_severity           2.2348     0.2180  10.251  &lt; 2e-16 ***
nurse_per_patient             -0.8597     0.1589  -5.411 1.49e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.909 on 245 degrees of freedom
Multiple R-squared:  0.6199,    Adjusted R-squared:  0.6137 
F-statistic: 99.88 on 4 and 245 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section></section>
<section>
<section id="interaction-effects" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>3. Interaction Effects</h1>

</section>
<section id="what-is-an-interaction-effect" class="slide level2">
<h2>What Is an Interaction Effect?</h2>
<p>An <strong>interaction effect</strong> occurs when the effect of one variable on the outcome <strong>depends on the value of another variable</strong>.</p>
<div class="fragment">
<p><br></p>
<p>Mathematically:</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 (X_1 \times X_2) + \epsilon\]</span></p>
<p><br></p>
<ul>
<li>The interaction coefficient <span class="math inline">\(\beta_3\)</span> captures how the effect of <span class="math inline">\(X_1\)</span> <strong>changes across levels</strong> of <span class="math inline">\(X_2\)</span> (or vice versa)</li>
</ul>
</div>
</section>
<section id="when-to-use-interactions" class="slide level2">
<h2>When to Use Interactions</h2>
<p>Use interaction terms when:</p>
<ul>
<li class="fragment"><strong>Theory</strong> or prior research suggests an effect should vary across groups</li>
<li class="fragment"><strong>Visual inspection</strong> shows different slopes for different groups</li>
<li class="fragment">You want to test whether an intervention <strong>works differently</strong> for different populations or conditions</li>
</ul>
<div class="fragment">
<p><br></p>
<p><strong>Examples</strong>:</p>
<ul>
<li class="fragment">A medication may work better for younger vs.&nbsp;older patients</li>
<li class="fragment">Additional staffing may have different impacts in big vs.&nbsp;small hospitals</li>
<li class="fragment">A new policy may affect urban and rural hospitals differently</li>
</ul>
</div>
</section></section>
<section>
<section id="continuous-x-categorical-interaction" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>3.1. Continuous x Categorical Interaction</h1>

</section>
<section id="example-does-staffing-effect-vary-by-hospital-ownership" class="slide level2">
<h2>Example: <br> Does Staffing Effect Vary by Hospital Ownership?</h2>
<p><strong>Question</strong>: Does improving nurse staffing increase patient satisfaction equally in all hospitals?</p>
<div class="fragment">
<p><br></p>
<p><strong>Why it might differ</strong>:</p>
<ul>
<li class="fragment"><strong>For-Profit hospitals</strong>: Investor-owned, focused on financial performance</li>
<li class="fragment"><strong>Non-Profit hospitals</strong>: Community-owned, mission-driven, may invest more in quality</li>
<li class="fragment"><strong>Hypothesis</strong>: Additional nurses might have a bigger impact in non-profit hospitals</li>
</ul>
</div>
</section>
<section id="loading-the-data-1" class="slide level2">
<h2>Loading the Data</h2>
<p>Let’s load the data using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a aria-hidden="true" tabindex="-1"></a>satisfaction_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week12_satisfaction_data.csv"</span>)</span>
<span id="cb15-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Set ownership as a factor with For-Profit as the reference category</span></span>
<span id="cb15-4"><a aria-hidden="true" tabindex="-1"></a>satisfaction_data <span class="ot">&lt;-</span> satisfaction_data <span class="sc">%&gt;%</span></span>
<span id="cb15-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ownership =</span> <span class="fu">factor</span>(ownership, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"For-Profit"</span>, <span class="st">"Non-Profit"</span>)))</span>
<span id="cb15-6"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(satisfaction_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X hospital_id  ownership nurse_ratio patient_volume avg_acuity
1 1           1 For-Profit        3.18            472       1.87
2 2           2 For-Profit        4.84            308       2.15
3 3           3 For-Profit        4.64            272       1.64
4 4           4 Non-Profit        5.18            673       1.88
5 5           5 For-Profit        3.21            494       2.22
  patient_satisfaction
1                 45.5
2                 57.8
3                 60.5
4                 78.5
5                 43.4</code></pre>
</div>
</div>
</section>
<section id="visualizing-the-potential-interaction" class="slide level2">
<h2>Visualizing the Potential Interaction</h2>
<p>Before running the model, always visualize to see if an interaction might exist:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(satisfaction_data, <span class="fu">aes</span>(<span class="at">x =</span> nurse_ratio, <span class="at">y =</span> patient_satisfaction,</span>
<span id="cb17-2"><a aria-hidden="true" tabindex="-1"></a>                              <span class="at">color =</span> ownership)) <span class="sc">+</span></span>
<span id="cb17-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb17-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb17-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb17-6"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Nurse-to-Patient Ratio"</span>,</span>
<span id="cb17-7"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Patient Satisfaction Score"</span>,</span>
<span id="cb17-8"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Ownership Type"</span>,</span>
<span id="cb17-9"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Does Staffing Effect Differ by Hospital Ownership?"</span>,</span>
<span id="cb17-10"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">"Different slopes suggest an interaction effect"</span></span>
<span id="cb17-11"><a aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb17-12"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Slide12_files/figure-revealjs/fig-interaction-visual-1.png" id="fig-interaction-visual" width="864" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;3
</p></section>
<section id="fitting-the-interaction-model" class="slide level2">
<h2>Fitting the Interaction Model</h2>
<p>Use <code>*</code> to include both main effects and the interaction (as we did in two-way ANOVA):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># nurse_ratio * ownership = nurse_ratio + ownership + nurse_ratio:ownership</span></span>
<span id="cb18-2"><a aria-hidden="true" tabindex="-1"></a>model_interact <span class="ot">&lt;-</span> <span class="fu">lm</span>(patient_satisfaction <span class="sc">~</span> nurse_ratio <span class="sc">*</span> ownership,</span>
<span id="cb18-3"><a aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> satisfaction_data)</span>
<span id="cb18-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_interact)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="interpreting-the-interaction" class="slide level2">
<h2>Interpreting the Interaction</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top" style="margin-left: auto; margin-right: auto;">
<caption>Regression with Interaction Effect</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">37.543</td>
<td style="text-align: right;">1.445</td>
<td style="text-align: right;">25.987</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">34.700</td>
<td style="text-align: right;">40.386</td>
</tr>
<tr class="even">
<td style="text-align: left;">nurse_ratio</td>
<td style="text-align: right;">3.211</td>
<td style="text-align: right;">0.351</td>
<td style="text-align: right;">9.155</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">2.521</td>
<td style="text-align: right;">3.901</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ownershipNon-Profit</td>
<td style="text-align: right;">3.879</td>
<td style="text-align: right;">2.140</td>
<td style="text-align: right;">1.812</td>
<td style="text-align: right;">0.071</td>
<td style="text-align: right;">-0.334</td>
<td style="text-align: right;">8.091</td>
</tr>
<tr class="even">
<td style="text-align: left;">nurse_ratio:ownershipNon-Profit</td>
<td style="text-align: right;">2.917</td>
<td style="text-align: right;">0.520</td>
<td style="text-align: right;">5.607</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">1.893</td>
<td style="text-align: right;">3.941</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br> The full model: <span class="math display">\[\widehat{\text{Satisfaction}} = 37.54 + 3.21(\text{Nurse Ratio}) + 3.88(\text{Non-Profit}) + 2.92(\text{Nurse Ratio} \times \text{Non-Profit})\]</span></p>
</section>
<section id="understanding-the-coefficients" class="slide level2 scrollable">
<h2>Understanding the Coefficients</h2>
<ol type="1">
<li class="fragment"><strong>nurse_ratio (3.21)</strong>: Effect of staffing <strong>for For-Profit hospitals</strong> (reference group)</li>
<li class="fragment"><strong>ownershipNon-Profit (3.88)</strong>: Difference between Non-Profit and For-Profit <strong>when nurse_ratio = 0</strong> (mathematical baseline, not a realistic scenario)</li>
<li class="fragment"><strong>nurse_ratio:ownershipNon-Profit (2.92)</strong>: <strong>THE INTERACTION</strong> – the additional effect of staffing in Non-Profit hospitals beyond the For-Profit effect</li>
</ol>
<div class="fragment">
<p><strong>Computing the Effect for Each Group</strong>:</p>
<ul>
<li class="fragment"><strong>For-Profit</strong>: Each additional nurse → 3.21 satisfaction points</li>
<li class="fragment"><strong>Non-Profit</strong>: Each additional nurse → 3.21 + 2.92 = 6.13 satisfaction points</li>
</ul>
</div>
</section>
<section id="visualizing-the-interaction-effect" class="slide level2">
<h2>Visualizing the Interaction Effect</h2>

<img data-src="Slide12_files/figure-revealjs/fig-interaction-plot-1.png" id="fig-interaction-plot" width="864" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;4
</p></section>
<section id="practice-1-continuous-x-categorical-interaction" class="slide level2">
<h2>Practice 1: Continuous x Categorical Interaction</h2>
<p><strong>Question</strong>: Does IT investment improve hospital quality scores equally for Teaching and Non-Teaching hospitals?</p>
<div class="fragment">
<p><br></p>
<p><strong>Why it might differ</strong>:</p>
<ul>
<li class="fragment"><strong>Teaching hospitals</strong>: Have research missions, complex case mixes, and specialized staff who can leverage advanced IT tools (e.g., clinical decision support, predictive analytics)</li>
<li class="fragment"><strong>Non-Teaching hospitals</strong>: May lack the technical workforce and workflows to fully utilize IT investments</li>
<li class="fragment"><strong>Hypothesis</strong>: IT investment may have a stronger effect in Teaching hospitals where the infrastructure and expertise exist to translate technology into quality gains</li>
</ul>
</div>
</section>
<section id="practice-dataset-hospital-quality" class="slide level2">
<h2>Practice Dataset: Hospital Quality</h2>
<p>We will use a dataset of <strong>350 U.S. hospitals</strong> with the following variables (for all three practice activities):</p>
<div style="font-size: 0.8em;">
<table class="caption-top">
<colgroup>
<col style="width: 30%">
<col style="width: 38%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: center;">Type</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>hospital_id</code></td>
<td style="text-align: center;">ID</td>
<td style="text-align: left;">Unique hospital identifier</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>region</code></td>
<td style="text-align: center;">Categorical</td>
<td style="text-align: left;">U.S. region (Midwest, Northeast, South, West)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>teaching_status</code></td>
<td style="text-align: center;">Categorical</td>
<td style="text-align: left;">Teaching or Non-Teaching</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>it_investment</code></td>
<td style="text-align: center;">Continuous</td>
<td style="text-align: left;">Annual IT spending (in $1,000s)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>avg_los</code></td>
<td style="text-align: center;">Continuous</td>
<td style="text-align: left;">Average length of stay (days)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>quality_score</code></td>
<td style="text-align: center;">Continuous</td>
<td style="text-align: left;">Composite quality score (0–100)</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="practice-1-continuous-x-categorical-interaction-1" class="slide level2">
<h2>Practice 1: Continuous x Categorical Interaction</h2>
<p><strong>Step 1.</strong> Load the data and set the reference category:</p>
<p>Let’s load the dataset and set “Non-Teaching” as the reference category for <code>teaching_status</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a aria-hidden="true" tabindex="-1"></a>quality_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week12_quality_data.csv"</span>)</span>
<span id="cb19-2"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a aria-hidden="true" tabindex="-1"></a>quality_data <span class="ot">&lt;-</span> quality_data <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">teaching_status =</span> <span class="fu">factor</span>(teaching_status,</span>
<span id="cb19-5"><a aria-hidden="true" tabindex="-1"></a>                                  <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Non-Teaching"</span>, <span class="st">"Teaching"</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="practice-1-continuous-x-categorical-interaction-2" class="slide level2">
<h2>Practice 1: Continuous x Categorical Interaction</h2>
<p><strong>Step 2.</strong> Visualize the relationship between <code>it_investment</code> and <code>quality_score</code>, colored by <code>teaching_status</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(quality_data, <span class="fu">aes</span>(<span class="at">x =</span> ___, <span class="at">y =</span> ___, <span class="at">color =</span> ___)) <span class="sc">+</span></span>
<span id="cb20-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb20-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb20-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"IT Investment ($K)"</span>, <span class="at">y =</span> <span class="st">"Quality Score"</span>,</span>
<span id="cb20-5"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Teaching Status"</span>,</span>
<span id="cb20-6"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Does IT Investment Effect Differ by Teaching Status?"</span>) <span class="sc">+</span></span>
<span id="cb20-7"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Do the slopes appear different? What does this suggest?</p>
</section>
<section id="practice-1-continuous-x-categorical-interaction-3" class="slide level2 scrollable">
<h2>Practice 1: Continuous x Categorical Interaction</h2>
<p><strong>Step 3.</strong> Fit the interaction model and interpret the results:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a aria-hidden="true" tabindex="-1"></a>model_quality <span class="ot">&lt;-</span> <span class="fu">lm</span>(___ <span class="sc">~</span> ___ <span class="sc">*</span> ___,</span>
<span id="cb21-2"><a aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> quality_data)</span>
<span id="cb21-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_quality)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions</strong>:</p>
<ol type="1">
<li>What is the effect of IT investment for <strong>Non-Teaching</strong> hospitals?</li>
<li>What is the effect of IT investment for <strong>Teaching</strong> hospitals? (Hint: add the main effect and interaction coefficients)</li>
<li>Is the interaction term statistically significant? What does this mean for hospital administrators?</li>
</ol>
</section></section>
<section>
<section id="categorical-x-categorical-interaction" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>3.2. Categorical x Categorical Interaction</h1>

</section>
<section id="example-does-treatment-effect-vary-by-insurance-type" class="slide level2">
<h2>Example: <br> Does Treatment Effect Vary by Insurance Type?</h2>
<p><strong>Question</strong>: Does an intensive diabetes (vs.&nbsp;standard) program work differently for patients with different insurance types?</p>
<div class="fragment">
<p><br></p>
<p><strong>Why it might vary</strong>:</p>
<ul>
<li class="fragment"><strong>Private</strong>: Fewest access barriers – broader networks, more specialist availability</li>
<li class="fragment"><strong>Medicaid</strong>: Logistical barriers – fewer accepting providers, transportation, time off work</li>
<li class="fragment"><strong>Medicare</strong>: More time for appointments (often retired), but mobility/health limitations</li>
</ul>
</div>
</section>
<section id="loading-the-data-2" class="slide level2">
<h2>Loading the Data</h2>
<p>Let’s load the data using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a aria-hidden="true" tabindex="-1"></a>diabetes_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week12_diabetes_data.csv"</span>)</span>
<span id="cb22-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(diabetes_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X patient_id         treatment insurance baseline_a1c age a1c_reduction
1 1          1     Standard Care   Private          7.2  67          0.50
2 2          2     Standard Care  Medicaid          9.2  64          1.08
3 3          3 Intensive Program  Medicaid          8.8  64          1.34
4 4          4     Standard Care  Medicaid          8.8  78          1.16
5 5          5 Intensive Program  Medicare          7.6  66          1.14</code></pre>
</div>
</div>
</section>
<section id="visualizing-the-data-2" class="slide level2">
<h2>Visualizing the Data</h2>
<p>Let’s visually inspect the patterns in the data before fitting the model:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(diabetes_data, <span class="fu">aes</span>(<span class="at">x =</span> insurance, <span class="at">y =</span> a1c_reduction, <span class="at">fill =</span> treatment)) <span class="sc">+</span></span>
<span id="cb24-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb24-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb24-4"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Insurance Type"</span>,</span>
<span id="cb24-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"HbA1c Reduction"</span>,</span>
<span id="cb24-6"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Treatment"</span>,</span>
<span id="cb24-7"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Does Treatment Effectiveness Vary by Insurance Type?"</span></span>
<span id="cb24-8"><a aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb24-9"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Slide12_files/figure-revealjs/fig-catcat-explore-1.png" id="fig-catcat-explore" width="864" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;5
</p></section>
<section id="setting-factors-and-fitting-the-model" class="slide level2">
<h2>Setting Factors and Fitting the Model</h2>
<p>Let’s set the reference categories for both treatment and insurance:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a aria-hidden="true" tabindex="-1"></a>diabetes_data <span class="ot">&lt;-</span> diabetes_data <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb25-3"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">treatment =</span> <span class="fu">factor</span>(treatment, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Standard Care"</span>, <span class="st">"Intensive Program"</span>)),</span>
<span id="cb25-4"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">insurance =</span> <span class="fu">factor</span>(insurance, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Medicaid"</span>, <span class="st">"Medicare"</span>, <span class="st">"Private"</span>))</span>
<span id="cb25-5"><a aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<p>Let’s fit the model with the interaction between treatment and insurance:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># treatment * insurance = treatment + insurance + treatment:insurance</span></span>
<span id="cb26-2"><a aria-hidden="true" tabindex="-1"></a>model_diabetes <span class="ot">&lt;-</span> <span class="fu">lm</span>(a1c_reduction <span class="sc">~</span> treatment <span class="sc">*</span> insurance,</span>
<span id="cb26-3"><a aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> diabetes_data)</span>
<span id="cb26-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_diabetes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</section>
<section id="interpreting-categorical-x-categorical-interactions" class="slide level2">
<h2>Interpreting Categorical x Categorical Interactions</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top" style="margin-left: auto; margin-right: auto;">
<caption>Regression Results: Treatment x Insurance Interaction</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.904</td>
<td style="text-align: right;">0.048</td>
<td style="text-align: right;">18.851</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.809</td>
<td style="text-align: right;">0.998</td>
</tr>
<tr class="even">
<td style="text-align: left;">treatmentIntensive Program</td>
<td style="text-align: right;">0.349</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">4.965</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.211</td>
<td style="text-align: right;">0.488</td>
</tr>
<tr class="odd">
<td style="text-align: left;">insuranceMedicare</td>
<td style="text-align: right;">0.147</td>
<td style="text-align: right;">0.068</td>
<td style="text-align: right;">2.156</td>
<td style="text-align: right;">0.032</td>
<td style="text-align: right;">0.013</td>
<td style="text-align: right;">0.280</td>
</tr>
<tr class="even">
<td style="text-align: left;">insurancePrivate</td>
<td style="text-align: right;">0.180</td>
<td style="text-align: right;">0.074</td>
<td style="text-align: right;">2.430</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">0.034</td>
<td style="text-align: right;">0.326</td>
</tr>
<tr class="odd">
<td style="text-align: left;">treatmentIntensive Program:insuranceMedicare</td>
<td style="text-align: right;">0.218</td>
<td style="text-align: right;">0.098</td>
<td style="text-align: right;">2.232</td>
<td style="text-align: right;">0.026</td>
<td style="text-align: right;">0.026</td>
<td style="text-align: right;">0.410</td>
</tr>
<tr class="even">
<td style="text-align: left;">treatmentIntensive Program:insurancePrivate</td>
<td style="text-align: right;">0.703</td>
<td style="text-align: right;">0.105</td>
<td style="text-align: right;">6.704</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.497</td>
<td style="text-align: right;">0.909</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="understanding-each-coefficient" class="slide level2 scrollable">
<h2>Understanding Each Coefficient</h2>
<p><strong>Reference Group</strong>: Standard Care + Medicaid</p>
<ol type="1">
<li class="fragment"><strong>Intercept (0.904)</strong>: Predicted HbA1c reduction for Standard Care with Medicaid</li>
<li class="fragment"><strong>treatmentIntensive Program (0.349)</strong>: Additional effect of Intensive Program <strong>for Medicaid patients only</strong></li>
<li class="fragment"><strong>insuranceMedicare (0.147)</strong>: Medicare vs.&nbsp;Medicaid difference <strong>for Standard Care only</strong></li>
<li class="fragment"><strong>insurancePrivate (0.18)</strong>: Private vs.&nbsp;Medicaid difference <strong>for Standard Care only</strong></li>
<li class="fragment"><strong>Interaction: Medicare (0.218)</strong>: How much more effective the Intensive Program is for Medicare <strong>compared to</strong> Medicaid</li>
<li class="fragment"><strong>Interaction: Private (0.703)</strong>: How much more effective the Intensive Program is for Private <strong>compared to</strong> Medicaid</li>
</ol>
</section>
<section id="treatment-effects-by-insurance-group" class="slide level2">
<h2>Treatment Effects by Insurance Group</h2>
<p><strong>Computing treatment effects for each group</strong>:</p>
<ul>
<li class="fragment"><strong>Medicaid</strong>: Treatment effect = 0.349</li>
<li class="fragment"><strong>Medicare</strong>: Treatment effect = 0.349 + 0.218 = 0.567</li>
<li class="fragment"><strong>Private</strong>: Treatment effect = 0.349 + 0.703 = 1.052</li>
</ul>
<div class="fragment">
<p><br></p>
<p>The Intensive Program is effective across all insurance types, but <strong>most effective</strong> for Private insurance patients.</p>
</div>
</section>
<section id="visualizing-categorical-x-categorical-interaction" class="slide level2">
<h2>Visualizing Categorical x Categorical Interaction</h2>

<img data-src="Slide12_files/figure-revealjs/fig-catcat-bar-1.png" id="fig-catcat-bar" width="864" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;6
</p></section>
<section id="practice-2-categorical-x-categorical-interaction" class="slide level2">
<h2>Practice 2: Categorical x Categorical Interaction</h2>
<p><strong>Question</strong>: Does the quality advantage of Teaching hospitals vary across U.S. regions?</p>
<div class="fragment">
<p><br></p>
<p><strong>Why it might differ</strong> (potentially):</p>
<ul>
<li class="fragment"><strong>Northeast</strong>: High concentration of academic medical centers and research funding, so teaching hospitals may have a large quality edge</li>
<li class="fragment"><strong>South/Midwest</strong>: Fewer teaching hospitals, potentially serving underserved populations, so the teaching advantage may be smaller</li>
<li class="fragment"><strong>West</strong>: Strong tech and innovation culture, so even Non-Teaching hospitals may adopt best practices, narrowing the gap</li>
</ul>
</div>
</section>
<section id="practice-2-categorical-x-categorical-interaction-1" class="slide level2">
<h2>Practice 2: Categorical x Categorical Interaction</h2>
<p><strong>Step 1.</strong> Using the same <code>quality_data</code>, set the reference categories:</p>
<p>Let’s set “Non-Teaching” as the reference for <code>teaching_status</code> and “Midwest” as the reference for <code>region</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a aria-hidden="true" tabindex="-1"></a>quality_data <span class="ot">&lt;-</span> quality_data <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb27-3"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">teaching_status =</span> <span class="fu">factor</span>(teaching_status,</span>
<span id="cb27-4"><a aria-hidden="true" tabindex="-1"></a>                             <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Non-Teaching"</span>, <span class="st">"Teaching"</span>)),</span>
<span id="cb27-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">region =</span> <span class="fu">factor</span>(region,</span>
<span id="cb27-6"><a aria-hidden="true" tabindex="-1"></a>                    <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Midwest"</span>, <span class="st">"Northeast"</span>, <span class="st">"South"</span>, <span class="st">"West"</span>))</span>
<span id="cb27-7"><a aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="practice-2-categorical-x-categorical-interaction-2" class="slide level2">
<h2>Practice 2: Categorical x Categorical Interaction</h2>
<p><strong>Step 2.</strong> Visualize quality scores by teaching status and region:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(quality_data, <span class="fu">aes</span>(<span class="at">x =</span> ___, <span class="at">y =</span> ___, <span class="at">fill =</span> ___)) <span class="sc">+</span></span>
<span id="cb28-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb28-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Region"</span>, <span class="at">y =</span> <span class="st">"Quality Score"</span>, <span class="at">fill =</span> <span class="st">"Teaching Status"</span>,</span>
<span id="cb28-4"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Does the Teaching Hospital Advantage Vary by Region?"</span>) <span class="sc">+</span></span>
<span id="cb28-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Does the gap between Teaching and Non-Teaching hospitals look the same in every region?</p>
</section>
<section id="practice-2-categorical-x-categorical-interaction-3" class="slide level2 scrollable">
<h2>Practice 2: Categorical x Categorical Interaction</h2>
<p><strong>Step 3.</strong> Fit the interaction model and interpret the results:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a aria-hidden="true" tabindex="-1"></a>model_region <span class="ot">&lt;-</span> <span class="fu">lm</span>(___ <span class="sc">~</span> ___ <span class="sc">*</span> ___,</span>
<span id="cb29-2"><a aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> quality_data)</span>
<span id="cb29-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_region)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Questions</strong>:</p>
<ol type="1">
<li>What is the predicted quality score for a <strong>Non-Teaching</strong> hospital in the <strong>Midwest</strong> (reference group)?</li>
<li>What is the teaching advantage in the <strong>Midwest</strong> vs.&nbsp;in the <strong>West</strong>? (Hint: add the teaching main effect and the relevant interaction coefficient)</li>
</ol>
</section>
<section id="practice-2-categorical-x-categorical-interaction-4" class="slide level2 scrollable">
<h2>Practice 2: Categorical x Categorical Interaction</h2>
<ol start="3" type="1">
<li>Use <code>emmeans()</code> to compare Teaching vs.&nbsp;Non-Teaching within each region.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a aria-hidden="true" tabindex="-1"></a>emm <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(model_region, <span class="sc">~</span> teaching_status <span class="sc">|</span> region)</span>
<span id="cb30-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(emm, <span class="at">adjust=</span><span class="st">"tukey"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><br> <strong>Question</strong>:</p>
<ol start="3" type="1">
<li>In which region shows the largest gap? In which region shows the smallest gap?</li>
</ol>
</section></section>
<section>
<section id="continuous-x-continuous-interaction" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>3.3. Continuous x Continuous Interaction</h1>

</section>
<section id="example-does-pt-session-benefit-depend-on-patient-age" class="slide level2">
<h2>Example: <br> Does PT Session Benefit Depend on Patient Age?</h2>
<p><strong>Question</strong>: Does the benefit of additional physical therapy (PT) sessions depend on patient age?</p>
<div class="fragment">
<p><br></p>
<p><strong>Why it might vary</strong>:</p>
<ul>
<li class="fragment">Younger patients may have faster tissue repair and adaptation</li>
<li class="fragment">Older patients may have comorbidities limiting response to therapy</li>
<li class="fragment">Thus, additional PT sessions might provide greater improvement for younger patients</li>
</ul>
</div>
</section>
<section id="loading-the-data-3" class="slide level2">
<h2>Loading the Data</h2>
<p>Let’s load the data using the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a aria-hidden="true" tabindex="-1"></a>pt_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/mba642-spring-26/mba642-spring-26.github.io/refs/heads/main/datasets/week12_pt_data.csv"</span>)</span>
<span id="cb31-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pt_data, <span class="dv">5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  X patient_id pt_sessions age baseline_function function_improvement
1 1          1          16  31                53                 27.1
2 2          2          22  51                31                  0.0
3 3          3           5  30                40                  7.5
4 4          4          11  37                31                 14.6
5 5          5           5  48                49                 10.3</code></pre>
</div>
</div>
</section>
<section id="visualizing-the-data-3" class="slide level2">
<h2>Visualizing the Data</h2>
<p>Let’s visually inspect the patterns in the data before fitting the model:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pt_data, <span class="fu">aes</span>(<span class="at">x =</span> pt_sessions, <span class="at">y =</span> function_improvement, <span class="at">color =</span> age)) <span class="sc">+</span></span>
<span id="cb33-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb33-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_gradient</span>(<span class="at">low =</span> <span class="st">"steelblue"</span>, <span class="at">high =</span> <span class="st">"coral"</span>) <span class="sc">+</span></span>
<span id="cb33-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb33-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Number of PT Sessions"</span>,</span>
<span id="cb33-6"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Function Improvement"</span>,</span>
<span id="cb33-7"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"Age"</span>,</span>
<span id="cb33-8"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Does PT Session Effectiveness Vary by Age?"</span></span>
<span id="cb33-9"><a aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb33-10"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>

</div>
<img data-src="Slide12_files/figure-revealjs/fig-contcont-explore-1.png" id="fig-contcont-explore" width="864" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;7
</p></section>
<section id="fitting-the-model-1" class="slide level2">
<h2>Fitting the Model</h2>
<p>Let’s fit the model with the interaction between PT sessions and age:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># pt_sessions * age = pt_sessions + age + pt_sessions:age</span></span>
<span id="cb34-2"><a aria-hidden="true" tabindex="-1"></a>model_pt <span class="ot">&lt;-</span> <span class="fu">lm</span>(function_improvement <span class="sc">~</span> pt_sessions <span class="sc">*</span> age,</span>
<span id="cb34-3"><a aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> pt_data)</span>
<span id="cb34-4"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_pt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="interpreting-the-results" class="slide level2">
<h2>Interpreting the Results</h2>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover caption-top" style="margin-left: auto; margin-right: auto;">
<caption>Regression Results: PT Sessions x Age Interaction</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.low</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">22.2460</td>
<td style="text-align: right;">3.1492</td>
<td style="text-align: right;">7.0639</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">16.0431</td>
<td style="text-align: right;">28.4490</td>
</tr>
<tr class="even">
<td style="text-align: left;">pt_sessions</td>
<td style="text-align: right;">0.8206</td>
<td style="text-align: right;">0.2137</td>
<td style="text-align: right;">3.8399</td>
<td style="text-align: right;">0.0002</td>
<td style="text-align: right;">0.3997</td>
<td style="text-align: right;">1.2415</td>
</tr>
<tr class="odd">
<td style="text-align: left;">age</td>
<td style="text-align: right;">-0.1612</td>
<td style="text-align: right;">0.0583</td>
<td style="text-align: right;">-2.7647</td>
<td style="text-align: right;">0.0061</td>
<td style="text-align: right;">-0.2761</td>
<td style="text-align: right;">-0.0464</td>
</tr>
<tr class="even">
<td style="text-align: left;">pt_sessions:age</td>
<td style="text-align: right;">-0.0200</td>
<td style="text-align: right;">0.0040</td>
<td style="text-align: right;">-4.9948</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">-0.0278</td>
<td style="text-align: right;">-0.0121</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="understanding-the-coefficients-1" class="slide level2 scrollable">
<h2>Understanding the Coefficients</h2>
<ol type="1">
<li class="fragment"><strong>pt_sessions (0.82)</strong>: Effect of one additional PT session <strong>when age = 0</strong> (not meaningful)</li>
<li class="fragment"><strong>age (-0.16)</strong>: Effect of one year of age <strong>when pt_sessions = 0</strong> (not meaningful)</li>
<li class="fragment"><strong>pt_sessions:age (-0.02)</strong>: <strong>THE INTERACTION</strong> – for each additional year of age, the benefit of one PT session decreases by 0.02 points</li>
</ol>
<div class="fragment">
<p><strong>Marginal effect formula</strong>:</p>
<p><span class="math display">\[\text{Effect of PT Sessions} = \beta_{\text{pt_sessions}} + \beta_{\text{interaction}} \times \text{Age}\]</span></p>
</div>
</section>
<section id="computing-marginal-effects-at-different-ages" class="slide level2">
<h2>Computing Marginal Effects at Different Ages</h2>
<ul>
<li class="fragment"><strong>Age 30</strong>: Effect = 0.82 + (30 × -0.02) = 0.22 points per session</li>
<li class="fragment"><strong>Age 50</strong>: Effect = 0.82 + (50 × -0.02) = -0.18 points per session</li>
<li class="fragment"><strong>Age 70</strong>: Effect = 0.82 + (70 × -0.02) = -0.58 points per session</li>
</ul>
<div class="fragment">
<p><br></p>
<p>The effect of PT sessions <strong>changes dramatically with age</strong>. Positive for younger patients, potentially negative for older patients.</p>
</div>
</section>
<section id="visualizing-with-probe_interaction" class="slide level2">
<h2>Visualizing with <code>probe_interaction()</code></h2>
<p>We can understand the interaction better by visualizing the predicted improvement across PT sessions for different ages using <code>probe_interaction()</code>, which is a part of the <code>interactions</code> package:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">probe_interaction</span>(model_pt,              <span class="co"># fitted model</span></span>
<span id="cb35-2"><a aria-hidden="true" tabindex="-1"></a>                  <span class="at">pred =</span> pt_sessions,     <span class="co"># x-axis variable</span></span>
<span id="cb35-3"><a aria-hidden="true" tabindex="-1"></a>                  <span class="at">modx =</span> age,             <span class="co"># moderator variable</span></span>
<span id="cb35-4"><a aria-hidden="true" tabindex="-1"></a>                  <span class="at">modx.values =</span> <span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">50</span>, <span class="dv">70</span>))  <span class="co"># values to plot separate lines</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>JOHNSON-NEYMAN INTERVAL

When age is OUTSIDE the interval [31.18, 47.33], the slope of pt_sessions
is p &lt; .05.

Note: The range of observed values of age is [25.00, 80.00]

SIMPLE SLOPES ANALYSIS

Slope of pt_sessions when age = 30.00: 

  Est.   S.E.   t val.      p
------ ------ -------- ------
  0.22   0.10     2.12   0.03

Slope of pt_sessions when age = 50.00: 

   Est.   S.E.   t val.      p
------- ------ -------- ------
  -0.18   0.06    -2.90   0.00

Slope of pt_sessions when age = 70.00: 

   Est.   S.E.   t val.      p
------- ------ -------- ------
  -0.58   0.10    -5.97   0.00</code></pre>
</div>

</div>
<img data-src="Slide12_files/figure-revealjs/fig-contcont-1.png" id="fig-contcont" width="864" class="r-stretch quarto-figure-center"><p class="caption">
Figure&nbsp;8
</p></section>
<section id="interpreting-the-visualization" class="slide level2">
<h2>Interpreting the Visualization</h2>
<p><strong>Simple Slopes Analysis</strong>:</p>
<ul>
<li><strong>Age 30</strong>: Positive slope – PT sessions are <strong>beneficial</strong></li>
<li><strong>Age 50</strong>: Negative slope – PT sessions are <strong>associated with worse outcomes</strong></li>
<li><strong>Age 70</strong>: Negative slope – PT sessions are <strong>associated with worse outcomes</strong></li>
</ul>
<div class="fragment">
<p><br> <strong>Key insight</strong>:</p>
<ul>
<li>The interaction creates a <strong>crossover effect</strong> where the treatment benefit reverses direction in different subgroups.</li>
<li>In practice, this would warrant investigation into confounding factors (e.g., sicker older patients may be prescribed more PT sessions, making PT <em>appear</em> less effective).</li>
</ul>
</div>
</section>
<section id="practice-3-continuous-x-continuous-interaction" class="slide level2">
<h2>Practice 3: Continuous x Continuous Interaction</h2>
<p><strong>Question</strong>: Does the benefit of IT investment on quality depend on a hospital’s average length of stay?</p>
<div class="fragment">
<p><br></p>
<p><strong>Why it might differ</strong>:</p>
<ul>
<li class="fragment"><strong>Low avg LOS hospitals</strong>: Likely efficient, high-turnover facilities – IT investments in scheduling and throughput tools may directly boost quality metrics</li>
<li class="fragment"><strong>High avg LOS hospitals</strong>: Often treating sicker or more complex patients – IT alone may not overcome the clinical challenges that drive longer stays</li>
<li class="fragment"><strong>Hypothesis</strong>: IT investment may have a stronger quality impact in hospitals with lower average length of stay</li>
</ul>
</div>
</section>
<section id="practice-3-continuous-x-continuous-interaction-1" class="slide level2">
<h2>Practice 3: Continuous x Continuous Interaction</h2>
<p><strong>Step 1.</strong> Using the same <code>quality_data</code>, visualize the relationship:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(quality_data, <span class="fu">aes</span>(<span class="at">x =</span> ___, <span class="at">y =</span> ___, <span class="at">color =</span> ___)) <span class="sc">+</span></span>
<span id="cb37-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb37-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_gradient</span>(<span class="at">low =</span> <span class="st">"steelblue"</span>, <span class="at">high =</span> <span class="st">"coral"</span>) <span class="sc">+</span></span>
<span id="cb37-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"IT Investment ($K)"</span>, <span class="at">y =</span> <span class="st">"Quality Score"</span>, <span class="at">color =</span> <span class="st">"Avg LOS"</span>,</span>
<span id="cb37-5"><a aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Does IT Investment Effectiveness Depend on Avg LOS?"</span>) <span class="sc">+</span></span>
<span id="cb37-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="practice-3-continuous-x-continuous-interaction-2" class="slide level2">
<h2>Practice 3: Continuous x Continuous Interaction</h2>
<p><strong>Step 2.</strong> Fit the interaction model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a aria-hidden="true" tabindex="-1"></a>model_it_los <span class="ot">&lt;-</span> <span class="fu">lm</span>(___ <span class="sc">~</span> ___ <span class="sc">*</span> ___,</span>
<span id="cb38-2"><a aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> quality_data)</span>
<span id="cb38-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_it_los)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="practice-3-continuous-x-continuous-interaction-3" class="slide level2 scrollable">
<h2>Practice 3: Continuous x Continuous Interaction</h2>
<p><strong>Step 3.</strong> Interpret the results:</p>
<p><strong>Questions</strong>:</p>
<ol type="1">
<li>Write out the marginal effect formula for <code>it_investment</code>: <span class="math display">\[\text{Effect of IT Investment} = \beta_{\text{it_investment}} + \beta_{\text{interaction}} \times \text{Avg LOS}\]</span></li>
<li>Compute the effect of IT investment at avg LOS = <strong>3 days</strong>, <strong>5 days</strong>, and <strong>7 days</strong></li>
</ol>
</section>
<section id="practice-3-continuous-x-continuous-interaction-4" class="slide level2 scrollable">
<h2>Practice 3: Continuous x Continuous Interaction</h2>
<p><strong>Step 4.</strong> Visualize and discuss:</p>
<ol start="3" type="1">
<li>Use <code>probe_interaction()</code> to visualize the effect of IT investment at avg LOS = <strong>3 days</strong>, <strong>5 days</strong>, and <strong>7 days</strong> (the same values from Q2):</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">probe_interaction</span>(model_it_los,</span>
<span id="cb39-2"><a aria-hidden="true" tabindex="-1"></a>                  <span class="at">pred =</span> ___,</span>
<span id="cb39-3"><a aria-hidden="true" tabindex="-1"></a>                  <span class="at">modx =</span> ___,</span>
<span id="cb39-4"><a aria-hidden="true" tabindex="-1"></a>                  <span class="at">modx.values =</span> <span class="fu">c</span>(___, ___, ___))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><br> 4. Is the interaction term statistically significant? If not, what does that tell hospital administrators – should they differentiate their IT investment strategy based on average length of stay, or can they apply a uniform approach?</p>
</section></section>
<section>
<section id="summary" class="title-slide slide level1 center" data-background-color="#40666e">
<h1>Summary</h1>

</section>
<section id="key-takeaways" class="slide level2">
<h2>Key Takeaways</h2>
<ul>
<li class="fragment"><strong>Dummy variables</strong> let us include categorical predictors in regression using 0s and 1s</li>
<li class="fragment">We can not only compare two categories or groups, but also <strong>multiple categories</strong> by creating k-1 dummy variables</li>
<li class="fragment">Use <code>emmeans()</code> for <strong>pairwise comparisons</strong> across multi-level categorical variables</li>
<li class="fragment"><strong>Interaction effects</strong> test whether the effect of one variable depends on another</li>
<li class="fragment">In interaction models, <strong>main effects</strong> have conditional interpretations (at zero or reference level)</li>
<li class="fragment">Use <code>probe_interaction()</code> for <strong>visualizing interaction effects</strong></li>
</ul>
</section>
<section id="assignments" class="slide level2 scrollable">
<h2>Assignments</h2>
<ol type="1">
<li><strong>Week 12 Reflection</strong>: Please share your thoughts on the lecture</li>
</ol>
<ul>
<li>3 interesting things</li>
<li>3 confusing or unclear things</li>
</ul>
<p>Due by 11:59pm on Sunday, April 5.</p>
</section>
<section id="assignments-1" class="slide level2 scrollable">
<h2>Assignments</h2>
<ol start="2" type="1">
<li><strong>Week 13 Reflection</strong>: Please share your thoughts on the lecture</li>
</ol>
<ul>
<li>3 interesting things</li>
<li>3 confusing or unclear things</li>
</ul>
<p><br></p>
<ol start="3" type="1">
<li><strong>Lab Assignment 5</strong>: Linear Regression</li>
</ol>
<p>Both are due by 11:59pm on Sunday, April 12.</p>
</section>
<section id="references" class="slide level2">
<h2>References</h2>
<p><strong>Statistical Methods</strong>:</p>
<ul>
<li>Gelman, A., &amp; Hill, J. (2006). <em>Data Analysis Using Regression and Multilevel/Hierarchical Models</em>. Cambridge University Press.</li>
<li>James, G., Witten, D., Hastie, T., &amp; Tibshirani, R. (2021). <em>An Introduction to Statistical Learning with Applications in R</em> (2nd ed.). Springer.</li>
</ul>
<p><strong>Healthcare Applications</strong>:</p>
<ul>
<li>Katikam, S. M., et al.&nbsp;(2025). Evaluation of ERAS Protocols in Abdominal Surgery. <em>Journal of Pharmacy &amp; Bioallied Sciences</em>, 17(Suppl 2), S1805-S1807.</li>
<li>Horwitz, L. I., et al.&nbsp;(2017). Hospital characteristics associated with risk-standardized readmission rates. <em>Medical Care</em>, 55(5), 528-534.</li>
<li>Turk, M. T., et al.&nbsp;(2023). Stakeholder Analysis: Medicare Diabetes Prevention Program. <em>American Journal of Managed Care</em>, 29(6), 308-312.</li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Week 12 | Linear Regression 2</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>